### ISSUE TITLE
Why the naming so confusing? (Vulcan? Telescope? Nova?)

### ISSUE THREAD

**Issue by 1c7** [telescopejs/telescope#10]
http://www.telescopeapp.org/

Get Started -> Valcan
Github -> this Github telescope repo, and Readme doesn't match with telescopeapp.org (at least at first glance)
Bottom FAQ -> use "Nova"

What???

**Comment by 1c7** [comment]
get the naming thing fixed! or at least put a FAQ explain this in telescopeapp.org

**Comment by 1c7** [comment]
seem like Nova is old name, Telescope is current name, and Vulcan is next name?

**Comment by 1c7** [comment]
http://docs.vulcanjs.org/vulcan.html
ok, so old name is Telescope, new name is Nova, next name is Vulcan.

get it.

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/37195133-8787d0a2-23ac-11e8-8a62-b0fa211c265b.png)

**Comment by matbrgz** [comment]
OMG sooo confuse..

**Comment by imcuttle** [comment]
Root of error is Github's url is case insensitive.

`https://github.com/telescopejs/telescope` is equals to `https://github.com/Telescopejs/Telescope`
