### ISSUE TITLE
Email notification settings no longer present in profile

### ISSUE THREAD

**Issue by jshimko** [TelescopeJS/Telescope#1002]
Users can't opt in/out of transactional emails anymore.

**Comment by samsolomon** [comment]
Also, doesn't look like the Toggle Email notification link is working in the Settings menu either. I disabled email notifications and users are still receiving notifications on every post.

**Comment by SachaG** [comment]
Yes, I think that happened a while back when we switched to Herald for the notifications. I thought the Settings link would work though.

**Comment by jshimko** [comment]
This should be fixed now.  Give the devel branch a test when you have a moment.  I [added the notification settings][1] to the user schema and [updated the logic in the notifications package][2] to check the user's settings before sending a notification email.  

[1]: https://github.com/TelescopeJS/Telescope/commit/e501f4ae3f9a117d79fd109f032a997ce52b75f3
[2]: https://github.com/TelescopeJS/Telescope/commit/bb4bafa3bcb113b71d37d845569c23a132e1628f

**Comment by jshimko** [comment]
Didn't think about it until now, but we're probably going to need to add a migration for this as well.  Since the notification settings weren't in the user schema before, the default values weren't being adding when the [`onCreateUser` callback for notification settings][1] ran.  So for any user that created an account since this issue started, the settings will be available on their profile edit page, but all notifications will be turned off by default because the `telescope.notifications` object doesn't exist yet in the database (which will likely also throw an error when the email notification logic checks for it).

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-notifications/lib/notifications.js#L177-L187

**Comment by SachaG** [comment]
We could just default the setting to `true` maybe?

**Comment by jshimko** [comment]
[Done][1].  :)

Just added the same default settings object that the `onCreateUser` callback was using.

[1]: https://github.com/TelescopeJS/Telescope/commit/dccf0ee92be0d5af1ccfda2c01a16e4cdc6c2ca9

**Comment by SachaG** [comment]
Actually, what I meant is that this is why we had:

```js
if(Users.getUserSetting('notifications.users', false, admin)){
//...
}
```

`getUserSetting` would make the setting default to `false` if it doesn't exist, which means we wouldn't need a migration.

**Comment by jshimko** [comment]
Yeah, but that didn't fix `telescope.notifications.posts`, `telescope.notifications.comments`, and `telescope.notifications.replies`.  Those didn't exist in the existing user objects in the database and were returning `undefined` on the checks that were happening for the email notifications.  The onCreateUser callback [here][1] was supposed to be adding those fields, but it wasn't getting inserted because of the missing schema.  

Also, the default notifications state for new users was to get an email when someone comments on your post or replies to your comments.  That scenario wasn't happening without the migration.  That's not necessarily broken, but it's not consistent with what new users were supposed to be getting when the user object gets created.  Right? 

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-notifications/lib/notifications.js#L177-L187

**Comment by SachaG** [comment]
But then we wouldn't be calling `telescope.notifications.posts` directly, so it wouldn't matter that it's not defined?

**Comment by jshimko** [comment]
Oh, sorry.  Yeah, I see what you mean.  I thought you were just talking about the getUserSetting for the new users notification.  

So same result, different method to get there.  Your call then.  I can remove the migration if that's what you prefer.  I just went that route so user documents would be consistent.  Either scenario works fine though.

**Comment by SachaG** [comment]
I think I'd rather avoid migrations if we can. But I'm also not sure if the user settings thing is working properly right now…

**Comment by SachaG** [comment]
> I think I'd rather avoid migrations if we can

Haha, looks like I was right about this… Your migration completely overwrites the `telescope` object for every user in your database:

```js
Meteor.users.update(user._id, {$set: { telescope: { notifications: defaultNotifications }}});
```

Should've been:

```js
Meteor.users.update(user._id, {$set: { "telescope.notifications": defaultNotifications }});
```
