### ISSUE TITLE
User links are /user/undefinedusername

### ISSUE THREAD

**Issue by kitsched** [TelescopeJS/Telescope#1003]
I used the quick deploy to Heroku button to set up the project, started using it, but I had an issue with items not showing in their categories. So I thought about upgrading - cloned the Heroku repository to my machine, added the github remote for sample-project, pulled the updates from sample-project and pushed them to Heroku.

Now the items appear in their categories, I can promote users to admin (I couldn't do this in the previous version either) but the link to my username (janos) is: /users/undefinedjanos and it's the same for the other users.

What did I do wrong?

**Comment by wilwaldon** [comment]
I'm having the same problem, quick deploy on Heroku as well.

http://myapp.herokuapp.com/users/undefinedwilliamw

As you might have noticed, Telescope added "undefined" to the user URL. If you remove "undefined" it works fine.

**Comment by wilwaldon** [comment]
Found the answer on this page: 

http://meta.telescopeapp.org/posts/hZbQDEkBNif7CGSrv

It's actually an Iron Router issue. If you come to the Slack chatroom I posted more info about this:

ok, it’s a temporary problem with Iron Router

sacha [2:43 PM]
you need to update it to 1.0.9

sacha [2:44 PM]
https://github.com/iron-meteor/iron-router/issues/1359

sacha [2:58 PM] 
I updated the deployment page with instructions on how to update on Heroku

sacha [2:58 PM]
http://docs.telescopeapp.org/v0.20/docs/deploying (edited)

sacha [2:58 PM]
in this specific case, you want to upgrade the `iron:router` package to version `1.0.9`

sacha [2:58 PM]
you can make sure the update worked by checking your `.meteor/versions` file (edited)

sacha [2:59 PM]
for some reason it didn’t quite work the first time I ran `meteor update` for me, so you might have to delete the `versions` file and do it again

**Comment by SachaG** [comment]
@wilwaldon yep, thanks for copy/pasting that :)

**Comment by kitsched** [comment]
`meteor update` fixed things. Thanks.

**Comment by dgmstuart** [comment]
It sounds like there's a workaround, but the one-click deploy isn't fixed yet? I ran it today and I'm experiencing this issue. 

Is there a plan to update the heroku deploy?

**Comment by kitsched** [comment]
It boils down to fixing the versions file. I'll submit a pull request to sample-proiect soon-ish. :smile:

**Comment by kitsched** [comment]
There we go, whenever they accept it.

**Comment by dgmstuart** [comment]
:bomb: BOOM - now that's a quick response :) Thanks @kitsched!

**Comment by SachaG** [comment]
@kitsched thanks! I forgot that the sample project still contained the wrong versions, good point!

**Comment by kitsched** [comment]
:+1:
