### ISSUE TITLE
Place values in different template positions

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#1006]
I want to show some other text in place of avatar image in posts.  How can i do that.

**Comment by SachaG** [comment]
That's not really an issue, so please ask for support on [Meta](http://meta.telescopeapp.org) or in the Slack chatroom. Also, make sure you read through the documentation first :)

**Comment by dittybijil** [comment]
Its ok.  But i Added the values to the modules as you suggested in the document.  But it result the same as old. So I want to know if there is any mistake in my code. Thats why i posted it as a doubt.
