### ISSUE TITLE
gravatar broken image

### ISSUE THREAD

**Issue by tima101** [TelescopeJS/Telescope#1010]
After removing dummy content, for Admin's avatar I get broken image:

<img class="avatar-image" src="https://secure.gravatar.com/avatar/2a82041e23648a138cc83f0071f413f4?default=404&amp;size=200" alt="avatar" onerror="this.style.display='none';" width="50" height="50">

I block it with: img.avatar-image {display:none;}

Does anyone see the same broken image?

**Comment by capensisma** [comment]
You can only get a broken gravatar image if the emails doesn't have an avatar
but can you explain more ? or give the link ?

**Comment by tima101** [comment]
Broken image comes from: https://secure.gravatar.com/avatar/2a82041e23648a138cc83f0071f413f4?default=404&size=200

Looks like this: 

![screen shot 2015-06-09 at 5 27 07 pm](https://cloud.githubusercontent.com/assets/10218864/8072586/d14e97f4-0ecc-11e5-8085-475d71b097d1.png)

**Comment by capensisma** [comment]
yes it from there ecause you didn't register your email onn www.gravatar.com and add your profile picture so it shows an empty/broken image that's way.
try adding you image on gravatar and try again ?

**Comment by tima101** [comment]
I see, you mean that it is a default behavior of the app?

**Comment by capensisma** [comment]
yes currently if the user hasn't registered his email on Gravatar it will show the broken image on the console though not in the profile since it's hidden

**Comment by tima101** [comment]
Alright, thanks for explanation. I would recommend to display circle with a single letter IF gravatar image does not exist.

**Comment by capensisma** [comment]
you're welcome
yes it already does that

**Comment by tima101** [comment]
I am bit of a stickler Meeseeks =)
I would recommend to hide "broken image" in case gravatar image does not exist. But not crucial.

**Comment by WassiMan** [comment]
I'm facing the same issu, and I think it's "crucial" to hide the broken image if the user doesn't have a Gravatar account, and I think Telescope already solved that, because the user in my case with broken image had a nice rounded first-letter-of-his-name as an avatar, but suddenly disappeared and turned into a broken image. The question is how to fix it?

**Comment by garyttierney** [comment]
From the Slack channel, can be fixed by overriding the meteor-avatar options:

Avatar.options = {
    gravatarDefault: 'mm' // default is 404
};

A list of valid defaults is at https://secure.gravatar.com/site/implement/images/#default-image

**Comment by WassiMan** [comment]
@garyttierney Where can I find this "meteor-avatar" file or package ? Do I have to install the  bengott:avatar package to perform those customizations ? If I change them successfully, will they be overridden when I do an upgrade to Telescope ?

**Comment by sk4blink** [comment]
Hi All - I'm running into the same issue where the gravatar images are showing as broken images by default if the user has not associated an image with their account. How do I implement this?

Avatar.options = {
    gravatarDefault: 'mm' // default is 404
};

I tried adding this code block to the 'extra code' section within the Telescope admin settings, but no luck. Any help would be greatly appreciated.

**Comment by tonyarash** [comment]
I got it to work by adding it to a config.js file that I'm using in my own client folder for customization. But you can add it to any js file in your folder and it should work.

**Comment by sk4blink** [comment]
Hmm... I've already deployed Telescope to my own server. How do I accomplish this? Do I have to add it a config.js file and re-deploy for it to take effect? Which specific config.js exactly?  

And to be clear, there's no way to fix this from the Telescope admin settings page is there? That would be ideal.

Thanks.

**Comment by tonyarash** [comment]
You should not touch any of the Telescope files. Most customization can be done outside of the package using your own files. You need to create a js file. You can call it anything. I chose config.js for myself. I would suggest putting inside of client folder. Look at the Meteor doc for folder structure. Test it by running Meteor in command line and looking at it on localhost:300. If all looks good then you will need to deploy the files to the server again.

**Comment by sk4blink** [comment]
Awesome. You're the man tonyarash. Fixed!

I followed your instructions exactly. I created a new dir in my Telescope directory called "client", created a new file called config.js and just added in the code 

Avatar.options = {
    gravatarDefault: 'mm' // default is 404
};

I tested locally and deployed to my server successfully. Now previously broken images show as the default avatar if no gravtar image exists.

**Comment by tonyarash** [comment]
Yeah, it's that easy. There are also many other things you can customize in Telescope this way including templates. See Telescope docs for more info.

**Comment by WassiMan** [comment]
Didn't work for me! Really strange!

**Comment by mhui** [comment]
Changing Avatar.options shouldn't be necessary because of this attribute on the gravatar image onerror="this.style.display='none';" but it's not working

**Comment by WassiMan** [comment]
Problem solved with the latest release (Telescope v0.21.1). I think the issue need to be closed.
