### ISSUE TITLE
non-translatable string

### ISSUE THREAD

**Issue by tima101** [TelescopeJS/Telescope#1011]
"Post" in post_list_compact.html

**Comment by capensisma** [comment]
Did you try using it in lower case ?
like "post" ?

**Comment by xavcz** [comment]
Hey, @tima101 ! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
