### ISSUE TITLE
cannot delete "url" on post_edit page

### ISSUE THREAD

**Issue by tima101** [TelescopeJS/Telescope#1012]
When I edit post and delete external url and click submit - url is still present and not deleted.

I use Compose's database to edit "url" attribute of the post. Can anyone reproduce the problem?

**Comment by jshimko** [comment]
Yep, I can confirm the same behavior.  Thanks for filing the issue.  We'll look into it.

**Comment by tima101** [comment]
Thanks for building it open-source!

**Comment by tima101** [comment]
@jshimko url can be replaced by new url but cannot be deleted by leaving input filed empty.

**Comment by yapus** [comment]
Also "/" is always being added to the end of the url. This is cannot be fixed through the interface
