### ISSUE TITLE
"telescope-sitemap" package is disabled

### ISSUE THREAD

**Issue by tima101** [TelescopeJS/Telescope#1016]
Is there a particular reason why?

**Comment by SachaG** [comment]
I think it's broken, and also apparently sitemaps are not that useful for SEO anymore.

**Comment by tima101** [comment]
I see. Thanks.

**Comment by milezteg** [comment]
Holy crap I've been trying to get this working for the last 2 hours.  *Sigh* - so glad finally found this thread.
