### ISSUE TITLE
Customizing the display of post attributes

### ISSUE THREAD

**Issue by ajaykumaran** [TelescopeJS/Telescope#1020]
We are trying to hide the Avatar and show a facebook like in that place. In early version we used to do it by changing the order in postInfo. In the current version we tried changing order in postComponents by refering to the sample code in your documentation as below, but no effect
Telescope.modules.add("postComponents", {
  template: 'customPostShares',
  order: 3
})

Kindly advice on how to do it..

**Comment by jshimko** [comment]
The code you mentioned above should work.  Are you sure the app has loaded it?  Where did you put that code?  Is the custom template available to the app as well?
