### ISSUE TITLE
URL with file extensions breaking

### ISSUE THREAD

**Issue by alwiser** [TelescopeJS/Telescope#1026]
If the URL being added is a .php page, a "/" is automatically added to the end of the URL, breaking it.

**Comment by SachaG** [comment]
Oh right I see what you mean. It has nothing to do with `.php`, it's just that a `/` gets added to all URLs.

**Comment by stevemdixon** [comment]
Is there an ETA for when this fix will be pushed?

**Comment by jamescmartinez** [comment]
+1

**Comment by SachaG** [comment]
It's already pushed to the `devel` branch. Hoping to release it soon, the new version just needs a little more testing and debugging first.

**Comment by stevemdixon** [comment]
Thanks, @SachaG!

**Comment by SachaG** [comment]
Released in 0.21.1.
