### ISSUE TITLE
Use meteor up deployed to a server error

### ISSUE THREAD

**Issue by guoyoujin** [TelescopeJS/Telescope#1032]
Hello, when I use meteor up deployed to a server error, is this why, what are the best solution：

Started TaskList: Deploy app 'Telescope' (linux)
[120.24.175.154] - Uploading bundle
[120.24.175.154] - Uploading bundle: SUCCESS
[120.24.175.154] - Setting up Environment Variables
[120.24.175.154] - Setting up Environment Variables: SUCCESS
[120.24.175.154] - Invoking deployment process
^[^[^[[120.24.175.154] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	pm-bcrypt/node_modules/bcrypt',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	gyp info ok 
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	js-bson: Failed to load c++ bson extension, using pure JS version
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3434: Connection refused
	App did not pick up! Please check app logs.
	-----------------------------------STDOUT-----------------------------------
	: Leaving directory `/opt/Telescope/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
	
	> fibers@1.0.1 install /opt/Telescope/tmp/bundle/programs/server/node_modules/fibers
	> node ./build.js
	
	`linux-x64-v8-3.14` exists; testing
	Binary is fine; exiting
	underscore@1.5.2 node_modules/underscore
	
	semver@4.1.0 node_modules/semver
	
	fibers@1.0.1 node_modules/fibers
	
	eachline@2.3.3 node_modules/eachline
	└── type-of@2.0.1
	
	source-map-support@0.2.8 node_modules/source-map-support
	└── source-map@0.1.32 (amdefine@0.1.0)
	
	chalk@0.5.1 node_modules/chalk
	├── ansi-styles@1.1.0
	├── escape-string-regexp@1.0.3
	├── supports-color@0.2.0
	├── has-ansi@0.1.0 (ansi-regex@0.2.1)
	└── strip-ansi@0.3.0 (ansi-regex@0.2.1)
	Waiting for MongoDB to initialize. (5 minutes)
	{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
	connected
	Telescope stop/waiting
	Telescope start/running, process 11326
	Waiting for 6000 seconds while app is booting up
	Checking is app booted or not?

**Comment by SachaG** [comment]
This looks like an issue with Meteor Up, not Telescope. You can come ask for help in the #deployment channel of the [Slack chatroom](slack.telescopeapp.org).

**Comment by guoyoujin** [comment]
I try to open this page, page 404

**Comment by SachaG** [comment]
Sorry, http://slack.telescopeapp.org

**Comment by guoyoujin** [comment]
It doesn't matter, I appreciate your help

**Comment by guoyoujin** [comment]
I try to enter the page, you said I don't know how to find out the answer to me, and help
