### ISSUE TITLE
Add Saturdays Option to Newsletter Schedule

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#1034]
Set this up on my fork, but thought it might be another good option to have by default. At some point, it might be nice to have each day as a checkbox and allow for total control. In the meantime, this is what I add to [telescope-newsletter/lib/server/cron.js](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-newsletter/lib/server/cron.js#L30):

```
case 4: // Once a week (Saturdays)
  // sched = {schedules: [{dw: [7]}]};
  schedule = recur.on(7).dayOfWeek();
```

And then add the option to the [newsletterFrequency schema](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-newsletter/lib/newsletter.js#L151):

```
 {
  value: 4,
  label: 'Saturdays'
}
```

**Comment by SachaG** [comment]
Yeah, why not. Having a checkbox for each day might make more sense than the current options.
