### ISSUE TITLE
Autoupvoted comment

### ISSUE THREAD

**Issue by appigram** [TelescopeJS/Telescope#1035]
When user write comment inside a post, his comment upvoted automatically and upvoters counter add +1.
How I can fix this behavior? Thanks

**Comment by SachaG** [comment]
Fix it how the comment is not upvoted? I'm afraid that's just the way it works, sorry… Why do you need to change it?

**Comment by appigram** [comment]
I think it's a little strange when a user writes a comment and automatically receives Like for own comment. Now it returns status upvoted, when writing any comments, and I want to prevent this action.

**Comment by SachaG** [comment]
OK, I just pushed a commit to `devel` to make it easier to disable that behavior: https://github.com/TelescopeJS/Telescope/commit/31f3384e855b0f7f61787fdd5248b95455018d09

So once those changes are merged and published in the next version of Telescope, you should be able to just remove that callback with:

```js
Telescope.callbacks.remove("commentSubmitAsync", "upvoteOwnComment");
```

**Comment by appigram** [comment]
Thanks for your help!
