### ISSUE TITLE
Locale in bootstrap-datetimepicker?

### ISSUE THREAD

**Issue by appigram** [TelescopeJS/Telescope#1037]
Can I use the locale in calendar to be translated into the selected language, set the output format of the date and change icons of the calendar?

For example, {{> afQuickField name = 'postedAt' template = "bootstrap3-horizontal" label-class = "control-label postedAt" input-col-class = "controls postedAt" placeholder = "__ / __ / __ __: __" timezoneId = "Europe / Moscow" format = "dd-mm-yyyy" locale = "RU" buttonClasses="fa fa-calendar"}}

The package is not compatible with https://github.com/michaelbishop/meteor-bootstrap-datepicker ?

Thank you!

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
