### ISSUE TITLE
Option to show link to post rather than external URL in feed.xml

### ISSUE THREAD

**Issue by Scott-Hutcheson** [TelescopeJS/Telescope#1038]
It would be great to be able to optionally change the link within the feed.xml page for RSS feeds to show the URL of the page to comment on a post i.e.  {{url}}/posts/... instead of the current link shown which is {{url}}/out?url=http...

*Reason for doing this is I would like to set up Slack to automatically post when a new post is created on the community, and to automatically tweet a link to the new post on Twitter. This will be done using https://ifttt.com/recipes.*

**Comment by SachaG** [comment]
Any other places where you'd want to change it? Maybe when tweeting out/sharing the link?

**Comment by camilleroux** [comment]
To do it, you just have to create a custom RSS package and using this line : ```     url: post.getPageUrl(true),``` (in the servePostRSS function)

**Comment by azsmith** [comment]
@SachaG places it'd be great to be able to change it: rss feeds, email newsletters, sharing (twitter, fb, etc)

**Comment by camilleroux** [comment]
:+1:

**Comment by SachaG** [comment]
Fixed on `devel`.
