### ISSUE TITLE
Use custom data attributes for event handlers

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#1039]
Would you be open to converting event handlers to target something like `[data-js="subscribe-link"]`? In the long run I think separating style and behavior will make customization even easier.

If you're okay with this, I could work on this as I create my next theme.

**Comment by SachaG** [comment]
Why not, I'm not sure what the best practice is for this. We could also decide to prefix event classes with `js`, as in `class="js-upvote-link"`.

**Comment by jamiewilson** [comment]
Yeah. I'll look into it a bit to see if there's any real advantage to using data attributes as opposed to classes. The class syntax is certainly easier to write so the js- prefix might be better.

**Comment by xavcz** [comment]
Hey! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
