### ISSUE TITLE
Not getting slack invitation

### ISSUE THREAD

**Issue by sungwoncho** [TelescopeJS/Telescope#1044]
I have put my email address at http://slack.telescopeapp.org/ several times, but have not got invitation email. It's been a few hours.

Not sure if this is an issue with slackin in general.

**Comment by SachaG** [comment]
Sorry about that, Slackin had some issues in the beginning, but I thought they had been fixed. Email me at hello at telescopeapp dot org and I'll add you manually.

**Comment by sungwoncho** [comment]
Okay. I did.

**Comment by sungwoncho** [comment]
any news?

**Comment by SachaG** [comment]
I replied to your email. If you didn't get my reply and aren't getting the invites, it might be a problem on your end?

**Comment by Rastalamm** [comment]
I can't seem to get an invite either?

Getting some errors when I try and enter my email. I emailed you for a manual invitation but wanted to keep you updated here as well. 

Attached is a screenshot of 
<img width="1423" alt="screen shot 2015-09-20 at 11 15 32 pm" src="https://cloud.githubusercontent.com/assets/9030131/9995747/f30bce1e-6040-11e5-9c5a-e1b1f903727a.png">
the console errors I am receiving.
