### ISSUE TITLE
Google Analytics Tracking ID showing as "Tracking Not Installed"

### ISSUE THREAD

**Issue by sk4blink** [TelescopeJS/Telescope#1046]
Hi All,

I'm trying to add in Google Analytics to my Telescope based site and read that I can just add my Google Analytics ID via the admin settings panel. I tried just adding in my ID - UA-XXXXXXXX-X into the settings panel, but the Google Analytics interface is still reporting the status as "Tracking Not Installed". Does anyone have any suggestions? Do I need to add the full tracking code script somewhere as well?  Thanks!

**Comment by jshimko** [comment]
I just tested this on a fresh Telescope install and Google Analytics is working fine for me.  Is it possible their test isn't working and your tracking is working fine?  Do you see anything on the realtime dashboard?

**Comment by sk4blink** [comment]
Thanks for the reply! For some reason it took close to 48 hours for it to
report data but it seems to be pulling in now. Thanks for the follow up
here.
