### ISSUE TITLE
Creating wrong slug when editing post

### ISSUE THREAD

**Issue by delgermurun** [TelescopeJS/Telescope#1047]
http://meta.telescopeapp.org/posts/DEGEkPH8sKvJJemeP/less-than-p-greater-than-v0-21rc-slugscope-less-than-p

https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-posts/lib/callbacks.js#L30

**Comment by jshimko** [comment]
Fixed in this PR:  https://github.com/TelescopeJS/Telescope/pull/1049
