### ISSUE TITLE
Move useraccounts to the theme, please

### ISSUE THREAD

**Issue by queso** [TelescopeJS/Telescope#1048]
I want to use useraccounts:bootstrap instead of unstyled, but the new refactored telescope forces useraccounts:unstyled as part of telescope-libs... Is there any way we can move to to the hubble theme instead, so each package can decide what they want to use?

/cc @splendido

**Comment by jshimko** [comment]
I suppose we could just make that an optional package.  That'd probably be the most flexible approach (and the least amount of work!).

**Comment by queso** [comment]
I would probably argue against an optional package because 100% of the first time users will want it :)

I am betting even custom themes are generally ok with it, but useraccounts-bootstrap is better for me and bad things happen when both are installed (you get template duplicate naming issues for things like errors)

**Comment by jshimko** [comment]
I just mean it's installed by default, but users can remove it if they want.  Like the Embedly plugin, for example.

**Comment by jshimko** [comment]
Anything in the `.meteor/packages` file is technically optional and anything in the `telescope:lib` package.js is required.

**Comment by jshimko** [comment]
The only issue I can think of with having it as a dependency of the theme is someone could potentially want to use the theme, but not the `useraccounts:unstyled` package.  So they'd be in the same position as you are.  Having it in the `.meteor/packages` instead solves that for everyone.

**Comment by queso** [comment]
Looks like we are back to the drawing board here? If I send a PR to move this package requirement to telescope-theme-base, will you accept that as a solution?

**Comment by SachaG** [comment]
@queso yeah let's do it this way for now.

**Comment by xavcz** [comment]
You can do this easily by extending the components on Nova now 😃
