### ISSUE TITLE
Redirect /p/* URLs to /posts/*

### ISSUE THREAD

**Issue by camilleroux** [TelescopeJS/Telescope#1051]
Posts URLs have changed but there is no redirection to keep the old ones working.

Example:
- http://news.pragmaticentrepreneurs.com/p/SYL4NoKK5FXJhiuLy/cto-d-une-startup-en-creation-5-erreurs-a-eviter (Old URL that doesn't work any more)
-http://news.pragmaticentrepreneurs.com/posts/SYL4NoKK5FXJhiuLy/cto-d-une-startup-en-creation-5-erreurs-a-eviter (New URL)

**Comment by SachaG** [comment]
The `/p/` URL was just a temporary thing I tried out, I don't think it was ever released officially?

**Comment by camilleroux** [comment]
I deployed the i18n branch to get French translations, so it came probably from here
