### ISSUE TITLE
Translations are not being included properly

### ISSUE THREAD

**Issue by shangrila** [TelescopeJS/Telescope#1057]
Continued from here:
http://meta.telescopeapp.org/posts/s6s2hukH3FBEpMacX/translations-are-not-being-included-properly

Question on possible bug. I have clean Telescope installation with Polish language enabled via admin panel.

As you can see on the screenshot, some of translations are not included. Despite being present in files.

I've marked Polish words with red lines and English with blue ones.

"Receive the best of right in your inbox." is present in:

``/Telescope/packages/telescope-newsletter/i18n/pl.i18n.json``

```
{
  "receive_the_best_of" : "Otrzymuj najlepsze z",
  "right_in_your_inbox" : "prosto do twojej skrzynki.",
  "get_newsletter" : "Zapisz się do Newslettera",
  "thanks_for_subscribing" : "Dziękujemy!",
  "newsletter" : "newsletter",
  "showBanner" : "Pokaż Baner",
  "mailChimpAPIKey" : "MailChimp API Key",
  "mailChimpListId" : "MailChimp List ID",
  "postsPerNewsletter" : "Liczba postów przypadająca na jeden Newsletter",
  "newsletterFrequency" : "Częstotliwość Newslettera",
  "newsletterTime" : "Godzina, w której ma być wysłany Newsletter",
  "enableNewsletter" : "Włącz Newsletter",
  "autoSubscribe" : "Auto Subskrybcja"
}
```

From what I see adding any line (like "receive_the_best_of") to 
``/Telescope/packages/telescope-core/i18n/pl.i18n.json`` solves the problem. 

But I assume it should not be like this.

**Comment by SachaG** [comment]
Oh, it was actually a very simple reason: the translation files were not being loaded! Fixed on `devel`.
