### ISSUE TITLE
Modify main.html

### ISSUE THREAD

**Issue by appigram** [TelescopeJS/Telescope#1058]
Hi, How can I modify  or replace main.html . I need replace "Loading..." title and to add new meta tags.
Thanks!

**Comment by SachaG** [comment]
You can't modify main.html unless you replace the whole `telescope:core` package, sorry. But if you want to add new meta tags you can just add a `<head>` section to any html file that's included in your project (you don't need the `<template>` tag) and it will get picked up automatically.
