### ISSUE TITLE
Problems sending emails and newsletter signup

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1059]
I am experiencing problems with sending emails and newsletter signup on DigitalOcean. Has anyone had the same problem? Mailchimp is set up (api-ket and list set) but when I sign up I don't get a response nor do I see any new signups on my Mailchimp account. Also, I don't receive any emails when I request a password reset. Any ideas what the issue might be?

Thank you.

**Comment by jshimko** [comment]
Have you set your MAIL_URL?  That can be done either via environment variable or on the Telescope settings page.

http://telescope.readme.io/v0.20/docs/basic-configuration#email-setup

**Comment by demerino** [comment]
I've been seeing a similar issue on Digital Ocean. Newsletters were working before updating to the newest release - but no longer seem to be sending.

- Only newsletter emails are not sending
- Signup for newsletter is working (emails are added to list) and automation emails via mailchimp are working (email when user is added to list)
- Forgot password emails are working
- MAIL URL is set
- default email is set (tho no one is checking it)

Did something change with sending Newsletters?

https://github.com/TelescopeJS/Telescope/tree/master/packages/telescope-newsletter implies that a confirmation email is sent (to the default email?). Is it required to confirm the newsletter before it is sent? Is that new?

**Comment by SachaG** [comment]
What happens in your server logs when you call `Meteor.call('testCampaign')` from the browser console? 

And no, you don't need to confirm the newsletter.

**Comment by MHerszak** [comment]
@jshimko I just tried a couple different possibilities and no SMPT url worked. @SachaG: Meteor.call returns nothing on the server and undefined in the browser console. What else could I try? Thank you!

**Comment by demerino** [comment]
I just get `undefined` when issuing the command from the root url.
If I am on xxx.com/email/campaign I get a similar Meteor undefined error.

Do I need to be in `debug` mode?

**Comment by davedg629** [comment]
Having the same issue here.

I ran ```Meteor.call('testCampaign')``` in the browser console. No email showed up in my inbox (also checked spam folder) and no error reported to Kadira (and errors have been reporting successfully there).

I'm hosting with Heroku and packages are up to date.

**Comment by demerino** [comment]
Checked my server logs...
```
 { [Error: from_email - XXXXX.YYYYY.com must be verified to send from it. [311]]
 reason: 'from_email - XXXX.YYYY.com must be verified to send from it.',
  details: undefined,
  message: 'from_email - XXXX.YYYY.com must be verified to send from it. [311]',
  errorType: 'Meteor.Error' }
```

My URL domain is different from the from_email. How do I go about verifying this domain?

**Comment by MHerszak** [comment]
It seems this is a problem with DigitalOcean. I just got a confirmation email from MailChimp for a request that I did a day ago. That is so weird. Is that a DigitalOceans policy?

**Comment by SachaG** [comment]
Those are MailChimp errors. It means you need to verify the domain you're sending from with MailChimp.
