### ISSUE TITLE
Private messages

### ISSUE THREAD

**Issue by Madsn** [TelescopeJS/Telescope#1060]
I was looking through the open issues and couldn't find anything regarding messaging, i.e. private/direct messages between users.

Anybody else feel like this would be a nice addition, could be as a plugin if it's not suitable to be part of the core.

**Comment by SachaG** [comment]
This is not on the roadmap for the core, but yeah I could see it as a plugin. Could even be something that works in any Meteor app, not just Telescope.

**Comment by tenshis** [comment]
This would be great
