### ISSUE TITLE
meta description 

### ISSUE THREAD

**Issue by meichenblatt** [TelescopeJS/Telescope#1061]
Hi, 

I am trying create dynamic meta descriptions by grabbing the first 100 characters of each post and put it in a meta description on the page of that post. 

I see that you are using ms seo to display the title of each post; <meta property="og:title" content="Deploying Telescope | undefined">. 

I tried adding the dynamic description it but it gave me an error because I can't define a route twice. 

I was wondering if you can add it or give me some direction on how  can do it.

Thank you!

**Comment by SachaG** [comment]
I would accept a PR to add the meta description, it's a good idea.

**Comment by meichenblatt** [comment]
Thank you! You are the Man!

**Comment by meichenblatt** [comment]
Is there a certain protocol I need to follow for a pull request?

**Comment by SachaG** [comment]
Just make sure to do it on the `devel` branch :)

**Comment by SachaG** [comment]
Done :)
