### ISSUE TITLE
Duplicate requests

### ISSUE THREAD

**Issue by appigram** [TelescopeJS/Telescope#1062]
Hi,
I found in browser console that Telescope sends repeated queries

https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/lang/ru.js?_=1436308155053
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/lang/ru.js?_=1436308155054

and

https://example.com/tap-i18n/ru.json
https://example.com/tap-i18n/ru.json

How to avoid this?

Thanks!

**Comment by SachaG** [comment]
I haven't noticed this personally. Closing this for now, unless you can provide a screencast/screenshot of this happening?
