### ISSUE TITLE
Search field problematic for keyboard-only users

### ISSUE THREAD

**Issue by ndarilek** [TelescopeJS/Telescope#1063]
As a blind user, I find myself arrowing through Telescope sites to pass the search field. Only, I notice that I often find myself on the /search route without having consciously done anything to get there. I dug in the code and found this in the keyup event handler:

    'keyup .search-field, search .search-field': function(e){
      e.preventDefault();
      var val = $(e.target).val(),
          $search = $('.search');
      if (val === '') {
        // if search field is empty, just do nothing and show an empty template
        $search.addClass('empty');
        Session.set('searchQuery', '');
        Router.go('search', null, {replaceState: true});
      } else {

Seems like you're tracking empty search values, but you're still redirecting to the search route. Maybe the assumption is that all keyboard input triggers a search, but this isn't true for keyboard-only screen reader users examining the site via arrows and just so happening to be on the search field.

Not sure what the best fix is:

 * Leave the existing route intact if the field is empty. Perhaps navigate to the previous route if the user is on the search page already and clears the field. The idea is that clearing the search field should restore the app's previous state, but either way it needs to not trigger just because the user presses an arrow on the search field.
 * Don't change the route at all if the field is empty.
 * Don't change the route if the new field value equals the old value. This should handle keyboard navigation, tab traversal, empty fields, etc. but would require tracking previous state of the field. Also, don't change to the search route if the field is empty.

Hoping this can be resolved as it's something I'm regularly hitting on Telescope sites. Even so, it's definitely among the friendliest community packages I've used in light of all the previous a11y fixes. :)

**Comment by SachaG** [comment]
Thanks for the bug report, I'll look into it. And thanks again for your huge help with a11y!

**Comment by SachaG** [comment]
I just pushed a fix, sorry it took so long! I just stopped changing route at all if the field is empty. 

I don't know how it feels from a UX perspective though. Maybe a manually-triggered search would be easier to work with.
