### ISSUE TITLE
Integrate Telescope with other meteor app

### ISSUE THREAD

**Issue by nikhildaga** [TelescopeJS/Telescope#1066]
I would like to share the users collection between my main meteor app and telescope. By that I mean, whenever a user registers on the main app, he/ she should be able to login with the same username / password.

There is a similar question on http://stackoverflow.com/questions/28135868/can-i-use-the-same-db-for-multiple-meteor-apps and some answers.

I am sure many others would like to have this functionality.

Can you please guide the correct way to do it. Maybe add it to documentation.

Thank you!

**Comment by SachaG** [comment]
There's a related question and solution here: https://github.com/TelescopeJS/Telescope/issues/963

I haven't tried it myself so I haven't had a chance to add a tutorial to the docs yet. But maybe you can give it a try.
