### ISSUE TITLE
Browser history and back button not working properly

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#1068]
Not exactly sure how to explain what's going on here, but it appears the new post slugs and history api might be messing with the back button functionality. Maybe [this bit needs to use pushState](https://github.com/TelescopeJS/Telescope/commit/082b7043710c5b9dde86f2f1da085d1fedf5c1ce#diff-25780e8ce35fb7ef60f8c6145d490babR157) instead of replaceState? I can take a look at it later as well.

Watch it in action here: http://quick.as/n89bsvzmv

**Comment by SachaG** [comment]
That might be happening because you're not using the full URL in your post links. Make sure you use `{{pathFor 'post_page'}}` and not just `/posts/{{_id}}`. 

Not sure why that causes this bug, but I think changing this should fix it.

**Comment by jamiewilson** [comment]
Ah. Okay, I'll check that out.
