### ISSUE TITLE
Custom Field name shown instead of label on profile page

### ISSUE THREAD

**Issue by Scott-Hutcheson** [TelescopeJS/Telescope#1070]
When adding a custom field with labels, the labels are not shown when viewing the profile page (User_info). Instead, the field name is displayed.

For example, for the following custom field, "cx.company" is shown on the profile page where "Company" is expected to be shown.

```javascript
Users.addField({
    fieldName: 'cx.company',
    public: true,
    fieldSchema: {
        type: String,
        optional: true,
        label: "Company",
        public: true,
        profile: true,
        editableBy: ["member"]
    }
});
```

**Screenshot from profile page user info shown below:**

![profile_example](https://cloud.githubusercontent.com/assets/7217244/8671712/6516b95e-2a1f-11e5-9603-518960fb7c26.png)

**Comment by almogdesign** [comment]
I'm having the same issue?

**Comment by almogdesign** [comment]
Any news regrading this?

**Comment by SachaG** [comment]
You could submit a PR :)

**Comment by almogdesign** [comment]
What view is that at I will take a look at it?

**Comment by SachaG** [comment]
I guess something is wrong here: https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-users/lib/client/templates/profile/user_info.html#L13
