### ISSUE TITLE
Match failed [400] when trying to complete Twitter signup (on meta.telescopeapp.org)

### ISSUE THREAD

**Issue by jschuur** [TelescopeJS/Telescope#1071]
I'm stuck signing up via Twitter, and get Match failed [400] when I try and complete my profile with my email address.

I ran into this problem on Telescope Meta, but since I can't complete my registration there, I can't post there specifically about it.

After I hit reply to comment on a thread, I realized I never signed up for an account, so went to create one, connected my Twitter account (@joostschuur), and saw this screen after I authorized Twitter via the pop-up and provided my email address to complete the signup.

I see the same prompt every time I return to the Meta Telescope site, and it doesn't matter if I give it a different email address, so it doesn't look like it's related to that one being in use. Trying to reset my password leads to an error that that user isn't known.

**Comment by SachaG** [comment]
Oh yeah, I'm testing some stuff on the devel branch, sorry about that. I'll fix it tomorrow :)

**Comment by jschuur** [comment]
Confirmed as fixed on my end. Thanks, Sascha!
