### ISSUE TITLE
Admin(s) should get a notification when a post is submitted and pending

### ISSUE THREAD

**Issue by capensisma** [TelescopeJS/Telescope#1078]
Hello,

I think this is a must : Admin(s) should get a notification when a post is submitted and pending because if not many times we miss the post submitted by the users and get lost or forgotten.

A simple notification like : username submitted post_name and it's waiting your approval!

Thanks

**Comment by SachaG** [comment]
That should be in there already. Is it not working?

**Comment by capensisma** [comment]
I never saw the notification to be honest
How can we add notification on events/actions ?

Can we have this it will be awesome 

thanks
