### ISSUE TITLE
Removing deleted user from Mailchimp list

### ISSUE THREAD

**Issue by agnitin** [TelescopeJS/Telescope#1079]
If a user is deleted, it is not automatically un-subscribed from the mailchimp list. If the user tries to register again with the same email, there is a login error that user is already subscribed. Think it would make sense to un-subscribe the user automatically on deletion

**Comment by jms301** [comment]
The pull request does still leave the situation where an e-mail address is changed, leaving the mailchimp newsletter with the old one. Presumably in that situation the old address should be removed and new one then added. 

You'd need a 'onUserChange' hook to do this cleanly though, wasn't sure if that was warranted.

**Comment by capensisma** [comment]
> The pull request does still leave the situation where an e-mail address is changed, leaving the mailchimp newsletter with the old one

No look the commented code at the end, It takes all cases when the user updated the email and even unsub

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
