### ISSUE TITLE
Admin Users 

### ISSUE THREAD

**Issue by Leeibrah** [TelescopeJS/Telescope#1082]
Hi,

I can get the app running but I cannot moderate the app like the admin. How can I get the Admin username and password or how do I create one?

NB: Can I also use MYSQL as my database instead of MongoDB?

**Comment by azizur** [comment]
The first account you create will be an admin account.

As of now it's not possible to use MYSQL.

**Comment by Leeibrah** [comment]
Thank you azizur. I had not noticed that until I saw the URL routing to see the first user was admin.

As for MYSQL part it is important because it is one of the most popular DB around.

**Comment by griiettner** [comment]
+++1 for MySQL database integration... I'm going through the files here to see how I could plug the meteor MySQL package... but so far no luck... I'll try to use Redux on this project and send to React... I know this is not the right thing to do... We have a very large MySQL database, with over 400k Articles, 50k users and 60k products... 

To change our front end and backed to NodeJS based platforms was not issue, but database must remain MySQL... I saw few examples around using MySQL and Meteor and it works great... So... I'll give a try... If you could just point a way where to start integrating another source of data, would be very helpful....

**Comment by xavcz** [comment]
@griiettner well, trying to plug meteor mysql package (I didn't even know it existed) like this wouldn't work. However, do you know Apollo? 

https://github.com/apollostack/ 
http://www.apollostack.com/

It's a modern data stack made by MDG folks (people behind Meteor), working with GraphQL and giving you the ability to query any kind of data source (rest, mongo, mysql, etc.). 

We've just started a branch https://github.com/TelescopeJS/Telescope/tree/apollo to work on that. Moreover, the Apollo's React integration cohabits with the Redux store. 

I've made a basic Redux try for Nova's flash messages, we'll see where it leads! Feel free to pull down and contribute.  

However we may not focus on integrating MySQL first, I guess it'll come down the road later.

Here is some info about Nova-pollo : https://gist.github.com/SachaG/d9380036bc7dc008a81dc02d342c6cdc

**Comment by griiettner** [comment]
@xavcz thanks for you reply... I'll definitely take a look and the new branch and contribute with what ever I can and my knowledge allows to... hehehe... Having GraphQL as the interface to manage data is great, because it allows the developer choose what ever source of data is best...

Thanks again and like I said... I'll check it out the new repo...
