### ISSUE TITLE
Up-voting resets number of articles shown on page

### ISSUE THREAD

**Issue by Scott-Hutcheson** [TelescopeJS/Telescope#1085]
Initially, 10 articles are displayed.
If I then click on "Load More", I see 20 articles.
Then, if I up-vote any article, the page reverts to 10 articles again.

**Comment by SachaG** [comment]
Oh you're right, that's definitely not the expected behavior. I'll look into it.

**Comment by Scott-Hutcheson** [comment]
@SachaG I had a look at a couple of other telescope sites. It is happening on http://meta.telescopeapp.org/ and my site www.customerexperience.io.

 However, it is not occurring on http://shaped.io. Also I can't be certain but I don't think it was happening prior to update to Telescope V0.22.1.

Thanks for quick response.

**Comment by SachaG** [comment]
Fixed it: https://github.com/TelescopeJS/Telescope/commit/346f50d52bdcf6ec8f5a2c86587dd46d9fb83f80

If you're running from the git repo you can just `git pull`, otherwise I'll push it to Atmosphere tomorrow.
