### ISSUE TITLE
User bio field not showing up under the user profile 

### ISSUE THREAD

**Issue by almogdesign** [TelescopeJS/Telescope#1087]
Under user profile there is no user bio field but when you edit user profile you can see the user bio option. 

![screen shot 2015-07-29 at 3 53 36 pm](https://cloud.githubusercontent.com/assets/169507/8957889/25191cc4-360a-11e5-89f6-322b1567e32e.png)
 
![screen shot 2015-07-29 at 3 53 49 pm](https://cloud.githubusercontent.com/assets/169507/8957892/28964066-360a-11e5-9021-55144712142f.png)

**Comment by SachaG** [comment]
Actually I see the bio field right there in your screenshot? Also I just tested it and it works as far as I can tell.

**Comment by almogdesign** [comment]
Not that is incorrect what your seeing was a test of me trying to add a custom field here is a screenshot showing it's not working and is a bug 
![screen shot 2015-08-02 at 3 10 26 pm](https://cloud.githubusercontent.com/assets/169507/9026042/e2923fda-3928-11e5-9750-cd7485cc2ea1.png)

**Comment by SachaG** [comment]
Not sure what to tell you, it does work for me… Although note that the field that gets displayed is `htmlBio`, not `bio` itself. Maybe that has something to do with it?

**Comment by SachaG** [comment]
Seems to be the same issue as #987
