### ISSUE TITLE
gifv file with imgur link not playing on mobile

### ISSUE THREAD

**Issue by juliankim** [TelescopeJS/Telescope#1088]
When you click on a thumbnail of gifv file on mobile. It 'tries' to play it if it's imgur but it can't. It doesn't seem to be able to resize too. So I think it's better to either make it work or go to the outgoing link if it's mobile.

**Comment by juliankim** [comment]
Plus, I found out it's not just gifv file on imgur, it happens on youtube thumbnail too (not always but pretty often).

**Comment by SachaG** [comment]
Actually I'm just going to remove the video light box for non-youtube and vimeo links, since they're not well supported by Embedly and FitVids.

**Comment by juliankim** [comment]
Nice!
