### ISSUE TITLE
Custom view not showing post navigation

### ISSUE THREAD

**Issue by almogdesign** [TelescopeJS/Telescope#1089]
When you create a custom view for example "top 15 posts" or "flagged posts" that view will not show the post navigation I also tried adding the following to the custom view template but it did not work 

{{> posts_views_nav}}

**Comment by SachaG** [comment]
The way this is handled will change soon. You can already try this on the `devel` branch actually:

```js
_.findWhere(Telescope.modules.top,{template: "posts_views_nav"}).only.push("postsDaily");
```

This basically tells the `posts_views_nav` template to be included on the `postsDaily` route.
