### ISSUE TITLE
mutating the [[Prototype]] of an object

### ISSUE THREAD

**Issue by graphific** [TelescopeJS/Telescope#1094]
debugging the js I get one warning at the c.materializeView function:
_mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create_

The line (disentangled as its minified) which it refers to:

<pre>!function(){
    var e=Package.meteor.Meteor,
    r=Package.underscore._,
    n=Package.mongo.Mongo;
    (
        function(){
        n.Collection.prototype.helpers=function(n){

            var o=this;
            if(o._transform&&!o._helpers) throw new e.Error("Can't apply helpers to '"+o._name+"' a transform function already exists!");

            o._helpers||(
                o._helpers=function t(e){return r.extend(this,e)},
                o._transform=function(e){
                return new o._helpers(e)}
            )
            ,r.each(
                n,function(e,r){
                    o._helpers.prototype[r]=e
                }
            )

        }

        }
    ).call(this),
    "undefined"==typeof Package&&(Package={}),Package["dburles:collection-helpers"]={}
}
();</pre>

[Stackoverflow](http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance) basically says that _"changing the prototype chain of an already existing object kills optimisations. Instead, you're supposed to create a new object with a different prototype chain via Object.create()."_

Im not sure about this: does this affect performance in any bad way, or (as it looks to me) refers to the way in which Telescope has helper prototypes, and so this is happening by design?

**Comment by SachaG** [comment]
The `materializeView` function is not part of the Telescope codebase, so I don't think this is the right place for this issue?

**Comment by graphific** [comment]
k tnx, will continue the quest for performance :)
