### ISSUE TITLE
Facebook sign-up not retreiving users email

### ISSUE THREAD

**Issue by donmarcello** [TelescopeJS/Telescope#1096]
When signing up via Facebook, Telescope is not retrieving the users email, asking in the second step (user_complete) to enter the email.

In the Users collection, the email along with other info is stored during initial signup, even before the user_complete, like this:

    {
    _id: "sdnlksgmklrmsdn",
      createdAt: ISODate("2015-08-06T06:43:41.011Z"),
      services: {
    facebook: {
      accessToken: "YOLOLOLOLOLOLOLOLO",
      expiresAt: 1444027419810,
      id: "123456789",
      email: "dave@tfbnw.net",
      name: "Dave Yolo",
      first_name: "Dave",
      last_name: "Yolo",
      link: "https://www.facebook.com/app_scoped_user_id/12345789/",
      gender: "male",
      locale: "de_DE",
      age_range: {
        min: 21
      }
    },
    resume: {
      loginTokens: [
        {
          when: ISODate("2015-08-06T06:43:43.542Z"),
          hashedToken: "YOLOLOLOLO/KSIkxHJr6StbBPH0="
        }
      ]
    }
      },
      profile: {
        name: "Dave"
      },
      telescope: {
        karma: 0,
        isInvited: false,
        postCount: 0,
        commentCount: 0,
        invitedCount: 0,
        upvotedPosts: [],
        downvotedPosts: [],
        upvotedComments: [],
        downvotedComments: [],
        displayName: "Dave",
        slug: "dave",
        inviteCount: 3,
        notifications: {
        users: false,
        posts: false,
        comments: true,
        replies: true
        }
          },
     isAdmin: false
    }

**Comment by xavcz** [comment]
Hey, @donmarcello! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And now we are using a workaround for this issue 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
