### ISSUE TITLE
Create setting for errorUrl param in embed.ly (Fallback when can't get thumbnail image)

### ISSUE THREAD

**Issue by nhtera** [TelescopeJS/Telescope#1097]
Please add more setting errorUrl for thumbnail when error occur in embed.ly.
Doc: http://embed.ly/docs/api/display/endpoints/1/display/resize

E.g:
Error thumbnail: http://i.embed.ly/1/image/crop?url=http%3A%2F%2Fnld2.vcmedia.vn%2Fthumb_w%2F540%2F2015%2Fanh-nguyen-tat-thanh-1438867369091.jpg&key=1790f14b1264426e8b308b1b96c55e97&width=80&height=50
Fallback with errorUrl param:
http://i.embed.ly/1/image/crop?url=http%3A%2F%2Fnld2.vcmedia.vn%2Fthumb_w%2F540%2F2015%2Fanh-nguyen-tat-thanh-1438867369091.jpg&errorUrl=http%3A%2F%2Fi.imgur.com%2FgRHibuN.png&key=1790f14b1264426e8b308b1b96c55e97&width=80&height=50

Or try use embedkit.com for extract info and rethumb.com service for thumbnail image
I think rethumb solve problem with image hosting prevent download: e.g: http://api.rethumb.com/v1/width/80/height/50/http://nld2.vcmedia.vn/thumb_w/540/2015/anh-nguyen-tat-thanh-1438867369091.jpg

**Comment by xavcz** [comment]
Hey, @nhtera! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
