### ISSUE TITLE
Not keep state of items (load more) when back in browser

### ISSUE THREAD

**Issue by nhtera** [TelescopeJS/Telescope#1101]
When I click to comment or edit -> back to pre page -> it will reload page and can't keep items.

There are obvious differences between the two sites. http://demo2.telescopeapp.org (not keep) and http://try.discourse.org (keep state)

**Comment by xavcz** [comment]
Hey, @nhtera ! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
