### ISSUE TITLE
Slow performance on Android

### ISSUE THREAD

**Issue by rclai** [TelescopeJS/Telescope#1105]
Has anyone noticed slow performance on Android using the Chrome browser? Or is it just crater.io's performance or a combination of both?

**Comment by juliankim** [comment]
I also have that problem too. It takes about 10 seconds to load on mobile while it loads in a sec on PC, have tested on two different Android phones. Also, do you have issues with gifv(always), youtube(often) thumbnails? when I try to play on site, it can't resize and it covers the whole website and doesn't even close when I hit back button on the phone.

**Comment by juliankim** [comment]
There are big three things that need some enhancements on mobile (android). 
1. First loading - takes about 10 sec
2. 'Load more' - quite serious, takes 3-7 sec
3. 'Back' on mobile needs to be much more responsive - this is quite serious, when I press back button on phone it takes at least 3 sec to actually go back. Of course many people would press back button again which will get them somewhere that they don't want to end up at.

**Comment by rclai** [comment]
Same. All the slow points are when I click on a link. It takes seconds for the link to open up in a new tab as well as to see the discussions on the link.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And it's blazing fast with React now 🎉 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
