### ISSUE TITLE
Package constraint error

### ISSUE THREAD

**Issue by cloudunicorn** [TelescopeJS/Telescope#1108]
Getting this on what you just released:

While selecting package versions:
   error: Conflict: Constraint utilities:avatar@0.8.3 is not satisfied by utilities:avatar 0.8.2.
   Constraints on package "utilities:avatar":
   * utilities:avatar@0.8.3 <- telescope:lib 0.23.0 <- telescope:comments 0.23.0 <- telescope:core 0.23.0
   * utilities:avatar@0.8.3 <- telescope:lib 0.23.0 <- telescope:core 0.23.0

**Comment by SachaG** [comment]
Good catch, seems like version 0.8.3 of the avatar package isn't actually published to Atmosphere yet. Can you run `meteor update` and let me know if it's fixed?

**Comment by xavcz** [comment]
All good now on Nova 🎉
