### ISSUE TITLE
Speed is slow on new release version v0.23

### ISSUE THREAD

**Issue by goseivietnam** [TelescopeJS/Telescope#1109]
I don't know what is happening but apparently after updating the website seems to run heavier.
https://github.com/TelescopeJS/Telescope/releases/tag/v0.23
When clicking on the "load more" I now have to wait 3 to 4 seconds.
This is my site: https://whatishot.news/

**Comment by SachaG** [comment]
I don't think it can be related to this specific update, I didn't change anything that would affect speed. Also your site seems fast enough to me? I'll close this for now unless you have more details.
