### ISSUE TITLE
'Back' button on phones

### ISSUE THREAD

**Issue by juliankim** [TelescopeJS/Telescope#1110]
When you're watching opened-up thumbnail(youtube) and press 'back' button on phone, wouldn't it be reasonable to close it instead of actually going back the whole page? Also, youtube videos go off the screen sometimes on mobile that you can't press x button too, so pressing 'back' button would be the most reasonable thing users can do in that case.

**Comment by xavcz** [comment]
Hey, @juliankim! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
