### ISSUE TITLE
One click install doesn't work anymore

### ISSUE THREAD

**Issue by lawwantsin** [TelescopeJS/Telescope#1112]
-----> Fetching custom git buildpack... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
                                                                         2.5%##                                                                         3.9%######                                                              17.9%##########                                                             19.2%#########                                                        26.2%############                                                        26.3%#################                                                  33.8%#######################                                         46.5%##############################                                 57.4%##################################                               60.6%#####                          67.0%#######################################################               83.1%#####################################################################    98.3%###################################################################   99.6%################################################################### 100.0%
Meteor 1.1.0.3 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack_fb92cfe97cf322bc903a4df4a5f0ae7c/meteor-ktdI/.meteor/packages/meteor-tool/1.1.4/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
-----> Building Meteor with ROOT_URL: csftelescope.herokuapp.com
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app

I've tried it with a number of different URLs.  With and without http:// at the front.  I'm stumped.

**Comment by SachaG** [comment]
The repo might be broken, but also sometimes it just randomly doesn't work… and then works again if you try later.

**Comment by xavcz** [comment]
Hey, @lawwantsin! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
