### ISSUE TITLE
User profile image isn't working after I change profile image on Twitter

### ISSUE THREAD

**Issue by davedg629** [TelescopeJS/Telescope#1113]
I registered my user account on my Telescope app using my Twitter account. As expected, Telescope pulled my Twitter profile image and used it for my Telescope profile image. Since then, I updated my Twitter profile image and now my Telescope profile image doesn't work anymore.

You can see the issue on my profile page here - http://www.timferrissfanclub.com/users/dave-digiovanni

From what I can see by looking at the HTML, it's still trying to pull the old image, which doesn't exist on Twitter's servers anymore.

**Comment by SachaG** [comment]
The image grabbing happens at the framework level, I think that problem is going to be common to all Meteor apps. I'm afraid right now there's no workaround besides manually changing the URL in the database, sorry…

**Comment by davedg629** [comment]
Ah gotcha. I'll report the issue to the appropriate Meteor plugin then. Thanks.
