### ISSUE TITLE
Remaining camel cased templates: postsListIncoming, postsLoadMore, menuComponent, menuItem, commentsListController

### ISSUE THREAD

**Issue by yourcelf** [TelescopeJS/Telescope#1118]
A quick search reveals several templates that still have camelCase names as opposed to underscore_separated names  (the [intro blog post](http://www.telescopeapp.org/blog/telescope-v020-refactorscope/) for v0.20 indicates all template names should now be underscore separated):

    telescope-posts/lib/client/templates/posts_list/posts_list.html
    43:<template name="postsListIncoming">
    53:<template name="postsLoadMore">

    telescope-core/lib/client/templates/menu/menu_component.html
    41:<template name="menuComponent">
    82:<template name="menuItem">

    telescope-comments/lib/client/templates/comments_list/comments_list_controller.html
    1:<template name="commentsListController">

Renaming these  would be a breaking change for any theme developer who has overridden them, so change should probably come with some documentation or announcement. :)

(In adition to the above, there are several AutoForm-related templates that still use camelCase -- these will need to stay in camel case to properly function with AutoForm.)

**Comment by SachaG** [comment]
These templates are a bit special as they're "components", i.e. meant to be reusable throughout the app, or maybe even in different apps. That's why I left their name in camelCase, at least for now.

**Comment by xavcz** [comment]
No more templates now, hourra components 🎉
