### ISSUE TITLE
Users.getSubParams duplicates Users.pubsub.getSubParams; neither appear to be used

### ISSUE THREAD

**Issue by yourcelf** [TelescopeJS/Telescope#1119]
While working on customizations to user permissions for our theme, I found that both [telescope-users/helpers.js](https://github.com/TelescopeJS/Telescope/blob/cb095e966307b2feb5a6c3fec6438efcae98cc6b/packages/telescope-users/lib/helpers.js#L227-L270) and [telescope-users/pubsub.js](https://github.com/TelescopeJS/Telescope/blob/cb095e966307b2feb5a6c3fec6438efcae98cc6b/packages/telescope-users/lib/pubsub.js#L58-L101) have identical definitions of a ``getSubParams`` function.  The functions assume that admin-status is defined by the ``isAdmin`` property on the user, rather than using an abstraction like the ``Users.is.admin`` function.

However, I can't find anywhere that either of these functions are used.  Are they vestigial?

**Comment by SachaG** [comment]
Huh. I can't remember what these functions are supposed to do… I guess we can always keep one of them just in case it comes back to me :)

**Comment by xavcz** [comment]
All good now on Nova 🎉
