### ISSUE TITLE
setupUser callback doesn't use ``updateAdmin`` abstraction

### ISSUE THREAD

**Issue by yourcelf** [TelescopeJS/Telescope#1122]
The ``setupUser`` callback [assigns the first-ever registering user as an admin](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-users/lib/callbacks.js#L117).  It does so without using the [``Users.updateAdmin``](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-users/lib/helpers.js#L273-L275) helper, which means that packages attempting to redefine what confers admin status won't get this benefit.

Fixing it is tricky, though, because when that callback is called, the user model doesn't exist yet (hasn't been saved yet), and ``Users.updateAdmin`` only works for existing users.  We don't have an appropriate hook that will fire once the user exists.

This is probably not a huge deal: the only affected users will be those who have customized their admin definition already, and only if they needed a first-ever logging in user to be given admin status (which they could always do manually in their codebase, or via the mongo shell, or whatever).  Seems like it may not be worth a lot of hassle to fix it -- my only real worry is trying to avoid other parts of the codebase not using ``isAdmin`` abstractions where it would matter more, based on the example here.

**Comment by SachaG** [comment]
Yeah, I think it's probably a niche issue and we can leave it as it is. But good point about consistently using the abstractions. I'll try to be more careful :)
