### ISSUE TITLE
Not show the counts of pending posts in the category. Only Approved posts should be counted.

### ISSUE THREAD

**Issue by abhaytalreja** [TelescopeJS/Telescope#1125]
The new category count is great! but if you enable category counts and pending posts... the imported feeds adds up to the posts count, cause the are already created. But, not yet approved. I think we should add a conditional logic to only count approved Posts when approval is needed.

**Comment by abhaytalreja** [comment]
Also, when you delete a Post, the count doesn't get updated. On deleting a post the count should be reduced.

For now, i categorized the getting started post... and then used 
```Meteor.call('removeGettingStartedContent');```

It should technically, remove the category from the left menu display.

Is there a way to not show the counts, may be another settings attribute?

**Comment by SachaG** [comment]
Working on this. And you can hide the counts using CSS and `display:none`.

**Comment by abhaytalreja** [comment]
Another scenario for testing - Hiding the counts is not a problem... the whole display logic of the categories is dependent on the counts... the problem now is when i deleted some of the posts, counts (tracked at category level) still have a value and the categories show up...

Great to hear, you already working on it.. waiting for the update...
