### ISSUE TITLE
On adding a new menu item in "userMenu" the record comes but the href is missing.

### ISSUE THREAD

**Issue by abhaytalreja** [TelescopeJS/Telescope#1126]
In a custom package, when i just try to add any new entry for the userMenu it doesn't set the href. So the link doesn't work.. Here is a sample code...

```
{
    route: 'reports',
    label: 'Reports',
    description: 'Reports',
    adminOnly: true
  }
```

**Comment by xavcz** [comment]
I won't tell my speech I send in old issue, I know you know @abhaytalreja that we run on Nova now  👯 

Currently cleaning old stuff, I'm closing this 👍
