### ISSUE TITLE
Fails at deployment state

### ISSUE THREAD

**Issue by adamisdead** [TelescopeJS/Telescope#1128]
Any ideas on what I'm doing wrong?  Sorry, I'm a noobie for certain:
If I sudo, I get a bunch of mongo connectivity errors, if I don't, this:

/home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EACCES, open '/home/adam/.meteorsession'
    at Object.Future.wait (/home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as readFile] (/home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:1350:24)
    at readSessionData (/home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/auth.js:134:27)
    at Object.exports.getSessionId (/home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/auth.js:845:32)
    at /home/adam/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/stats.js:64:23
    - - - - -

=> Build Error. Check the logs printed above.
adam@ADAMLINUX:~$ 

Sudo attempt:
------------------------------------------------------------------
Started TaskList: Deploy app 'meteor' (linux)
[107.170.220.154] - Uploading bundle
[107.170.220.154] - Uploading bundle: SUCCESS
[107.170.220.154] - Setting up Environment Variables
[107.170.220.154] - Setting up Environment Variables: SUCCESS
[107.170.220.154] - Invoking deployment process
[107.170.220.154] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	fault',
	gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.36',
	gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
	gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	gyp info ok 
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	
	/usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
	    throw err;
	          ^
	Error: TIMEOUTED_WAIT_FOR_MONGO
	    at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
	    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
	-----------------------------------STDOUT-----------------------------------
	-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	wait-for-mongo: auth failed
	----------------------------------------------------------------------------

**Comment by haraldur12** [comment]
Can you check your password again ? It seems like you have made a typo somewhere. Then try using MUPX for deploying. I had to deal with this problem for a long while but switching from mup to mupx solved the problem for me. However in this case it seems like you have mistyped your password.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
