### ISSUE TITLE
Subscribe to comment thread not working.

### ISSUE THREAD

**Issue by sohanking** [TelescopeJS/Telescope#1129]
Even after creating a new Telescope app the Subscribe to comment thread is not working. In the previous version when i click on that, it would change but give an error message in the server logs.
![error](https://cloud.githubusercontent.com/assets/11256375/9712777/ae535a8e-556a-11e5-93d1-3653e4524b0b.png). So i tried using a new app and it wont even change when clicked. Gives a new error message. 
`
I20150907-14:02:58.866(5.5)?
I20150907-14:03:02.952(5.5)? Exception while invoking method 'subscribePost' Err
or: Match error: Expected string, got object
I20150907-14:03:02.953(5.5)?     at checkSubtree (packages/check/match.js:159:1)

I20150907-14:03:02.953(5.5)?     at check (packages/check/match.js:32:1)
I20150907-14:03:02.953(5.5)?     at [object Object].Meteor.methods.subscribePost
 (packages/telescope:subscribe-to-posts/lib/subscribe-to-posts.js:132:1)
I20150907-14:03:02.954(5.5)?     at [object Object].methodMap.(anonymous functio
n) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
I20150907-14:03:02.954(5.5)?     at maybeAuditArgumentChecks (packages/ddp/lived
ata_server.js:1617:1)
I20150907-14:03:02.954(5.5)?     at packages/ddp/livedata_server.js:648:1
I20150907-14:03:02.955(5.5)?     at [object Object]._.extend.withValue (packages
/meteor/dynamics_nodejs.js:56:1)
I20150907-14:03:02.955(5.5)?     at packages/ddp/livedata_server.js:647:1
I20150907-14:03:02.956(5.5)?     at [object Object]._.extend.withValue (packages
/meteor/dynamics_nodejs.js:56:1)
I20150907-14:03:02.956(5.5)?     at [object Object]._.extend.protocol_handlers.m
ethod (packages/ddp/livedata_server.js:646:1)
I20150907-14:03:02.967(5.5)? Sanitized and reported to the client as: Match fail
ed [400]
I20150907-14:03:02.968(5.5)?`

**Comment by jms301** [comment]
This exception is from code [here](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-subscribe-to-posts/lib/subscribe-to-posts.js#L130) 

But the root cause is the change to make moduleData explicitly set the module is set [here](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-subscribe-to-posts/lib/subscribe-to-posts.js#L40) and has no data context so the remote method call [here](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-subscribe-to-posts/lib/client/templates/post_subscribe.js#L14) has no data context.

**Comment by jms301** [comment]
Last post was incorrect on the location where the module is created, but it does indeed have no data-context. See [here](https://github.com/TelescopeJS/Telescope/pull/1135/files) for the fix.

**Comment by sohanking** [comment]
I tried by creating a custom_comment_list.html and replacing 
-  {{> modules "commentThreadBottom"}}
+  {{> modules zone="commentThreadBottom" moduleData=this}}
as you said but it wont work. Am i doing anything wrong. Please let me know the correct way. Thank you.

**Comment by jms301** [comment]
A custom template worked when I tried it did you also change the template name? 

```<template name="custom_comment_list">```

**Comment by sohanking** [comment]
yes,
<template name="custom_comment_list">
  <ul class="comments comment-list" aria-live="polite">
    {{#each child_comments}}
      {{> comment_item}}
    {{/each}}
  </ul>
  {{> modules zone="commentThreadBottom" moduleData=this}}
</template>
This is the code i used.

**Comment by jms301** [comment]
If I put the file `custom_comment_list.html` in the root of the telescope directory with contents: 


```<template name="custom_comment_list">
  <ul class="comments comment-list" aria-live="polite">
    {{#each child_comments}}
      {{> comment_item}}
    {{/each}}
  </ul>
  {{> modules zone="commentThreadBottom" moduleData=this}}
</template>```

I can subscribe to posts and it seems to work.

**Comment by sohanking** [comment]
ok will try again..Thank you.

**Comment by SachaG** [comment]
@jms301 Thanks, I'll fix it

**Comment by SachaG** [comment]
https://github.com/TelescopeJS/Telescope/commit/63bfed8d4d1415db7c98152ac0bce27c047a2206
