### ISSUE TITLE
"Error: Server sent add for existing id" error in Google search results

### ISSUE THREAD

**Issue by artiparty** [TelescopeJS/Telescope#1130]
![telescope-error](https://cloud.githubusercontent.com/assets/6714920/9722322/cfea4466-55b3-11e5-9e18-8257ef3f961b.jpg)

Many of my posts (not all of them) scanned by Google have an error in it's description *Error: Server sent add for existing id:*

**Comment by SachaG** [comment]
I saw you already posted in https://github.com/meteorhacks/fast-render/issues/80. There's not much I can do on my side, sorry…
