### ISSUE TITLE
Cannot fetch all the comments of the current user from inside a post page

### ISSUE THREAD

**Issue by mahmoudfelfel** [TelescopeJS/Telescope#1138]
I can't get the list of comments made by the current logged in user when trying to do that from inside a post page, i get only the comments from the user on this post, but i want to return all his comments regardless if he commented on this post or no.
```javascript
Comments.find({_id: Meteor.userId}).find().fetch();
```
Any ideas how can i accomplish that ?

**Comment by SachaG** [comment]
You need to publish that data first. Look into `Meteor.publish()` and `Meteor.subscribe()`, this is a good place to start: https://www.discovermeteor.com/blog/understanding-meteor-publications-and-subscriptions/
