### ISSUE TITLE
outGoingLink setting not working anymore in last v0.23.0

### ISSUE THREAD

**Issue by meteorplus** [TelescopeJS/Telescope#1144]
Hi 

I just noticed today that outGoingLink setting is not working anymore in last version 0.23.0 can someone confirm?

Thanks

**Comment by SachaG** [comment]
That setting only affects RSS feeds. Is that not working?

**Comment by davemorro** [comment]
I'm finding that the RSS feed is always using outgoingLink as the <link> node, but using discussion link within the <description> node. Is that the intended functionality @SachaG ? I'm using the latest version available to the heroku 1-click build.

**Comment by SachaG** [comment]
You're right, it was broken. Just pushed a fix to `devel`.

**Comment by xavcz** [comment]
Hey, @davemorro (I'm sure the others folks are aware of my message 😄 )! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
