### ISSUE TITLE
[Feature request] - Spam screen - prevent spammers from knowing they're caught. (aka "shadow-banning")

### ISSUE THREAD

**Issue by dalerka** [TelescopeJS/Telescope#1147]
Apologies if this already has been discussed somewhere else. :)

Instead of removing the spam content (manually/automatically) and thus *signaling* to spammers that they can create a new account and keep spamming, perhaps the following approach could be good:

1) Implement a *tiered propagation* of a new post - i.e. when a new post is published only few of the currently logged in users can see it (including the poster). Then, if nobody *downvoted/flagged* this post for an hour, the post will be accessible to a greater online audience (picked randomly). Then after another hour (if not many people downvoted/flagged the post) the post may be published to everyone.

2) *"Your content is for you only"* - if a user gets certain number of their posts/comments "flagged" they should not be removed or blocked, but instead their content (posts, comments) should be visible only to them and to people from the same region (city etc.). This is not a silver bullet, but can help to fool less savvy quick spammers. 

3) Of course we should keep in mind some edge cases, when it is required to deliver a new post/comment in real-time to everyone, or granting *spam-screen-exemption* to certain users based on karma, activity history etc.

BTW, perhaps such functionality could be implemented as a stand-alone package which can be configured via some hooks to accept some signals from an app and then command that app what to do about a malicious user and their content (mark a post as "spam", a user as "fenced" etc.) and also keep a log of such activity and provide a view/template to list the logs. 

Any ideas or comments?

**Comment by SachaG** [comment]
I'm not aware of spam being a huge problem for Telescope just yet. If it does become an issue I'll probably just implement simple shadow-banning (you can still see your posts, but nobody else can)?

**Comment by dalerka** [comment]
Thanks @SachaG, forgot the term :)  
Updated the title so others can find this thread easier. I agree, that for now spam isn't much of a problem for Telescope-based sites, but perhaps it is time to kick some ideas, so that some kind of a plug-n-play package can be developed sooner than later. In the best case it could be a package suitable for *Orion-CMS* and the upcoming *Spacedrop-CMS* but I have no idea how such package could be "app-agnostic".  
Spam management would be a good "out-of-the-box" feature and help wider adoption of Telescope among less tech-skilled folks (IMHO).

**Comment by xavcz** [comment]
Hey, @dalerka! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
