### ISSUE TITLE
Exception while invoking method 'editPost' MongoError: Cannot update 'categories' and 'categories' at the same time

### ISSUE THREAD

**Issue by Jarskih** [TelescopeJS/Telescope#1150]
When trying out new Telescope version v0.25.0 I get error when trying to edit posts:
Cloned the repo again to different folder and same problem.

"Exception while invoking method 'editPost' MongoError: Cannot update 'categories' and 'categories' at the same time"

![editerror](https://cloud.githubusercontent.com/assets/9105185/10123896/28254b98-6546-11e5-9b23-ce05c3923ae1.png)

**Comment by delgermurun** [comment]
I can confirm this error.

**Comment by constantx** [comment]
Just got this error today. I'm on `telescope:core@0.25.0* Telescope core package`. Does that version have the fix?

**Comment by SachaG** [comment]
@constantx you probably need to update to the latest version (0.25.3 I think)
