### ISSUE TITLE
[Opera Mini] Ugly CSS on top of Header

### ISSUE THREAD

**Issue by hoihei** [TelescopeJS/Telescope#1151]
Environment : Opera Mini 7.6.4 in Android 4.2
Step : Use Opera Mini to Open any telescope based website
Expected result : Clean telescope website
Result : CSS code appears on top of telescope website, screenshoot attached.

![screenshot_2015-09-28-07-15-38](https://cloud.githubusercontent.com/assets/327342/10125753/d5daf6e0-65b2-11e5-93ed-2e85a804faad.png)
![screenshot_2015-09-28-07-15-28](https://cloud.githubusercontent.com/assets/327342/10125754/d5db9bc2-65b2-11e5-88bf-b77583a83b23.png)

**Comment by SachaG** [comment]
Oh, that's a weird one!

**Comment by xavcz** [comment]
Hey, @hoihei! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
