### ISSUE TITLE
in sitemap.js line 

### ISSUE THREAD

**Issue by mostaphazeghaouigmail** [TelescopeJS/Telescope#1153]
52    posts.forEach(function(post) {
  53         postPages[url] = {page: post.getPageUrl(), lastmod: post.postedAt, changefreq: "daily"};
  54    });

on line 53  url is not defined.

**Comment by SachaG** [comment]
I haven't personally been using the Sitemap package, actually. I should probably remove it from the repo…

**Comment by mostaphazeghaouigmail** [comment]
I use to index in google all posts, because the button "load more", do not think it followed by google.
i fixed:
52 posts.forEach(function(post) {
     var url = post.getPageUrl();
53 postPages[url] = {page: url, lastmod: post.postedAt, changefreq: "daily"};
54 });
thanks

**Comment by xavcz** [comment]
Hey, @mostaphazeghaouigmail! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
