### ISSUE TITLE
Nothing changes after updating Telescope

### ISSUE THREAD

**Issue by mhlavacka** [TelescopeJS/Telescope#1154]
I have an old version of Telescope in my app. I tried to update with

$ sudo git remote add telescope https://github.com/TelescopeJS/Telescope.git

and 

$ git pull telescope master

but nothing has changed.

**Comment by SachaG** [comment]
That seems like more of a Git issue?

**Comment by xavcz** [comment]
Hey, @mhlavacka! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
