### ISSUE TITLE
Initial page is totally blank after launching Telescope

### ISSUE THREAD

**Issue by kaona** [TelescopeJS/Telescope#1156]
This conversation is from telescopeapp.slack.com - we seem to be having the same problem.

@landonsyn: I'm working in c9.io's IDE with Meteor. I've followed the install steps & replace the default '.media/packages' content w/ the Telescope stuff. (https://telescope.readme.io/docs)
When I launch meteor c9 tells me the app is live, but all I see is a blank page. 
I see no way to create a user/admin or to login.
How do I get to setting up an admin account (https://telescope.readme.io/v0.20/docs/basic-configuration)? (edited)

alain [11:29 AM] 
@landonsyn: i am having the same issue. Nothing comes up. Using Sublime Text 3 and following https://telescope.readme.io/docs/installing-telescope 2nd option

**Comment by SachaG** [comment]
Any errors?
