### ISSUE TITLE
Google analytics, first access to website aren't tracked.

### ISSUE THREAD

**Issue by mostaphazeghaouigmail** [TelescopeJS/Telescope#1162]
if you type the URL in the browser, this pageview aren't notified google analytics, but the next pageviews are notified correctly. only the first access to website has the problem.

**Comment by xavcz** [comment]
Hey, @mostaphazeghaouigmail! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
