### ISSUE TITLE
Embedly thumbnail images display incorrect on Mobile 

### ISSUE THREAD

**Issue by kevinsteger** [TelescopeJS/Telescope#1165]
I have activated Embedly with a 120x120 square thumbnail.  When displayed on Mobile devices the thumbnail displays over the top of the article title text and does not lay out correctly.

What is the proper size thumbnail or how / where is this issue fixed?

**Comment by SachaG** [comment]
Do you have a screenshot?

**Comment by xavcz** [comment]
Hey, @kevinsteger! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
