### ISSUE TITLE
Views checkboxes not displayed in Admin

### ISSUE THREAD

**Issue by vayovayo** [TelescopeJS/Telescope#1169]
I've juste updated to v0.25.3

The views checkboxes have disappeared from my admin settings panel.
Screenshot with error:
https://www.dropbox.com/s/e38aj4wteyvj0tv/Capture%20d%27%C3%A9cran%202015-10-19%2000.57.06.png?dl=0

Note I've been able to update settings and add my previous selection of views via mongoDB.

**Comment by abhaytalreja** [comment]
I had the same problem... the thing is that if you have any custom views defined... you need to make sure you change the item.label to item.name and label() is a new function..
See below for example on how the views should be...

your views should have name like [This!](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-posts/lib/menus.js#L13)
The label will be a function like [This!](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-posts/lib/menus.js#L48)
and Finally, if you have any custom views defined and copied the views_menus.js you might want to make sure you are checking for item.name and not item.label like [This!](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-posts/lib/client/templates/views_menu.js#L7)

**Comment by SachaG** [comment]
Yeah sorry, I had to change things a bit between the name/label properties to make internationalization work better.

**Comment by vayovayo** [comment]
Thanks for your info. I had no custom views defined so the problem was different. 

I did a temporary fixture that I put in my lib folder for the `Settings.schema`. 

I changed `label: view.label()`   to  `label: view.label` for `defaultView` and `postViews` objects

**Comment by xavcz** [comment]
Hey, @vayovayo! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
