### ISSUE TITLE
Can't startup with meteor 1.2.0.2

### ISSUE THREAD

**Issue by aleebaba** [TelescopeJS/Telescope#1171]
C:\Users\bruce.lee\mymeteor\Telescope-master>meteor
[[[[[ C:\Users\bruce.lee\mymeteor\Telescope-master ]]]]]

=> Started proxy.
=> Started MongoDB.
telescope:email: updating npm dependencies -- html-to-text...
telescope:newsletter: updating npm dependencies -- html-to-text...
telescope:post-by-feed: updating npm dependencies -- feedparser,
to-markdown, he, iconv-lite...
telescope:rss: updating npm dependencies -- rss...
=> Errors prevented startup:

   While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:dochead/package.browserify.js: Cannot find module
   'load-script' from
   '\C\Users\bruce.lee\AppData\Local\.meteor\packages\kadira_dochead\1.2.2\npm'

=> Your application has errors. Waiting for file change.

**Comment by SachaG** [comment]
I haven't seen this before, sorry… Could it be a windows issue? Or maybe an issue with `kadira:dochead` itself?

**Comment by aleebaba** [comment]
I think it shouldn't be  an windows issue.
I  tyied to install  kadira:dochead again using 'meteor add kadira:dochead'.but it doesn't work.

**Comment by julia-r** [comment]
Look at this issue in the meteor project: https://github.com/kadirahq/meteor-dochead/issues/11

Do "meteor update" and try again

**Comment by aleebaba** [comment]
Thanks julia,  SachaG is right, it's a windows issue,because there is no such an issue in my Macbook Pro......

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
