### ISSUE TITLE
Compile time errors show a file path without enough information

### ISSUE THREAD

**Issue by bySabi** [TelescopeJS/Telescope#1172]
This come from this post on Meteor forum: https://forums.meteor.com/t/compile-time-errors-show-a-file-path-without-enough-information/11870/1
I don´t know is some one fill a similar issue.
To solved we must move `ecmascript` package from `telescope:lib\packages.js` to `.meteor\packages`

**Comment by SachaG** [comment]
Are you still running into this issue?

**Comment by bySabi** [comment]
Hi @SachaG I don't use Telescope but folder and package architecture. I had put `ecmascript` on `.meteor\packages`  and add to each package and remove from `mypackage:lib` api.imply cause, like say in forum thread, build compile errors don´t have full path.
I don´t tested on Telescope,  just guest it have the same problem.

**Comment by bySabi** [comment]
Maybe Telescope no have this problem right now cause is not converted to meteor 1.2 yet.

**Comment by SachaG** [comment]
Oh, if this is not a Telescope issue then let me close this. Nobody has reported it yet in any case.

**Comment by bySabi** [comment]
Hi @SachaG I tested this on Telescope and the problem is there.
Test your self. Add a syntax error to any file and see the output.
I add one '{' to pages.js on `telescope:pages`and this is the output.

```
> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   lib/pages.js:67:3: lib/pages.js: Unexpected token (67:3)
``` 

Is impossible to know who package this file belong.

**Comment by bySabi** [comment]
I fill a issue on meteor: https://github.com/meteor/meteor/issues/5551
