### ISSUE TITLE
Telescope:sitemap not working w/ errors

### ISSUE THREAD

**Issue by alexbernson** [TelescopeJS/Telescope#1173]
I just tried installing Telescope:sitemaps onto the latest Telescope main branch, using `meteor add telescope:sitemap` and then deployed. When I try and access the sitemap (https://coffeehustle.com/sitemap.xml), the server throws an error and restarts. The error is below:

>W20151021-09:35:15.287(-7)? (STDERR) ReferenceError: url is not defined
>W20151021-09:35:15.289(-7)? (STDERR)     at lib/server/sitemaps.js:53:19
>W20151021-09:35:15.290(-7)? (STDERR)     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
>W20151021-09:35:15.290(-7)? (STDERR)     at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:869:1)
>W20151021-09:35:15.290(-7)? (STDERR)     at [object Object].cursorProto.(anonymous function) packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
>W20151021-09:35:15.290(-7)? (STDERR)     at [object Object].kadira_Cursor_forEach [as forEach] packages/meteorhacks_kadira/lib/hijack/set_labels.js:63:1)
>W20151021-09:35:15.290(-7)? (STDERR)     at lib/server/sitemaps.js:52:13
>W20151021-09:35:15.291(-7)? (STDERR)     at Array.forEach packages/es5-shim/packages/es5-shim.js:458:1)
>W20151021-09:35:15.291(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
>W20151021-09:35:15.291(-7)? (STDERR)     at lib/server/sitemaps.js:44:7
>W20151021-09:35:15.292(-7)? (STDERR)     at packages/gadicohen_sitemaps/packages/gadicohen_sitemaps.js:75:1

I did no additional configuration or anything, though I am using the telescope:prerender package modified for https FWIW. Please let me know if there's any more information I can provide. Thanks!

**Comment by andmitsch** [comment]
Did you define the domain in the admin menu correctly?

**Comment by alexbernson** [comment]
Yep! Though it is https if that matters.






On Wed, Oct 21, 2015 at 1:49 PM -0700, "Andi" <notifications@github.com> wrote:












Did you define the domain in the admin menu correctly?

**Comment by capensisma** [comment]
Hello Alex :) I saw your issue earlier 

anyway way I think there is a problem or issue in that package here 

```
posts.forEach(function(post) {
        postPages[url] = {page: post.getPageUrl(), lastmod: post.postedAt, changefreq: "daily"};
      });
```

and from the error you pasted 
```W20151021-09:35:15.287(-7)? (STDERR) ReferenceError: url is not defined
W20151021-09:35:15.289(-7)? (STDERR) at lib/server/sitemaps.js:53:19
W20151021-09:35:15.290(-7)? (STDERR) at [object Object]..extend.forEach 
```

we know that url isn't defined so may be post.url like this:


```
posts.forEach(function(post) {
        postPages[post.url] = {page: post.getPageUrl(), lastmod: post.postedAt, changefreq: "daily"};
      });
```

I will PR this if it fixes it!

**Comment by alexbernson** [comment]
awesome that fixed it. Though now the sitemap is only showing the top/best/new and a random one of the site's posts, is that expected behavior?

**Comment by capensisma** [comment]
That's my name: Awesome :D lool

yes it's expected behaviour you can see it on the top!

**Comment by constantx** [comment]
@alexbernson comment out this line to get more than one post (around line 48):
```
fields: {postedAt: 1, slug: 1, _id: 1},
```
