### ISSUE TITLE
Admin Settings menu items not displaying properly

### ISSUE THREAD

**Issue by FalseHen** [TelescopeJS/Telescope#1175]
Since updating to the latest version of Telescope, the settings menu is not longer displaying properly.

Prior to the update, the menu looked like this: https://i.imgur.com/WGzLyak.png

After updating, the menu looks like this: https://i.imgur.com/3NXsyEH.png

**Comment by SachaG** [comment]
Fixed.

**Comment by FalseHen** [comment]
Thanks, Sacha. This is close to where it was before, but "pages" and "feeds" in this list are still lowercase. The others are uppercase.
