### ISSUE TITLE
Child categories not displaying in admin menu

### ISSUE THREAD

**Issue by FalseHen** [TelescopeJS/Telescope#1176]
Since updating to the latest version of Telescope, child categories (categories with a parent category selected) no longer display in Settings > Categories.

If a new category is created with a parent category, the category is created but not visible on this page. All changes must be made directly from the database.

**Comment by xavcz** [comment]
Hey, @FalseHen! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
