### ISSUE TITLE
Facebeook crawler catching wrong meta & og

### ISSUE THREAD

**Issue by vayovayo** [TelescopeJS/Telescope#1177]
Since last Telescope update,

SEOStuff seems to be broken.

Facebook can't crawl the postsList or postPage but do crawl the loading page instead. (title & description are defined). Any idea where that could come from? 

Facebook:
https://www.dropbox.com/s/1smprsrqqnvn54j/Capture%20d%27%C3%A9cran%202015-10-24%2012.09.59.png?dl=0

Here is the postPage data crawled by facebook (in the facebook link debugger):
https://developers.facebook.com/tools/debug/og/echo?q=http%3A%2F%2Fbuythatsh.it%2Fposts%2FqqH5RmXzv8eRMKNBD%2Fchewbacca-lined-clog

**Comment by SachaG** [comment]
You might need to use a service like http://prerender.io to generate crawlable copies of your pages?

**Comment by vayovayo** [comment]
Thanks ! I'll take a look at it.

**Comment by sparkzilla** [comment]
I have the same problem. FB's object debugger does not read the og tags. I read somewhere that it may be related to domain name, DNS and Heroku. I will do a test on a clean install to get more info.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
