### ISSUE TITLE
 How to Downgrade Telescope Version?

### ISSUE THREAD

**Issue by Shurmonkey** [TelescopeJS/Telescope#1183]
Hi. how can i downgrade Telescope Version?

i updated to 25.5 and my web logo gets super small besides this i like to downgrade to 24. for apply some themes that don't work in 25.

thanks and Best Regards

**Comment by SachaG** [comment]
Just manually change the version for all packages in your `.meteor/packages` file. That being said downgrading is a bad idea, it's better to try and stay up to date so you can benefit from the latest features and bugfixes.

**Comment by Shurmonkey** [comment]
This is my packages file, where i change the versions manually?
i dont see the 25.5 current version.
Thanks.

# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

############ Telescope Core ############

telescope:core

############ Telescope Packages (Optional) ############

# Note: all following packages depend on telescope:core; Additional internal dependencies are mentioned

telescope:migrations
telescope:api
telescope:daily # singleday
telescope:datetimepicker
telescope:debug
telescope:email
telescope:embedly
telescope:getting-started
telescope:invites
telescope:kadira
telescope:newsletter
telescope:notifications
telescope:pages
telescope:post-by-feed
telescope:releases
telescope:rss
telescope:scoring
telescope:search
telescope:share
telescope:singleday
# telescope:sitemap
telescope:subscribe-to-posts # notifications
telescope:tagline-banner
telescope:tags
telescope:theme-base
telescope:update-prompt

############ Your Custom Packages ############

telescope:theme-hubble



jeremy:telescope-plugin-hero

**Comment by SachaG** [comment]
Oh sorry my bad, I meant `.meteor/version`, not `.meteor/packages`.

**Comment by Shurmonkey** [comment]
Perfect @SachaG  it solved my question!!
thanks for create Telescope ;)
