### ISSUE TITLE
No plugin known to handle file errors trying to "meteor update"

### ISSUE THREAD

**Issue by williammwhite** [TelescopeJS/Telescope#1189]
Trying to update to the latest version and getting errors.  I'm using one of the Scopemount themes (Magellan).  Any ideas?  

> meteor update
telescope:email: updating npm dependencies -- html-to-text...                      
telescope:newsletter: updating npm dependencies -- html-to-text...
telescope:post-by-feed: updating npm dependencies -- feedparser, to-markdown, he, iconv-lite...
telescope:rss: updating npm dependencies -- rss...
=> Errors while initializing project:         
                                              
While building package telescope:core:
error: No plugin known to handle file 'public/img/default-avatar.png'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('public/img/default-avatar.png', 'client').
error: No plugin known to handle file 'public/img/loading-balls.svg'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('public/img/loading-balls.svg', 'client').
error: No plugin known to handle file 'public/img/loading.svg'. If you want this file to be a static asset, use addAssets instead of addFiles;
eg, api.addAssets('public/img/loading.svg', 'client').

While building package telescope:datetimepicker:
error: 'fonts/glyphicons-halflings-regular.eot'. If you want this file to be a static asset, use addAssets
instead of addFiles; eg, api.addAssets('fonts/glyphicons-halflings-regular.eot', 'client').
error: No plugin known to handle file 'fonts/glyphicons-halflings-regular.svg'. If you want this file to be a static asset, use addAssets
instead of addFiles; eg, api.addAssets('fonts/glyphicons-halflings-regular.svg', 'client').
error: No plugin known to handle file 'fonts/glyphicons-halflings-regular.ttf'. If you want this file to be a static asset, use addAssets
instead of addFiles; eg, api.addAssets('fonts/glyphicons-halflings-regular.ttf', 'client').
error: No plugin known to handle file 'fonts/glyphicons-halflings-regular.woff'. If you want this file to be a static asset, use addAssets
instead of addFiles; eg, api.addAssets('fonts/glyphicons-halflings-regular.woff', 'client').

While building package telescope:getting-started:
error: No plugin known to handle file 'content/images/stackoverflow.png'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('content/images/stackoverflow.png', 'client').
error: No plugin known to handle file 'content/images/telescope.png'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('content/images/telescope.png', 'client').

**Comment by xavcz** [comment]
Hey, @williammwhite! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
