### ISSUE TITLE
cookie law in EU for Telescope 

### ISSUE THREAD

**Issue by Shurmonkey** [TelescopeJS/Telescope#1192]
HI @SachaG  , i need that my page created with Telescope shows the cookie message that its needed in the EU.

how I can add this package?

and another question, Tesescope can be monetized with adsense or something like that?

Thanks

**Comment by SachaG** [comment]
These are more general customization questions than code-related issues, so a better place to ask them would be the [Slack chatroom](http://slack.telescopeapp.org). That being said you can do both if you read up on the customization documentation.
