### ISSUE TITLE
Not able to build app for android platform

### ISSUE THREAD

**Issue by Codepanelorg** [TelescopeJS/Telescope#1193]
I'm trying to run meteor (Telescope app) for android platform using following command:

 $ meteor run android --verbose

However, the whole process stuck and showing the only message: 
"Starting emulator for android app".

I didn't get any error in the terminal. And when I'm trying to me build my app using following command:

 $ meteor build /Desktop/Test --server myAndroidApp.meteor.com

The tarball is created successfully in the destination folder (which is /Desktop/Test), but again the process stuck at building app for android and showing the only message: "Building cordova app for android".

There are no error logs. Setup all the environment by referring to all the steps mentioned on the official website links. Here are the details of the environment setup on my system:

OS: Ubuntu 15.10
java: build 1.8.0_65-b17
android sdk: variable path setup properly (android commands working)
meteor: 1.2.1
Android packages installed: API level 24-22

Meteor/Telescope app is build and running fine on desktop (web browser).
Repeated the complete steps twice but with no output for android platform.Please suggest how to get this done.

Or is there any way to fix things up manually on Windows or Linux?

**Comment by denyskoch** [comment]
I have the same issue. My meteor version is the same. Identical problem. Running meteor on OSX El Capitan. Building a test app in Android Studio works.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
