### ISSUE TITLE
User Invite Link in Email is broken

### ISSUE THREAD

**Issue by papabetalar** [TelescopeJS/Telescope#1194]
The link (Join "Project Name) in the email that is sent out to invited users is broken.

**Comment by eyaltoledano** [comment]
+1

**Comment by SachaG** [comment]
A PR would be appreciated :)

**Comment by eyaltoledano** [comment]
Got the latest install up on streamhunt.io
Have set up SMTP with both Mailgun and Mandrill - both worked from a deliverability perspective.

The link (join project) sends to /atSignup and consequently isn't clickable.

One note is that both Mailgun and Mandrill rewrite URLs when click and open tracking is enabled. This requires a CNAME record pointing to the SMTP domain (mailgun.org or mandrillapp.com for instance).

In that instance, the link becomes clickable, and sends to the click tracking url, but the following redirect still goes to /atSignup (no actual URL) and therefore no page.

**Comment by SachaG** [comment]
PR welcome :)

**Comment by SachaG** [comment]
Fixed in the next release
