### ISSUE TITLE
siteURL and logoURL

### ISSUE THREAD

**Issue by sparkzilla** [TelescopeJS/Telescope#1195]
Hi, the image on my notification emails was broken and I noticed that siteUrl has a trailing slash, but the logoUrl has a leading slash. When the two are combined you end up with extra slashes in the URL:

siteURL: http://mediabub.com/
logoURL: /img/logo.jpg  (the logo will not show if no leading slash is used

{{siteUrl}}{{logoUrl}}
result: http://mediabub.com//img/logo.jpg

**Comment by SachaG** [comment]
`logoUrl` should also be an absolute URL. That should fix it.
