### ISSUE TITLE
Invite form not showing

### ISSUE THREAD

**Issue by sparkzilla** [TelescopeJS/Telescope#1196]
Please check this completely new and untouched deploy to Heroku.

https://invitetest.herokuapp.com/users/sparkzilla/edit  

Login: user: sparkzilla, password: telescope

You can see the invite form is missing. 

You can also login as admin, password: telescope. In the admin Account page the form is there.

I believe the problem is related to the number of allowed invites.

**Comment by sparkzilla** [comment]
Ok, it seems I have a misunderstanding about the way it works. Apparently if I select "Require Invite to Post" then the invite system will work. But I want to anyone to be able to post even if they are not invited (if the just find the site) AND if they are invited. In other words, I want to use the invite system as a way to spread the word about the site, irrespective of being able to post.

**Comment by SachaG** [comment]
That's not really what invites do, sorry. You could clone the invites package and modify it to add in this new "spread the word" feature though.
