### ISSUE TITLE
telescope automatic templates replacement for package

### ISSUE THREAD

**Issue by Sshuichi** [TelescopeJS/Telescope#1197]
Hello 
I'm building a theme. 
I'm trying the doc for replacing a template. after writing my custom_post_title.html, It didn't have any effect. 

Should I add something in my package.js ? 
I tried adding the html but the console said : 

>>'lib/client/templates/custom_post_title.html'. If you want this file to be a
   static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/client/templates/custom_post_title.html', 'client').

But I guess templates are not assets. 

How do I fix this ?

**Comment by SachaG** [comment]
Did you check http://docs.telescopeapp.org/docs/troubleshooting ?

**Comment by Sshuichi** [comment]
Ok, I checked the troubleshooting , nothing rings a bell. 
Here is my code: 

Package.onUse(function (api) {


    api.use([
        'telescope:core@0.25.0',
        'telescope:theme-base@0.25.0'
    ]);
    api.use(['fourseven:scss'], ['client']);

    api.addFiles([
        'lib/config.js'
    ], ['client','server']);
    api.addFiles([
        'lib/client/stylesheets/manga-theme.scss',
    ], ['client']);

});

My custom packages :
    ############ Your Custom Packages ############
    
    # custom
    telescope:theme-hubble
    sshuichi:manga-theme

in manga-theme/lib/client/templates/custom_post_title:
`<template name="post_title">
    <a href="{{postLink}}" class="post" target="{{postTarget}}">{{title}} hahaha</a>
    </template>`

I think I should see the title of my post + hahaha , but I see naught. 

Can you help ?

**Comment by SachaG** [comment]
It doesn't seem like you're including the template file in your package?

See: 

```
Are you including your files?
Make sure you're including all your package's files with api.addFiles in the package manifest.

You can verify that a template is being properly loaded by opening up your console and typing Template.yourTemplateName.
```

**Comment by Sshuichi** [comment]
But wait, it doesn't say so in the docs ! I'm replacing not adding new template.
