### ISSUE TITLE
Template highlighting does not work

### ISSUE THREAD

**Issue by amelialin** [TelescopeJS/Telescope#1199]
https://www.youtube.com/watch?v=7Ux4wxg7Kko

According to this video I should be able to press tilde and see zones highlighted to show me which parts of my site are in what template files--a very nifty feature! However this is not working for me; pressing tilde does nothing for me. Perhaps this was a preview feature that was never launched, it's not clear to me?

**Comment by SachaG** [comment]
Make sure you have added the `telescope:debug` package.

**Comment by amelialin** [comment]
Thanks Sacha! Will try that.

On Sun, Nov 15, 2015 at 12:36 AM, Sacha Greif <notifications@github.com>
wrote:

> Make sure you have added the telescope:debug package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/issues/1199#issuecomment-156783547>
> .
>



-- 
Amelia Lin
469-222-0841
