### ISSUE TITLE
telescope-embedly: regenerating thumbnail click results in misleading error.

### ISSUE THREAD

**Issue by kabalin** [TelescopeJS/Telescope#1201]
I guess this is regeression introduced in dafae9b57, checkIfPreviouslyPosted callback triggered by  thumbnail prefill results in validating URL of the current post, since _id is not taken into account in the duplicate check, error message informing user about duplicated URL pops up.

**Comment by xavcz** [comment]
Hey, @kabalin! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
