### ISSUE TITLE
Cannot access admin menu

### ISSUE THREAD

**Issue by lesbeben** [TelescopeJS/Telescope#1206]
Hi,

I've installed telescope 0.25.5 locally today, following the tutorial at https://telescope.readme.io/docs (Option 2).
I created a user as instructed in https://telescope.readme.io/v0.25/docs/basic-configuration but the admin menu does not show up.
The console is not displaying any errors...
Is this a known issue ?

**Comment by SachaG** [comment]
Your user is probably not an admin (the `isAdmin` flag is not `true`)?

**Comment by lesbeben** [comment]
Hi,

Thanks for answering.
I thought the first user created was automatically granted admin rights? at least that is what the tutorial says. Is there a way to manually gran tadmin privileges to one or several users?
How can I check if this flag is present on a user?

**Comment by SachaG** [comment]
It should, but maybe that didn't happen for some reason. You can check and modify the user object through the database (`meteor mongo` in the shell).

**Comment by lesbeben** [comment]
OK I'll try that, thank you.
