### ISSUE TITLE
Safari rendering

### ISSUE THREAD

**Issue by sparkzilla** [TelescopeJS/Telescope#1208]
Telescope does not render properly on Safari on Mac, iPad and IPad mini. The post title overlays the embedded image. With so many people using Macs and iOs this should be a high-priority item.

![safari rendering](https://cloud.githubusercontent.com/assets/6822523/11737686/d19a7b4c-9fa9-11e5-8360-41ca4d449741.png)

**Comment by sparkzilla** [comment]
Also there is a related problem, also on Safari: The Register and Sign In section sticks to the bottom of the page, causing an overlap with other menu items.

![image2](https://cloud.githubusercontent.com/assets/6822523/11737762/7b5c0c68-9faa-11e5-9f6d-437b03c2b6e4.PNG)

**Comment by SachaG** [comment]
Fixing part of this issue in the next release.
