### ISSUE TITLE
Unescaped quotes in the email newsletter

### ISSUE THREAD

**Issue by sparkzilla** [TelescopeJS/Telescope#1209]
Comments that have quotes appear as unescaped characters in the email newsletter. The " character appears as `&quot;`

![download](https://cloud.githubusercontent.com/assets/6822523/11737842/42c42ca4-9fab-11e5-8869-3f4a06dc72d3.jpg)

**Comment by xavcz** [comment]
Hey, @sparkzilla! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
