### ISSUE TITLE
Callbacks losing context

### ISSUE THREAD

**Issue by queso** [TelescopeJS/Telescope#1212]
So it looks like the way callbacks happen, we lose access to the Meteor context for methods such as `this.connection`, which has info I need for passing on to Akismet.

**Comment by SachaG** [comment]
Hmm, how would we fix this? Should we `bind` the function to something?

**Comment by jonbaer** [comment]
Just curious are you building something like a telescope-akismet package for crater.io (ie via https://github.com/dfischer/akismet) ...

**Comment by queso** [comment]
I opted to just added the data I needed from the connection string into the Post schema itself to avoid this problem.
