### ISSUE TITLE
Can't deploy Telescope after update

### ISSUE THREAD

**Issue by BanzaiTokyo** [TelescopeJS/Telescope#1222]
using mup / ec2

Started TaskList: Deploy app 'akihabara' (linux)
[akihabara.tokyo] - Uploading bundle
[akihabara.tokyo] - Uploading bundle: SUCCESS
[akihabara.tokyo] - Setting up Environment Variables
[akihabara.tokyo] - Setting up Environment Variables: SUCCESS
[akihabara.tokyo] - Invoking deployment process
[akihabara.tokyo] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	wn args   '-Dnode_lib_file=node.lib',
	gyp info spawn args   '-Dmodule_root_dir=/opt/akihabara/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	gyp info ok 
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	gex@0.2.1 node_modules/ansi-regex
	
	ansi-styles@1.1.0 node_modules/ansi-styles
	
	chalk@0.5.1 node_modules/chalk
	
	escape-string-regexp@1.0.3 node_modules/escape-string-regexp
	
	strip-ansi@0.3.0 node_modules/strip-ansi
	
	has-ansi@0.1.0 node_modules/has-ansi
	
	supports-color@0.2.0 node_modules/supports-color
	
	eachline@2.3.3 node_modules/eachline
	
	type-of@2.0.1 node_modules/type-of
	
	amdefine@1.0.0 node_modules/amdefine
	
	asap@2.0.3 node_modules/asap
	
	underscore@1.5.2 node_modules/underscore
	
	meteor-promise@0.5.0 node_modules/meteor-promise
	
	source-map-support@0.3.2 node_modules/source-map-support
	
	semver@4.1.0 node_modules/semver
	
	source-map@0.1.32 node_modules/source-map
	
	promise@7.0.4 node_modules/promise
	
	fibers@1.0.5 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	akihabara stop/waiting
	akihabara start/running, process 19490
	Waiting for 45 seconds while app is booting up
	Checking is app booted or not?
	akihabara stop/waiting
	akihabara start/running, process 19636
	----------------------------------------------------------------------------

**Comment by SachaG** [comment]
Check the logs with `mup logs -f` while you're deploying.

**Comment by BanzaiTokyo** [comment]
[akihabara.tokyo] error: Script restart attempt #40
Meteor requires Node v0.10.40 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #41
Meteor requires Node v0.10.40 or later.
error: Forever detected script exited with code: 1
Kadira: completed instrumenting the app
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated

I guess I need to update Node for Meteor. Do you have an idea how it could be done?
node -v
v0.12.2

**Comment by BanzaiTokyo** [comment]
sorry, I should have noticed   "setupNode": false in mup.json
now, after update to 0.10.40 everything works as a charm!

**Comment by SachaG** [comment]
Awesome :)
