### ISSUE TITLE
Daily feed not automatically refreshed for a new day

### ISSUE THREAD

**Issue by AddedLayer** [TelescopeJS/Telescope#1225]
When daily feed is the default for the post list, only the days that are already displayed get updated in real time. Any new days aren't displayed until the page is manually refreshed.

For example,
Say I opened the app on a Thursday and left the browser open. All posts for Thursday automatically show up. But on Friday, no posts are shown (not even the date itself). When refreshed, then Friday's post are shown. 

Is this the intended functionality?

**Comment by SachaG** [comment]
Yeah, it's not ideal, but it's just how it works due to the way it's coded. I just assumed it's a rare enough use case that it's not the end of the world if it works like this.
