### ISSUE TITLE
Embedly display (thumbnail) usage

### ISSUE THREAD

**Issue by AddedLayer** [TelescopeJS/Telescope#1226]
I'm getting 5K+ calls to Display API in Embedly every day. I don't have more than 50 posts/day (post-by-feed) so it seems that everyday all thumbnails are regenerated and therefore getting a cumulative effect. If Cloudinary is supposed to fix this issue, can you take a look at issue #1224. I'm having issues with https.

**Comment by SachaG** [comment]
Well, thumbnails are not "regenerated", but since they're stored on Embedly's servers one visitor equals one API call. So yeah, that's why the Cloudinary plugin exists. The https thing shouldn't be too hard to fix.
