### ISSUE TITLE
Theme demos not working

### ISSUE THREAD

**Issue by dheerajbhaskar** [TelescopeJS/Telescope#1227]
Hi Guys,

## Problem
The following theme demos are not working.
- http://sm-gemini.meteor.com/
- http://sm-lulin.meteor.com/
- http://sm-magellan.meteor.com/
- http://sm-colossus.meteor.com/
- http://sm-palomar.meteor.com/

## What do I mean by not working
There's only a loader at the middle with the site being unusable.
Screenshot below.

### Screenshots
![screenshot 42](https://cloud.githubusercontent.com/assets/2944909/12144634/1e377c1a-b4af-11e5-9b1e-c51950014707.png)
![screenshot 38](https://cloud.githubusercontent.com/assets/2944909/12144635/1e3920c4-b4af-11e5-8ba9-e8ca40902653.png)
![screenshot 39](https://cloud.githubusercontent.com/assets/2944909/12144636/1e3cda98-b4af-11e5-9792-73c1d7bb82a7.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/2944909/12144637/1e3e646c-b4af-11e5-8df4-ecc204ef238e.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/2944909/12144638/1e40d648-b4af-11e5-91a2-74aa032bf118.png)

> Note: These are the only ones I checked. Other theme demos may not be working.

**Comment by dheerajbhaskar** [comment]
This is not due to my internet connection speed/reliability either - I'm on a fairly reliable, fast 20mbps connection and the telescope demo is loading.

**Comment by dheerajbhaskar** [comment]
Okay it just loaded now. It took 15mnis :open_mouth: 

Did a reload and it was relatively faster but still abysmally slow. 
![image](https://cloud.githubusercontent.com/assets/2944909/12144821/51b0638a-b4b0-11e5-80aa-42ce31f3f2f5.png)

This might have been a temporary preoblem, I shall go ahead and close this issue.

**Comment by SachaG** [comment]
I'm not sure about this specific issue, but sadly these themes are not maintained anymore :*

**Comment by dheerajbhaskar** [comment]
Ironically enough we had a temporary Internet issue - extremely long ping
and low upload rate. My confidence was from the fact that I was streaming
YouTube in another tab.

With regards to the themes, we might be able to adopt them. No promises,
but we're an app and Web dev company (agency). These look good enough that
we might use them in a product for a client. In which case we'll naturally
maintain them. Of course, I'm saying this with not much understanding of
the complexities of the theme (s) at this point.

On Wed 6 Jan, 2016 11:14 pm Sacha Greif <notifications@github.com> wrote:

> I'm not sure about this specific issue, but sadly these themes are not
> maintained anymore :*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/issues/1227#issuecomment-169400789>
> .
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by SachaG** [comment]
Oh, that'd be awesome. I already have the theme author's agreement for other people to come in and "adopt" them :)

They don't have any complex features, it's just that Telescope got a few updates that changed a few things, and they fell out of date.

**Comment by dheerajbhaskar** [comment]
Very cool. We'll probably need your help or someone else from our team
might have to take a look the license when we get started.

That's good news, simpler the better. The way I see it, we will have to
"fix" for those breaking changes anyway, if we have to use the latest
telescope with the themes.

On Wed 6 Jan, 2016 11:25 pm Sacha Greif <notifications@github.com> wrote:

> Oh, that'd be awesome. I already have the theme author's agreement for
> other people to come in and "adopt" them :)
>
> They don't have any complex features, it's just that Telescope got a few
> updates that changed a few things, and they fell out of date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/issues/1227#issuecomment-169403416>
> .
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by dheerajbhaskar** [comment]
Hey @SachaG I'm setting up a telescope app with [Galileo theme](http://scopemount-blog.surge.sh/scopemount-theme-galileo/) for a friend.

So I forked the sample-project of telescope into [this repo](https://github.com/dheerajbhaskar/telescope-samarth).

The theme is indeed broken - it doesn't look like the demo site. Do you have any hunches on where I can look to start fixing this?

PS: Is this issue a good place or would you suggest elsewhere to discuss this?

**Comment by capensisma** [comment]
Hey @dheerajbhaskar that Galileo Theme is using an older version of Telescope that is why it's not working!!

**Comment by dheerajbhaskar** [comment]
Hey @Capensis got it. I'm wondering how to fix it, or at least start fixing
it.

Please let me know if I'm thinking in the right direction; somebody other
than Capensis can also pitch in. I see two options:

1. **Slightly time taking**: Based off of a hunch from this commit:
https://github.com/montecruiseto/scopemount/commit/259baf098f04f69e353f95280645b4c5a00f22f3
I think the main reason for the brokenness would be template renames, CSS
selector changes or some other refactoring. If I read a little bit of the
source of telescope (or even the changelog or diffs) and that of the
galileo theme, I can fix this. Reading code takes time. My additional
incentive here is that I'd get to understand how a fairly complex meteor
app can be structured. Also, we're an agency which can reuse this effort.

2. **Quick Fix**: Rollback telescope to 0.22.2 - last telescope version
galileo was supported against.

I see that I can do option 2 - rollback - and then upgrade telescope step
by step and fix any breaking change I see. This seems faster.

If either of you gentlemen (or sb else) can tell me which commit I need to
rollback the sample project to to be at v0.22.2, I will be on my way.


On Thu, Feb 11, 2016 at 10:38 PM Capensis <notifications@github.com> wrote:

> Hey @dheerajbhaskar <https://github.com/dheerajbhaskar> that Galileo
> Theme is using an older version of Telescope that is why it's not working!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/issues/1227#issuecomment-182960819>
> .
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---
