### ISSUE TITLE
Post to Feed not working for some RSS feeds

### ISSUE THREAD

**Issue by AddedLayer** [TelescopeJS/Telescope#1228]
Is there some type of blacklist that prohibits the import of certain RSS feeds? I'm building a news site for Suriname South America and for every site hosted there it doesn't import the feed. For sites in the US it does work. Initially I thought it could be Digital Ocean or CloudFlare but even on localhost I have the same issue. For example,
importing this works: http://www.starnieuws.com/rss/starnieuws.rss
but this one doesn't: http://dwtonline.com/rss/rss-feed/ 

Any ideas what might cause the issue? An RSS import plugin for Wordpress works fine for all sites. So not sure what is happening here.

**Comment by SachaG** [comment]
Is the import triggering any errors? Any messages in the logs?

**Comment by AddedLayer** [comment]
Not getting any errors or warnings in the browser console or when I check the server-side logs (mup logs -f). 

I just did some more digging and found out that the issue is with the <link> attribute in the rss feed. For dwtonline.com for example, if I use the root domain such as <http://dwtonline.com/laatste-nieuws/2016/01/07/rijbewijs-dronken-bestuurder-na-aanrijding-ingevorderd/>, the RSS import doesn't work. But when I replace the <link> for each item in the RSS feed to a bit.ly link for example, the import works. This is on the same server in Suriname, so my guess is that it's not server location, but for some odd reason the link domain for each RSS item. 

I checked the post-to-feed source code but couldn't find any reason why it would "validate" the link for each item before importing. Any suggestions on how to move forward?

**Comment by SachaG** [comment]
Could this be an issue with the [Feedparser](https://github.com/danmactough/node-feedparser) NPM package used by Telescope? Maybe if you can give it a quick test outside of Telescope, we can narrow down the problem?

**Comment by AddedLayer** [comment]
Just did a plain node project with the feedparser and was able to import the RSS feed. For every item, I got the following structure:

{ title: 'Ontvluchtte arrestant aangehouden',
  description: 'De 21-jarige arrestant Cliff  M.  is aangehouden nadat hij uit handen van de politie was ontvlucht. De verdachte is dinsdag naar het parket gebracht ter voorgeleiding en daarna opgehaald door de politie.',
  summary: 'De 21-jarige arrestant Cliff  M.  is aangehouden nadat hij uit handen van de politie was ontvlucht. De verdachte is dinsdag naar het parket gebracht ter voorgeleiding en daarna opgehaald door de politie.',
  date: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
  pubdate: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
  pubDate: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
  link: 'http://dwtonline.com/laatste-nieuws/2016/01/07/ontvluchtte-arrestant-aangehouden/',
  guid: 'http://dwtonline.com/356951.aspx',
  author: null,
  comments: null,
  origlink: null,
  image: {},
  source: {},
  categories: [],
  enclosures: [],
  'rss:@': {},
  'rss:title': { '@': {}, '#': 'Ontvluchtte arrestant aangehouden' },
  'rss:link': 
   { '@': {},
     '#': 'http://dwtonline.com/laatste-nieuws/2016/01/07/ontvluchtte-arrestant-aangehouden/' },
  'rss:pubdate': { '@': {}, '#': 'Thu, 07 Jan 2016 13:07:00 GMT' },
  permalink: 'http://dwtonline.com/356951.aspx',
  'rss:guid': { '@': {}, '#': 'http://dwtonline.com/356951.aspx' },
  'rss:description': 
   { '@': {},
     '#': 'De 21-jarige arrestant Cliff  M.  is aangehouden nadat hij uit handen van de politie was ontvlucht. De verdachte is dinsdag naar het parket gebracht ter voorgeleiding en daarna opgehaald door de politie.' },
  meta: 
   { '#ns': [ [Object], [Object], [Object], [Object] ],
     '@': [ [Object], [Object], [Object], [Object] ],
     '#xml': { version: '1.0', encoding: 'UTF-8' },
     '#type': 'rss',
     '#version': '2.0',
     title: 'DWTonline.com',
     description: 'Het laatste nieuws van DWTonline.com',
     date: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
     pubdate: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
     pubDate: Thu Jan 07 2016 08:07:00 GMT-0500 (EST),
     link: 'http://dwtonline.com',
     xmlurl: 'http://dwtonline.com/rss/rss-feed/',
     xmlUrl: 'http://dwtonline.com/rss/rss-feed/',
     author: null,
     language: 'nl',
     favicon: null,
     copyright: null,
     generator: 'umbraco',
     cloud: {},
     image: {},
     categories: [],
     'rss:@': {},
     'rss:title': { '@': {}, '#': 'DWTonline.com' },
     'rss:link': { '@': {}, '#': 'http://dwtonline.com' },
     'rss:pubdate': { '@': {}, '#': 'Thu, 07 Jan 2016 13:07:00 GMT' },
     'rss:generator': { '@': {}, '#': 'umbraco' },
     'rss:description': { '@': {}, '#': 'Het laatste nieuws van DWTonline.com' },
     'rss:language': { '@': {}, '#': 'nl' },
     'atom:link': { '@': [Object] } } }

=====

Since it is able to get the feed, I'm guessing the problem is with post creation.

**Comment by SachaG** [comment]
I added logging and tried that feed, and it seems like it returns an error:

```
{ [Error: failed [500] <!DOCTYPE html>
 <html>
     <head>
         <title>Runtime Error</title>
         <meta name="viewport" content="width=device-width" />
         <style>
          body {font-family:"Verdana";font-weight:normal;font-
          p {font-family:"Verdana";font-weight:normal;color:black
          b {font-family:"Verdana";font-weight:bold;color:black;
          H1 { font-family:"Verdana";font-weight:normal;font-size
         ...] stack: [Getter] }
```

Not sure why it works outside of Telescope though…

**Comment by SachaG** [comment]
I added some console.log calls on the devel branch, if you want to work off that. I can't figure out why exactly it's triggering an error though… I have to confess I don't remember how that code works very well.

**Comment by AddedLayer** [comment]
Can you try using this feed: http://dwtonline.com/rss/rss-20/ 

That feed has same content but links are pointing to a single bit.ly link. Not sure why getting a 500 status code.

**Comment by AddedLayer** [comment]
Okay I'll pull the dev branch and see what happens. Thanks!

**Comment by AddedLayer** [comment]
I'm getting the same error. On a working example, I can't find anything useful to isolate the issue. I'll contact their devs and hope to resolve it that way. Thanks for the help!

**Comment by AddedLayer** [comment]
I isolated the issue. This is where the trouble is

````javascript
var get = HTTP.get(item.link, {followRedirects: false});

        if (!!get.statusCode && (get.statusCode === 301 || get.statusCode === 302) &&
            !!get.headers && !!get.headers.location) {
              post.url = get.headers.location;
            }
````

The HTTP.get is not working properly. Is the `post.url = get.headers.location;` really needed?
If I wanted to disable that bit of code, would that be possible in the master branch? I'm still a bit new to meteor so is it possible that I just add the package files manually for the feed-to-post?

**Comment by SachaG** [comment]
Did you figure it out? I don't really remember what that bit of code does, to be honest. I think just follow redirects for cases when a feed's URL has changed? If you wanted to change it, your best bet would be cloning the post-by-feed package and using your own custom version.
