### ISSUE TITLE
Error: Username already exists [403] Meteor

### ISSUE THREAD

**Issue by Naoto-Ida** [TelescopeJS/Telescope#1230]
I'm getting the error mentioned in the title in a coworker's environment.

I have no issues with getting it to run.

W20160108-14:35:54.898(9)? (STDERR) ~/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160108-14:35:54.898(9)? (STDERR) 						throw(ex);
W20160108-14:35:54.898(9)? (STDERR) 						      ^
W20160108-14:35:54.955(9)? (STDERR) Error: Username already exists. [403]
W20160108-14:35:54.956(9)? (STDERR)     at checkForCaseInsensitiveDuplicates (password_server.js:203:13)
W20160108-14:35:54.956(9)? (STDERR)     at createUser (password_server.js:977:3)
W20160108-14:35:54.956(9)? (STDERR)     at AccountsServer.Accounts.createUser (password_server.js:1049:10)
W20160108-14:35:54.956(9)? (STDERR)     at createDummyUsers (lib/server/dummy_content.js:38:12)
W20160108-14:35:54.956(9)? (STDERR)     at _ (lib/server/dummy_content.js:112:5)
W20160108-14:35:54.956(9)? (STDERR)     at ~/projectname/.meteor/local/build/programs/server/boot.js:249:5

I'm not that familiar with how packages in Meteor work,
but I navigated to ~/.meteor/packages/telescope_getting-started/ and found dummy_contents.js.

Commenting out line 112 where it is trying to create dummy users didn't do anything.

**Comment by rizafahmi** [comment]
+1 I did deploy to DigitalOcean with local mongodb reproduce similar error message.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
