### ISSUE TITLE
architecture question

### ISSUE THREAD

**Issue by rdewolff** [TelescopeJS/Telescope#1233]
Wondering if you have planned changing / updating the application modular structure for the upcoming 1.3 release of Meteor?

**Comment by SachaG** [comment]
Not really. We'll see once 1.3 is out what benefits it would bring, and if it's worth doing something about it.

**Comment by rdewolff** [comment]
Do you have any particular advices about your experience with the current architecture you are using?

- what are you happy with?
- what could be done better?
- any big architecture problem?

**Comment by SachaG** [comment]
That's kind of a big topic. Maybe you can check this out instead: https://meteor.hackpad.com/Building-Large-Apps-Tips-d8PQ848nLyE

**Comment by rdewolff** [comment]
Thanks @SachaG - I know it's not an easy questions.

Concerning Meteor 1.3 release, there has been an interesting questiosn asked on meteor forums : https://forums.meteor.com/t/1-3-best-practice-package-based-architecture-and-how-does-package-js-fit-into-1-3/16532

**Comment by Alino** [comment]
I am using package based architecture on my project, and my project has 40 custom packages made specially for the project. And those packages are used across 3 meteor apps. So I was wondering how other package based architecture meteor projects are handling the upgrade to meteor 1.3

I tried it (upgrading to meteor 1.3), but it broke the apps, and seems as a too big task for me to rewrite everything to work in new es6 import/export modules style. If telescope ignores meteor 1.3 I am going to stay on meteor 1.2 as well.
