### ISSUE TITLE
"Creating zones" documentation outdated

### ISSUE THREAD

**Issue by JulianKingman** [TelescopeJS/Telescope#1238]
Here: http://docs.telescopeapp.org/docs/template-modules

It should say ````{{> modules zone="myZoneName"}}```` instead of ````{{> modules "myZoneName"}}````

**Comment by SachaG** [comment]
Thanks, you can submit an annotation on Readme.io :)

**Comment by JulianKingman** [comment]
How?

**Comment by JulianKingman** [comment]
Ah, got it, signing in on the docs.
