### ISSUE TITLE
Newsletter sending old articles after upgrade

### ISSUE THREAD

**Issue by cuberoot** [TelescopeJS/Telescope#1239]
I am running Telescope at http://news.omegawriters.com. I recently upgraded to the latest version of Telescope (Cloudinary release...). After doing that, Telescope started sending out old news items in the newsletter instead of the most recent ones. I've attached a PDF of the latest email that Telescope sent out for us.

I tried restarting the server. Does anyone have any suggestions?

[OmegaNewsletter.pdf](https://github.com/TelescopeJS/Telescope/files/111502/OmegaNewsletter.pdf)

**Comment by SachaG** [comment]
Is this still happening on a regular basis, or did it only happen a couple times? Telescope should only pick up posts that are more recent than the last email campaign that was sent out.

**Comment by SachaG** [comment]
Just to be safe I'll limit the posts that are picked up for the newsletter to the ones from the past week, no matter the date of the previous newsletter campaign.

**Comment by cuberoot** [comment]
Sorry, missed the first question. It has happened three times since the upgrade so far.

**Comment by cuberoot** [comment]
FYI, we are still having problems with this a month later.

**Comment by SachaG** [comment]
Have you updated to the latest version of Telescope? What if you play around with the code here?

https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-newsletter/lib/server/campaign.js#L4-L19

**Comment by cuberoot** [comment]
Ok, hadn't seen any activity in this issue, so I hadn't tried updating. Doing that now. I'll let you know how it goes!

**Comment by xavcz** [comment]
Hey, @cuberoot! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
