### ISSUE TITLE
Settings - users

### ISSUE THREAD

**Issue by Kak3n** [TelescopeJS/Telescope#1240]
Settings - List of users isn't responsive
![example](https://cloud.githubusercontent.com/assets/7171250/12824517/d754247c-cb71-11e5-9ac0-a67b892a01bc.png)

**Comment by SachaG** [comment]
That's true. Making tables responsive is tricky, probably not something I'll work on myself at this time.

**Comment by xavcz** [comment]
Hey, @Kak3n! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
