### ISSUE TITLE
Console.log(this)

### ISSUE THREAD

**Issue by ykptke** [TelescopeJS/Telescope#1243]
here [console.log](https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-posts/lib/callbacks.js#L54) on server after post submit

**Comment by uooq** [comment]
This incurs crazy log spew!!   One liner fix.  :)

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
