### ISSUE TITLE
Creating Users

### ISSUE THREAD

**Issue by patrick-ogrady** [TelescopeJS/Telescope#1244]
Is there a way to prevent signup by email address domain? Also, require email verification for signup.

**Comment by abhaytalreja** [comment]
@patrick-ogrady not sure what you mean by sign-up prevention... if you mean you only want to sign-up using social media?
i added email verification by adding..

```
sendVerificationEmail: true
```

https://github.com/TelescopeJS/Telescope/blob/85e9d00088370373be266cb92deb61c72b0b9fb5/packages/telescope-users/lib/config.js

you can read further here... http://www.mightymeteorites.com/articles/how-do-i-send-a-verification-email-using-meteors-user-accounts-package

**Comment by patrick-ogrady** [comment]
I would like to require the user to verify their email before they use the service...is that possible?

**Comment by abhaytalreja** [comment]
Yes, that can be possible. With the above feature if the user is verified, you can check the status in the users object. say `Meteor.user().isVerify` or something is true then take the user to guest page or your service dashboard/page.

**Comment by xavcz** [comment]
Hey, @patrick-ogrady! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
