### ISSUE TITLE
Delete an invited user?

### ISSUE THREAD

**Issue by andrewijmcdonald** [TelescopeJS/Telescope#1247]
I'm having trouble with the invite system, as a result I need to resend some invites to email accounts that didn't work correctly

How can I delete the invites?

**Comment by xavcz** [comment]
Hey, @andrewijmcdonald! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. FYI, invites are no longer part of core.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
