### ISSUE TITLE
Email invite links not working

### ISSUE THREAD

**Issue by andrewijmcdonald** [TelescopeJS/Telescope#1248]
I have sent some invites, but the links don't work. This is the raw generated email code:

~~~
http://foooo.meteor.com/
andrew [/users/andrew] invited you to join Foooo

Join Foooo [/register]

Change your notifications settings =
[http://site.meteor.com/account]
~~~

As you can see, the two most important links are missing the website url.

Any ideas how I can fix this, or is it user error?

**Comment by wietsevr** [comment]
+1. There's a PR for that here: https://github.com/TelescopeJS/Telescope/pull/1242.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue (which has been fixed on legacy & nova).

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
