### ISSUE TITLE
One-click deploy build issue on Heroku

### ISSUE THREAD

**Issue by ummahusla** [TelescopeJS/Telescope#1249]
Hello, 
I'm trying to setup telescope app to **Heroku**, to play around it. Everything went smooth until **Build App** stage where I've got next issue. Can anyone help me to sort it out? I've pressed One-Click deploy button on the Telescope homepage.

**There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.**

```
-----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
###############################################                      73.3%
Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack20160222-158-rhqe0b/meteor-wXAi/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
-----> Building Meteor with ROOT_URL: testph12315.herokuapp.com
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app
```

**Comment by capensisma** [comment]
Hi,

Just change testph12315.herokuapp.com to http://testph12315.herokuapp.com when adding it as ROOT_URL

`$ROOT_URL, if specified, must be an URL.`

**Comment by ummahusla** [comment]
Oh dear.. My bad. 

Thank you.
