### ISSUE TITLE
Nova contributions

### ISSUE THREAD

**Issue by paulmolluzzo** [TelescopeJS/Telescope#1251]
After reading [this post](http://www.telescopeapp.org/blog/building-apps-with-nova-react-meteor/) I'm sure others would like to contribute to Nova. If there's a roadmap or contributions guidelines some documentation would be great (e.g. A CONTRIBUTING file).

**Comment by SachaG** [comment]
Good point! Here's a post that outlines what needs to be done: http://www.telescopeapp.org/blog/getting-started-with-nova/

And a roadmap: https://trello.com/invite/b/dwPR0LTz/bc701c998b1c85c113ea40ec54dfbd54/nova-roadmap

**Comment by paulmolluzzo** [comment]
I suggest you add a 'Nova' label to the issues for this repo too. It'll make it easier to organize issues and PRs you get for the repo.

**Comment by SachaG** [comment]
Good idea :)

**Comment by xavcz** [comment]
@paulmolluzzo closing it, but thanks for the inspiration! After cleaning old issues, we are going for a new label this month : https://hacktoberfest.digitalocean.com/

😄
