### ISSUE TITLE
Travis CI, tests, linting, etc

### ISSUE THREAD

**Issue by paulmolluzzo** [TelescopeJS/Telescope#1253]
There's a Travis CI file for the `master` branch, but nothing for the `nova` branch. Without that all PRs are going to fail. See [here](https://github.com/TelescopeJS/Telescope/pull/1252).

I don't think there are any tests yet (even `meteor test-packages` isn't really doing much), so I don't know what to test with Travis just yet, but I guess we can make sure it actually builds and starts the app.

Also, it'd be great to have an editorconfig and linter. There's an editorconfig in `master` that probably still works. For linting, perhaps you can look at [xo](https://www.npmjs.com/package/xo) since there's very little configuration to bother with and there's a plugin for ST, Atom, vim, and a few others.

**Comment by SachaG** [comment]
Oh I do have editorconfig, jshintrc, eslintrc, etc. files but they're gitignored. I'll include them in the project then. 

And the Travis thing is probably not too bad until we actually have tests?

**Comment by paulmolluzzo** [comment]
Without a travis.yml Travis will use a default config that assumes you have a Rails app. The result is you'll always fail.

At least have Travis run meteor and lint the app. You want to be able to pass or all PRs will technically be failing, though not by a fault of the new code.

The linting is important IMO so that you don't have future white space only commits or "added a semicolon" updates. Also, if you go to ES6/2015 there are some rules that might be overlooked without a linter (like block scoping variables).

**Comment by xavcz** [comment]
Hey @paulmolluzzo! 

We are going through helpful utilities like linting, tests, and CI step by step. We removed the Travis build: we won't write any tests for now, and yeah the config file was broken. 

Another config broken is eslint: #1470. I don't know much about ESLint, maybe you know useful rules that would fit the project? 

Fyi, I think we'll write test when we leave Meteor and become a React - Apollo - Node app :rocket:
