### ISSUE TITLE
Issues with direct links to pending posts

### ISSUE THREAD

**Issue by JoshRWeinstein** [TelescopeJS/Telescope#1254]
When I, as an admin, receive an email about a new post pending approval and click on it:
I get taken to a page but the post doesn't load. There seems to be an issue of a piece of the URL missing, e.g.

this post works:
http://list.joshrweinstein.com/posts/6bW5carZSuJpSRxH5/connecting-with-angels-vc-s-investing-in-hardware

but this is what is sent, but doesn't work:
http://list.joshrweinstein.com/posts/6bW5carZSuJpSRxH5/

Has anyone else noticed similar issues? Should I fix locally and submit a pull request?

**Comment by xavcz** [comment]
Nice catch @JoshRWeinstein! There was a missing `slug` in the notification data 😅
