### ISSUE TITLE
Warning: React attempted to reuse markup in a container but the checksum was invalid

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1261]
I have an issue with Server side rendering and I found this StackOverflow [question](http://stackoverflow.com/questions/33521047/warning-react-attempted-to-reuse-markup-in-a-container-but-the-checksum-was-inv) which has some suggestions that don't work for me at the moment. Any ideas?

console output:

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <p data-reactid=".18w
 (server) <div class="wrapper" warning @ modules.js:23533

**Comment by SachaG** [comment]
I don't think this really affects the app? It just means the SSR'ed code is different. In some cases it can't be helped, so we just have to use the no-ssr package: https://github.com/kadirahq/react-no-ssr
