### ISSUE TITLE
Object.Users.can.post - has no method '_isAdmin' in permissions.js

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1263]
There seems to be an issue with the _Admin() helper.

20. // use _isAdmin because there is an isAdmin property on the User schema already
21. Users.helpers({_isAdmin: function () {return Users.is.admin(this);}}); 

Any idea how to avoid this?

W20160305-12:53:56.777(-7)? (STDERR) Error when doing SSR. path:/: Object [object Object] has no method '_isAdmin'
W20160305-12:53:57.020(-7)? (STDERR) TypeError: Object [object Object] has no method '_isAdmin'
W20160305-12:53:57.020(-7)? (STDERR)     at Object.Users.can.post (packages/nova:users/lib/permissions.js:82:12)

**Comment by xavcz** [comment]
This doesn't exist anymore 👍
