### ISSUE TITLE
how to configure Google Tag Manager with Telescope ?

### ISSUE THREAD

**Issue by jayeshdalwadi** [TelescopeJS/Telescope#1265]
I Try to configure Google Tag Manager and i found  https://github.com/GorillaStack/meteor-iron-router-gtm for configure GTM but it was not working with FlowRouter.

Can you Please help me how we can configure GTM  with Telescope.

**Comment by jayeshdalwadi** [comment]
if(Meteor.isClient){
FlowRouter.triggers.enter( [ enterFunction ] );
FlowRouter.triggers.exit( [ exitFunction ] );
  function enterFunction() {
    $('body').append("<noscript id='gtmnoscript'><iframe src=\"//www.googletagmanager.com/ns.html?id=GTM-XXXX\" height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript><script id='gtmscript'>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-XXXXX');</script>")
  }

  function exitFunction() {
    $('#gtmnoscript').remove();
    $('#gtmscript').remove();
  }
}

writing above code block it working for me. this is right way to handle this situation.

Thanks..

**Comment by xavcz** [comment]
Hey, @jayeshdalwadi! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
