### ISSUE TITLE
Can't run Nova 

### ISSUE THREAD

**Issue by forcepath** [TelescopeJS/Telescope#1266]
During npm install:
=> Errors prevented startup:

   While checking for fourseven:scss@0.9.6:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by SachaG** [comment]
Looks like `fourseven:scss` is required by `nova:share`. Maybe you can remove that package, or tweak the `fourseven:scss` dependency's version number?

**Comment by nayelo** [comment]
I just removed `nova-share` and removed it as a dependency from `base-components` and nova's up. Sorry to be lazy, if anyone has the right version number I'll put it back. Amazing work @SachaG and I love the 4 new meteor packages, saved me days of studying.

**Comment by paulmolluzzo** [comment]
The `nova:share` package doesn't specify a version for `fourseven:scss`, so I don't know why it's trying to use `@0.9.6`:
```js
  api.use([
    'nova:core@0.25.7',
    'fourseven:scss'
  ]);
```

If I grep through the project `fourseven:scss` is required by a number of packages, with various package versions like `1.0.0`, `2.1.1`, and `3.4.1`:
```
~/packages/_nova-embedly/
~/packages/_nova-post-by-feed/
~/packages/_nova-subscribe-to-posts/
~/packages/_telescope-daily/
~/packages/nova-categories/
~/packages/nova-lib/
~/packages/nova-newsletter/
~/packages/nova-search/
~/packages/nova-share/
```

It's certainly possible that `nova:share` is the issue, and @nayelo getting it working by removing the package is a good sign. I don't know what version it ought to be pinned to, but honestly, there's so little SCSS in the share package I am guessing any version will do.

I can't reproduce the issue myself, so this is all the advice I can offer.

**Comment by nayelo** [comment]
Restored everything and changed `nova:share` to look for the current version:

```
  api.use([
    'nova:core@0.25.7',
    'fourseven:scss@3.4.1'
  ]);
```

It says `fourseven:scss*  upgraded from 0.9.6 to 3.4.1` and everything works now.

**Comment by paulmolluzzo** [comment]
@nayelo nice! Can you make a PR for that?

**Comment by paulmolluzzo** [comment]
Though I'm still not sure why that was necessary. Without a version definition it should grab the latest... :confused:

**Comment by nayelo** [comment]
Will do in a couple hours. And yes, it's strange.

**Comment by xavcz** [comment]
Well `nova:share` doesn't exist anymore (if someone wants to recreate it, PR welcomed 👍 ), and we fixed the issue with the different versions of `fourseven:scss` 😄
