### ISSUE TITLE
use Rebass UI components?

### ISSUE THREAD

**Issue by vonwao** [TelescopeJS/Telescope#1271]
What do you think Rebass, any desire to use it for Nova?

http://jxnblk.com/rebass/

Finally a react-friendly (and stateless, functional) component library.

**Comment by SachaG** [comment]
Oh that's really cool! We could totally use this, but I wonder if we need to import all these components? Or maybe just recreate the ones we want?

Also, Nova's default front-end component package is supposed to remain very simple and unstyled to be easy to customize, so I don't know if that fits in with this goal?

**Comment by vonwao** [comment]
I think Rebass should be treated like a framework, like a Bootstrap for React.  So we just import the components that are useful.  Maybe not all are useful.  Things like the different Button components and input components could be useful. 

If you look at the code, you'll see it is very simple and the styles are decoupled.  See for example Button component.  And the Base and config are also simple:
https://github.com/jxnblk/rebass/blob/master/src/Button.js
https://github.com/jxnblk/rebass/blob/master/src/Base.js
https://github.com/jxnblk/rebass/blob/master/src/config.js

It is easy to customize by writing a configuration JS file:
https://github.com/jxnblk/rebass/blob/master/demo/configurations/basic.js

I think it fits the goal very well.  If you compare this to solid.css file, the base styles are much smaller.

**Comment by xavcz** [comment]
Hey @vonwao! I kind of refactored this issue in #1464 with some guidelines :)

I'm closing this one, feel free to give a try to what Nova is today, and maybe create a theme with Rebass! 😄 🚀
