### ISSUE TITLE
Embedly Error messages shown to all users

### ISSUE THREAD

**Issue by smhutch** [TelescopeJS/Telescope#1272]
When `getEmbedlyData` returns an error, the error is shown to all users. As shown below (In the image shown above, I am signed in as an admin user, however I also triggered this message while signed in as a non-admin user). Perhaps this error should only be shown through `console.log`, rather than returned to the end user?

![screenshot_030916_031438_pm](https://cloud.githubusercontent.com/assets/7217244/13640823/19006abe-e60e-11e5-9f5d-f2a70e678114.jpg)

**Comment by xavcz** [comment]
Hey, @smhutch! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
