### ISSUE TITLE
Individual user's page not showing all their posts and comments

### ISSUE THREAD

**Issue by flantascience** [TelescopeJS/Telescope#1274]
Hi!
I have an issue which is occurring on multiple Telescope deployments.  When I access the "Users" admin page which lists every user, their number of posts/comments, and karma - everything looks fine and seems accurate.   But when I click on an individual user to see their posts/comments, they do not all populate.  Many are missing.

Any ideas what is going on?

Here is a screenshot showing this issue: <a href="http://flantascience.com/images/issues%20with%20students%20posts.jpg">HERE</a>

Going into my Compose.Io database, when I search the Author under the Posts collection, they all appear: <a href="http://flantascience.com/images/database%20lets%20me%20find%20them%20all.jpg">HERE</a>

Note:  When I look at a particular User's database entry, it doesn't list their posts: <a href="http://flantascience.com/images/user%20collection%20shows%20none.jpg">HERE</a>

And the site this particular screenshot is from is here:   http://bio365.opensourcehigh.com/

**Comment by guo** [comment]
I am having this issue after upgrading to the latest version (7/26/2016): not seeing the posts and comments in users profile.

BTW, which theme are you using? It looks cool! And where is the user list admin page? Thanks!

**Comment by SachaG** [comment]
@guo the initial issue by @flantascience was about the Legacy version, which had a completely different UI. This is what the page should look like: http://demo.telescopeapp.org/users/sample

**Comment by guo** [comment]
@SachaG I see. I am using nova. I found there might be some issue when I upgraded the code: the posts in users profile are all missing. After I edited some posts, the edited posts reappear in user profile page.

**Comment by SachaG** [comment]
Oh I think I know what happened.

**Comment by xavcz** [comment]
This issue got fixed 👍  🎉
