### ISSUE TITLE
Internal links to posts within the site bring you to a blank page (until you refresh)

### ISSUE THREAD

**Issue by flantascience** [TelescopeJS/Telescope#1275]
One some of my posts descriptions, I will link to other posts on the site.  In almost 100% of cases, when a user clicks on the link, it takes them to the new post but the content is completely blank.  If you click 'refresh', the content appears.

An example page where this occurs is <a href="http://videos.opensourcehigh.com/posts/gskGu58mL6dLtygG9/december-student-video-contest-announcement-open-source-high">HERE</a>

Note, it happens on every link except the first one for "How does a microphone work."

The workaround I've been using is to open the links in a new tab using target="_blank"

**Comment by capensisma** [comment]
Solution http://stackoverflow.com/questions/4425198/markdown-target-blank

**Comment by flantascience** [comment]
Isn't this the same thing I mentioned there?   Using target=blank to open in a new page?  I think I've already got that.  In fact, I think you had skyped me that solution :)

I'm trying to get it to load on the same page.

**Comment by xavcz** [comment]
Hey, @flantascience! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
