### ISSUE TITLE
Exception from Tracker recompute function: too much recursion  especially in firefox

### ISSUE THREAD

**Issue by bogere** [TelescopeJS/Telescope#1277]
Thank you very much for this wonderful web app you created.
I do not why iam getting this error in console(client) especially for firefox browser and not getting it  in chrome... 
[Exception in callback of async function: TypeError: Messages.clearSeen is not a function
    at Router._filters.clearSeenMessages (http://localhost:3010/lib/router/filters.js?](url)

**Comment by xavcz** [comment]
Hey, @bogere! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
