### ISSUE TITLE
Migrating remote db to a local db

### ISSUE THREAD

**Issue by angrygoats** [TelescopeJS/Telescope#1282]
I'm working on a telescope deployment that was deployed to Heroku and managed there. It appears to me that the entire application is configured via the database, so managing the installation locally will require me a to copy the database.

The documentation seems to be missing on doing this. What I have tried is this:

1. `mongodump` the remote db
2. `mongorestore` the remote db into a db of the same name (which one is the question)
3. Since it doesnt seems telescope infers the right DB, I set `$MONGO_URL` to point to `localhost:27017/my_database` and fire up the server with `meteor`

The result is it SEEMS some stuff got configured correctly - the title for example is correct. However, there is no styling, and no html is rendered. 

Is there a best practice for doing such a thing? I have verified my databases are 1 to 1, including the name. 

From the logs I get this error a lot:

```
I20160330-10:35:51.268(-7)? Warning: language en is not supported in this project, fallback language (en)
I20160330-10:35:51.269(-7)? Exception in setInterval callback: TypeError: Object [object Object] has no method 'en'
I20160330-10:35:51.269(-7)?     at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:29:16)
I20160330-10:35:51.269(-7)?     at Object.i18n.t (packages/telescope:i18n/i18n.js:37:20)
I20160330-10:35:51.270(-7)?     at Object.schema.(anonymous function).label (packages/telescope:i18n/i18n.js:52:21)
I20160330-10:35:51.270(-7)?     at packages/aldeed_simple-schema.js:1811:31
I20160330-10:35:51.270(-7)?     at Function._.each._.forEach (packages/underscore.js:142:22)
I20160330-10:35:51.270(-7)?     at [object Object].SimpleSchema.getDefinition (packages/aldeed_simple-schema.js:1809:5)
I20160330-10:35:51.270(-7)?     at checkObj (packages/aldeed_simple-schema.js:2391:16)
I20160330-10:35:51.270(-7)?     at packages/aldeed_simple-schema.js:2487:11
I20160330-10:35:51.270(-7)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20160330-10:35:51.270(-7)?     at packages/aldeed_simple-schema.js:2479:11
```

**Comment by xavcz** [comment]
If you were using Legacy, upgrading to 1.3 may have broken stuff. I advice you to try Nova :+1:
