### ISSUE TITLE
iOS links not opening

### ISSUE THREAD

**Issue by gg2001** [TelescopeJS/Telescope#1283]
Telescope has been great, the web app is amazing, however there is an issue with the mobile app. When I press a link that was posted, it does not open. I have the ability to add it to my reading list, but I cannot actually open it in Safari. I am using Meteor 1.3, running on iOS 9.2. I have deployed my app to Heroku, and I am using an iPhone 6s. Is there a way to fix this? Is anyone else having a similar problem?

This problem has been there from previous meteor versions, so I do not think this is a new problem.

**Comment by xavcz** [comment]
Hey, @gg2001! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
