### ISSUE TITLE
Question: Is it possible to 'post to category'

### ISSUE THREAD

**Issue by benedfit** [TelescopeJS/Telescope#1293]
Hi

I'm looking for the best way to allow users to add posts to the category they are viewing, without having to choose the categories themselves. Are there any plugins that could achieve this?

Cheers

Ben

**Comment by MHerszak** [comment]
You mean you are within a category and you want to submit post?

**Comment by benedfit** [comment]
Yes, but have the category you are in auto-select in the new post form. E.g. I'm viewing all the posts in the 'support' category. I click the 'post' button and 'support' is already selected from the available categories in the form

**Comment by SachaG** [comment]
Not currently possible, sorry.

**Comment by bluerabbbit** [comment]
Would be a nice feature to add though. +1

**Comment by xavcz** [comment]
Hey @benedfit @bluerabbit! 

It could be done now, as Nova changed a lot in the past months 😄 

You could create a custom component for `nova:forms` inspired on the shape of the checkbox group or `nova:forms-tag` that would catch the category's slug (if existing) thanks to `withRouter` (router method) and add the value to the state of the form 👍 

Feel free to create a package for that or to come by the Slack room to ask any question!
