### ISSUE TITLE
Exception while invoking method upvotePost

### ISSUE THREAD

**Issue by shingo0620** [TelescopeJS/Telescope#1296]
When I want to change my vote from downvote to upvote

I20160411-17:06:35.901(8)? Exception while invoking method 'upvotePost' { stack: 'ReferenceError: itemd is not defined\n    at [object Object].Telescope.operateOnItem (lib/vote.js:40:45)\n    at [object Object].Meteor.methods.upvotePost (lib/vote.js:99:36)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/Users/shingo0620/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)',
I20160411-17:06:35.912(8)?   source: 'method' }

**Comment by xavcz** [comment]
Hey, @shingo0620! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
