### ISSUE TITLE
error in first tutorial

### ISSUE THREAD

**Issue by mckinleymedia** [telescopejs/telescope#13]
Had to change line 9 in "moviesUsers" to this:
currentUser ? <p>Welcome, {currentUser.displayName} {currentUser.isAdmin && `(admin)`}</p>:

**Comment by imcuttle** [comment]
Hi, @mckinleymedia !
Sorry, I guess the repo is not you wanted #10 .

**Comment by mckinleymedia** [comment]
Oops. Sry. Closing...
