### ISSUE TITLE
posted at doesn't automaically give you a timestamp

### ISSUE THREAD

**Issue by bluerabbbit** [TelescopeJS/Telescope#1305]
So, if I add a new post to mysite, I have to manually type in the posted at time.
Running the latest from master nova

**Comment by SachaG** [comment]
Well, if you leave it empty it should get set automatically. But yeah, I agree it should be prefilled with the current time, too.

**Comment by franciskim** [comment]
Getting `Invalid Date` on my posts as well.

**Comment by xavcz** [comment]
I've made some changes to the `postedAt` field on Posts collection recently. I have no error posting/editing with a normal account and an admin account. How did you get an invalid date value?

**Comment by franciskim** [comment]
I'm on the master branch. Funny thing is out of the 3 posts I've created, 1 actually has a date. I'm on the Sydney time zone which is GMT +10...

**Comment by franciskim** [comment]
checked out the devel branch and ran npm install again, then now I have the the date field showing in the post edit page. Issue seems fixed...

**Comment by xavcz** [comment]
Cool!
