### ISSUE TITLE
[Nova] npm errors when running npm install on clean clone

### ISSUE THREAD

**Issue by nicholasalanbrown** [TelescopeJS/Telescope#1307]
Really excited about Nova!

I get peer dependency errors when running `npm install` on a clean `git clone` of Nova. See the screen shot below:

![image](https://cloud.githubusercontent.com/assets/3259022/14615356/3a8db9a0-0573-11e6-9a95-2eb3256c24c8.png)

Does the repo need to be reverted to an earlier version of React until those packages support the newest?

**Comment by capensisma** [comment]
Just use my packages.json here https://github.com/TelescopeJS/Telescope/pull/1303
 and it will fix it

yes the clean install doesn't work now :(

**Comment by capensisma** [comment]
but if you use that it will fix the dependencies

**Comment by nicholasalanbrown** [comment]
That mostly worked, by I still get a warning about `react-addons-pure-render-mixin`:

![image](https://cloud.githubusercontent.com/assets/3259022/14619919/ff51698a-0587-11e6-8217-3df5d6f09d82.png)

**Comment by capensisma** [comment]
Your app is working correctly and that's just a warning just ignore it for now until it gets fixed (new version)

**Comment by SachaG** [comment]
Well I don't recommend downgrading to 0.14, since most packages should work with React 15 in the neat future. The errors shouldn't prevent you from running your app unless maybe you've got an old version of NPM, so I would suggest making sure you have NPM 3+ first.

**Comment by capensisma** [comment]
yes sure but npm 3+ is having very bad issue on windows so if you're on mac or linux go for it

but on windows nope! for now

**Comment by SachaG** [comment]
Oh ok, I didn't know. In that case then yeah, you can use 0.14 for now.

**Comment by xavcz** [comment]
Try on a fresh clone or pull the latest updates, it works fine now (react 15.3.x)
