### ISSUE TITLE
Switch from login > register keeps password but not username

### ISSUE THREAD

**Issue by justintime4tea** [TelescopeJS/Telescope#1308]
When you click "Log In" and fill out the form but instead need to register so you then click register, it keeps the password you've already typed but the username (though it is shown) is not recognized when submitting the form.

Reproduction Steps:

1. Goto Telescope deployed app
2. Click "Log In" and fill out username and password.
3. Do not click "Sign In" and instead click "Register"
4. Fill out your e-mail
5. Click "Register"
6. Receive error about missing username (though you can see it in username form field)
7. Refill the username but do not refill password and email, they should still be there
8. Click "Register" - Now it accepts username and previously entered password as well as email and then creates user.

![login_register_bug_image-01](https://cloud.githubusercontent.com/assets/4065262/14625925/3133835c-05b5-11e6-9d70-b04fc3fa8287.jpg)
![login_register_bug_image-02](https://cloud.githubusercontent.com/assets/4065262/14625928/374d20b8-05b5-11e6-95f3-bc344298ca29.jpg)

**Comment by SachaG** [comment]
Thanks! But actually Nova uses [accounts-ui](https://github.com/studiointeract/accounts-ui) to handle accounts, so that issue probably belongs on their repo. Maybe you can cross-post it there?
