### ISSUE TITLE
Cannot view Admin page?

### ISSUE THREAD

**Issue by mela-s** [TelescopeJS/Telescope#1309]
Hi. I installed Telescope today and I got it to run locally -- hurrah.

After looking through some pages/issues, I've read that there is supposed to be an Admin page where you can identify settings such as grid/list format. Does this page still exist? I'm registered as an Admin (that box is ticked on my profile page). I can only see the Settings modal but the settings appear limited.

I'm not a developer (testing this as a side to my actual tasks) so I apologise in advance if the answer is glaringly obvious :/

**Comment by SachaG** [comment]
Sorry, that admin page only existed in the previous (Legacy) version, it doesn't exist anymore. It's been replaced by the settings modal (or the `settings.json` file).
