### ISSUE TITLE
Meteor 1.3 breaks telescope?

### ISSUE THREAD

**Issue by JulianKingman** [TelescopeJS/Telescope#1310]
I'm getting these errors:
````
Uncaught Error: Helpers dictionary has to be an object
Uncaught ReferenceError: Events is not defined
````

And on the server side:
````
Warning: language en is not supported in this project, fallback language (en)
Exception in setInterval callback: TypeError: Object [object Object] has no method 'en'
````

It looks like meta.telescopeapp.org is down, but I found a cached page where there was discussion that telescope is not compatible with Meteor 1.3, is that right, or is there something that can be done to fix it?

**Comment by SachaG** [comment]
Legacy Telescope is not compatible with 1.3, but Nova is. And http://meta.telescopeapp.org/ works for me?

**Comment by JulianKingman** [comment]
Is there something that can be done to make it compatible, or is it best to switch

**Comment by SachaG** [comment]
It's definitely best to switch if you can. Or else just stay on 1.2.

**Comment by JulianKingman** [comment]
I'll stay on 1.2 for now, I've written a lot of custom code. What makes it incompatible? Is it fixable, or the issues are too extensive?

**Comment by arrygoo** [comment]
:<

**Comment by xavcz** [comment]
Hey @JulianKingman! This may require a lot of work, I advice to switch to Nova 👍 

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Comment by JulianKingman** [comment]
OK, thank you!
