### ISSUE TITLE
Heroku Build Failing

### ISSUE THREAD

**Issue by splnty** [TelescopeJS/Telescope#1313]
Heroku Brand New App Log: 

-----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
###############################                                         47.0%###################################                                       48.7%###########################################                               60.4%
Meteor 1.3.2.4 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack20160423-158-48bm7a/meteor-6HNq/.meteor/packages/meteor-tool/1.3.2_4/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
$ROOT_URL, if specified, must be an URL.
-----> Upgrading meteor to METEOR@1.3.2.2
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app

**Comment by SachaG** [comment]
Heroku can fail sometimes, you just need to try again. That being said I would recommend MupX over Heroku as a deploy method.
