### ISSUE TITLE
Add soft delete for comments

### ISSUE THREAD

**Issue by justintime4tea** [TelescopeJS/Telescope#1314]
# Feature Request

Add the ability to ***`soft delete`*** comments.

**Soft Delete:**  
```
Replace body of comment with "Delete" and flag as isDeleted.
Remove ability to edit and "soft delete" once comment is flagged as isDeleted.
Reduce the posts and users comment count.
Subsequent replies to "soft deleted" comment will remain un-touched.
```

**Comment by justintime4tea** [comment]
I created this so I could reference the issue ID when creating the feature branch and subsequent pull request.
Feature branch will be labeled:  feature-1314 and can be referenced back to this issue.

**Comment by CollinGraves** [comment]
Can this be closed?
