### ISSUE TITLE
Need a website Telescope Nova demo!

### ISSUE THREAD

**Issue by kienvn** [TelescopeJS/Telescope#1316]
I'm new to Telescope
I built a website use https://github.com/TelescopeJS/sample-project
But this website less features than old Telescope
I don't know i did anything wrong.
Can you build a website demo like http://demo.telesc.pe/ or share website you built by Telescope Nova?

**Comment by Jarskih** [comment]
You can use legacy Telescope. It looks like demo app on that link.

**Comment by sanshiro** [comment]
@Jarskih i have the same problem here as @kienvn, can you add a "deploy on heroku" function with the regular legacy telescope to test? O.o i'm very noob on github

**Comment by Jarskih** [comment]
I recommend using MupX to deploy Telescope to Digitalocean server.

**Comment by xavcz** [comment]
The demo is at http://meta.telescopeapp.org 🎉
