### ISSUE TITLE
Running in a subfolder produces unwanted redirect on each page load

### ISSUE THREAD

**Issue by IlyaSemenov** [TelescopeJS/Telescope#1322]
Problem
======

Running in a subfolder produces unwanted redirect on each page load.

For instance, if you set up Telescope to run at http://localhost:3000/telescope, it will load up fine, show the feed and then immediately redirect to http://localhost:3000/telescope/telescope

Steps to reproduce
==============

Run a fresh Telescope install:
```
$ git clone https://github.com/TelescopeJS/Telescope
$ cd Telescope
$ npm install
$ ROOT_URL=http://localhost:3000/telescope meteor
...
=> App running at: http://localhost:3000/telescope
```

1. Open http://localhost:3000/telescope
2. In a few seconds, the app will load and redirect to http://localhost:3000/telescope/telescope
3. (optionally) Refresh the page and it will redirect to http://localhost:3000/telescope/telescope/telescope

Duplicate ticket
====
There is a ticket #105 mentioning the same topic but it's 3 years old.

For the time being Telescope works **mostly** fine when started with non-root `ROOT_URL` (the resources load fine, the post feeds show up at first, the registration and login works, etc.) — it's only needed to trace and fix the extra redirect.

**Comment by SachaG** [comment]
I just don't recommend running Telescope in a sub-directory, sorry. The benefits are probably not worth the extra work involved to make it work.
