### ISSUE TITLE
Admin Email cannot receive the new user creation notifications

### ISSUE THREAD

**Issue by bingyangli** [TelescopeJS/Telescope#1328]
I followed the READ.ME to set up the email config. It works fine for the email testing cheat sheet at localhost:3000/emails. But when I created a new user, the admin email cannot receive the creation notification.

**Comment by yoodame** [comment]
@bingyangli I had to check the "New Users Notifications" box as admin to receive notifications.

**Comment by capensisma** [comment]
You need to restart the app after adding the smtp settings

**Comment by xavcz** [comment]
:+1:
