### ISSUE TITLE
Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

### ISSUE THREAD

**Issue by naysumyat** [TelescopeJS/Telescope#1331]
I am getting this error after a fresh install of Nova  on OSX.My meteor version is 1.3.1.
Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

**Comment by SachaG** [comment]
Did you run `npm install`?

**Comment by naysumyat** [comment]
I just run meteor . Sorry. I didn't recognize my  npm install command has not finished successfully.it is ok now. thanks
