### ISSUE TITLE
Million upvotes by a user

### ISSUE THREAD

**Issue by sahanDissanayake** [TelescopeJS/Telescope#1338]
Hi
At the moment all the upvotes are saved on user > telescope > upvotedPosts ( lets say )

A user has million upvotes, so does that mean telescope is going to send the million upoted records inside user > telescope > upvotedPosts  to the client ?

I'm just curious how to get around this issue. 
This is similar to http://www.wired.com/2015/11/how-instagram-solved-its-justin-bieber-problem/

**Comment by SachaG** [comment]
Yes. Whenever someone does have a million upvotes on a user object, they'll be welcome to submit a PR to fix the problem :)

**Comment by sahanDissanayake** [comment]
ook so no premature optimisation ?

**Comment by sahanDissanayake** [comment]
is this issue / scale matter on your mind tho ? 

Can u guide me how to go about this ? how could one look at this issue and submit a pr before they hit a million records and slowing everything down ? thanks

**Comment by SachaG** [comment]
Yeah it's not very complicated, you'd just need to create a separate `votes` collection and make a join (and migrate existing data).

**Comment by SachaG** [comment]
You can look at how comments are implemented for example.

**Comment by sahanDissanayake** [comment]
tanks, thats what i wanted. some guidance. I will look in to it

**Comment by sahanDissanayake** [comment]
Hi Sacha,

I'm trying to find where and how the scaling is taking place with comments,

I still see an array of commenters inside the post object in Telescope.

Is that ok to have million userId's inside an array ``post > commenters []`` ? thanks

**Comment by SachaG** [comment]
You're right that the ids of commenters are stored on the post document, to make it easy to (for example) show the avatars of the 3 most recent commenters. But it could easily be removed, and you'll note the comments themselves aren't stored on the post document.

**Comment by sahanDissanayake** [comment]
yes, that is correct. Only the id's are stored. 
is this line doing anything ??
https://github.com/TelescopeJS/Telescope/blob/5679ecf7e8324606363dde6a78a7cb4a326bd9cf/packages/nova-comments/lib/custom_fields.js#L28

I was testing and more that 4 ids are stored on a post comments field

**Comment by SachaG** [comment]
This line doesn't change how many IDs are stored, only how many are joined onto the post document at join time on the client (see https://github.com/meteor-utilities/react-list-container).

**Comment by sahanDissanayake** [comment]
I think I finally got it.
I just have the count of children documents on the main Document and lets say all the comments in a different collection. When I need to get all the comments for the Main Document I get them through either a method call or a publish/sub

thanks Sacha
