### ISSUE TITLE
No links working on Safari.

### ISSUE THREAD

**Issue by sampattuzzi** [TelescopeJS/Telescope#1343]
This previously worked fine when using the default packages installed by meteor. Navigation would work on all platforms.

However, since updating to devel (ae7865396fdc7505ef0833fb6363455e92405bf2) it has become impossible to navigate anywhere on iPhone. I'm not sure if this is also a problem on master as another bug prevents me from testing that.

**Comment by SachaG** [comment]
I wonder why it would only happen on iPhone. Anything in the console?

**Comment by BenTristem** [comment]
Hi Sacha, so this happens on iPhone and iPad in both Chrome and Safari. Nothing in the logs that I can see. Any idea where to start?

**Comment by BenTristem** [comment]
@xavcz this is the issue I was referring to, reproduced both locally and via Scalingo on iPad and iPhone in multiple browsers... odd!

**Comment by SachaG** [comment]
Does it happen in desktop browsers too?

**Comment by BenTristem** [comment]
No, just iOS

**Comment by sampattuzzi** [comment]
Correction: this happens in Safari too. Apparently it was due to react-intl using the new Intl JS API which is not yet supported by Safari on any platform. I have created a pull request for this.

**Comment by xavcz** [comment]
The issue got fixed 👍
