### ISSUE TITLE
Hyphen removed from subdomain

### ISSUE THREAD

**Issue by cllns** [TelescopeJS/Telescope#1347]
I'm hosting at a domain like: `http://my-forum.example.com`
The 'text' posts are fine, but when I share a URL, it switches to:
 `http://myforum.example.com/out?url=http%3A%2F%2Fgoogle.com`

Which is a broken link, because my site isn't `myforum.example.com`

Not sure if it's only because it's a subdomain, or any part of the URL.

**Comment by cllns** [comment]
I was able to fix this by setting the site's domain in the Settings.

The settings form says it uses `Meteor.absoluteUrl()` by default, so maybe the issue is in Meteor?

**Comment by SachaG** [comment]
That's weird! I don't really know why that would happen, but glad you found a fix.
