### ISSUE TITLE
crash when meteor update 

### ISSUE THREAD

**Issue by fortunto2** [TelescopeJS/Telescope#1350]
When update to Meteor 1.3.3

`
WARNING: npm peer requirements not installed:
 - react@15.1.0 installed, react@^0.14.6 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

WARNING: npm peer requirements not installed:
 - react@15.1.0 installed, react@^0.14.6 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

/home/rustam/.meteor/packages/meteor-tool/.1.3.3.1guq8e6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						      ^
TypeError: Cannot read property 'ListContainer' of undefined
    at meteorInstall.node_modules.meteor.nova:base-components.lib.common.Header.jsx (packages/nova:base-components/lib/common/Header.jsx:9:23)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at meteorInstall.node_modules.meteor.nova:base-components.lib.components.js (packages/nova:base-components/lib/components.js:5:53)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/packages/nova_base-components.js:4584:1
    at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/packages/nova_base-components.js:4591:3
    at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/boot.js:291:10
    at Array.forEach (native)
Exited with code: 8
Your application is crashing. Waiting for file change.
`

**Comment by SachaG** [comment]
What if you update and try again now?

**Comment by fortunto2** [comment]
new git clone and npm install
give error

`
lled/read-installed.js:263:14
747 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
747 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
747 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
747 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
748 verbose cwd /home/rustam/lifefilm/Telescope
749 error Linux 4.2.0-35-generic
750 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "history"
751 error node v0.12.14
752 error npm  v2.15.1
753 error code EPEERINVALID
754 error peerinvalid The package history@3.0.0 does not satisfy its siblings' peerDependencies requirements!
754 error peerinvalid Peer use-named-routes@0.3.1 wants history@^2.0.0
755 verbose exit [ 1, true ]

`

**Comment by fortunto2** [comment]
after manual install history, run meteor
and give error

W20160616-17:24:32.217(5)? (STDERR)           
W20160616-17:24:32.217(5)? (STDERR) /home/rustam/.meteor/packages/meteor-tool/.1.3.3.wlexty++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160616-17:24:32.218(5)? (STDERR)             				throw(ex);
W20160616-17:24:32.218(5)? (STDERR)             				      ^
W20160616-17:24:32.385(5)? (STDERR) TypeError: undefined is not a function
W20160616-17:24:32.386(5)? (STDERR)     at meteorInstall.node_modules.meteor.nova:base-components.lib.common.SearchForm.jsx (packages/nova:base-components/lib/common/SearchForm.jsx:68:18)
W20160616-17:24:32.386(5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160616-17:24:32.387(5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160616-17:24:32.387(5)? (STDERR)     at meteorInstall.node_modules.meteor.nova:base-components.lib.components.js (packages/nova:base-components/lib/components.js:14:53)
W20160616-17:24:32.387(5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160616-17:24:32.388(5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160616-17:24:32.389(5)? (STDERR)     at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/packages/nova_base-components.js:5139:1
W20160616-17:24:32.391(5)? (STDERR)     at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/packages/nova_base-components.js:5145:3
W20160616-17:24:32.391(5)? (STDERR)     at /home/rustam/lifefilm/Telescope/.meteor/local/build/programs/server/boot.js:291:10
W20160616-17:24:32.392(5)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8                        
`
`

**Comment by fortunto2** [comment]
now worked, thanks
after update from git
