### ISSUE TITLE
Having trouble installing.

### ISSUE THREAD

**Issue by cashloop** [TelescopeJS/Telescope#1352]
Hello, I'm trying to install Telescopejs. This is the first time I've used Command line (Terminal on Mac 10.6.8) so please forgive me if it's an obvious mistake. I've read that Meteor doesn't work on 10.6.8 but I have gotten it to load the default project, where it counts how many times you click the button. So I assume it installs the most compatible version with my Mac.

Here are the commands I ran:
meteor create telescope
cd telescope
git clone git@github.com:TelescopeJS/Telescope.git
npm install
metoer

And this is what terminal replies with:
`=> Exited with code: 8
                                              
Unable to resolve some modules:

  "react" in                                  
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(web.browser)
  "react-intl" in                             
/Users/jim/telescope/Telescope/packages/nova-forms/lib/NovaForm.jsx
(web.browser)
  "react-bootstrap" in                        
/Users/jim/telescope/Telescope/packages/nova-demo/demo-components.jsx
(web.browser)
  "react-router" in                           
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(web.browser)
  "react-router-bootstrap" in                 
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/users/UsersMenu.jsx
(web.browser)
  "classnames" in                             
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/common/Vote.jsx
(web.browser)
  "moment" in                                 
/Users/jim/telescope/Telescope/packages/nova-users/lib/helpers.js
(web.browser)
  "formsy-react" in                           
/Users/jim/telescope/Telescope/packages/nova-forms/lib/FormComponent.jsx
(web.browser)
  "formsy-react-components" in                
/Users/jim/telescope/Telescope/packages/nova-forms/lib/FormComponent.jsx
(web.browser)
  "react-cookie" in                           
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/common/Newsletter.jsx
(web.browser)
  "react-komposer" in                         
/Users/jim/telescope/Telescope/packages/nova-core/lib/containers/AppComposer.jsx
(web.browser)
  "react-tag-input" in                        
/Users/jim/telescope/Telescope/packages/nova-forms-tags/lib/components/Tags.jsx
(web.browser)
  "react-mounter" in                          
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(web.browser)
  "use-named-routes" in                       
/Users/jim/telescope/Telescope/packages/nova-base-routes/lib/routes.jsx
(web.browser)
  "history/lib/createBrowserHistory" in       
/Users/jim/telescope/Telescope/packages/nova-base-routes/lib/routes.jsx
(web.browser)
  "marked" in                                 
/Users/jim/telescope/Telescope/packages/nova-users/lib/callbacks.js
(web.browser)
  "react-bootstrap-datetimepicker" in         
/Users/jim/telescope/Telescope/packages/nova-forms/lib/DateTime.jsx
(web.browser)
  "classnames/dedupe" in                      
/Users/jim/telescope/Telescope/packages/nova-forms/lib/row.js
(web.browser)
  "intl-locales-supported" in                 
/Users/jim/telescope/Telescope/packages/nova-lib/lib/intl-polyfill.js
(web.browser)
  "intl" in                                   
/Users/jim/telescope/Telescope/packages/nova-lib/lib/intl-polyfill.js
(web.browser)
  "sanitize-html" in                          
/Users/jim/telescope/Telescope/packages/nova-lib/lib/utils.js
(web.browser)
  "speakingurl" in                            
/Users/jim/telescope/Telescope/packages/nova-lib/lib/utils.js
(web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save react react-intl react-bootstrap react-router
react-router-bootstrap classnames moment formsy-react formsy-react-components
react-cookie react-komposer react-tag-input react-mounter use-named-routes
history marked react-bootstrap-datetimepicker intl-locales-supported intl
sanitize-html speakingurl
                                              
                                              
Unable to resolve some modules:

  "marked" in                                 
/Users/jim/telescope/Telescope/packages/nova-users/lib/callbacks.js
(os.osx.x86_64)
  "react" in                                  
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(os.osx.x86_64)
  "react-intl" in                             
/Users/jim/telescope/Telescope/packages/nova-forms/lib/NovaForm.jsx
(os.osx.x86_64)
  "react-bootstrap" in                        
/Users/jim/telescope/Telescope/packages/nova-demo/demo-components.jsx
(os.osx.x86_64)
  "react-router" in                           
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(os.osx.x86_64)
  "react-router-bootstrap" in                 
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/users/UsersMenu.jsx
(os.osx.x86_64)
  "classnames" in                             
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/common/Vote.jsx
(os.osx.x86_64)
  "moment" in                                 
/Users/jim/telescope/Telescope/packages/nova-users/lib/helpers.js
(os.osx.x86_64)
  "formsy-react" in                           
/Users/jim/telescope/Telescope/packages/nova-forms/lib/FormComponent.jsx
(os.osx.x86_64)
  "formsy-react-components" in                
/Users/jim/telescope/Telescope/packages/nova-forms/lib/FormComponent.jsx
(os.osx.x86_64)
  "react-cookie" in                           
/Users/jim/telescope/Telescope/packages/nova-base-components/lib/common/Newsletter.jsx
(os.osx.x86_64)
  "cloudinary" in                             
/Users/jim/telescope/Telescope/packages/nova-cloudinary/lib/server/cloudinary.js
(os.osx.x86_64)
  "react-komposer" in                         
/Users/jim/telescope/Telescope/packages/nova-core/lib/containers/AppComposer.jsx
(os.osx.x86_64)
  "juice" in                                  
/Users/jim/telescope/Telescope/packages/nova-email/lib/server/email.js
(os.osx.x86_64)
  "html-to-text" in                           
/Users/jim/telescope/Telescope/packages/nova-newsletter/lib/server/mailchimp.js
(os.osx.x86_64)
  "handlebars" in                             
/Users/jim/telescope/Telescope/packages/nova-email/lib/server/email.js
(os.osx.x86_64)
  "react-tag-input" in                        
/Users/jim/telescope/Telescope/packages/nova-forms-tags/lib/components/Tags.jsx
(os.osx.x86_64)
  "mailchimp" in                              
/Users/jim/telescope/Telescope/packages/nova-newsletter/lib/server/mailchimp_api.js
(os.osx.x86_64)
  "react-mounter" in                          
/Users/jim/telescope/Telescope/packages/nova-demo/demo-app.jsx
(os.osx.x86_64)
  "use-named-routes" in                       
/Users/jim/telescope/Telescope/packages/nova-base-routes/lib/routes.jsx
(os.osx.x86_64)
  "history/lib/createBrowserHistory" in       
/Users/jim/telescope/Telescope/packages/nova-base-routes/lib/routes.jsx
(os.osx.x86_64)
  "react-bootstrap-datetimepicker" in         
/Users/jim/telescope/Telescope/packages/nova-forms/lib/DateTime.jsx
(os.osx.x86_64)
  "classnames/dedupe" in                      
/Users/jim/telescope/Telescope/packages/nova-forms/lib/row.js
(os.osx.x86_64)
  "intl-locales-supported" in                 
/Users/jim/telescope/Telescope/packages/nova-lib/lib/intl-polyfill.js
(os.osx.x86_64)
  "intl" in                                   
/Users/jim/telescope/Telescope/packages/nova-lib/lib/intl-polyfill.js
(os.osx.x86_64)
  "sanitize-html" in                          
/Users/jim/telescope/Telescope/packages/nova-lib/lib/utils.js
(os.osx.x86_64)
  "speakingurl" in                            
/Users/jim/telescope/Telescope/packages/nova-lib/lib/utils.js
(os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save marked react react-intl react-bootstrap
react-router react-router-bootstrap classnames moment formsy-react
formsy-react-components react-cookie cloudinary react-komposer juice
html-to-text handlebars react-tag-input mailchimp react-mounter
use-named-routes history react-bootstrap-datetimepicker intl-locales-supported
intl sanitize-html speakingurl
                                              
I20160616-10:06:30.449(1)? ** You've set up some data subscriptions with Meteor.publish(), but
I20160616-10:06:30.451(1)? ** you still have autopublish turned on. Because autopublish is still
I20160616-10:06:30.452(1)? ** on, your Meteor.publish() calls won't have much effect. All data
I20160616-10:06:30.452(1)? ** will still be sent to all clients.
I20160616-10:06:30.453(1)? **                 
I20160616-10:06:30.453(1)? ** Turn off autopublish by removing the autopublish package:
I20160616-10:06:30.456(1)? **                 
I20160616-10:06:30.459(1)? **   $ meteor remove autopublish
I20160616-10:06:30.460(1)? **                 
I20160616-10:06:30.460(1)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20160616-10:06:30.461(1)? ** for each collection that you want clients to see.
I20160616-10:06:30.462(1)?                    
W20160616-10:06:30.471(1)? (STDERR)           
W20160616-10:06:30.472(1)? (STDERR) /Users/jim/.meteor/packages/meteor-tool/.1.3.3.ems6rm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160616-10:06:30.472(1)? (STDERR)             				throw(ex);
W20160616-10:06:30.473(1)? (STDERR)             				      ^
W20160616-10:06:32.433(1)? (STDERR) ReferenceError: Picker is not defined
W20160616-10:06:32.434(1)? (STDERR)     at meteorInstall.Telescope.packages._nova-invites.lib.server.routes.js (Telescope/packages/_nova-invites/lib/server/routes.js:2:1)
W20160616-10:06:32.435(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160616-10:06:32.435(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160616-10:06:32.436(1)? (STDERR)     at /Users/jim/telescope/.meteor/local/build/programs/server/app/app.js:21137:1
W20160616-10:06:32.436(1)? (STDERR)     at /Users/jim/telescope/.meteor/local/build/programs/server/boot.js:291:10
W20160616-10:06:32.437(1)? (STDERR)     at Array.forEach (native)
W20160616-10:06:32.437(1)? (STDERR)     at Function._.each._.forEach (/Users/jim/.meteor/packages/meteor-tool/.1.3.3.ems6rm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160616-10:06:32.438(1)? (STDERR)     at /Users/jim/telescope/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
`

Any help would be greatly appreciated!  Thank you

**Comment by SachaG** [comment]
It sounds like it can't find NPM modules. So that means `npm install` didn't work properly, I guess.

**Comment by cashloop** [comment]
ok I'll give that another try. Let me just check I have this right. So in my project folder (telescope) I have node_modules, Telescope (git clone git@github.com:TelescopeJS/Telescope.git), server, client folders and package.json. Is this set up correctly, or does Telescope file need to be in Client?
Should I run npm install in 
cd telescope
cd Telescope

**Comment by SachaG** [comment]
It doesn't sound like you cloned the repo properly, there are no Telescope, server, or client directories inside the project. Maybe you could clone it again from scratch?

**Comment by merhawifissehaye** [comment]
@SachaG There is no Telescope, server, or client directory in the github repo. Take a look at [this](https://github.com/TelescopeJS/Telescope).
I encountered the same issue. I `npm install` and then `meteor` after cloning the repository and `cd`ing into it. I found the following error:

```
Unable to resolve some modules:

  "react-overlays/lib/utils/overlayPositionUtils" in /Users/merhawi/Documents/hubs/codehub/meteor/Telescope/node_modules.old/react-bootstrap/lib/utils/overlayPositionUtils.js
(web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save react-overlays 
```

Then the application crashes. 

```
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
```

**Comment by xavcz** [comment]
I advice you to follow the README instructions, it's working well now 👍 🎉
