### ISSUE TITLE
[Nova] Post comments sort

### ISSUE THREAD

**Issue by beeva-franciscocalle** [TelescopeJS/Telescope#1354]
Since - in Nova - comments cannot be up/down-voted, post comments view should not use score for sorting anymore. Code in `nova-comments/lib/views.js` should be changed

```js
Comments.views.add("postComments", function (terms) {
  return {
    selector: {postId: terms.postId},
    options: {limit: 0, sort: {score: -1, postedAt: -1}}
  };
});
```

I can post a PR if needed.

**Comment by SachaG** [comment]
Good point! I'll change it.

**Comment by kevinyun** [comment]
Is there a setting in Nova where we can enable comments to be upvoted/downvoted?

Any reason comment voting was removed for Nova?

**Comment by osterkraft** [comment]
I'm also interested in knowing more about this feature. If it's not on the roadmap, could anyone advise on the best way to implement it? Would writing an extension module be sufficient, or would I need to replace nova-comments completely?

**Comment by SachaG** [comment]
@osterkraft the part that makes this a little bit more complex is that comments are nested. So to implement a sort properly, we'd need to do it recursively on each branch of the comment tree. 

Practically speaking, I think that would mean modifying the `Utils.unflatten` function to accept a fourth `sort` parameter, which can then be controlled by the component. All comments are currently loaded on the client so the sort can be client-only, by the way. 

I'd be happy to accept a PR for this :)

**Comment by osterkraft** [comment]
Thanks @SachaG for your feedback. It seems you implemented this again recently if I'm not mistaken :+1:

**Comment by SachaG** [comment]
Comment voting works now, but for comment sorting the situation hasn't changed.
