### ISSUE TITLE
NovaForm submitCallback not working

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1355]
I looked at the code and it should work but I am currently doing a simple console.log but the call back isn't fired even when the props are available. Any idea?

**Comment by SachaG** [comment]
Hard to say without more data. Do you have a link to your code?

**Comment by MHerszak** [comment]
`<NovaForm currentUser={Meteor.user()}
                     collection={Lectures}
                     methodName="lectures.new"
                     submitCallback={function(doc){
                            console.log(doc);
                            doc = _.extend(doc, {
                              createdAt: new Date(),
                              courseId: Meteor.userId()
                            });
                            return document;
                      }}
                      successCallback={(res)=>{
                        Messages.flash("A lecture was added.", "success");
                     }}/>`
I am currently working on adding a new prop to pass those values. submitCallback is just not fired even though I don't see any issue with the code. No idea.

**Comment by SachaG** [comment]
Looking at the code, even if it were called it wouldn't really do much. I'll push a commit to improve it.

**Comment by SachaG** [comment]
Also I would recommend just using hidden fields to pass data. Seems like the simplest way to do it to me.

**Comment by MHerszak** [comment]
I did it adding a new field. I am guessing I will try it later again. Thanks, thou!
