### ISSUE TITLE
Possible to install on shared hosting? without npm install command

### ISSUE THREAD

**Issue by cashloop** [TelescopeJS/Telescope#1357]
Hello, my shared hosting won't let me run the 'npm install' command. Is there any way to install telescope without it?

**Comment by SachaG** [comment]
https://github.com/TelescopeJS/Telescope/#deployment

**Comment by cashloop** [comment]
Thank you. I took a look at Meteor Up but to install that it also requires 'npm install' command. Or am I missing something?

**Comment by SachaG** [comment]
Yes, you need to have Node to run MupX locally, and you also need to install it on your server to run Meteor,

**Comment by cashloop** [comment]
damn ok my hosting only allows jailshell. I think I will have to go with digitalocean.
