### ISSUE TITLE
Vue.js migration

### ISSUE THREAD

**Issue by janat08** [TelescopeJS/Telescope#1358]
What about that? The vue.js documentation will explain how the 2 differ, but evidently it's more so convenient or otherwise less ironclad.

**Comment by SachaG** [comment]
The goal for Telescope would be that it's not React-dependant (apart from the components package), but we're not quite there yet. I'll be happy to accept any PR that makes it easier to use other front-end frameworks though.

**Comment by tomwwabo** [comment]
Today it would be pretty easy to add Vue and  later Angular Support to Vulcan

# Vue Support

If i would need to summarize Vue.js I would call it a "best of" of the react and angular worlds.


- https://github.com/akxcv/vuera
  - a seamless interop layer between react and vue
- https://quasar.dev/
  - the Ultimate Cross Platform Front-End Development Framework which is based on Vue.js
    supports ProgressiveWebApps, which already are pretty advanced
       - see https://whatwebcando.today/
- and with a little help of 
       - https://github.com/GeekyAnts/vue-native-core
       - https://www.microsoft.com/en-us/research/publication/static-typescript/
- the Javascript Codebase could reach compiled native performance, as it would have been coded directly in  C++. So no hybrid-app weirdness anymore like in react-native.
- especially if vulcan.js would also join forces with https://feathersjs.com/


# Hosting

Things that come in handy and help with hosting: 

- https://github.com/dokku/dokku
  - A self-hosted platform-as-a-service solution like https://www.heroku.com/
    - which is based on https://www.docker.com/
-  http://debops.org/ 
  - a pre-configured batteries-included virtualized datacenter, which is based on
    - debian
    - ansible
    - docker
    - vagrant
