### ISSUE TITLE
error when update legacy telescope

### ISSUE THREAD

**Issue by fortunto2** [TelescopeJS/Telescope#1361]
Hi
when use legacy branch
and meteor update
i have i18n error

W20160621-00:20:07.863(5)? (STDERR) /home/rustam/.meteor/packages/meteor-tool/.1.3.3_1.jszyqq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160621-00:20:07.865(5)? (STDERR)             				throw(ex);
W20160621-00:20:07.866(5)? (STDERR)             				      ^
W20160621-00:20:07.879(5)? (STDERR) Error: package-tap.i18n should be loaded before languages files (*.i18n.json)
W20160621-00:20:07.879(5)? (STDERR)     at meteorInstall.node_modules.meteor.telescope:email.home.rustam.lifefilm.telescope-zeiss.packages.telescope-email.package-tap.i18n (home/rustam/lifefilm/telescope-zeiss/packages/telescope-email/package-tap.i18n:1:1)
W20160621-00:20:07.879(5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160621-00:20:07.880(5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160621-00:20:07.880(5)? (STDERR)     at home/rustam/lifefilm/telescope-zeiss/packages/telescope-email/package-tap.i18n:1:1
W20160621-00:20:07.880(5)? (STDERR)     at home/rustam/lifefilm/telescope-zeiss/packages/telescope-email/package-tap.i18n:1:1
W20160621-00:20:07.880(5)? (STDERR)     at /home/rustam/lifefilm/telescope-zeiss/.meteor/local/build/programs/server/boot.js:297:10
W20160621-00:20:07.881(5)? (STDERR)     at Array.forEach (native)
W20160621-00:20:07.881(5)? (STDERR)     at Function._.each._.forEach (/home/rustam/.meteor/packages/meteor-tool/.1.3.3_1.jszyqq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160621-00:20:07.881(5)? (STDERR)     at /home/rustam/lifefilm/telescope-zeiss/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8                        
=> Your application is crashing. Waiting for file change.

**Comment by SachaG** [comment]
Sorry, that branch is not supported anymore. I can't really guarantee that it will be compatible with future updates of Meteor or its packages.
