### ISSUE TITLE
no custom labels for custom forms?

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#1363]
I've quickly added support for the label tag in `packages/nova-forms/lib/NovaForm.jsx`
by replacing this:
`const intlFieldName = this.context.intl.formatMessage({id:this.props.collection._name+"."+fieldName});
field.label = (typeof this.props.labelFunction === "function") ? this.props.labelFunction(intlFieldName) : intlFieldName;`
with this:
`if (!fieldSchema.label)
{
	const intlFieldName = this.context.intl.formatMessage({id: this.props.collection._name+"."+fieldName});
	field.label = (typeof this.props.labelFunction === "function") ? this.props.labelFunction(intlFieldName) : intlFieldName;
}
else
	field.label = fieldSchema.label;`

**Comment by SachaG** [comment]
I thought it would be confusing to have two ways to set labels (via `react-intl` and `label`). So I'm not sure we really need `label`?
