### ISSUE TITLE
delete categories not working

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#1367]
the delete button doesn't remove the category.

**Comment by SachaG** [comment]
Did you delete it from `settings.json` as well?

**Comment by plainspace** [comment]
+1 I'm having this issue. running the app. removed from `settings.json`. 

`Uncaught TypeError: Cannot read property 'call' of undefined - CategoriesEditForm.jsx:19`

**Comment by xavcz** [comment]
Fixed it in this commit https://github.com/TelescopeJS/Telescope/commit/bfd0b595f306cac9a8c693ec29caac748e430f9b on `devel`. Thanks for raising the issue!
