### ISSUE TITLE
cron.js goes into endless loop to schedule newsletters

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1377]
I just merged and started the app to see if it runs. Then this (see attached image) came up and I would like to understand if that is the normal behaviour? What happens is that scheduleNewsletter goes into an endless loop. I am using the fake api keys in Telescope settings. Does this maybe add this undocumented feature?
![screen shot 2016-06-29 at 17 25 24](https://cloud.githubusercontent.com/assets/4604432/16472102/d5c45210-3e1e-11e6-8960-b72f7cf84aae.png)

**Comment by SachaG** [comment]
Well if you're using fake API keys the API call is not going to work. Maybe that's why it's looping?

**Comment by MHerszak** [comment]
It just happened today. Not sure what changed.

**Comment by SachaG** [comment]
I've been working on the cron code, so I might've broken something. Is this the latest devel?

**Comment by MHerszak** [comment]
Yes latest "devel"

**Comment by plainspace** [comment]
+1 I'm seeing this but have pulled the devel branch...

**Comment by garrisons** [comment]
+1 I'm seeing this on the master branch as well...

**Comment by xavcz** [comment]
The problem was because of `newsletterTime` & `newsletterFrequency`, got fixed now 👍

**Comment by Discordius** [comment]
I seem to be running into this problem on the latest devel branch
