### ISSUE TITLE
`npm install` ends with "Killed"

### ISSUE THREAD

**Issue by kramer65** [TelescopeJS/Telescope#1378]
I'm trying to run Telescope on an Ubuntu 16.04 server. I follow the instructions in the readme:

```
curl https://install.meteor.com/ | sh
git clone git@github.com:TelescopeJS/Telescope.git
npm install
```

The first two commands run without an error, but the last command end in Killed:

```
$ npm install
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
extract:moment → gunzTarP ▐ ╢███████████████████████░░░░░░░░░░╟
Killed
```

Since it doesn't give any information I'm was unsure what could be wrong. Somebody on Stackoverflow gave the tip to first run `npm install cross-spawn` and then `meteor install` again. This fixed the npm install issue, but when I now try to run the app using meteor it ends with "Killed" again:

```
$ meteor
Killednloading meteor-tool@1.3.2_4...        |
```

Any idea what I could do to get it running? All tips are welcome!

**Comment by xavcz** [comment]
@kramer65 It may come from the fact you don't have enough memory on your server, [similar thread on DigitalOcean forum](https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what).

Adding swap may solve your problem: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-12-04

**Comment by kramer65** [comment]
Thanks, that solved it!
