### ISSUE TITLE
Why does Telescope take 800 MB to run?

### ISSUE THREAD

**Issue by kramer65** [TelescopeJS/Telescope#1382]
I've set up Telescope on a simple Ubuntu 16.04 server installation, which uses about 60 MB to run after ssh-ing into it. I then setup telescope and run it using the regular

    npm install
    meteor

This works fine (I see `App running at: http://localhost:3000/` on the terminal), but the server is using 865 MB of memory. Is this normal, or is there something wrong?

**Comment by SachaG** [comment]
That's probably normal. It'll use less memory if you run it in production mode.
