### ISSUE TITLE
New Post and Sign In buttons not doing anything

### ISSUE THREAD

**Issue by IlyaSemenov** [TelescopeJS/Telescope#1384]
On a clean checkout of the laster master (9cc12be2dae6a0bd1979e731e475738344cb7d94), New Post and Sign In buttons don't work (not doing anything when clicked).

Steps to reproduce:

```bash
rm -rf ~/.meteor*
curl https://install.meteor.com/ | sh
git clone https://github.com/TelescopeJS/Telescope.git
cd Telescope
npm install
meteor
```

* open <http://localhost:3000>
* click New Post - **nothing will happen** (instead, New Post dialog should appear)
* click Log In > Register - **nothing will happen** (instead, the registration form should appear)
* click Log In, fill in username/pass, click Sign In - **the cursor will change to "disabled" and nothing will happen**

This is reproducible on OS X 10.11.5 and Ubuntu 16.04 (server side), in Chrome, Safari and Firefox (client side).

Apart of lots of [react-bootstrap warnings](https://github.com/react-bootstrap/react-bootstrap/issues/1994), there's only one error in the browser javascript console:

`std_accounts-ui.js:23595 Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.`

**Comment by IlyaSemenov** [comment]
`package.json` requests `"react": "^15.0.1"` which (as of today) installs `react@15.2.0`

**Comment by SachaG** [comment]
Oh ok, try going back to 15.0.1 then.

**Comment by IlyaSemenov** [comment]
Yes, it did the trick, although it added a few more warnings to npm output:
```
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
npm WARN react-dom@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

I ended up replacing `^` with `~` for 3 of these packages in `package.json`, and I believe the same must be done in `master`.

**Comment by SachaG** [comment]
Could you submit a PR with your package.json? Or else just paste its contents here?

**Comment by machado2** [comment]
It is still happened today when I clicked the "deploy to Heroku" button here to check this project out.
