### ISSUE TITLE
Install train wreck -- react-router fails peer dependency

### ISSUE THREAD

**Issue by martinhbramwell** [TelescopeJS/Telescope#1386]
Hello.  Sorry to bug ya!

My first experience with Telescope : 

     cd projects/
     git clone https://github.com/TelescopeJS/Telescope.git
     cd Telescope/
     npm install

... which gets me ...

     npm WARN peerDependencies The peer dependency react-router@>=2.0.0 included from react-router-bootstrap will no
     npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
     npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
     npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

     npm ERR! Linux 4.4.0-28-generic
     npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
     npm ERR! node v4.4.7
     npm ERR! npm  v2.15.8
     npm ERR! code EPEERINVALID

     npm ERR! peerinvalid The package react-router@3.0.0-alpha.1 does not satisfy its siblings' peerDependencies requirements!
     npm ERR! peerinvalid Peer react-router-bootstrap@0.23.0 wants react-router@>=2.0.0

     npm ERR! Please include the following file with any support request:
     npm ERR!     /home/you/projects/Telescope/npm-debug.log

Do I have to change my version of NodeJS or something?

**Comment by xavcz** [comment]
Try to update NPM globally to v3: `npm install -g npm@3`
You will still get some warnings about dependency but the app would run!

**Comment by martinhbramwell** [comment]
Yeah,  That works,   Thank you very much.
