### ISSUE TITLE
warning: react-router@2.x needed

### ISSUE THREAD

**Issue by fortunto2** [TelescopeJS/Telescope#1388]
Hi
How to solve this problem?
I seem out of this error, the page is constantly overloaded
eg here http://new.life2film.com/f/v7ecEcHurdEsjrua5

`W20160706-18:52:55.666(5)? (STDERR) WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
W20160706-18:52:55.666(5)? (STDERR)  - react-router@3.0.0-alpha.1 installed, react-router@2.x needed
W20160706-18:52:55.666(5)? (STDERR)           
W20160706-18:52:55.667(5)? (STDERR) Read more about installing npm peer dependencies:
W20160706-18:52:55.667(5)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160706-18:52:55.667(5)? (STDERR)           
W20160706-18:52:58.206(5)? (STDERR) Warning: Material-UI: userAgent should be supplied in the muiTheme context
W20160706-18:52:58.206(5)? (STDERR)       for server-side rendering.

`

**Comment by SachaG** [comment]
I don't think you can solve it, but if you use NPM > 3 then that error becomes a warning and you can still run the app fine.
