### ISSUE TITLE
Can't register on deployed Telescope

### ISSUE THREAD

**Issue by kramer65** [TelescopeJS/Telescope#1390]
After some [initial install-trouble](https://github.com/TelescopeJS/Telescope/issues/1383), I now have my installation of Telescope live here: http://146.185.181.9/

I've got a problem registering though. It simply forbids me to click on the register button:

![your_gif_from_mp4togif_com_1467987671779](https://cloud.githubusercontent.com/assets/596581/16690403/0943cd7c-4528-11e6-8732-61a80a475af8.gif)

I tried in 4 different browsers, but with the same result.

Does anybody know what could be wrong here? All tips are welcome!

**Comment by xavcz** [comment]
It may be related to this issue: https://github.com/TelescopeJS/Telescope/issues/1384
