### ISSUE TITLE
npm install step fails react-router@3.0.0-alpha.1 does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by zorrobyte** [TelescopeJS/Telescope#1398]
npm WARN peerDependencies The peer dependency react-router@>=2.0.0 included from react-router-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-router@3.0.0-alpha.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-bootstrap@0.23.0 wants react-router@>=2.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rossfisher/Telescope/npm-debug.log

**Comment by SachaG** [comment]
You need to upgrade your npm. See multiple other issues about this.

**Comment by voidale** [comment]
I also had this problem with node v4, can't ignore it it will not run the app, had to downgrade to react-router@2.6.1 hopefully this doesn't break anything @SachaG?
