### ISSUE TITLE
Adding custom datepicker 

### ISSUE THREAD

**Issue by plainspace** [TelescopeJS/Telescope#1400]
This looks good: 

https://atmospherejs.com/netanelgilad/ui-bootstrap-datepicker
http://eonasdan.github.io/bootstrap-datetimepicker/

Any hints for adding something like this? I already added a custom field. 

```
Posts.addField(
  {
    fieldName: 'speechYear',
    fieldSchema: {
      type: String,
      optional: false,
      publish: true,
      insertableIf: Users.is.memberOrAdmin, // insertable by regular logged in users and admins
      editableIf: Users.is.ownerOrAdmin // editable by the post's owner or admins
    }
  }
)
```

**Comment by plainspace** [comment]
I just noticed that `/packages/nova-forms/lib/datetime.scss` is a thing. Is it advisable to uncomment this line or create a custom package component?

**Comment by SachaG** [comment]
Just give your custom field `control: "datetime"` and it should work out of the box with the latest `devel` :)

**Comment by plainspace** [comment]
thanks! I'm not using `devel`. should I be?

**Comment by SachaG** [comment]
If you want the datepicker, yes.
ᐧ

**Comment by plainspace** [comment]
Dumb question: is there any _other_ reason to be using the devel branch? Just confused about what is happening there and what the relationship is to master.

**Comment by SachaG** [comment]
Devel is the development branch. Once features are stable, they're ported back to the master branch.

**Comment by xavcz** [comment]
The datepicker is extendable and in `nova:forms` 👍 🎉
