### ISSUE TITLE
Cloning nova:base-styles

### ISSUE THREAD

**Issue by plainspace** [TelescopeJS/Telescope#1402]
@SachaG when you say, " you can also just clone the entire nova:base-components package and then make your modification directly there." what exactly do you mean? In other words, what are the instructions for doing so?

**Comment by SachaG** [comment]
I just meant copying-and-pasting the directory and using that as a base for your own package. 

I don't actually recommend that unless you know that you're going to modify every aspect of the front-end though. Even for Sidebar, which has a lot of custom components, I'm still using the extend approach over the copy-everything approach.
