### ISSUE TITLE
What's the location of accounts-password config

### ISSUE THREAD

**Issue by janat08** [TelescopeJS/Telescope#1408]
After having cloned telescope on top, old configuration remains (non-default) asking for email and 6 letters password instead of username and 8 letter pass.

**Comment by xavcz** [comment]
You can customize the behavior of `Accounts.ui` components here: https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-base-components/lib/users/UsersAccountForm.jsx#L16-L20 👍 

To learn more about how to customize, check the docs of `std:accounts-ui`: https://github.com/studiointeract/accounts-ui#accountsuiconfigoptions
