### ISSUE TITLE
Unknown props 'onToggle' warning

### ISSUE THREAD

**Issue by rifie** [TelescopeJS/Telescope#1409]
Hi, 

I already install the Telescope and found some warning. I can see it on my browser but i can't click the dropdown, i can't click" log in" and others that connected with dropdown. 

`App running at: http://localhost:3000/
I20160725-19:00:00.053(7) (percolatestudio_synced-cron.js:60) SyncedCron: Starting "checkScheduledPosts".
I20160725-19:00:00.061(7) (percolatestudio_synced-cron.js:60) SyncedCron: Finished "checkScheduledPosts".
W20160725-19:04:51.725(7)? (STDERR) Warning: Unknown props `onToggle`, `componentClass`, `block`, `justified`, `vertical`, `bsClass` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.731(7)? (STDERR)     in div (created by ButtonGroup)
W20160725-19:04:51.732(7)? (STDERR)     in ButtonGroup (created by Dropdown)
W20160725-19:04:51.732(7)? (STDERR)     in Dropdown (created by Uncontrolled(Dropdown))
W20160725-19:04:51.733(7)? (STDERR)     in Uncontrolled(Dropdown) (created by UsersAccountMenu)
W20160725-19:04:51.733(7)? (STDERR)     in UsersAccountMenu (created by Header)
W20160725-19:04:51.733(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.733(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.734(7)? (STDERR)     in header (created by Header)
W20160725-19:04:51.734(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.734(7)? (STDERR)     in Header (created by Layout)
W20160725-19:04:51.734(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.734(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.735(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:51.735(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:51.736(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:51.736(7)? (STDERR)     in RouterContext
W20160725-19:04:51.737(7)? (STDERR) Warning: Unknown props `useAnchor`, `bsRole`, `active`, `navItem`, `navDropdown`, `bsStyle` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.737(7)? (STDERR)     in button (created by Button)
W20160725-19:04:51.737(7)? (STDERR)     in Button (created by DropdownToggle)
W20160725-19:04:51.738(7)? (STDERR)     in DropdownToggle (created by Dropdown)
W20160725-19:04:51.738(7)? (STDERR)     in div (created by ButtonGroup)
W20160725-19:04:51.738(7)? (STDERR)     in ButtonGroup (created by Dropdown)
W20160725-19:04:51.739(7)? (STDERR)     in Dropdown (created by Uncontrolled(Dropdown))
W20160725-19:04:51.739(7)? (STDERR)     in Uncontrolled(Dropdown) (created by UsersAccountMenu)
W20160725-19:04:51.739(7)? (STDERR)     in UsersAccountMenu (created by Header)
W20160725-19:04:51.740(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.740(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.741(7)? (STDERR)     in header (created by Header)
W20160725-19:04:51.741(7)? (STDERR)     in div (created by Header)
W20160725-19:04:51.741(7)? (STDERR)     in Header (created by Layout)
W20160725-19:04:51.741(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.742(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.742(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:51.742(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:51.742(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:51.743(7)? (STDERR)     in RouterContext
W20160725-19:04:51.848(7)? (STDERR) Warning: Unknown props `layout`, `validationError`, `validationErrors`, `validatePristine`, `addonBefore`, `addonAfter`, `buttonBefore`, `buttonAfter` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.848(7)? (STDERR)     in input (created by Input)
W20160725-19:04:51.848(7)? (STDERR)     in Input (created by Newsletter)
W20160725-19:04:51.848(7)? (STDERR)     in form (created by Formsy)
W20160725-19:04:51.848(7)? (STDERR)     in Formsy (created by Newsletter)
W20160725-19:04:51.849(7)? (STDERR)     in div (created by Newsletter)
W20160725-19:04:51.849(7)? (STDERR)     in Newsletter (created by Layout)
W20160725-19:04:51.850(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.850(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.850(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.850(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:51.850(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:51.851(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:51.851(7)? (STDERR)     in RouterContext
W20160725-19:04:51.940(7)? (STDERR) Warning: There is an internal error in the React performance measurement code. We did not expect componentWillMount timer to stop while ctor timer is still in progress for another instance. Please report this as a bug in React.
W20160725-19:04:51.956(7)? (STDERR) Warning: Unknown props `dropup`, `pullRight`, `bsSize` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.956(7)? (STDERR)     in div (created by ButtonGroup)
W20160725-19:04:51.956(7)? (STDERR)     in ButtonGroup (created by Dropdown)
W20160725-19:04:51.957(7)? (STDERR)     in Dropdown (created by Uncontrolled(Dropdown))
W20160725-19:04:51.957(7)? (STDERR)     in Uncontrolled(Dropdown) (created by DropdownButton)
W20160725-19:04:51.957(7)? (STDERR)     in DropdownButton (created by CategoriesList)
W20160725-19:04:51.957(7)? (STDERR)     in div (created by CategoriesList)
W20160725-19:04:51.957(7)? (STDERR)     in CategoriesList (created by withRouter(CategoriesList))
W20160725-19:04:51.957(7)? (STDERR)     in withRouter(CategoriesList) (created by ListContainer)
W20160725-19:04:51.957(7)? (STDERR)     in ListContainer (created by PostsListHeader)
W20160725-19:04:51.957(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.958(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.958(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.958(7)? (STDERR)     in PostsListHeader (created by PostsList)
W20160725-19:04:51.958(7)? (STDERR)     in div (created by PostsList)
W20160725-19:04:51.958(7)? (STDERR)     in PostsList (created by ListContainer)
W20160725-19:04:51.958(7)? (STDERR)     in ListContainer (created by PostsHome)
W20160725-19:04:51.958(7)? (STDERR)     in PostsHome (created by RouterContext)
W20160725-19:04:51.959(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.959(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.959(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.959(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:51.959(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:51.959(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:51.959(7)? (STDERR)     in RouterContext
W20160725-19:04:51.960(7)? (STDERR) Warning: Unknown prop `noCaret` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.960(7)? (STDERR)     in button (created by Button)
W20160725-19:04:51.960(7)? (STDERR)     in Button (created by DropdownToggle)
W20160725-19:04:51.960(7)? (STDERR)     in DropdownToggle (created by Dropdown)
W20160725-19:04:51.960(7)? (STDERR)     in div (created by ButtonGroup)
W20160725-19:04:51.960(7)? (STDERR)     in ButtonGroup (created by Dropdown)
W20160725-19:04:51.961(7)? (STDERR)     in Dropdown (created by Uncontrolled(Dropdown))
W20160725-19:04:51.961(7)? (STDERR)     in Uncontrolled(Dropdown) (created by DropdownButton)
W20160725-19:04:51.961(7)? (STDERR)     in DropdownButton (created by CategoriesList)
W20160725-19:04:51.961(7)? (STDERR)     in div (created by CategoriesList)
W20160725-19:04:51.961(7)? (STDERR)     in CategoriesList (created by withRouter(CategoriesList))
W20160725-19:04:51.961(7)? (STDERR)     in withRouter(CategoriesList) (created by ListContainer)
W20160725-19:04:51.962(7)? (STDERR)     in ListContainer (created by PostsListHeader)
W20160725-19:04:51.962(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.962(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.962(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.962(7)? (STDERR)     in PostsListHeader (created by PostsList)
W20160725-19:04:51.963(7)? (STDERR)     in div (created by PostsList)
W20160725-19:04:51.963(7)? (STDERR)     in PostsList (created by ListContainer)
W20160725-19:04:51.963(7)? (STDERR)     in ListContainer (created by PostsHome)
W20160725-19:04:51.963(7)? (STDERR)     in PostsHome (created by RouterContext)
W20160725-19:04:51.964(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.964(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.964(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.966(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:51.967(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:51.968(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:51.968(7)? (STDERR)     in RouterContext
W20160725-19:04:51.984(7)? (STDERR) Warning: Unknown props `eventKey`, `divider`, `header`, `activeClassName` on <a> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160725-19:04:51.984(7)? (STDERR)     in a (created by SafeAnchor)
W20160725-19:04:51.985(7)? (STDERR)     in SafeAnchor (created by MenuItem)
W20160725-19:04:51.985(7)? (STDERR)     in li (created by MenuItem)
W20160725-19:04:51.985(7)? (STDERR)     in MenuItem (created by CategoriesList)
W20160725-19:04:51.986(7)? (STDERR)     in LinkContainer (created by CategoriesList)
W20160725-19:04:51.986(7)? (STDERR)     in div (created by CategoriesList)
W20160725-19:04:51.986(7)? (STDERR)     in ul (created by DropdownMenu)
W20160725-19:04:51.986(7)? (STDERR)     in DropdownMenu (created by Dropdown)
W20160725-19:04:51.987(7)? (STDERR)     in div (created by ButtonGroup)
W20160725-19:04:51.988(7)? (STDERR)     in ButtonGroup (created by Dropdown)
W20160725-19:04:51.988(7)? (STDERR)     in Dropdown (created by Uncontrolled(Dropdown))
W20160725-19:04:51.990(7)? (STDERR)     in Uncontrolled(Dropdown) (created by DropdownButton)
W20160725-19:04:51.990(7)? (STDERR)     in DropdownButton (created by CategoriesList)
W20160725-19:04:51.991(7)? (STDERR)     in div (created by CategoriesList)
W20160725-19:04:51.992(7)? (STDERR)     in CategoriesList (created by withRouter(CategoriesList))
W20160725-19:04:51.992(7)? (STDERR)     in withRouter(CategoriesList) (created by ListContainer)
W20160725-19:04:51.993(7)? (STDERR)     in ListContainer (created by PostsListHeader)
W20160725-19:04:51.993(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.994(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.995(7)? (STDERR)     in div (created by PostsListHeader)
W20160725-19:04:51.996(7)? (STDERR)     in PostsListHeader (created by PostsList)
W20160725-19:04:51.996(7)? (STDERR)     in div (created by PostsList)
W20160725-19:04:51.997(7)? (STDERR)     in PostsList (created by ListContainer)
W20160725-19:04:51.997(7)? (STDERR)     in ListContainer (created by PostsHome)
W20160725-19:04:51.998(7)? (STDERR)     in PostsHome (created by RouterContext)
W20160725-19:04:51.998(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.999(7)? (STDERR)     in div (created by Layout)
W20160725-19:04:51.999(7)? (STDERR)     in Layout (created by App)
W20160725-19:04:51.999(7)? (STDERR)     in IntlProvider (created by App)
W20160725-19:04:52.000(7)? (STDERR)     in App (created by Container(App))
W20160725-19:04:52.000(7)? (STDERR)     in Container(App) (created by RouterContext)
W20160725-19:04:52.001(7)? (STDERR)     in RouterContext
W20160725-19:04:53.070(7)? (STDERR) Warning: There is an internal error in the React performance measurement code. We did not expect ctor timer to stop while componentWillMount timer is still in progress for another instance. Please report this as a bug in React.
W20160725-19:04:53.070(7)? (STDERR) Mon Jul 25 2016 19:04:52 GMT+0700 (WIB) 'error while server-rendering' 'TypeError: Cannot read property \'_currentElement\' of null\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactCompositeComponent.js:734:52)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactCompositeComponent.js:715:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactCompositeComponent.js:634:12)\n    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactCompositeComponent.js:548:12)\n    at Object.ReactReconciler.performUpdateIfNecessary (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactReconciler.js:165:22)\n    at runBatchedUpdates (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactUpdates.js:151:21)\n    at ReactReconcileTransaction.Mixin.perform (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/Transaction.js:138:20)\n    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/Transaction.js:138:20)\n    at ReactUpdatesFlushTransaction._assign.perform (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactUpdates.js:90:38)\n    at Object.flushBatchedUpdates (/Users/rifie/Documents/marvo/tel/Telescope/node_modules/react/lib/ReactUpdates.js:173:19)'
`
Any thoughts is much appreciated. thank you

**Comment by SachaG** [comment]
I'm not sure why this is happening but it means you don't have the right version of React. See similar issues. Make sure you're using the version specified in `package.json`.

**Comment by selasi** [comment]
Hi Rifie, did the permission solve your problem? Am having same error and was wondering how you were able to solve it. Thanks

**Comment by xavcz** [comment]
If you clone / pull the latest version, this bug has been fixed 👍  happy hacking!
