### ISSUE TITLE
Not able to subscribe to emails

### ISSUE THREAD

**Issue by brianyang** [TelescopeJS/Telescope#1411]
### getting error when subscribing to emails

I've traced the error and don't know why the add method is failing.

settings.json contains 
- valid mailchimp API key
- list id
- valid mailgun smtp

```
  "defaultEmail": "hello@world.com",
  "mailUrl": "smtp://postmaster@sandbox123.mailgun.org/",
  "scoreUpdateInterval": "30",

  "embedlyKey":"123foo",
  "mailChimpAPIKey": "somekey123",
  "mailChimpListId": "listid123",

```

the meteor action `newsletter.addUser` calls `MailChimpList.add()` but this fails and throws an error: 

```
    try {
      return MailChimpList.add(user, false);
    } catch (error) {
      throw new Meteor.Error(500, error.message);
    }
```

How can I get a more meaningful error? All I'm getting is 'error is not defined [500]'

**Comment by SachaG** [comment]
You could add a `console.log(error)` in there?

**Comment by xavcz** [comment]
It's working well now 👍

**Comment by aayushkapoor206** [comment]
Hey @xavcz I'm facing the same issue... What was the solution?
