### ISSUE TITLE
user edit page loads wrong data.

### ISSUE THREAD

**Issue by guo** [TelescopeJS/Telescope#1414]
I came across a bug that http://xxx/{user-slug}/edit page loads wrong data. (using devel branch)
Repo step.
1. login as admin
2. edit userA (I changed a group.)
3. try to edit userB. You can see the initial page loads the correct data of userB. Then all the fields change to userA's.

**Comment by SachaG** [comment]
Hmm, I haven't been able to reproduce this. Could you maybe record a screencast showing the issue?

**Comment by guo** [comment]
Ok. I couldn't not repro either now. It seems it is gone after I rebooted server. It might be an issue in the past with cached data.  Closing for now. I will update if I repro'd it again. Thanks!
