### ISSUE TITLE
Setup Fail Ubuntu 14.04 LTS + Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by saydulk** [TelescopeJS/Telescope#1421]
## hello, i am not able to setup Telescope into Ubuntu. its waited me more then 8+ hours  after execute : $ meteor
                $ meteor all
                $ meteor update

and others all technique that exists into INTERNET by google :) @queso @ndarilek @ryw @byennen @yourcelf

**Comment by saydulk** [comment]
Last login: Fri Aug  5 18:28:59 2016 from 180.211.155.46
root@ubuntutrusty:~# cd Telescope/
root@ubuntutrusty:~/Telescope# meteor
[[[[[ ~/Telescope ]]]]]                       

=> Started proxy.                             
                                              
=> Meteor 1.3.4: npm@3.9.6, .babelrc support, improved import declarations,
DDP update batching, and more:
https://github.com/meteor/meteor/blob/master/History.md#v134

This release is being downloaded in the background. Update your app to
Meteor 1.3.4 by running 'meteor update'.
                                              
=> Started MongoDB.                           
   Downloading webapp@1.2.8...               |

**Comment by SachaG** [comment]
Please avoid abusing mentions.
