### ISSUE TITLE
Load more count is broken

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1429]
The load more total count always shows the count for all posts, even when you select a category or other filter.

**Comment by xavcz** [comment]
Tried it on my instance with posts with / without categories on different views (top & pending). After cleaning my cache (subs manager ^^), the total count showed me on each view/categories the amount expected.

How did you get to this?

**Comment by SachaG** [comment]
I noticed this while working on Crater. I'll pay attention next time to see when exactly it's happening.

**Comment by xavcz** [comment]
I faced this issue too!

It comes from the difference between what the client filter and what's published: terms.selector passed to the list container & selector used on the client are different. Classic meteor coder problem? :trollface: 

![](https://www.discovermeteor.com/images/blog/ownership-2.png)

Total count being calculated server-side, the app tells us that there are more post for us. 

Well if I may quote you: 
> So we’re hoping Meteor gets some new pagination features in the near future, and that this blog post becomes obsolete soon!

Apart from this silly acknowledgement of failure, I'll play with that next week while moving PostsLists to Apollo and use their native pagination feature: https://medium.com/apollo-stack/pagination-and-infinite-scrolling-in-apollo-client-59ff064aac61#.k18y5obkb

**Comment by SachaG** [comment]
Haha. I thought I would've made sure this didn't happen… But yeah I agree that Apollo would be better!

**Comment by xavcz** [comment]
> I'll play with that next week

*Two months later...*👯

I've made something functional, and will clean it up to use `fetchMore` ([apollo docs](http://dev.apollodata.com/react/pagination.html#fetch-more)) 👍

**Comment by xavcz** [comment]
The count is back 👍 Some pagination work is next step now 👍
