### ISSUE TITLE
Start meteor failed on Windows, meteor@1.4.1.1, nodejs@6.3.1

### ISSUE THREAD

**Issue by xgenvn** [TelescopeJS/Telescope#1434]
Hi,
I cloned the latest repo and `npm install` was normal exited.
When I try to do ```meteor``` to start the app, after pulling and installing several packages, I receive these error:

```
[[[[[ C:\dev\js\Telescope ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\ttt\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\ttt\AppData\Local\Temp\mt-2wwk91\os\packages\chuangbo_cookie.js.map'
    at Error (native)
```

I also try on my Linux box and it's working just fine. Is there anyone else on Windows experience the same issues?

**Comment by eddyfosman** [comment]
Run cmd as Admin, then:
npm install --global --production windows-build-tools
meteor update
meteor

Have a nice day!

**Comment by xgenvn** [comment]
@eddyfosman I've already installed the windows-build-tools, however it doesn't help.
I notice that the errors only happen after pulling percolatestudio:meteor-synced-cron package.

**Comment by valdiz777** [comment]
I am experiencing this issue as well

**Comment by sonicviz** [comment]
me three

**Comment by eddyfosman** [comment]
I also encountered synced-cron problem, but I don't remember how I cleared it. You should create a new project then deploy from the start.

**Comment by sonicviz** [comment]
I just did that, after downloading the latest release, and it seems to work now.

Where's the admin settings on the menu, or isn't there one? 
I'm logged in as admin but don't see any menu. I thought there used to be one?

**Comment by xavcz** [comment]
Nice to hear that on the latest release it's solved 👍 

@sonicviz there isn't any admin panel anymore, you can customize Nova with `settings.json`.

**Comment by nirajpd** [comment]
I am having the same issue , Windows 10 and meteor is up to date. Tried running percolatestudio:meteor-synced-cron  , same error. Tried running meteorhacks:unblock , similar error. I hope I d on't have to build a Linux box just for this :-(
