### ISSUE TITLE
Telescope and Slingshot authorization

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1435]
I have a question regarding Slingshot upload and server-side validation of Users.canEdit.

```
Slingshot.createDirective("imageUpload", Slingshot.S3Storage, {
  bucket: "bucketName",

  maxSize: 10 * 1024 * 1024,

  allowedFileTypes: ["image/png", "image/jpeg", "image/gif"],

  authorize: (file, metaContext) => {
    //Deny uploads if user can't edit the document.
    const {currentUser,document} = metaContext;
    
    return Users.canEdit(currentUser,document); // document.
  },

  key: (file,metaContext) => {
    //Store file into a directory.
    const {document} = metaContext;

    return document.prefix + "" +document.fileName;
  },
});
```
The error I am getting in the console is as follows: 
`Exception while invoking method 'slingshot/uploadRequest' TypeError: document.getCollectionName is not a function at [object Object].Users.canEdit (packages/nova:users/lib/groups.js:155:35)`

The package is loaded and `document.getCollectionName` works perfectly on the client side but it doesn't seem to work server side. Is there something I am not seeing or is a "document" treated differently on the server? Not sure if this is a real issue?

**Comment by SachaG** [comment]
Maybe `document` is not an instance of a User? You can pass it through `Users._transform(document)` first (I think?) to make it one.

**Comment by xavcz** [comment]
@MHerszak If you want to upload an image, I have built a package to upload images to Cloudinary from a `NovaForm` (compatible with `nova:cloudinary` which uploads embedly thumbnails to cloudinary).

The goal being to have as fewer dependencies on external meteor / npm packages as possible, it's a simple package and independent from slingshot. However, if you are into uploading to S3 and stuff like this, I guess we could find a way to do it!

Fyi, here is the repo: https://github.com/xavcz/nova-forms-upload/

**Comment by MHerszak** [comment]
@xavcz thanks but I don't want to use to many services since I am already using AWS. Maybe in the future?

**Comment by MHerszak** [comment]
@SachaG it worked. Could you please send me a link to the implementation since I can't find it in the code space. There are to many dependencies.

**Comment by SachaG** [comment]
Sorry, the implementation of what?

**Comment by MHerszak** [comment]
`Users._transform` where can I find the implementation of it?

**Comment by SachaG** [comment]
Somewhere in the Meteor source code… Not sure where though :(

**Comment by MHerszak** [comment]
Okay, thanks!
