### ISSUE TITLE
'TypeError: Cannot read property \'idStringify\' of undefined\n

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1436]
I am getting a console error:

` Thu Sep 01 2016 11:50:22 GMT-0600 (MDT) 'error while server-rendering' 'TypeError: Cannot read property \'idStringify\' of undefined\n    at PublishContext.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1)\n    at packages/meteorhacks_fast-render/lib/server/publish_context.js:34:1\n    at Array.forEach (native)\n    at PublishContext._addCursor (packages/meteorhacks_fast-render/lib/server/publish_context.js:33:1)\n    at packages/meteorhacks_fast-render/lib/server/context.js:85:1\n    at Array.forEach (native)\n    at Context.processPublication (packages/meteorhacks_fast-render/lib/server/context.js:84:1)\n    at Context.subscribe (packages/meteorhacks_fast-render/lib/server/context.js:41:1)\n    at SsrContext.addSubscription (packages/reactrouter:react-router-ssr/lib/ssr_context.js:30:18)\n    at packages/reactrouter:react-router-ssr/lib/ssr_data.js:13:20'`

When you refresh the app the first thing you want to see is usually the `Loading..` component but I am getting an `undefined` and than `Loading..` instead. Has anyone ever had this issue with Telescope? Any ideas of what might be causing this?

**Comment by SachaG** [comment]
I think it's an issue with the reactive-publish package. Maybe ask/search there?

**Comment by MHerszak** [comment]
Okay.

**Comment by MHerszak** [comment]
So for some reason JSON wasn't available. I updated to reactrouter:react-router-ssr@3.1.5 from 3.1.4 and this upgraded meteorhacks:fast-render from 2.12.0 to 2.16.0. It works so much faster now. My must have worked with an older version.
