### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by selasi** [TelescopeJS/Telescope#1442]
I had an old telescope app which was running well until now when it decided to break. After trying everything possible and couldn't resolve it, I cloned a new repo but got this error. Is there something am not doing right? Thanks

[[[[[ ~/Work/Telescope ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
nova:rss: updating npm dependencies -- rss... 
=> Errors prevented startup:                  
   
   While loading package fourseven:scss@3.9.0:
   error: Command failed:
   /Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild
   --no-bin-links --update-binary
   { [Error: EACCES: permission denied, mkdir
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/vendor/darwin-x64-46']
   errno: -13,
   code: 'EACCES',
   syscall: 'mkdir',
   path:
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/vendor/darwin-x64-46'
   }
   gyp info it worked if it ends with ok
   gyp verb cli [ '/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
   gyp verb cli
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.4.0
   gyp info using node@4.5.0 | darwin | x64
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp verb check python checking for Python executable "python2" in the PATH
   gyp verb `which` failed Error: not found: python2
   gyp verb `which` failed     at getNotFoundError
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:14:12)
   gyp verb `which` failed     at F
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:69:19)
   gyp verb `which` failed     at E
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:81:29)
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:90:16
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:44:5
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/access.js:8:5
   gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
   gyp verb check python checking for Python executable "python" in the PATH
   gyp verb `which` succeeded python /usr/bin/python
   gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
   gyp verb get node dir no --target version specified, falling back to host node version: 4.5.0
   gyp verb command install [ '4.5.0' ]
   gyp verb install input version string "4.5.0"
   gyp verb install installing version: 4.5.0
   gyp verb install --ensure was passed, so won't reinstall if already installed
   gyp verb install version is already installed, need to check "installVersion"
   gyp verb got "installVersion" 9
   gyp verb needs "installVersion" 9
   gyp verb install version is good
   gyp verb get node dir target node version installed: 4.5.0
   gyp verb build dir attempting to create "build" dir:
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/build
   gyp ERR! configure error 
   gyp ERR! stack Error: EACCES: permission denied, mkdir
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/build'
   gyp ERR! stack     at Error (native)
   gyp ERR! System Darwin 15.6.0
   gyp ERR! command "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
   gyp ERR! cwd
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass
   gyp ERR! node -v v4.5.0
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   Build failed
   
   npm ERR! Darwin 15.6.0
   npm ERR! argv "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/npm-debug.log
   { [Error: EACCES: permission denied, mkdir
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/vendor/darwin-x64-46']
   errno: -13,
   code: 'EACCES',
   syscall: 'mkdir',
   path:
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/vendor/darwin-x64-46'
   }
   gyp info it worked if it ends with ok
   gyp verb cli [ '/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
   gyp verb cli
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.4.0
   gyp info using node@4.5.0 | darwin | x64
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp verb check python checking for Python executable "python2" in the PATH
   gyp verb `which` failed Error: not found: python2
   gyp verb `which` failed     at getNotFoundError
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:14:12)
   gyp verb `which` failed     at F
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:69:19)
   gyp verb `which` failed     at E
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:81:29)
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:90:16
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:44:5
   gyp verb `which` failed     at
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/access.js:8:5
   gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
   gyp verb check python checking for Python executable "python" in the PATH
   gyp verb `which` succeeded python /usr/bin/python
   gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
   gyp verb get node dir no --target version specified, falling back to host node version: 4.5.0
   gyp verb command install [ '4.5.0' ]
   gyp verb install input version string "4.5.0"
   gyp verb install installing version: 4.5.0
   gyp verb install --ensure was passed, so won't reinstall if already installed
   gyp verb install version is already installed, need to check "installVersion"
   gyp verb got "installVersion" 9
   gyp verb needs "installVersion" 9
   gyp verb install version is good
   gyp verb get node dir target node version installed: 4.5.0
   gyp verb build dir attempting to create "build" dir:
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/build
   gyp ERR! configure error 
   gyp ERR! stack Error: EACCES: permission denied, mkdir
   '/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass/build'
   gyp ERR! stack     at Error (native)
   gyp ERR! System Darwin 15.6.0
   gyp ERR! command "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
   gyp ERR! cwd
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/node_modules/node-sass
   gyp ERR! node -v v4.5.0
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   Build failed
   
   npm ERR! Darwin 15.6.0
   npm ERR! argv "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-yjmp7/npm-debug.log
   
   
   While loading package meteorhacks:kadira-binary-deps@1.5.0:
   error: Command failed:
   /Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild
   --no-bin-links --update-binary
   node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v46-darwin-x64.tar.gz 
   node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
   gyp ERR! clean error 
   gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
   gyp ERR! stack     at Error (native)
   gyp ERR! System Darwin 15.6.0
   gyp ERR! command "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "clean"
   gyp ERR! cwd
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/node_modules/v8-profiler
   gyp ERR! node -v v4.5.0
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   node-pre-gyp ERR! build error 
   node-pre-gyp ERR! stack Error: Failed to execute
   '/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node
   /Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
   clean' (1)
   node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
   (/Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
   node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
   node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
   node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
   node-pre-gyp ERR! System Darwin 15.6.0
   node-pre-gyp ERR! command
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.bin/node-pre-gyp"
   "install" "--fallback-to-build"
   node-pre-gyp ERR! cwd
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/node_modules/v8-profiler
   node-pre-gyp ERR! node -v v4.5.0
   node-pre-gyp ERR! node-pre-gyp -v v0.6.29
   node-pre-gyp ERR! not ok 
   
   npm ERR! Darwin 15.6.0
   npm ERR! argv "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the v8-profiler@5.6.5 install script 'node-pre-gyp install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the v8-profiler package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs v8-profiler
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls v8-profiler
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/npm-debug.log
   node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v46-darwin-x64.tar.gz 
   node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
   gyp ERR! clean error 
   gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
   gyp ERR! stack     at Error (native)
   gyp ERR! System Darwin 15.6.0
   gyp ERR! command "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "clean"
   gyp ERR! cwd
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/node_modules/v8-profiler
   gyp ERR! node -v v4.5.0
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   node-pre-gyp ERR! build error 
   node-pre-gyp ERR! stack Error: Failed to execute
   '/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node
   /Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
   clean' (1)
   node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
   (/Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
   node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
   node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
   node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
   node-pre-gyp ERR! System Darwin 15.6.0
   node-pre-gyp ERR! command
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.bin/node-pre-gyp"
   "install" "--fallback-to-build"
   node-pre-gyp ERR! cwd
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/node_modules/v8-profiler
   node-pre-gyp ERR! node -v v4.5.0
   node-pre-gyp ERR! node-pre-gyp -v v0.6.29
   node-pre-gyp ERR! not ok 
   
   npm ERR! Darwin 15.6.0
   npm ERR! argv "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the v8-profiler@5.6.5 install script 'node-pre-gyp install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the v8-profiler package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs v8-profiler
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls v8-profiler
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/iSela/.meteor/packages/meteorhacks_kadira-binary-deps/.1.5.0.34kqrv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-11z4an6/npm-debug.log
   
   
   While building package nova:base-styles:
   error: No plugin known to handle file 'lib/stylesheets/main.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/stylesheets/main.scss', 'client').
   
   While loading plugin `compileScssBatch` from package `fourseven:scss`:

   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11:
   Missing binding
   /Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/vendor/darwin-x64-46/binding.node
   Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 4.x
   
   Found bindings for the following environments:
   - Windows 32-bit with Node.js 4.x
   
   This usually happens because your environment has changed since running `npm install`.
   Run `npm rebuild node-sass` to build the binding for your current environment.
   at Object.<anonymous>
   (/Users/iSela/.meteor/packages/fourseven_scss/.3.9.0.h1hldb++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load
   (/Users/iSela/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/node/runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous> (/tools/isobuild/bundler.js:1569:22)
   at Object.require (/tools/isobuild/bundler.js:1546:11)
   at meteorInstall.node_modules.meteor.compileScssBatch.plugin.compile-scss.js (packages/compileScssBatch/plugin/compile-scss.js:3:18)
   at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
   at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
   at <runJavaScript-42>:339:1
   at <runJavaScript-42>:345:3
   
   
   While building package nova:debug:
   error: No plugin known to handle file 'lib/stylesheets/debug.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/stylesheets/debug.scss', 'client').
   
   While building package nova:embedly:
   error: No plugin known to handle file 'lib/stylesheets/embedly.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/stylesheets/embedly.scss', 'client').
   
   While building package nova:forms:
   error: No plugin known to handle file 'lib/datetime.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/datetime.scss', 'client').
   
=> Your application has errors. Waiting for file change.

**Comment by xavcz** [comment]
Hey @selasi! Your problem seems to be related with inconsistency between `fourseven:scss` versions (3.8.0_1 especially).

I have harmonized versions on `devel` branch. Could you clone a fresh repo, checkout on devel branch (`git checkout devel`), `npm install` and then `meteor`, and tell me if it works? :)
