### ISSUE TITLE
Looping on windows 10, extracting 

### ISSUE THREAD

**Issue by sonicviz** [TelescopeJS/Telescope#1448]
Please see the console log below.

It's stuck looping on " Extracting std:accounts-ui@1.2.6...       \ "

I thought I'd resolved this previously as explained on https://forums.meteor.com/t/solution-to-meteor-hanging-extracting-package-on-windows/28873/5 but that solution is not working.

Can you tell me where std:accounts-ui@1.2.6 is being referenced from, as it's not in the main package file, it's a lower level dependency,

==============================================================
Console log:
----------------------------------------------------------------------------------------------------------
G:\Meteor Projects\Project X\Telescope-master>meteor update
This project is already at Meteor 1.4.1.1, the latest release.
   Extracting std:accounts-ui@1.2.6...       \

**Comment by uapasha** [comment]
same here

**Comment by uapasha** [comment]
@sonicviz dunno why but meteor reset and meteor --verbose helped

**Comment by sonicviz** [comment]
@uapasha Thanks, I forgot I tried that once as well and it worked. Will try it. ty.

**Comment by xavcz** [comment]
Cool! We'll spread the word for windows user to use `meteor reset`! 👍

**Comment by rishavs** [comment]
I had the same issue.
For me reset didnt do anything.

I instead installed 7 zip on my system and deleted the 7zip.exe packed with the meteor at
`\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin\`

after this the meteor command worked.
