### ISSUE TITLE
fixed contextTypes on packages/nova-forms/lib/DateTime.jsx

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#1449]
updateCurrentValue is wrongly defined as a propType, when it should be a
contextType. It has been defined as a childContextType in NovaForm.jsx

fixed below:

    DateTime.propTypes = {
      datatype: React.PropTypes.any,
      group: React.PropTypes.any,
      label: React.PropTypes.string,
      name: React.PropTypes.string,
      value: React.PropTypes.any,
    };

    DateTime.contextTypes = {
      addToAutofilledValues: React.PropTypes.func,
      updateCurrentValue: React.PropTypes.func
    };

**Comment by xavcz** [comment]
Nice catch! Fixed 👍

**Comment by sweetppro** [comment]
Cool,
It was too much effort to set up a repo for such a small fix.
