### ISSUE TITLE
Sending email notifications.

### ISSUE THREAD

**Issue by singhalarchit** [TelescopeJS/Telescope#1450]
Hello,
I am new to telescope. I want to send email notifications from my app hosted on heroku. I have attached Mailgun free email add-on to my app. I do not know what to do now? 

What changes do I have to make to the app using Admin Settings on the UI?
Do I need to modify any code?

I have a limit of 300 emails/day using Mailgun. I just need my app to send some email for now. If it works I can purchase some subscription to send more emails.

Please help.

**Comment by xavcz** [comment]
Hey @singhalarchit, you are using the Legacy version of Telescope with like you said have an Admin Settings to allow what you need. It works out of the box. Just fill your credentials in the inputs.

However, you should be aware that this version is not maintained anymore.
