### ISSUE TITLE
Getting notifications on the site

### ISSUE THREAD

**Issue by singhalarchit** [TelescopeJS/Telescope#1451]
Hello,
I am new to telescope and I need to add functionality to have notifications for each user on top right of their login page. Notifications can be related to new post/new reply, etc.

How can I achieve it?

Please help.

**Comment by meteorplus** [comment]
check this PR https://github.com/TelescopeJS/Telescope/pull/1453

**Comment by singhalarchit** [comment]
My application is based on telescope-<> rather than nova-<>

**Comment by xavcz** [comment]
@singhalarchit referring your duplicated issue #1450, you have it out of the box on Legacy (application based on telescope-<>)

If you want to have this kind of feature on Nova (nova-<>), I'm pretty sure @meteorplus will build a package for that 🎯
