### ISSUE TITLE
Tell folks how to deploy Nova with latest Meteor Up (kadirahq/meteor-up) 

### ISSUE THREAD

**Issue by xavcz** [TelescopeJS/Telescope#1455]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), *highly inspired* by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍

### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a cool trick or two in the process on how to hack & customize Telescope Nova! 🔭

### 🤔 What you will need to know

Meteor Up (MUP) deployment with Meteor 1.4, Markdown syntax.

[Meteor Up](https://github.com/kadirahq/meteor-up/) is a command line tool that allows you to deploy any Meteor app to your own server. It currently supports Ubuntu and is powered by Docker.

[Markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/) is what makes issues, PRs and docs well formatted on GitHub.

### 🎯 The Goal

A lot of people have hardtime when deploying Telescope app by now, and generally speaking Meteor 1.4 apps with MUP. Which version of MUP shall I use? Arunoda/MUP, MupX, KadiraHQ/MUP? Wich docker image?

Let's clarify all that! 🙌 

### 📋 Step by Step
**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---

- [x] Claim this issue (@asmita005)
- [x] Fork the repo and [setup repository locally](https://github.com/TelescopeJS/Telescope#getting-started).
- [x] Be sure to have the latest `kadirahq/meteor-up` installed (MUP 1.0.3 atm).
- [ ] Create a `.deploy` folder.
- [ ] Init Meteor Up with `mup init`. 
- [ ] Replace the content of the newly created `settings.json` with the content of `sample_settings.json`.
- [ ] Modify `mup.js` on the `ROOT_URL` field (absolute url) and add a `docker` field with `abernix/meteord:base` docker image. We recommend to take inspiration (or copy/paste) on this [gist](https://gist.github.com/xavcz/6ddc2bb6f67fe0936c8328ab3314641d).
- [x] Update the `README.md` on the [Deployment section](https://github.com/TelescopeJS/Telescope#deployment) with instructions & comments on how to deploy (have a server (digital ocean droplet recommended, `cd .deploy`, `mup setup`, modify `settings.json` with your own, `mup deploy --settings settings.json`).
- [x] Open a PR to `devel` branch, mentioning this issue.
- [x] Someone else: review & merge! 🎉

Ping us in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by asmita005** [comment]
Hello @xavcz ! i would like to take up this starter issue. 
Thanks

**Comment by xavcz** [comment]
Awesome @asmita005! Go for it! 🚀  And again, do not hesitate to come by the [Telescope Slack room](http://slack.telescopeapp.org) if you have any trouble on this one!
