### ISSUE TITLE
Keep scrolling position when moving between different routes

### ISSUE THREAD

**Issue by xavcz** [TelescopeJS/Telescope#1460]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), _highly inspired_ by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍
### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a cool trick or two in the process on how to hack & customize Telescope Nova! 🔭
### 🤔 What you will need to know

Meteor, React, React-Router v3 API ([repo/v3](https://github.com/ReactTraining/react-router/tree/v3))
### 🎯 The Goal

After scrolling 30 posts and losing position when you hit the "back button", this can be frustrating. 

We could add some scroll-hooks on some routes to preserve the scroll position, especially on the posts list and posts daily routes. 

You should find API / prop which manages that and you would give it to relevant `Route` objects. 

I think that would be relevant only if `SubsManager` is on, meaning that the data are cached and that when you come back to a previous route, posts are still displayed.
### 📋 Step by Step

**Working on your first Pull Request?** You can learn how from this _free_ series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---
- [x] Claim this issue (@vitaliemaldur)
- [x] Fork the repo, [setup repository locally](https://github.com/TelescopeJS/Telescope#getting-started) and checkout on `devel` branch.
- [ ] Find the API for scrolling position with `react-router@3`
- [ ] Add the prop to the relevant routes where scrolling position should be preserved
- [ ] Tests behavior moving to differents routes (categories, user profile, daily, best, pending, idk..) that everything works fine
- [ ] Open a PR to `devel` branch, mentioning this issue.
- [ ] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by vitaliemaldur** [comment]
Hi,

How can I run Nova with `SubsManager` in order to cache the data? Thx

**Comment by xavcz** [comment]
Hey @vitaliemaldur! You can use the `cacheSubscription` props on `List/DocumentContainer` https://github.com/meteor-utilities/react-list-container#cachesubscription-bool

Do you wish to work on this?

**Comment by vitaliemaldur** [comment]
I will try.

**Comment by xavcz** [comment]
Awesome! 🎉

**Comment by xavcz** [comment]
We now use `useScroll()` from `react-router-scroll` 👌
