### ISSUE TITLE
Can't use ES6 features in custom package

### ISSUE THREAD

**Issue by octohedron** [TelescopeJS/Telescope#1467]
I'm trying to code my own Meteor package based on the custom-package located in the `/packages` folder.

It throws `SyntaxError` at the first `import` statement in one of my packages files, if I comment the `import` it throws at the next one or in a different file that also has ES6 features.

```
    (STDERR) in the root directory of your application.
    (STDERR) /Users/octohedron/Documents/App/.meteor/local/build/programs/server/packages/my_package.js:1924
    (STDERR) import { MyClass } from 'maths/dist/edit';
    (STDERR) ^^^^^^    
    (STDERR)           
    (STDERR) SyntaxError: Unexpected reserved word
    (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
    (STDERR)     at /Users/octohedron/Documents/App/.meteor/local/build/programs/server/boot.js:287:30
    (STDERR)     at Array.forEach (native)
    (STDERR)     at Function._.each._.forEach (/Users/octohedron/.meteor/packages/meteor-tool/.1.4.1_1.ge5qu0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    (STDERR)     at /Users/octohedron/Documents/App/.meteor/local/build/programs/server/boot.js:128:5
```

It works in `/Telescope/packages/my-package/lib/` but not in `/Telescope/packages/my-package/lib/client/`.

Could it be that all folders named /client/ in meteor are treated differently?

**Fix if anyone has the same issue:** `/client/` folders don't support ES6.

Do I have to manually transpile all my package's code to vanilla jS to be able to use it in my custom meteor package?

**Comment by xavcz** [comment]
You could use Meteor's `api.mainModule` in `package.js` to use es6 syntax and create an entrypoint client-side. Have a look at other packages in Telescope Nova to see how it's written 👍
