### ISSUE TITLE
Shortcut to submit a form (new NovaForm event handler)

### ISSUE THREAD

**Issue by xavcz** [TelescopeJS/Telescope#1471]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), *highly inspired* by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍

### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a neat trick or two in the process on how to hack & customize Telescope Nova! 🔭

### 🤔 What you will need to know

Meteor, React.

### 🎯 The Goal

What about being able to submit a post or a comment after typing with a standard shortcut: Ctrl + Enter (or Cmd + Enter on Mac) ? 👊

Forms in Nova work thanks to `NovaForm` (in `nova:forms` package), which uses [Formsy](https://github.com/christianalfoni/formsy-react/) under the hood.

To enable this feature (proposed in #850), we would need an event handler on `NovaForm` component that calls its method `submitForm` if the right keys are pressed. 

No changes are needed on `submitForm`: it uses directly the data of Formsy, that can be retrieved with `this.refs.form.getModel()` ([see Formsy API docs](https://github.com/christianalfoni/formsy-react/blob/master/API.md#getmodel)).

Useful link : [React Events](https://facebook.github.io/react/docs/events.html)

### 📋 Step by Step
**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---

- [x] Claim this issue (@aszx87410)
- [x] Fork the repo, [setup repository locally](https://github.com/TelescopeJS/Telescope#getting-started) & checkout on `devel` branch.
- [x] Bind a new event handler to `NovaForm` that listen for keys pressed.
- [x] Make it call `submitForm` with the form's data.
- [x] Check if it works well.
- [x] Open a PR to `devel` branch, mentioning this issue.
- [x] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by aszx87410** [comment]
Hi, I want to work on this issue, can I?

**Comment by aszx87410** [comment]
Already finished. Please let me know if there is any problem, thanks.

**Comment by xavcz** [comment]
Awesome, thanks a lot! Merged 🔘👊
