### ISSUE TITLE
Legacy themes don't work with Nova

### ISSUE THREAD

**Issue by prayagmukhi** [TelescopeJS/Telescope#1473]
I have recently discovered telescope and found out about its themes.

http://www.telescopeapp.org/themes

I tried installing this theme,

https://atmospherejs.com/montecruiseto/telescope-theme-sm-lulin

using
`$ meteor add montecruiseto:telescope-theme-sm-lulin`

but it doesn't seem to work and neither does any other theme.
What am i missing here?

**Comment by xavcz** [comment]
Hey @prayagmukhi! 

These themes were built for Telescope Legacy, a version of Telescope running with Blaze, the native Meteor's engine view. By the way, most of these themes got broken on latest version of Legacy :/

Now, we are running with Nova, which is React-based, so these themes won't work with it.

Hopefully, we'll soon see new themes 🎉  #1464
