### ISSUE TITLE
latest devel doesn't update logged in status

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#1476]
when I log in to the latest level, the login button still shows as a login button, rather than showing the user name as it should.

**Comment by sweetppro** [comment]
my bad, it seems to be an error with my custom theme.
:(

**Comment by xavcz** [comment]
Did it come from the `currentUser` passed via the context now in `Header`? I've changed that lately, it's no more passed via props.

**Comment by sweetppro** [comment]
I needed to change this:
`const MAT_Header = ({currentUser}) =>`
to this:
`const MAT_Header = (props, {currentUser}) =>`

and ad this:
`MAT_Header.contextTypes = {
  currentUser: React.PropTypes.object,
};`
