### ISSUE TITLE
Docker Hub images are outdated

### ISSUE THREAD

**Issue by ze-phyr-us** [TelescopeJS/Telescope#1477]
The `Dockerfile` previously added in https://github.com/TelescopeJS/Telescope/pull/962 was removed some time later, so Docker Hub builds have been failing for some six months. See https://hub.docker.com/r/telescopeapp/telescope/builds/

**Comment by xavcz** [comment]
Hey @ze-phyr-us! Thanks for the heads up. We've never really used it, do you need it? We can re-upload the `Dockerfile` again if requested

**Comment by ze-phyr-us** [comment]
Well, Docker is a very convenient method of deploying anything, including Telescope :)

It may help more people try out Telescope without having to touch their system. I certainly did, before deciding to deploy it in production (again using Docker).

See for instance this guide http://spartatek.se/meteor_blog/docker/2016/01/12/running-telescope.html
Getting Telescope up and running is as simple as

```
docker run --name mongo -d mongo --smallfiles
docker run --name telescope --link mongo:db -e ROOT_URL=http://localhost -e MONGO_URL=mongodb://db -p 3000:80 -d telescopeapp/telescope:devel
```

**Comment by xavcz** [comment]
Ok, nice! We usually recommend deploying Telescope with [Meteor Up](https://github.com/kadirahq/meteor-up), which uses Docker under the hood. I didn't know you could do like this 👍 

File added! 🐳

**Comment by ze-phyr-us** [comment]
Thanks!
