### ISSUE TITLE
Blank login popup

### ISSUE THREAD

**Issue by elnurvl** [TelescopeJS/Telescope#1478]
Master branch has a bug causing appear blank dropdown menu when clicking on Login button.

**Comment by jelenajjo** [comment]
@elnurvl  Just wanted to ask about that too. :+1:

**Comment by xavcz** [comment]
Yep it's due to a problem with `react-bootstrap`, see #1463.

Anyway, I'm about to merge `devel` in `master`, that won't a problem anymore 🗡 

Thanks for reporting!
