### ISSUE TITLE
Apollo Containers

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1483]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), *highly inspired* by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍

### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a cool trick or two in the process on how to hack & customize Telescope Nova! 🔭

### 🤔 What you will need to know

Meteor, React, [Apollo](http://apollostack.com), and GraphQL. 
 
### 🎯 The Goal

Replace the various **containers** used in Telescope (which all use the [react-list-container](https://github.com/meteor-utilities/react-list-container) package) with **Apollo/GraphQL** equivalents. 

Note: a container is a special component that doesn't display any HTML, but instead takes on the job of loading data from the server, before passing that data on to other components (thus preserving separation of concerns between containers and presentational components). 

There's two types of containers in the current codebase, `ListContainer` (for multiple documents) and `DocumentContainer` (for single documents). 

Additionally, a container can either subscribe to (i.e. load) data from the server and then pass it on, or just fetch data already stored in memory and then pass it on. With Apollo, the second use case would probably just be a Redux operation and not involve GraphQL. 

### 📋 Step by Step
**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---

- [x] Claim this issue.
- [x] `PostsSingle` posts container
- [x] `PostsHome` posts container
- [x] `PostsDay` posts container
- [x] `PostsListHeader` categories container (note: no subscription)
- [x] `UsersProfile` posts container
- [x] `PostsEditForm` post container
- [x] `UsersAccounts` user container
- [x] `UserSingle` user container
- [ ] Test if it works.

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

I'll leave @xavcz complete this issue with more details :)

**Comment by xavcz** [comment]
With Meteor package `apollo@0.1.x`, we may be able to get rid of the `AppComposer` container thanks to the current user being given by Apollo Server.

We'll be then able to also use it in our resolvers with the `context` (3rd parameter)

**Comment by kytwb** [comment]
Can I claim this issue and work on it this week-end?

**Comment by SachaG** [comment]
@kytwb sure, that'd be great! Just indicate in this thread which container you're working on so we don't duplicate the work.

**Comment by xavcz** [comment]
@kytwb awesome! 🎉 please join the Slack room: http://slack.telescopeapp.org

We are actively discussing there about Apollo, and especially this issue 🤔🚀

**Comment by kytwb** [comment]
@SachaG @xavcz coming back to you and on Slack this week-end to get up to speed and start working on it 😄

**Comment by xavcz** [comment]
Done 👌
