### ISSUE TITLE
Apollo Mutations

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1485]
### 🤔 What you will need to know

Meteor, React, [Apollo](http://apollostack.com), and GraphQL. 
### 🎯 The Goal

For each method, we need to do three things:
1. Trigger the appropriate `refetchQuery` in the method's callback to update the relevant data.
2. Replace the Meteor method call with a GraphQL query call.
3. Optionally, take care of optimistic updates (a.k.a. latency compensation) when needed.

We'll probably want to do step 1 for all methods to get a working app back, then think about step 2 and 3 later on. 
### 📋 Step by Step
- [x] Claim this issue.
- [x] `comments.deleteById` in `CommentsItem.jsx`
- [x] `posts.cancelUpvote` in `Vote.jsx`
- [x] `posts.upvote` in `Vote.jsx`
- [x] `posts.remove` in `PostsEditForm.jsx`
- [x] `Meteor.call(this.props.methodName, document, this.methodCallback)` in `NovaForm.jsx` 
- [x] Newsletter methods -> mutation
- [x] Test if it works.
- [x] Open a PR to `devel` branch, mentioning this issue.
- [x] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by SachaG** [comment]
After talking with @xavcz we've decided to keep Meteor methods in place for v1 of the Apollo integration (even at the cost of no optimistic updates). So this is on stand-by.

**Comment by epaminond** [comment]
Let me take this one. :)

**Comment by xavcz** [comment]
@epaminond awesome! Let's coordinate on Slack for this one 👍

http://slack.telescopeapp.org

**Comment by SachaG** [comment]
We made some progress on this with the `postVote()` method, which is now latency compensated (aka optimistic UI).

**Comment by epaminond** [comment]
I'm obviously not finishing it for hacktoberfest, but I'd still work on this issue. :)

**Comment by SachaG** [comment]
@epaminond cool! Note that we've decided to get everything working with the old Meteor methods first (call it "stage 1") before switching to actual Apollo mutations ("stage 2"). 

So right now I'm focusing on making the methods play nice with Apollo :)

**Comment by epaminond** [comment]
@SachaG , do I understand correct that we shouldn't publish data to the client and instead use Apollo? Just been checking `comments.deleteById` and it seems `commentId` is present, but it's comment itself isn't on the client.

**Comment by SachaG** [comment]
Yes, you're right. We can't do things like `comment = Comments.findOne(commentId)` on the client anymore since we basically have no data in Minimongo. So for now we'll just do without latency compensation:

```
'comments.deleteById': function (commentId) {

    if (Meteor.isClient) {
       // do nothing…
    } else {
    check(commentId, String);
    
    var comment = Comments.findOne(commentId);
    var user = Meteor.user();
    ....
    }
}
```

**Comment by epaminond** [comment]
What about refetching? Is it that we should pass `refetchQuery` all the way down to delete comment call?

**Comment by SachaG** [comment]
Actually I'm kind of changing my mind on this, sorry… I wanted to keep Meteor methods, but then I realized that this would require complicated strategies to pass and call `refetchQuery` everywhere (which will not be necessary with Apollo mutations, unless I'm mistaken). 

So it's probably not worth it. So let's work in the Apollo mutations one by one after all :)

**Comment by xavcz** [comment]
For the `collectionRemove` mutations, should we handle them at the level of the edit form? 

Or should we wrap the `CollectionEditForm` in a single container giving access to the document `query getCollection` +  `mutation collectionRemove`?

See for example `PostsEditForm` having a container wrapping a `NovaForm`, I guess we could apply first or second solution: https://github.com/TelescopeJS/Telescope/blob/apollo/packages/nova-base-components/lib/posts/PostsEditForm.jsx#L59-L75.

**Comment by SachaG** [comment]
Oh that's a good question… I think it makes sense to say that edit forms should always contain a delete link, too. After all if someone can edit an item they should probably be able to delete it?

We could start like this, and if people also want stand-alone delete buttons we can also have some kind of `withDeleteMutation` HoC/container.

**Comment by epaminond** [comment]
@SachaG , I've played around with those mutations, but couldn't get them work. Do we have an example of implemented mutations anywhere except for the `FormWithMutation`?

Also if we aren't using `refetchQuery` how will data get updated?

**Comment by xavcz** [comment]
@epaminond update mutations update themselves the document with the fields given to the mutation! :+1: On new doc insert you need to use `updateQueries` to specify which fields to update.

Btw, I would recommend to do a _total refresh_ of your clone, there has been some breaking changes yesterday and few minutes ago 🌊  
```
git pull
meteor reset
npm install
# now it's ready to rock 🎸
```
