### ISSUE TITLE
Apollo SSR

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1486]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), _highly inspired_ by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍
### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a cool trick or two in the process on how to hack & customize Telescope Nova! 🔭
### 🤔 What you will need to know

Meteor, React, [Apollo](http://apollostack.com), and GraphQL. 

More info: 
- https://github.com/thereactivestack/meteor-react-router-ssr#example-with-redux
- http://dev.apollodata.com/react/redux.html
- http://dev.apollodata.com/react/server-side-rendering.html
### 🎯 The Goal

Figure out how to integrate Apollo with server-side rendering. 
### 📋 Step by Step

**Working on your first Pull Request?** You can learn how from this _free_ series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---
- [x] Claim this issue.
- [x] …
- [x] Test if it works.
- [x] Open a PR to `devel` branch, mentioning this issue.
- [x] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

I'll leave @xavcz complete this issue with more details :)

**Comment by xavcz** [comment]
We may need to use [`react-router-redux`](https://github.com/reactjs/react-router-redux) to bind the Redux state with the router state, as explained here https://github.com/thereactivestack/meteor-react-router-ssr/issues/89#issuecomment-252849287 and in the example provided by the meteor package.

We'll dive into this soon, any help appreciated!

**Comment by xavcz** [comment]
I can't get the [`fetchData` (react-apollo)](https://github.com/apollostack/react-apollo/blob/71bad833733904a5fda427830479d159ddeca016/src/graphql.tsx#L197-L215) function to work with the [`fetchDataHook` (reactrouter:react-router-ssr)](https://github.com/thereactivestack/meteor-react-router-ssr/blob/9762f12c5d5512c5cfee8663a29428f7e4c141f8/lib/server.jsx#L241-L257).

I'll try with the implementation of https://github.com/apollostack/GitHunt-React/blob/master/ui/server.js

**Comment by xavcz** [comment]
So it's working by tweaking `reactrouter:react-router-ssr` code:
- `wrapperHook` accept an additional parameter `option`: we give the login token caught in the cookies ;
- `preRender` accept an additinal parameter `app`: we fetch data app with `getDataFromTree`.

I don't like the fact we have to declare `let` variables `undefined` at first, such as `initialState`, `store`, `client` in the routes, and then let them be overwritten by the hooks of `ReactRouterSSR`.

This will need a refactor to use Nova without `ReactRouterSSR` and newest APIs of `react-apollo`.

*Note: thanks @jasonnathan (https://github.com/thereactivestack/meteor-react-router-ssr/issues/101) for the inspiration* 👍

**Comment by jasonnathan** [comment]
Actually @xavcz, I hacked `server.jsx` too to get it working in a way that seemed more `apollo / react-router-ssr` friendly.

I moved `preRender` down after `wrapperHook` and gave it the `{app}` argument.

_On a side note, `wrapperHook`, being a client option is ambiguous considering it was called on the server too._

After that, my setup looks like this:

````jsx
let client, initialState,
     url = "localhost",
     opts = {
       ssrMode: Meteor.isServer
     };

// relevant for apollo when a client query is made
if(Meteor.isClient && process.env.NODE_ENV === 'production'){
  url = "public-url.com";
}

// setup apollo's networkInterface
opts.networkInterface = createNetworkInterface({
  credentials: 'same-origin', uri: `http://${url}:3000/graphql`
});

// I think this is what you were referring to where its undefined till hook is called
const rehydrateHook = state => initialState = state;

const wrapperHook = app => {
  opts.initialState = initialState;
  client = new ApolloClient(opts);
  return <ApolloProvider client={client}>{app}</ApolloProvider>
};

// the preRender is simpler. All it needed was the `app` argument
const preRender = (req, res, app) => Promise.await(getDataFromTree(app));

// dehydrating in a way that is apollo friendly. Queries & mutations need to be removed
const dehydrateHook = () => ({apollo:{data:client.store.getState().apollo.data}})

const htmlHook = html => {
  const head = ReactHelmet.rewind();
  return html.replace('<head>', '<head>' + head.title + head.base + head.meta + head.link + head.script);
}

// the weirdest thing, to put wrapperHook in clientOptions, inferring it only runs on the client
const clientOptions = {wrapperHook, rehydrateHook};
const serverOptions = {htmlHook, preRender, dehydrateHook};

ReactRouterSSR.Run(AppRoutes(), clientOptions, serverOptions);
````

**Comment by xavcz** [comment]
Hehe yes, I followed the same path, actually I walked through the code of your site to understand. It's pretty smart 👍  Then I've hacked in some other places RR:SSR to adapt it the way we setup routes & apollo client in Nova.

On the next steps, we'll take inspiration on https://github.com/apollostack/react-apollo/blob/master/examples/meteor/server/index.js & & GitHunt, and try what happens without RR:SSR (and so FastRender... and InjectData local patch)

**Comment by jasonnathan** [comment]
Cool link, thanks!
