### ISSUE TITLE
Apollo Nested Comments Thread

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1489]
### 🤔 What you will need to know

Meteor, React, [Apollo](http://apollostack.com), and GraphQL. 
### 🎯 The Goal

Recreate Telescope's Reddit-style nested comment threads with Apollo. 

There are basically two approaches: 
1. Load all of a post's comments and nest them on the client.
2. Perform the nesting in GraphQL and only load the first three levels of nesting (better).
### 📋 Step by Step
- [x] Claim this issue.
- [x] ... 
- [x] Test if it works.
- [x] Open a PR to `devel` branch, mentioning this issue.
- [x] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by SachaG** [comment]
Some insights from @helfer:

```
let me think for a second about the nested comments.

depending on how you want to represent that nesting, and what you want to show at the beginning (before having expanded anything), I think you’ll want different ways of loading it on the server.

the most straightforward way in the GraphQL schema would be to give each comment a `nested_comments` field, and then just fetch those documents with a resolver.

then the fetchMore could simply use a query that accesses more comments from that particular document.

if you want to load everything at once, you could do that as well (with a special loader), but still access them in a nested fashion.

I guess I’d need some more specifics to know what the best way is. But there’s definitely a lot of possibilities with GraphQL, and they can be made efficient as well
```

See also: https://github.com/facebook/graphql/issues/91

**Comment by xavcz** [comment]
👏 🚀
