### ISSUE TITLE
Apollo Extensible Schema

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1490]
### 🤔 What you will need to know

Meteor, React, [Apollo](http://apollostack.com), and GraphQL. 
### 🎯 The Goal

Generate the Apollo Schema from SimpleSchema to make it extensible. 
### 📋 Step by Step
- [ ] Claim this issue.
- [ ] Do it. 
- [ ] Test if it works.
- [ ] Open a PR to `devel` branch, mentioning this issue.
- [ ] Someone else: review & merge! 🎉

Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by xavcz** [comment]
Well done @SachaG 🎉 

*Note: [generator code](https://github.com/TelescopeJS/Telescope/blob/apollo/packages/nova-lib/lib/graphql.js#L71-L133) & [usage](https://github.com/TelescopeJS/Telescope/blob/apollo/packages/nova-posts/lib/schema.js#L374)*
