### ISSUE TITLE
Is there a rule to make a package dependent from another or not?

### ISSUE THREAD

**Issue by MHerszak** [TelescopeJS/Telescope#1495]
For instance the api package. The api package is currently dependent of post and comment packages which isn't necessary due to callback functionality from nova:lib. I prefer to add  callbacks to each package rather than specific packages to keep less dependencies in case I want to remove dependency. Any advice in this regard?

**Comment by SachaG** [comment]
Yes, I think keeping dependencies to a minimum is always good. So basically the "rule" would be to remove dependencies until something breaks :)
