### ISSUE TITLE
Apollo Extensible Components

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1496]
Make sure components are still extensible with `Telescope.components.Foo = Bar`. This probably means splitting out non-presentational (i.e. Apollo) code from the presentational components files.

**Comment by xavcz** [comment]
As we have `nova:base-containers` & `nova:base-components`, I think we are good on this one 👍

**Comment by xavcz** [comment]
We were not good in fact 😅 

After a long discussion on Slack, we ended up deciding to do like this:
https://github.com/TelescopeJS/Telescope/commit/17513c1a980f224802b10752d7a2011464af3de2
