### ISSUE TITLE
Apollo Questions

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1498]
Let's centralize all our questions about Apollo in here and I'll try to get someone from the Apollo team to answer them all at once. 

- [x] Can you use dots inside GraphQL mutation names? for example could you name your mutation `posts.new` or would it have to be `postsNew`?
- [x] When I call a mutation using `this.props.myMutation(...).then(result => {// do something})`, the returned document is available as `result.data.nameOfMutation`. Is there a way to change that `nameOfMutation` part to something else?
- [ ] The example in http://dev.apollodata.com/react/cache-updates.html#updateQueries uses `unshift` to add a new comment at the top of the list. So far so good, but what if your list is sorted? For example, let's say I have a list of books sorted alphabetically and I'm adding a new book somewhere in the list. Would I need to manually re-sort the list myself inside the `updateQueries` function and return that, or is there some kind of helper?
- [x] If I get a document back as a result of a mutation and it gets inserted in the store properly, would Apollo know not to re-query the server for it? what criteria would Apollo use to decide?

**Comment by SachaG** [comment]
- [ ] How would you handle a blackbox field in your schema? I make API requests to a third-party service that returns data, and I want to store that data on my objects but I don't know its shape.
- [ ] What are the advantages of using Fragments as opposed to just regular JS strings?

**Comment by xavcz** [comment]
[ ] How would you handle server-side rendering with Apollo and Meteor, especially get the `Accounts._storedLoginToken` and pass it to `ApolloClient` client side?

**Comment by xavcz** [comment]
For the blackbox fields, what about using https://github.com/taion/graphql-type-json ?

**Comment by SachaG** [comment]
Actually Jonas suggested using Scalar JSON types, I don't know if that's what he meant.

**Comment by xavcz** [comment]
Yep that's it!
