### ISSUE TITLE
Login form from modal does not work

### ISSUE THREAD

**Issue by qge** [TelescopeJS/Telescope#1500]
Version: v0.27.3
Go to any post without login, The modal triggered by "Please log in to comment." is blank.

**Comment by SachaG** [comment]
You might need to upgrade the `std:accounts-ui` package to the latest version?

**Comment by qge** [comment]
@SachaG I'm using std:accounts-ui@1.2.6, which is the latest version on atmosphere.

**Comment by SachaG** [comment]
I actually published 1.2.8: https://atmospherejs.com/std/accounts-ui

**Comment by xavcz** [comment]
1.2.8 solves the problem 👍
