### ISSUE TITLE
Conflicting users

### ISSUE THREAD

**Issue by tenshis** [TelescopeJS/Telescope#1501]
If I have a user Mark Smith who logs in via Facebook, his profile name will automatically be `/users/mark-smith`.

If another user comes along and registers an account (without facebook) with the username _mark-smith_, his profile name will, too, be `/users/mark-smith`

**Comment by xavcz** [comment]
Thanks for reporting the issue @tenshis! The code to prevent this behavior was already present but it missed an edge case 👍 

Fixed on `devel` branch!

**Comment by osterkraft** [comment]
Hey guys, sorry to reopen, but I have a similar issue. 

I added `accounts-facebook` as well as `pauli:accounts-linkedin`, and signup & login works fine. However, as a user wants to connect with several accounts, the same e-mail gets registered for different user ids. Have any of you tackled this before? The project `yubozhao/meteor-link-accounts` needs a maintainer and does not seem to support the pauli linkedin project unfortunately.

**Comment by xavcz** [comment]
This is sadly a Meteor problem.. that this `yubozhao/meteor-link-accounts` tried to solve.

**Comment by osterkraft** [comment]
Thanks for the input @xavcz, I'll try find a way to handle it.
