### ISSUE TITLE
Can't publish new i18n package.

### ISSUE THREAD

**Issue by sherryxiao1988** [TelescopeJS/Telescope#1506]
I am creating a new package for zh-CN, but depending on the same version of nova:core as nova-i18n-en-us does throws an error when publishing the package.

Version used in package.js:

```
Package.onUse(function (api) {

  api.versionsFrom("METEOR@1.0");
  api.use([
    'nova:core@0.27.3-nova'
  ]);

  api.addFiles([
    'lib/zh_CN.js'
  ], ["client", "server"]);
});
```

Error thrown (error disappear if delete the above dependency):
```
meteor publish --create
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```

Any thoughts?

Thanks!
Shundan

**Comment by xavcz** [comment]
Hey Shundan! What happens if you remove the `@0.27.3-nova` dependency?

**Comment by xavcz** [comment]
Maybe @abhaytalreja can help on this, he just published a package ([theme](https://github.com/abhaytalreja/nova-class-bargain-theme/)) having dependencies on Nova v0.27.3

**Comment by sherryxiao1988** [comment]
thank you @xavcz !  removing ```@0.27.3-nova``` works!  I will add the zh-CN link to README once it's published and tested.

**Comment by sherryxiao1988** [comment]
@xavcz  Another error:

```
=> Errors while publishing:

While publishing the package:
error: You must specify a version constraint for package nova:core
```

Looks I have to specify a version for nova:core?

**Comment by xavcz** [comment]
I've made a PR on your repo with minor tweaks concerning the package publishing & the fit with Nova internationalisation & settings, see sherryxiao1988/nova-i18n-zh-CN#1. I believe we can close this issue and continue the discussion over there.

Moreover, @qge recently made a PR for `zh-CN` too: https://github.com/TelescopeJS/Telescope/pull/1503. I (unfortunately) do not speak Chinese, I don't know what the differences are, maybe you can coordinate your efforts? Anyway, we will be glad to accept another translation and add it to the `Readme.md` if you feel that both packages cannot live together!

**Comment by sherryxiao1988** [comment]
@xavcz Still experiencing the same error after merging your pull request :

running meteor publish --create

```
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```
