### ISSUE TITLE
How do I remove the 'sign up for the newsletter' banner?

### ISSUE THREAD

**Issue by gg2001** [TelescopeJS/Telescope#1509]
With Nova, there is a sign up for the newsletter banner that keeps showing up. How do I remove this?

**Comment by xavcz** [comment]
Remove the `nova:newsletter` package and remove the `<Telescope.components.Newsletter />` from `Layout.jsx` (`nova:base-components`).

Btw, I'd advise you to watch the screencasts explaining how to customize Nova on http://www.telescopeapp.org/
