### ISSUE TITLE
Reset password link broken?

### ISSUE THREAD

**Issue by gg2001** [TelescopeJS/Telescope#1510]
Whenever I go to this link, it simply redirects me to the homepage. Any fix to this?
<img width="600" alt="screen shot 2016-11-15 at 0 15 46" src="https://cloud.githubusercontent.com/assets/16451579/20301769/c78e842e-aac8-11e6-8606-6e7942921c24.png">

**Comment by xavcz** [comment]
Yeah, it got fixed in the latest release (2 hours ago)! 

I see that your site is running on v0.27.3: update to v.027.4 and it will work 🎉

**Comment by gg2001** [comment]
Working fine now, thank you very much!
