### ISSUE TITLE
few issues with the one-click Heroku deploy

### ISSUE THREAD

**Issue by MaxPleaner** [TelescopeJS/Telescope#1516]
There are two issues I encountered using the "one click deploy" button [here](docs.telescopeapp.org/docs/deploying)

Some parts of the UI are broken. The user system wasn't working - buttons are errantly disabled and even if they are manually enabled, submitting them does nothing.

I thought these issues might be because the telescope / nova version is out of date. So I tried `git clone` . Heroku said "it appears you have cloned an empty repository" and the folder is indeed empty. 

Furthermore I tried running `meteor update` on the deployed app itself, but that wasn't working

```txt
> heroku run meteor update -a max-nova-app
Running meteor update on ⬢ max-nova-app... up, run.2447 (Free)
bash: meteor: command not found
```

**Comment by xavcz** [comment]
Yeah the one-click deploy refers to the `TelescopeJS/sample-project` which is outdated. As this docs that refers to Telescope Legacy (powered with Blaze). 

We should disable this repo & this doc which is not up to date neither.

So I recommend to follow the [Deployment section of the README](https://github.com/TelescopeJS/Telescope#deployment) if you want to deploy the app online. 

Or [install it locally](https://github.com/TelescopeJS/Telescope#first-steps).

Happy hacking 👍
