### ISSUE TITLE
Allow excerpt length in settings.json

### ISSUE THREAD

**Issue by z3to** [TelescopeJS/Telescope#1517]
I noticed that currently the length of the excerpt is hard-coded to 30 words in `Posts.before.insert` and `Posts.before.update`. Wouldn't it be desirable to define this setting globally and even allow to alter this value in the `settings.json`?

And as well for th newsletter: Here the length is in hard-coded to 20 word at two positions in `Newsletter.build`.

**Comment by xavcz** [comment]
Hey @z3to! 

Yeah that looks like a nice-to-have feature to be able to manage the excerpt from the settings!

We would have a default value of 30 / 20 like it is now, and it would be replaced by the settings if you specified it!

Are you OK to do a PR? 👍  Feel free to drop by the [Slack room](http://slack.telescopeapp.org) if you need any help :)

**Comment by xavcz** [comment]
Integrated by @philweber 🎩
