### ISSUE TITLE
Newsletter job endless loop

### ISSUE THREAD

**Issue by areohbe** [TelescopeJS/Telescope#1519]
I'm having trouble diagnosing what is causing this to happen in my project, but **sometimes** when I build my app locally the following cron job runs in an endless loop:

```
I20161130-10:31:05.917(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Starting "scheduleNewsletter".
I20161130-10:31:05.918(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Finished "scheduleNewsletter".
I20161130-10:31:05.926(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Starting "scheduleNewsletter".
I20161130-10:31:05.928(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Finished "scheduleNewsletter".
I20161130-10:31:05.933(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Starting "scheduleNewsletter".
I20161130-10:31:05.936(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Finished "scheduleNewsletter".
I20161130-10:31:05.941(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Starting "scheduleNewsletter".
I20161130-10:31:05.943(-8) (percolatestudio_synced-cron.js:84) SyncedCron: Finished "scheduleNewsletter".
```

Last night my project was building fine, this morning I am seeing the issue and I have made no modifications to my project. Yes, I am using my actual mailchimp API keys.

**Comment by xavcz** [comment]
*From Slack:*
> areohbe [5:33 AM]  looks like adding `newsletterFrequency` to settings fixed my issue :slightly_smiling_face:

Glad to know you fixed it!

For the records, the newsletter frequency should be something like this
```
"newsletterFrequency": [1,2,3,4,5,6,7], // will run everyday of the week
```

**Comment by Billboz** [comment]
That didn’t work for me so I just changed the ‘enableNewsLetter’ to false and it loaded the sample_settings without going into the scheduling loop.
```
    "enableNewsletter":false,
    "newsletterFrequency": [1,2,3,4,5,6,7],

```
I will try to figure out why it didn’t work for me and get back with you if I do.

**Comment by xavcz** [comment]
Hey @Billboz, loading the app from the sample_settings, you will need to have both right the `newsletterFrequency`  and the mailchimp api keys:
```
// sample_settings.json
"mailChimpAPIKey": "123foo",
"mailChimpListId": "123foo",
```

**Comment by kevinyun** [comment]
@xavcz Similar to OP, I have the mailchimp keys set up, but this doesn't seem to work for me either -- still getting continuously running newsletter job.

I just put `enableNewsletter` to `false` for now as well.

**Comment by SachaG** [comment]
@kevinyun have you double-checked that your API keys are valid?

**Comment by kevinyun** [comment]
Yup, double checked just now. I don't have a verified email on Mailchimp yet -- do you think that could that be a factor? (currently waiting for a CNAME to validate on Mailgun DNS so can't verify the domain on Mailchimp just yet)

**Comment by SachaG** [comment]
That might be it. Usually there's an error in the server logs or something though.
