### ISSUE TITLE
Errors installing it

### ISSUE THREAD

**Issue by Hostile** [TelescopeJS/Telescope#1523]
Got npm installed on ubuntu 14.04

gyp ERR! command
   "/home/vodeoo/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/vodeoo/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild"
   gyp ERR! cwd
   /tmp/mt-1du7t2c/npm/node_modules/.temp-rbrd9b/node_modules/bcrypt
   gyp ERR! node -v v4.6.2
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Linux 3.13.0-105-generic
   npm ERR! argv
   "/home/vodeoo/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/vodeoo/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--update-binary"
   npm ERR! node v4.6.2
   npm ERR! npm  v3.10.9
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.7.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/mt-1du7t2c/npm/node_modules/.temp-rbrd9b/npm-debug.log

=> Your application has errors. Waiting for file change.

**Comment by Hostile** [comment]
then from cloning it 

    /build/programs/server/boot.js:128:5
    W20161208-00:59:19.750(-5)? (STDERR)     at     /home/vodeoo/Telescope/.meteor/local/build/programs/server/boot.js:344:5
    => Exited with code: 1
    => Your application is crashing. Waiting for file change.

**Comment by xavcz** [comment]
>The babel-runtime npm package could not be found in your node_modules
directory.
If it can't find the `babel-runtime`, that means you don't have the node modules installed. So after cloning it from git, do you `npm install` again 👍 

You may have another warning when starting the app due to meteor/npm about bcrypt native/js, you'll be able to solve it by specifying explicitly using the Meteor's node version`meteor npm install bcrypt`

**Comment by Hostile** [comment]
now this:

Your app is crashing. Here's the latest log:
/home/vodeoo/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Can't find npm module 'juice'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/home/vodeoo/Telescope/.meteor/local/build/programs/server/boot.js:200:17)
    at options.fallback (packages/modules-runtime.js:445:18)
    at Module.require (packages/modules-runtime.js:112:16)
    at Module.Mp.import (/home/vodeoo/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.nova:email.lib.server.email.js (/home/vodeoo/Telescope/.meteor/local/build/programs/server/packages/nova_email.js:94:288)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/home/vodeoo/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.nova:email.lib.server.js (packages/nova:email/lib/server.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:181:9)
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by Hostile** [comment]
ok did meteor npm install --save bcrypt and meteor npm install --save juice and it worked
