### ISSUE TITLE
nova:forms-tags  dependency error. Can't find npm module 'meteor/nova:forms-tags/lib/export.js'. Did you forget to call  'Npm.depends' in package.js within the 'module runtime' package

### ISSUE THREAD

**Issue by shashanksmf** [TelescopeJS/Telescope#1524]
I included nova:forms-tags in meteor/package.js
And used Tags in my-custom-package custom_fields as shown below
import Tags from 'meteor/nova:forms-tags';

When i try to run its showing me the following error
Can't find npm module  'meteor/nova:forms-tags/lib/export.js'. Did you forget to call  'Npm.depends' in package.js within the 'module runtime' package

**Comment by SachaG** [comment]
Where is that error coming from?

**Comment by shashanksmf** [comment]
In the my-custom-package/ custom_fields.js...i have imported tags lik below
import Tags from 'meteor/nova:forms-tags';
I have a package nove-forms-tags in packages folder and also added package name in '/meteor/packages.js'
But when i run meteor command it is showing me the above error in console.

**Comment by SachaG** [comment]
Are you also depending on `nova:forms-tags` inside your custom package's `package.js`? (in the `api.use` block?)

**Comment by SachaG** [comment]
I'll update the readme:

```
# Usage

1. Add `nova:forms-tags` to your `.meteor/packages` file.
2. Add `nova:forms-tags` to your custom package's dependencies in `package.js`. 
3. Add the [react-tag-input](https://www.npmjs.com/package/react-tag-input) NPM package with `npm install react-tag-input --save`.
4. In your code, `import Tags from 'meteor/nova:forms-tags'` and then set `control: Tags` on a custom field.
```

**Comment by shashanksmf** [comment]
@SachaG : Thanks..it worked...!!!
