### ISSUE TITLE
Users is not defined in nova:users/lib/schema.js.

### ISSUE THREAD

**Issue by comus** [TelescopeJS/Telescope#1525]
hello

see: https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-users/lib/schema.js#L193

may be import Users from './collection.js'

although it causes circular dependencies

**Comment by xavcz** [comment]
Hey good catch!

For the moment we'll stay with these circular dependencies (there are others in posts for instance).

**Comment by xavcz** [comment]
Fixed 👍
