### ISSUE TITLE
Page refresh problem on the Apollo branch

### ISSUE THREAD

**Issue by pixelpunch** [TelescopeJS/Telescope#1527]
Wanted to report that -

1. On Log-in the page doesn't automatically refresh, but shows this - http://screencast.com/t/dqk7v0d1s - the user is logged in but shows up only when the page is physically refreshed

2. A new post shows up in the list but AFTER 10 seconds (on local dev) without refreshing. Is this an outcome of replacing DDP with GraphQL?

**Comment by SachaG** [comment]
The first thing is a bug, but the second one is the expected behavior. Posts are now refreshed on a 20s interval.

**Comment by pixelpunch** [comment]
Thanks, Sacha. But as there is no confirmation on submission, a 20s interval might disorient the user . Can't it be made shorter?

**Comment by pixelpunch** [comment]
Issue closed. There IS a confirmation :)
