### ISSUE TITLE
export Routes always empty array

### ISSUE THREAD

**Issue by comus** [TelescopeJS/Telescope#1531]
from the source code
```
export let Routes = [];

export const addRoute = routeOrRouteArray => {
  const addedRoutes = Array.isArray(routeOrRouteArray) ? routeOrRouteArray : [routeOrRouteArray];
  Routes = Routes.concat(addedRoutes);
  return Routes;
}
```

call addRoute one times
and export variable `Routes` still equal empty array []

**Comment by xavcz** [comment]
Feel free to send a PR with your thought process as a description :)

Related files:
- https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-base-components/lib/routes.js
- https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-routing/lib/routing.jsx
- https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-lib/lib/routes.js
