### ISSUE TITLE
Moving from Nova Classic to Nova Apollo/GraphQL

### ISSUE THREAD

**Issue by adalidda** [TelescopeJS/Telescope#1533]
Hi,

I am working to migrate my nova app from Nova Classic to Nova Apollo/GraphQL (version 1.0.0). When I run my app locally with the command:
MONGO_URL='mongodb://user:password@ip1:port1,ip2:port2/dbname?authSource=admin&replicaSet=replicasetname&readPreference=nearest&w=majority'  meteor --settings settings.json

My app using Nova Apollo/GraphQL can access my database and display posts. However when I deploy it with mup (the latest), my App can't access my database. 

PS: I used the same mup.js that I deployed and run successfully with Nova classic.
my mup.js used 
MONGO_URL: 
MONGO_OPLOG_URL:

What could be the reason ?

Thank You
Adalidda

**Comment by xavcz** [comment]
Do you have any errors output?

I haven't deployed yet, maybe @SachaG have any insight on this?

**Comment by SachaG** [comment]
I actually haven't deployed an Apollo app yet either… I didn't think there could be an issue here since as far as I know the db is still accessed the same way by Meteor. 

@adalidda did you upgrade your version of Meteor at the same time? Could this be part of the issue?

**Comment by xavcz** [comment]
Hey @adalidda!

Found your messages, [#1](http://meta.telescopeapp.org/posts/WdseTamAEBGcAzLNG/telescope-nova-version-0-27-5-apollo-graphql-version) & [#2](http://meta.telescopeapp.org/posts/oZgvC8X64iJhi6PAE/additional-info-on-the-migration-from-telescope-nova-classic) on Meta: glad you solved the problem 🎉 

Thanks for the kind messages & we will update the docs to prevent people to run in similar problems! 👍 Don't hesitate to drop by the [Slack room](http://slack.telescopeapp.org) 👋
