### ISSUE TITLE
Malware on demo.

### ISSUE THREAD

**Issue by cmboros** [TelescopeJS/Telescope#1545]
Hey

I just check and the demo have some malware or at least sucuri.net see it as malware. 
https://forums.meteor.com/t/malware-detected-in-meteorjs-custom-build-deployment/31468
https://sitecheck.sucuri.net/results/http://demo.telescopeapp.org

Thanks

**Comment by dominictracey** [comment]
I assume this is not the code itself but rather one of the posts? Which does beg the question of how malware of whatever type could be transmitted through a post or comment. Sites use markdown rather than allowing raw HTML to prevent exactly this sort of thing.

**Comment by SachaG** [comment]
It looks like this is about the code itself, so I assume it's a false positive. The related entry doesn't mention Meteor or Node at all:

http://labs.sucuri.net/db/malware/malware-entry-mwjs160?17

**Comment by xavcz** [comment]
Closing as it's false positive. We'll clean the demo and deploy the apollo version soon 🌊
