### ISSUE TITLE
Access Apollo Client's data when running `collection.parameters` callbacks

### ISSUE THREAD

**Issue by xavcz** [TelescopeJS/Telescope#1546]
✍️ _This issue comes from a bug of the posts disappearing when doing a vote mutation on a post list filtered by category_

*Note: I'm trying to keep note of the thinking process, @SachaG*

In order to have the right `selector` & `options` for our Mongo queries, we use the handy `collection.getParameters` helper function: 
```js
// get mongo selector and options objects based on current terms
const { selector, options } = collection.getParameters(terms);
```

We use `collection.parameters` callbacks functions defined as:
```js
const CollectionSomeFilteringFunction = (parameters, terms) => {
  // do some stuff to extend the current parameters, based on the current terms

  // give the parameters to the next callback function
  return parameters;
}
```

We sometimes rely on other collections data there: it works great in our resolvers, as we have access to all the data (server-side); however it leads to troubles client-side.

Especially this one `PostsCategoryParameter`: https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-categories/lib/parameters.js#L31-L32

We try to find `Categories` based on their slug, but client-side this returns an empty cursor (`Mingo.query(selector)`).

An example of what's happening:
1. Showing a basic list, and acting on it: no problem
2. Moving to a "category view" (`terms.cat = foo`): new results are sent from the server we got them, but the `mingo.query` cursor is empty. The results are still shown because we didn't modified them (`** no action **`)
3. Voting: pops off, the query reducer listening for mutation try to reorder with a `selector.categories = {$in: []}` === it didn't find any categories, and so no posts with this kind of `categories = []`.

![gif list emptied](https://d17oy1vhnax1f7.cloudfront.net/items/2y1P1G3U3s2y2s2L1M0W/Screen%20Recording%202017-01-28%20at%2004.30%20PM.gif?v=e4a42335)

**Solution:**
I don't know if it's clear, but my assumption would be to *plug the Apollo Client* to the `terms` when asking for `collection.getParameters`, so we could get the data from the client instead of an empty category. Maybe with this utility function: https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-categories/lib/schema.js#L2-L22

**Comment by SachaG** [comment]
Good detective work!

**Comment by SachaG** [comment]
By the way, feel free to reopen the issue if the problems happens elsewhere, too. Ultimately I think any "Collection.find()" is a code smell, but right now I don't know the right way to solve this… (maybe using `context` like in Apollo resolvers, and having a more structured connector layer with its own API?)
