### ISSUE TITLE
Install npm package in Nova package?

### ISSUE THREAD

**Issue by xyx2011** [TelescopeJS/Telescope#1547]
When I try to add the following to my package.js:
```javascript
api.use([
    // Nova packages
    'nova:core@1.0.0',
    // third-party packages
    'material-ui@0.16.7',
    'react-tap-event-plugin@2.0.0'
  ]);
```
I got unknown package error, is there anyway to use npm package in custom package but not install it in global Nova app? maybe create as a new npm repo? Thanks!

**Comment by xyx2011** [comment]
this answer is to use `NPM.depend` like this: 

```javascript
Npm.depends({
    'material-ui': '0.16.7',
    'react-tap-event-plugin': '2.0.0'
});

Package.onUse(function (api) {

  api.versionsFrom(['METEOR@1.0']);

  api.use([
    'nova:core@1.0.0',
  ]);

  api.x

  api.mainModule("lib/server.js", "server");
  api.mainModule("lib/client.js", "client");

});

```

**Comment by SachaG** [comment]
Well, you can also just add any npm package to your `package.json`. In fact that's probably the best approach, because if you use `Npm.depends` you'll now have some NPM packages imported through your Meteor packages, and some through `package.json`, and you might run into conflicts or issues.
