### ISSUE TITLE
Posts.removeField("url") => generate error

### ISSUE THREAD

**Issue by adalidda** [TelescopeJS/Telescope#1549]
Hi,

With Apollo/GraphQL version, it seem that when I use Posts.removeField("url"); in custom_fields.js, Nova generate error and I can't access my database anymore.

This was working in nova-classic.

Thank You
Adalidda

**Comment by xavcz** [comment]
Hey @adalidda 

Can you paste the error here please?

**Comment by adalidda** [comment]
Yes, you are right. Just finish reading the new doc again and understand that I have to remove it from the fragment.

Thank You Xavier.

**Comment by xavcz** [comment]
Hey @adalidda ! Fragments API has been updated, they are working better than never, and new docs again 😄 : http://nova-docs.telescopeapp.org/data-layer.html#Fragments
