### ISSUE TITLE
Disabling Embedly is quite problematic

### ISSUE THREAD

**Issue by juliancwirko** [TelescopeJS/Telescope#1550]
Hi, when I want to remove Embedly package completely I get some errors related to GraphQL. I needed to remove `thumbnailUrl` from `PostsList.fragment`so I tried to replace the component with CustomPostsList component just to be able to overwrite this, but this isn't the solution. I guess it could be done somehow, maybe I don't know something. Anyway, it would be great to be able to just remove Embedly when we don't want thumbnails at all. The same is with `PostsPage.fragment`.

Ps. also when I don't remove the Embedly package and not configure EmbedlyKey in settings I get errors when posting because in `nova:embedly` package in `EmbedlyURL.jsx` we have `result.data.getEmbedlyData` which is `null` in that case and `result.data.getEmbedlyData.title` throws error. Data check there is needed.

I could send a PR but I don't know exactly how to resolve these issues.

**Comment by SachaG** [comment]
You'll always need to remove `thumbnailUrl` from the fragment. But I agree replacing fragments should be easier, in fact I just pushed some changes to `devel` to do just that. You can refer to the documentation (http://nova-docs.telescopeapp.org/data-layer.html) to learn more. Let me know if that helps :)

**Comment by juliancwirko** [comment]
Yes, I tought so :) 
So, I've used new `registerFragment` from `devel`. It seems to work. I only get this warning http://dev.apollodata.com/core/fragments.html#unique-names , but it isn't a problem for me. 
Thanks. New fragments api is much cleaner. I like it :)

**Comment by SachaG** [comment]
Great! Yeah I've just been ignoring these warnings as well for now ;)

**Comment by xavcz** [comment]
Hey @juliancwirko! Fragments API has been updated, they are working better than never, you can have a look there: http://nova-docs.telescopeapp.org/data-layer.html#Fragments

**Comment by juliancwirko** [comment]
Great, do you plan to officially release v1.0.0 anytime soon? Thanks.

**Comment by xavcz** [comment]
[One last task](https://trello.com/c/T7LX2Dt2/103-display-nicer-error-texts-in-form-find-a-formatted-message-or-fallback-to-only-error-message) and yes 👍 

So I'd say later today or tomorrow? 🌮

**Comment by xavcz** [comment]
@juliancwirko yay! `master` is stable 💯

**Comment by juliancwirko** [comment]
Great :) so I need to start my updates :)

**Comment by xavcz** [comment]
You are welcome on the Slack chatroom if you need any help: http://slack.telescopeapp.org 😊

**Comment by jeffreywyman** [comment]
I agree with original post. When I disable embedly, I get this error:

[Error: Network error: Network request failed with status 400 - "Bad Request"]
 graphQLErrors: [],
networkError:
 { [Error: Network request failed with status 400 - "Bad Request"]
 response:
Body {
 url: 'http://localhost:3000/graphql',
status: 400,
 statusText: 'Bad Request',
headers: [Object],
 ok: false,
body: [Object],
bodyUsed: false,
 size: 0,
 timeout: 0,
_raw: [],
 _abort: false } },
  message: 'Network error: Network request failed with status 400 - "Bad Request"',
I20170212-14:44:43.325(-5)?   extraInfo: undefined }

**Comment by xavcz** [comment]
You'll need to register a new `PostsList` fragment without `thumbnailUrl`, see http://nova-docs.telescopeapp.org/data-layer.html#Replacing-Fragments
