### ISSUE TITLE
Error when using getFragment - Nova Apollo-GraphQL

### ISSUE THREAD

**Issue by adalidda** [TelescopeJS/Telescope#1551]
Hi,

I follow the example in the doc section data-layer.htm and my custom custom_fields.js contain below code:
```
import Posts from "meteor/nova:posts";
import { registerFragment, getFragment } from 'meteor/nova:lib';
import gql from 'graphql-tag';

Posts.addField(
  {
    fieldName: 'ReadFullStoryAt',
    fieldSchema: {
      type: String,
      optional: true, // this field is not required
      insertableBy: ['members'],
      editableBy: ['members'],
      viewableBy: ['guests'],
      publish: true,                                                                                                     // 112
    },
  }
);

const CustomPostsListFragment = gql`
  fragment CustomPostsList on Post {
    ...PostsList
       ReadFullStoryAt 
  }

  ${getFragment('PostsList')}

`;

registerFragment(CustomPostsListFragment, 'PostsList');
```

When I run my app, I got the following error:
```
TypeError: getFragment is not a function
W20170201-14:39:07.273(7)? (STDERR)     at meteorInstall.node_modules.meteor.adalidda-site.lib.custom_fields.js (packages/adalidda-site/lib/custom_fields.js:57:5)
```
Then I search for getFragment and registerFragment under nova-lib folder and I don't found both of them any where !

What is wrong ?

Thank You
Adalidda

**Comment by xavcz** [comment]
It looks like you are on the `master` branch, aren't you? We didn't merge the `getFragment` it yet on `devel` 😳

Please checkout on the `devel` for the moment:
```
git checkout devel
```

Apologies! We are going to do some improvement on this `getFragment` function. Don't hesitate to come by the [Slack chatroom](http://slack.telescopeapp.org) to stay tuned 👍

**Comment by adalidda** [comment]
Oh great. If you work on improvement, I suggest to include it automatically
with addfield (add to fragment) and removefield (remove from fragment).

Once again, thank you so much. Now, we are able to deploy our new Nova
Apollo GraphQL to our test url https://nova.adalidda.com

Thank You so much

Adalidda

**Comment by xavcz** [comment]
Well, I already pong you on the other issue, but putting it here in case of... There is a new API for fragments, here is the docs: http://nova-docs.telescopeapp.org/data-layer.html#Fragments

**Comment by adalidda** [comment]
Thank You Xavier.

Adalidda
