### ISSUE TITLE
Is there a quick way to change which URL gets called for GraphQL?

### ISSUE THREAD

**Issue by pavanagrawal123** [TelescopeJS/Telescope#1554]
Currently, I'm running on a server for testing, however the app is making all GrapQL calls to localhost... How can I point this to the correct URL?

**Comment by SachaG** [comment]
Maybe try changing the `ROOT_URL` environment variable?

**Comment by pavanagrawal123** [comment]
I currently have this in my telescope folder's .env
ROOT_URL=http://10.1.10.XXX:3000 meteor
When I run the meteor application it still says starting on localhost:3000
And GraphQL calls are still made to localhost...

Will I have to use the deployment instructions from the documentation?
Thanks for your help!

**Comment by SachaG** [comment]
Changing the `ROOT_URL` won't change the actual URL your app runs on, but I thought it would change the URL of the GraphQL endpoint being queried. It looks like that's dependent on `Meteor.absoluteUrl()`, what does that return for you?

**Comment by lbang** [comment]
I think this is a Meteor issue. See [https://github.com/meteor/meteor/issues/4696](url)

In the meantime, what I have done is changed the nova-apollo [client.js](https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-apollo/lib/client.js) file from 
`const url = Meteor.absoluteUrl(path);` 
to 
`const url = Meteor.absoluteUrl(path, {rootUrl: "http://10.1.10.XXX:3000"});`

**Comment by meteorplus** [comment]
`ROOT_URL=http://10.1.10.XXX:3000 meteor` this will work I used this on c9.io

Even if you see `When I run the meteor application it still says starting on localhost:3000` it works!
But the main problem is GraphQL that won't use your provided IP and port! 
`And GraphQL calls are still made to localhost...`

there is a server.js file where all the GraphQl takes everything (URL to make calls to)

I am still struggling with until now too

**Comment by xavcz** [comment]
I've added your modification @lbang

@pavanagrawal123 @meteorplus what if you add this setting inside `public` (so it's accessible by both client & server), does it work?
```json
"developmentServerIp": "http://IP_ADDRESS:PORT/",
```
