### ISSUE TITLE
List of categories not sorted when add new post

### ISSUE THREAD

**Issue by adalidda** [TelescopeJS/Telescope#1560]
Hi,

When add a new post the list of categories is not sorted. I want to have it sorted. I think that I should modify nova-categories/lib/custom_fields.js

Posts.addField(
  {
    fieldName: 'categories',
    fieldSchema: {
      type: [String],
      control: "checkboxgroup",
      optional: true,
      insertableBy: ['members'],
      editableBy: ['members'],
      viewableBy: ['guests'],
      form: {
        noselect: true,
        type: "bootstrap-category",
        order: 50,
        options: formProps => getCategoriesAsOptions(formProps.client),
      },
      resolveAs: 'categories: [Category]'
    }
  }
);

to add something equivalent to the version in Nova Classic
var categories = Categories.find({}, {sort: {name: 1}}).map(function (category)

I spent many hours, reading Nova code, but still don' t find how to do it with Nova Apollo/GraphQL.

Could you please point out how to do or add this sort to the next release (when having many categories, it's more convenient to have them sorted).

Thank You
Adalidda

**Comment by xavcz** [comment]
You will want to use array method `.sort` to sort the result of `getCategoriesAsOptions(formProps.client)`. 

You can see the code of the functions used here: https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-categories/lib/schema.js#L15-L24

Sort docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

Btw, if you want to get better at this kind of things, I recommend JS30 🚀 http://javascript30.com

**Comment by xavcz** [comment]
And you should do the modifications in your own custom package, not in `nova:categories` directly :)

**Comment by adalidda** [comment]
Thank You Xavier

Adalidda
