### ISSUE TITLE
Scss compiler error

### ISSUE THREAD

**Issue by jetordie** [TelescopeJS/Telescope#1562]
When I run **meteor** in my project dir (fresh default install) I'm getting the following:

```While processing files with fourseven:scss (for target web.browser):
  /packages/telescope_theme-base/lib/client/scss/screen.scss: Scss compiler error: ".error" failed to @extend ".grid-block".
  The selector ".grid-block" was not found.
  Use "@extend .grid-block !optional" if the extend should be able to fail.
```

I only found one other post (on Reddit) mentioning the same issue without resolution.

**Comment by SachaG** [comment]
I don't think there's any `grid-block` selector in the codebase so I'm not sure what that's about. I'd suggest trying to reinstall from a fresh clone of the repo.

**Comment by SachaG** [comment]
Oh it looks like you're still on the legacy branch for some reason, that's not supported anymore, sorry…
