### ISSUE TITLE
405 error on Meteor?

### ISSUE THREAD

**Issue by jetordie** [TelescopeJS/Telescope#1567]
Nova works fine on my meteorapp.com subdomain, but I'm getting a 405 error when I access the site from my domain (cname to meteor). How can I fix this?

```
Fetch API cannot load http://***.meteorapp.com/graphql. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.***.com' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by SachaG** [comment]
What's meteorapp.com ? Maybe try a different hosting method?

**Comment by xavcz** [comment]
It's Galaxy stuff, isn't it @jetordie?

It looks like a CORS issue. Did you specify the `ROOT_URL` of your app to point to your domain instead of `xxx.meteorapp.com`? (default)

**Comment by xavcz** [comment]
I believe we could enhance our GraphQL server start with some kind of warning message (or even prevent the app to start?!) if we the `ROOT_URL` is different from the `Meteor.absoluteUrl()` ?

**Comment by jetordie** [comment]
Thank you @xavcz -- I somehow didn't see that setting in the Meteor setup process. All is working well now.
