### ISSUE TITLE
Deploying to Heroku: Unable to complete "npm start". Missing start script error

### ISSUE THREAD

**Issue by yogeshbalan** [TelescopeJS/Telescope#1571]
**I am trying to deploy it on Heroku but it is showing this missing start script error.
Please help me in this regard.**

0 info it worked if it ends with ok
1 verbose cli [ '/home/username/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
5 verbose cwd /home/username/WebDev/Backup/HelloMakersWebApp
6 error Linux 3.13.0-105-generic
7 error argv "/home/username/.nvm/versions/node/v7.4.0/bin/node" "/usr/local/bin/npm" "start"
8 error node v7.4.0
9 error npm  v4.0.5
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by xavcz** [comment]
Mmmh.. 

We do have a `npm start` command, but it's just a fancy thing to display a message to lead to the docs & then launch Meteor thanks to `meteor --settings settings.json`.

Did you setup the Meteor buildpack to deploy to Heroku? Here is an article about that: https://www.coshx.com/blog/2016/08/19/how-to-deploy-a-meteor-1-4-app-to-heroku/

**Comment by yogeshbalan** [comment]
I haven't tried Meteor buildpack yet.
Thanks for the suggestion. will try it

**Comment by jaisharmafps** [comment]
It looks like you might not have defined a start script in your package.json file or your project does not contain a server.js file.

You could either change the name of your application script to server.js or add the following to your package.json

`"scripts": {
"start": "server.js"
},`

[source](http://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start)
