### ISSUE TITLE
Cannot add user to group with Users.methods.addGroup(user._id, 'groupName');

### ISSUE THREAD

**Issue by oskareke** [TelescopeJS/Telescope#1575]
Adding users to groups by calling Users.methods.addGroup(user._id, 'groupName') on the server as per the documentation doesn't work for me and I cannot find any signs in the code of this feature being implemented - hence my question, is it implemented? ;P

**Comment by SachaG** [comment]
You're right, that method is deprecated and should be removed from the docs.
