### ISSUE TITLE
How import posts from csv?

### ISSUE THREAD

**Issue by atherdon** [TelescopeJS/Telescope#1576]
I understand that default posts was imported by some functionality, but cannot find it myself.
Thanks in advance!

**Comment by xavcz** [comment]
You can have a look in `nova:getting-started` :)

If you want to import from CSV, you should look for some [npm package that does that](https://www.npmjs.com/search?q=csv) and then transform the data into [an object corresponding to the Posts schema](https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-posts/lib/schema.js), `title` being the only required field!

Happy hacking 🚀 📊

**Comment by atherdon** [comment]
@xavcz thank you!
