### ISSUE TITLE
Can't turn off email notifications

### ISSUE THREAD

**Issue by dominictracey** [TelescopeJS/Telescope#1580]
Out of the box the notification options are not set on the user object (`notifications_comments`, `notifications_posts`, etc.). In the Edit Account page, the checkboxes are all not set - which would seem to indicate that by default, users won't get any email notifications. To check a user's settings, you can pass in a default value that the [helper function](https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-users/lib/helpers.js#L146) will return to you if the attribute isn't present on the user in question.

Taking comment notifications as an example, the [notification callback for a new comment](https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-notifications/lib/callbacks.js#L85) passes in a default value of true. This means that if a user leaves the notification setting "Replies to my comments" unchecked, they will actually get notifications because the Users helper function returns the default 'true' for the initial state of `undefined`.

It gets worse though, because there is no way to actually turn notifications off. You can check the Account setting to true and everything works properly, but then when you uncheck "Replies to my comments", it doesn't save `false` for `notifications_comments`, it actually removes the key from the user object, getting you back to undefined yielding true.

I'm happy to create a PR for this if there is a consensus on how it should work. e.g. should all of the Notification settings be set to true for new users and the default value passed to the helper be false?

**Comment by xavcz** [comment]
Oh nice catch! 

> should all of the Notification settings be set to true for new users and the default value passed to the helper be false?

Yeah, that looks like a good way to go! 👌 Btw, we normally leverage some default settings from the json file https://github.com/TelescopeJS/Telescope/blob/master/sample_settings.json#L16

Don't hesitate to ping here, on "working-on" PR or Slack! 🎉

**Comment by dominictracey** [comment]
Ok - I'll put together a PR on this.

**Comment by xavcz** [comment]
Interesting, thanks for the walkthrough! 👍 

Maybe the `boolean` value is not caught somehow? 

To see if it's a mutation problem, you can [uncomment these lines](https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-lib/lib/server/mutations.js#L90-L94) (and also the ones at the end of the function. Else this may be a simple schema problem + the way we handle the form 🤔

**Comment by dominictracey** [comment]
This should be resolved for all intents and purposes with PR #1600. Do you wait until the commit makes it on to master to close the issue?

**Comment by SachaG** [comment]
Oh no we can close it :)
