### ISSUE TITLE
Signup feature / Several Action buttons don't work in Safari (Devel branch)

### ISSUE THREAD

**Issue by movationdesign** [TelescopeJS/Telescope#1581]
Almost none of the action buttons work in Safari (Devel branch)

Recorded a short video of how it looks on my end:

http://g.recordit.co/TwGRHKbnW4.gif

**Comment by dominictracey** [comment]
Are there errors in the browser console?

**Comment by movationdesign** [comment]
Yep, I get get this in the Safari console: 
<img width="1423" alt="screen shot 2017-03-10 at 15 28 19" src="https://cloud.githubusercontent.com/assets/14575481/23798758/472bbbc4-05a6-11e7-875f-9bd4a1374ba0.png">

**Comment by xavcz** [comment]
cc @comus

**Comment by dominictracey** [comment]
I saw this a couple of days ago. It's not just the signup feature so the issue title is a little misleading, I think the react-router Links are non-functional, right?

**Comment by movationdesign** [comment]
@dominictracey yep — edited it. However it's not everything that doesn't work. You can still click on posts and comments.

**Comment by xavcz** [comment]
Should be fixed now thanks to @comus 🎉
