### ISSUE TITLE
update a exist framework-demo example review not update immediatly

### ISSUE THREAD

**Issue by comus** [TelescopeJS/Telescope#1590]
if i edit a exist framework-demo movie recond.

such as:
![screenshot 2017-03-20 13 04 48](https://cloud.githubusercontent.com/assets/1200981/24089173/8e46010c-0d6e-11e7-8371-379d70374a15.png)

and then. name and year update immediatly, and review not.

![screenshot 2017-03-20 13 05 54](https://cloud.githubusercontent.com/assets/1200981/24089186/c5ba4968-0d6e-11e7-96a7-53d37279b1a9.png)

i know that it is about polling interval. but how to fix it? must wait several seconds to wait it get updated

refetch?

**Comment by SachaG** [comment]
I think this is because the query that loads the `review` property is the one for the `MoviesDetails` popup. But when you edit a field, that popup is not loaded. So the update can't run. 

At least, a similar problem was described here: https://github.com/apollographql/apollo-client/issues/1211

It looks like it's been fixed since, I need to look into it more.

**Comment by SachaG** [comment]
I made a quick video to show the issue: https://youtu.be/jNgQfmH0nKY

**Comment by SachaG** [comment]
Oh actually @tmeasday helped me figure it out: we were not asking for the `review` property back!

If you do this instead (`MoviesDetailsFragment` fragment) it'll work:

```
/* 

A component to configure the "edit movie" form.
Wrapped with the "withDocument" container.

*/

import React, { PropTypes, Component } from 'react';
import { Components, registerComponent, getFragment } from "meteor/nova:core";
import Movies from '../modules/collection.js';

const MoviesEditForm = props =>
  <Components.SmartForm 
    collection={Movies} 
    documentId={props.documentId}
    mutationFragment={getFragment('MoviesDetailsFragment')}
    showRemove={true}
    successCallback={document => {
      props.closeModal();
    }}
  />

registerComponent('MoviesEditForm', MoviesEditForm);
```
