### ISSUE TITLE
Unable to assign category to a post

### ISSUE THREAD

**Issue by manriquef** [TelescopeJS/Telescope#1592]
I just tested this on a vanilla install of the devel branch as of 15 minutes ago and I am unable to assign a category to the post. There appears to be no errors in the console and the mutation doesn't appear to be failing as I can edit all other fields in a post.

I am actively trying to solve this however I am still a beginner unfortunately.

**Comment by comus** [comment]
this is because recently PR i submitted: use npm simpl-schema
have some problems. but i found it. thank you

that 's the changes:

```js
Posts.addField(
  {
    fieldName: 'categories',
    fieldSchema: {
      type: Array,
      control: "checkboxgroup",
      optional: true,
      insertableBy: ['members'],
      editableBy: ['members'],
      viewableBy: ['guests'],
      form: {
        noselect: true,
        type: "bootstrap-category",
        order: 50,
        options: formProps => getCategoriesAsOptions(formProps.client),
      },
      resolveAs: 'categories: [Category]'
    }
  },
  {
    fieldName: 'categories.$',
    fieldSchema: {
      type: String,
      optional: true
    }
  }
);
```

i added a new `categories.$`. but i forgot wrap those object into an array. sorry

```js
Posts.addField([
  {
    fieldName: 'categories',
    fieldSchema: {
      type: Array,
      control: "checkboxgroup",
      optional: true,
      insertableBy: ['members'],
      editableBy: ['members'],
      viewableBy: ['guests'],
      form: {
        noselect: true,
        type: "bootstrap-category",
        order: 50,
        options: formProps => getCategoriesAsOptions(formProps.client),
      },
      resolveAs: 'categories: [Category]'
    }
  },
  {
    fieldName: 'categories.$',
    fieldSchema: {
      type: String,
      optional: true
    }
  }
]);
```

i will double check other custom fields, then i will submit a PR to solve this problem.

**Comment by xavcz** [comment]
Thanks @manriquef for reporting this bug, and thanks @comus for solving this issue! 🌮
