### ISSUE TITLE
Why is the JS bundle so big?

### ISSUE THREAD

**Issue by j-jackson** [TelescopeJS/Telescope#1594]
I was pretty excited when I read about Vulcan as it looked perfect for my application, but then I looked at the bundle size. Why is it so big? 

I know this is an issue that a lot of JS apps face but ~4.5MB seems massive for a simple app like telescope.

I tried starting from scratch by following along with the tutorial but it still ended up with around 4MB.

**Comment by SachaG** [comment]
You're right that the bundle is pretty big, but first of all the size is a lot smaller when everything is minified for production. 

Also, with the upcoming Meteor 1.5 we'll be able to use code splitting to reduce the bundle size a lot by removing things like datepickers, form elements, etc. that only need to be loaded at specific times.

**Comment by j-jackson** [comment]
Thanks for the reply!

if I run YSlow or chrome network tools on http://demo.telescopeapp.org I get 4.4 - 4.7MB of [JS](http://demo.telescopeapp.org/c8d820ab978ec2837bb2a6c5c708bc9f2cf912b0.js?meteor_js_resource=true).

I was just wondering if there was a specific package that was adding the extra weight that I might be able to remove, as most Meteor apps that I have looked at come in at around 2MB or 4 tops for much larger apps with admin dashboards etc. i.e galaxy.meteor.com is only 2.7MB with a lot of the same technologies such react,  redux, apollo etc.

Please don't think I'm not knocking Vulcan, I just want to know if there is something I can remove as I really want to use it but I think 4+ MB is way too much for any public facing site.   

A little bit off topic, but have you seen [SSRWPO](https://github.com/ssrwpo/ssr)? I have been really impressed with it so far and I know its main goal is performance so it might be worth having a look at. unfortunately it doesn't yet support Apollo  but they are [working on it](https://github.com/ssrwpo/ssr/issues/15).

**Comment by SachaG** [comment]
A better benchmark is http://sidebar.io/, which gives me 1.3MB. That demo runs a pretty old version. Also, you could also look at the size of just the core packages (i.e. the `framework-demo` package), that should already be a lot smaller. 

And yeah SSRWPO looks cool! @comus and @xavcz are in charge of all things SRR though so you'd have to ask them :)

**Comment by j-jackson** [comment]
Please correct me if I'm wrong (I'm certainly no expert!) but isn't 1.3MB cached?

Using galaxy.meteor.com as an example again:

Empty Cache: 2.7 MB
Primed Cache: 810 KB

Sidebar.io

Empty Cache: 5.3 MB
Primed Cache: 1.3 MB

I guess it is what it is, so if there isn't a simple explanation then please feel free to close the issue.

**Comment by SachaG** [comment]
This is what I get on sidebar.io with cache disabled and a hard reload: 

https://cl.ly/jeD6

But on the other hand when I download the bundle the file is 5MB… maybe 1.3 is the gzipped size? In any case we can agree it's too much! We definitely want to bring that down to a more reasonable size :)

**Comment by SachaG** [comment]
By the way, if you only keep the core packages the bundle size goes down to 3.8MB unzipped, and 829KB zipped. Still big, but better :)

**Comment by j-jackson** [comment]
@SachaG have you played with 1.5 yet? I was just reading a comment by benjamn that we can use dynamic imports in packages with `api.mainModule(file, where, { lazy: true }))`

Might be good to start thinking about how you might structure Vulcan so that non logged in users only get the absolute bare minimum.

**Comment by SachaG** [comment]
I haven't yet, but my idea was to start by lazy-loading custom forms components (datepickers, upload widgets, etc.).

**Comment by SachaG** [comment]
Btw if you'd like to take a shot at this, that'd be a huge help!

**Comment by j-jackson** [comment]
@SachaG I had a brief play with this and the 1.5 update went smoothly, however there appears to be some issues when rendering on the server when using dynamic imports. I will have another look when 1.5 hits rc.

**Comment by SachaG** [comment]
That's why I was thinking about doing it for forms, since most of them are displayed inside modals they don't need to be server-side rendered.
