### ISSUE TITLE
How to get hostname on the server?

### ISSUE THREAD

**Issue by j-jackson** [TelescopeJS/Telescope#1595]
I have a CMS style application which needs to find the current site by the hostname, but I'm having trouble working out where to do this in Vulcan.

I was thinking something like this:

1. Request comes in => http://sachagreif.com
2. Parse the url on the server => sachagreif
3. Save the hostname in redux => `{ currentSite: 'sachagreif' }`
4. Use currentSite in apollo queries 

```javascript
const SiteWithData = graphql(getUser, {
  options: (ownProps) => ({ variables: { site: ownProps.site } }),
  props: ({ data}) => ({
    data
  })
})(PostList)

export default connect(
  (state) => ({ site: state.currentSite })
)(SiteWithData)
```

Does this look ok? 

I am parsing the url in `/lib/server/render_context.js` with `req.headers.host` and have setup a `currentSite` reducer but can't figure out how to set its state from within`render_context.js`.

**Comment by comus** [comment]
this is how i set initial state on apolloReducer
https://github.com/TelescopeJS/Telescope/blob/devel/packages/vulcan-routing/lib/client/routing.jsx#L45-L52

**Comment by j-jackson** [comment]
Thanks @comus!

Not 100% sure how all this is working yet but it does work now!

```javascript
const apolloClientReducer = (state = {}, action) => {
  // console.log(initialState)
  if (initialState && initialState.apollo && !_.isEmpty(initialState.apollo.data) && _.isEmpty(state.data)) {
    state = initialState.apollo
  }
  const newState = context.apolloClient.reducer()(state, action);
  return newState;
}

const currentSiteReducer = (state = {}, action) => {
  if (initialState && initialState.currentSite && !_.isEmpty(initialState.currentSite)) {
    state = initialState.currentSite
  }
  return state
}

context.addReducer({ apollo: apolloClientReducer, currentSite: currentSiteReducer });
```
