### ISSUE TITLE
Mobile login not working Chrome, seems to hang on Safari

### ISSUE THREAD

**Issue by cloudunicorn** [TelescopeJS/Telescope#181]
Haven't been able to log in (twitter auth) at all on mobile Chrome - could be related to the tab-switching? It never goes back to telescope, and if you manually go back, you're not logged in.

Safari seems to send you back to the page but then 'loading' gif persists.

**Comment by lorensr** [comment]
For me on crater, twitter auth works in iOS Safari but not iOS Chrome

**Comment by xavcz** [comment]
Hey folks! Telescope (and Crater! 😄) have changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

Just tried this issue on both navigators on Crater, all good 🤘

The Legacy version is no longer supported, I'm closing this issue. I invite you to [check out the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
