### ISSUE TITLE
IE 11 error when you try to add comment

### ISSUE THREAD

**Issue by durukan** [TelescopeJS/Telescope#185]
I published telescope on meteor.com (http://sebebi.meteor.com) when i try to add a comment it gives the error below

browser: ie 11
app running on meteor.com
where: "var n=t.editor.exportFile();if("comment_reply"==getCurrentTemplate())"
error: "unable to get property 'exportFile' of undefined or null reference"

**Comment by xavcz** [comment]
Hey @durukan! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
