### ISSUE TITLE
subscription and Router.after problem

### ISSUE THREAD

**Issue by aykutyaman** [TelescopeJS/Telescope#186]
It seems that in router.js:
``` javascript
Router.after( function () {
  console.log(2);
  analyticsRequest(); 
});
```
callback is fired before settings subscription callback:
``` javascript
Meteor.subscribe('settings', function() {
  console.log(1);
  analyticsInit();
});
```
``` javascript
2
1
```
I think with this result, we won't have landing page analytics. 

To resolve this problem in my code I called ``` analyticsRequest(); ``` from the ``` analyticsInit() ``` in the ```analytics.js``` file.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot recently, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
