### ISSUE TITLE
New, Best and Digest for every Category?

### ISSUE THREAD

**Issue by AYLIEN** [TelescopeJS/Telescope#197]
Hi folks, thanks for sharing this great piece of software.

I've noticed that New, Best and Digest filters work for the whole board and not for individual Categories. So 2 questions: 
* Is this a complicated thing to do? 
* Is it on the roadmap by any chance?

**Comment by cerupcat** [comment]
Looking into how we might do this (since we need this feature). I think ideally the 'all' category would be the same theme for all categories. Meaning, each category would have the 'new', 'top', 'best', etc. just like 'all' does now.

**Comment by SachaG** [comment]
So right now the main obstacle to this is how routes and views work.

**Routes**: currently we have routes of the form `/category/xyz` and `/top`. To combine both, we'd need to support something like `/?category=xyz&sort=top`.

**Views**: currently, a post view takes a set of query terms and spits out query parameters, so they can't be combined. So we'd need a system where you can combine the `top` and `category` views, by chaining them for example.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot recently, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). This issue has also been fixed :octocat: 

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
