### ISSUE TITLE
Enhancement: Scripts embed template/widget

### ISSUE THREAD

**Issue by cloudunicorn** [TelescopeJS/Telescope#200]
It seems it'd be useful to have a clear spot in the code to drop scripts that need to be on every page in < head > or < body >. Presume this is what the "Extra Code" box is for? If so that's not clear and it doesn't always seem to work.

Particular wordpress scripts do this well for non-coders, might be a nice extensibility feature for Telescope.

**Comment by xavcz** [comment]
Hey, @cloudunicorn! Telescope has changed a lot recently, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! If you want to solve your problem on Nova, you can easily do it with `react-helmet` now, check where it's used (`nova:base-components`)

Happy hacking! :rocket:

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! :+1:
