### ISSUE TITLE
Uniqueness of URL

### ISSUE THREAD

**Issue by sauveregarder** [TelescopeJS/Telescope#247]
Current code validates uniqueness of url when submit post but doesn't when edit it, so what's the point?

**Comment by xavcz** [comment]
Hey, @sauveregarder! Telescope has changed a lot recently, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue (just solved it by the way 😄 ). I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! :rocket:

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! :+1:
