### ISSUE TITLE
Invites?

### ISSUE THREAD

**Issue by daviddiliberto** [TelescopeJS/Telescope#253]
Just launched an invite-only site and my users are wondering how they can share the invites they have. Currently my admin panel says they have 3 but they can not find how to find the invites in their profile settings and give to others. I am at a loss as well when i go on test accounts. Can anyone shed some light on how the invites work?

Thanks!

**Comment by jondobrowolski** [comment]
The concept of an invitation is "a written request inviting someone to go somewhere or to do something". This does not seem to currently be doing that, feels more like 'upgrade account'. I would love to be able to use it in a more intuitive manner (like some of the usage scenarios above)!

**Comment by SachaG** [comment]
This is a really old thread, I'll close it. Invites are not a huge priority right now, but I would gladly accept any PRs that improve the feature :)
