### ISSUE TITLE
Setting to disable Twitter or Facebook login

### ISSUE THREAD

**Issue by thelinuxlich** [TelescopeJS/Telescope#290]

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Like @Kikobeats pointed out, you can remove/add the accounts packages to disable/enable it. And also you'll need to edit `settings.json` to add your credentials.

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
