### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by queso** [TelescopeJS/Telescope#355]
Would you be open to making SEO improvements to the app?

So of the items would be: 

* [ ] Adding h1 or h2 tags to each link title
* [ ] Adding a meta description setting for the main page
* [ ] Setting custom titles and meta descriptions for each 'post page'
* [ ] Maybe adding a sitemap.xml option?

**Comment by delgermurun** [comment]
https://trello.com/c/dGWjDOJv/216-better-seo

SEO released, should we close it?

**Comment by SachaG** [comment]
I wanted @yourcelf to take another look first, I'll close it if he doesn't have the time.

**Comment by yourcelf** [comment]
It all looks good to me -- I just pushed a fix for #878.  I think we're good to go here with the exception of still unresolved post slugs in URLs.  Thanks @SachaG!

**Comment by queso** [comment]
This seems much better.
