### ISSUE TITLE
Add 'Site Newsletter' to user settings page

### ISSUE THREAD

**Issue by cloudunicorn** [TelescopeJS/Telescope#363]
I believe if a user clicks 'X' to hide the newsletter callout banner, they would then have no way to sign up for it in the future.

Should surface that signup persistently, as it might take use of the site to inspire signing up for the digest emails.

Thoughts?

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

And the newsletter button is now present on the user accounts page!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
