### ISSUE TITLE
Blank screen on mobile browser

### ISSUE THREAD

**Issue by Mbosco** [TelescopeJS/Telescope#364]
Loading telescope on an android phone give only a blank screen, i've tried on android 2.3 .
meteor.com loads successfully.

**Comment by SachaG** [comment]
Is this still happening?

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
