### ISSUE TITLE
Do not use throwError on server

### ISSUE THREAD

**Issue by niklasdstrom** [TelescopeJS/Telescope#373]
The throwError method is defined in client only, which creates a new error object to be displayed for the user.

In some cases it is also being used on the server which creates a 500 internal server error instead. 

Example of methods using throwError is 

````
removeComment
approvePost
unapprovePost
````

Calling method manually: 

````
Meteor.call('removeComment', 'gGxtyBXdkseE7PMAN')
Error invoking Method 'removeComment': Internal server error [500] 
````

I did some fiddling around (allowing everyone to access the edit page of a comment), and pressed the delete button. Because the methods are executed on both server and client, the correct error was displayed in an error message (but the following code did execute and i was routed to the post page). But there was an exception was thrown on the server:

````
I20140907-16:05:40.956(8)? Exception while invoking method 'removeComment' ReferenceError: throwError is not defined
````

This should instead throw a meteor error which should be caught in the client side. 

````
removeComment: function(commentId){
  var comment=Comments.findOne(commentId);
  if(canEdit(Meteor.user(), comment)){
    ...
  }else{
    throw new Meteor.Error(403, i18n.t("You don't have permission to delete this comment."));
  }
}
````

````
Meteor.call('removeComment', comment._id, function(error, result){
  if (error){
    throwError(error.reason);
  }else{
    Router.go("/posts/"+comment.postId)
    throwError("Your comment has been deleted.");
  }
});
````

This all brings another question to mind. How are error codes being handled in the app.
The numbers seem very random. Sometimes it's being used as an HTTP status code, other time its a random 6xx or 7xx error. It almost seems like its been done to get a unique error code for each error. If that is the case then they should be defined somewhere, because it will get impossible to keep track of which have been used - or what they mean.

**Comment by xavcz** [comment]
Hey @niklasdstrom! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

If you think errors should be handled differently now, feel free to reopen an issue or submit a PR 💯 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍
