### ISSUE TITLE
Could not install all the requested packages.

### ISSUE THREAD

**Issue by Sivan1525** [TelescopeJS/Telescope#388]
Hello,

I tried to install TelescopeJs in Ubuntu 12.04 and this is the error I get when I try to run meteor.

```
Refreshing package metadata. This may take a moment.
No compatible build found for sacha:juice@0.1.0
Could not install all the requested packages.

```

I did meteor update but still it is giving the same error when I run meteor

**Comment by xavcz** [comment]
Hey folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! And deployment works well with Mup2 on abernix docker image 🎐 👍 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
