### ISSUE TITLE
Voting Schema Based on Comments

### ISSUE THREAD

**Issue by arunoda** [TelescopeJS/Telescope#421]
Hi,

In Kadira Hub, I see a lot discussions. So I prefer voting algorithm takes input from the number of comments too.

Not sure that's there yet! But it's good if we could have tunable parameter. 
What do you think?

**Comment by xavcz** [comment]
Hey @arunoda, thanks for the idea! 

This issue has been lost for 2 years!! 😄  I'm closing this one and I just opened one with some guidelines here : https://github.com/TelescopeJS/Telescope/issues/1458
