### ISSUE TITLE
Comments not appearing until after a refresh

### ISSUE THREAD

**Issue by hyperperforator** [TelescopeJS/Telescope#427]
Hi!

(Sorry for yet another bug report) - comments don't seem to appear after submission until the user refreshes the entire site. I can reproduce this almost 100% of the time but not sure where to start on it. I didn't see this as a dupe so it might be unique to me.

![screenshot 2014-09-25 14 08 26](https://cloud.githubusercontent.com/assets/3075582/4398582/2f70a9b0-4459-11e4-9687-cb63ecf1a8a2.png)

**Comment by SachaG** [comment]
I *think* that's fixed? Haven't heard any complaints about it since?

**Comment by razvansky** [comment]
Hi,
I have noticed this behaviour on crater.io
I posted two comments, but in my profile I see "no comments" posted. Even after I refresh page in chrome.
![screen shot 2015-03-15 at 12 44 47](https://cloud.githubusercontent.com/assets/8016748/6655715/44fcf3f8-cb11-11e4-83da-7fae43e8a928.png)
![screen shot 2015-03-15 at 12 45 02](https://cloud.githubusercontent.com/assets/8016748/6655716/44ff466c-cb11-11e4-98bc-1034997a655c.png)

**Comment by SachaG** [comment]
That seems like a different issue, and it's probably specific to Crater. @queso any thoughts?

**Comment by queso** [comment]
Yeah, perhaps you can move this bug report over to https://github.com/meteorclub/crater.io/issues?
