### ISSUE TITLE
When no registered/no signed users click on "reply" it won't trigger anything

### ISSUE THREAD

**Issue by thinkxl** [TelescopeJS/Telescope#461]
http://cl.ly/image/2R2B0f2D0446

If I'm signed out, and click on reply it won't happen anything, I remember a window coming up that will tell me that I need to sign up.

**Comment by xavcz** [comment]
Hey @thinkxl! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
