### ISSUE TITLE
Extract email code in package

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#476]
Part of the `telescope-email` code could be extracted into its own package. Current issues preventing this:

- The `juice` package that takes care of inlining CSS contains a binary, which means it has to be compiled for each target architecture. That could prove pretty annoying if different people use different architectures. 
- The `html-to-text` NPM package that converts HTML emails to text doesn't work very well, it has a few bugs with link parsing.

**Comment by xavcz** [comment]
We are still using `juice` but the code is in its own package now 👍
