### ISSUE TITLE
Daily view sorting issue

### ISSUE THREAD

**Issue by MitjaBezensek** [TelescopeJS/Telescope#492]
I'm not sure if this is by design or not but it seems that the daily view has an issue with ordering the items. I just did a fresh clone of telescope and added some posts. I created another account to upvote one post and then I selected the daily view. As you can see the posts are now not ordered based on their score (if I switch to top view then they are).

![daily](https://cloud.githubusercontent.com/assets/2523721/4669512/ba478b64-556e-11e4-8923-9503be2ca61f.png)

As you can see the post 2 has two upvotes and is first on the list. However 9 and 6 should come before 4 and 1.

If I understand correctly this line does the sorting:
https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-daily/lib/daily.js#L14

But I guess sorting by ```postedAt```first is not correct? Also it would probably need to be ```score: -1``` instead of ```baseScore```?

**Comment by SachaG** [comment]
The code for this has changed quite a bit so I'm closing this for now.
