### ISSUE TITLE
Comments Link/Route Only Retrieves Subcomments One Level Deep

### ISSUE THREAD

**Issue by bengott** [TelescopeJS/Telescope#496]
I just noticed this while linking to a comment on crater.io and then duplicated it on my Telescope fork.

When you load a "/comments/comment_id" URL, it only shows subcomments one level deep. For example, when I tried to link to [this comment on crater.io](http://crater.io/comments/KeFvq9SP9wGWiPqCu), it only showed the 2 comments that were in direct reply to the specified comment but not the subcomments on those replies. If you then follow the link to the [parent post](http://crater.io/posts/L3JhN9WS5pJJ4FpW8) and then reload the comment post, the 2nd level of subcomments will be there. Sneaky, sneaky, Telescope. ;)

I'll try to track this one down and submit a PR sometime this week (unless somebody else beats me to it)!

**Comment by SachaG** [comment]
Oh, this makes sense actually. Each comments only knows about its parent. So if I have a thread like this:

```
A
|- B
  |- C
    |- D
```

And I'm on the page for comment B, then I can find all comments that have B as parent, which will be C. But if I want to get comment D, then I need to recursively look for comment who have comment *C* as parent, and so on…

Not sure how to fix that, apart from just getting *all* comments for that thread, but then that might take a while to load…

**Comment by SachaG** [comment]
Relevant: http://stackoverflow.com/questions/11304739/how-to-store-threaded-comments-using-mongodb-and-mongoose-for-node-js

**Comment by bengott** [comment]
Cool, thanks for the link. I still think the solution is to not have comment routes at all, only post routes with comment anchors (and inline comments!)

**Comment by bengott** [comment]
Also, I have some spare time right now, so expect a PR soon (finally!)

**Comment by SachaG** [comment]
Well, comment routes are kind of a bonus feature, I don't know that people actually use them. Except for replying, but I agree this should be done inline right on the post page. 

Also the comments roadmap has quite a few items now ;)

https://trello.com/c/GO6fIwQp/63-better-comments

**Comment by xavcz** [comment]
Hey @shtefcs! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. By the way comments can be retrieved with `http://host/post-slug#commentId` now 😄 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
