### ISSUE TITLE
iconmoon not working on windows. 

### ISSUE THREAD

**Issue by iamues** [TelescopeJS/Telescope#53]
They works great on Mac (Chrome, Firefox, Safari) not on Windows (7 and 8) with Chrome and Firefox. Any idea?

**Comment by xavcz** [comment]
Hey folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
