### ISSUE TITLE
Clarify "invited" on users admin page and add "invited" admin page

### ISSUE THREAD

**Issue by anthonymayer** [TelescopeJS/Telescope#575]
The "invited" filter on /all-users is kind of confusing. It looks like it will allow you to see users that have been invited, but actually it just lets you see users that have joined and were invited (even if they were invited after they joined, which is a whole other confusing thing). I'm not really sure what a good way of clarifying this would be, but it seems useful to do. Any ideas?

It also seems to make sense to have a separate admin view that shows all Invites and whether they converted to signed up users. It seems like it could be a handy thing and probably not that hard if it were based on similar code to the all-users.

**Comment by xavcz** [comment]
Hey @anthonymayer! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. The package invites is disabled by the way, but if you feel able to create a package for that, go for it 👯 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
