### ISSUE TITLE
How do we keep i18n files organized?

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#577]
As I add more strings to `en.i18n.json`, I expect the other languages will get more and more out of sync, making it hard to know what has been translated or not. 

What would be really great is a script or app that parses all i18n files, and then uses the English version as a master template to reorganize other languages, and fill in any missing keys. 

I'm not very familiar with i18n tools, but maybe there's already something like this out there?

**Comment by xavcz** [comment]
Hey folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. And by the way, we use packages for each language now! 🎯 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
