### ISSUE TITLE
Delay between adding a new post and the post showing on the homepage

### ISSUE THREAD

**Issue by MitjaBezensek** [TelescopeJS/Telescope#578]
It takes quite some time between adding a new link and it showing on any of the views.

**Comment by canadaduane** [comment]
Glad this has been documented and @SachaG  is on it. Thanks for keeping the issues list public and accessible. It took me a while to realize there was a pattern and I didn't do anything wrong. Another way of saying that: I'm glad I'm not crazy.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
