### ISSUE TITLE
Can't display post body in New Post notification email

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#585]
I thought [this PR](https://github.com/TelescopeJS/Telescope/commit/331f25e5938b1844f3e9007a188a46d13f56f705) fixed the issue, but it's only displaying in browser on the test route. I also tried taking out the conditional statement in the template, but that didn't work either. Let me know if I can get you more info.

**Comment by SachaG** [comment]
Are you still having this issue?

**Comment by xavcz** [comment]
Hey @jamiewilson! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
