### ISSUE TITLE
Redirect to thread when deleting comment

### ISSUE THREAD

**Issue by 57even** [TelescopeJS/Telescope#604]
When I delete my comment I should be redirected to the thread page instead of staying at the edit page for the deleted comment.

It would maybe make sense to have a link to the thread when I'm editing my comment. Otherwise yoo could have forgot what the original thread was about?

Is it decided not to have a delete button next to edit on the comments? Now I have to click edit and then delete in order to delete a comment.

**Comment by SachaG** [comment]
Fixed :)
