### ISSUE TITLE
Error: Cannot find module 'html-to-text'   How to solve it?

### ISSUE THREAD

**Issue by kopitiful** [TelescopeJS/Telescope#616]
(STDERR) /Users/.meteor/packages/meteor-tool/.1.0.36.jzr9qq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
(STDERR) 						throw(ex);
(STDERR) 						      ^
(STDERR) Error: Cannot find module 'html-to-text'
(STDERR)     at Function.Module._resolveFilename (module.js:338:15)
(STDERR)     at Function.Module._load (module.js:280:25)
(STDERR)     at Module.require (module.js:364:17)
(STDERR)     at require (module.js:380:17)
(STDERR)     at Object.Npm.require (/Users/telescope/telescope/.meteor/local/build/programs/server/boot.js:95:18)
(STDERR)     at app/Telescope/packages/telescope-email/lib/server/email.js:2:22
(STDERR)     at app/Telescope/packages/telescope-email/lib/server/email.js:97:3
(STDERR)     at /Users/telescope/telescope/.meteor/local/build/programs/server/boot.js:168:10
(STDERR)     at Array.forEach (native)
(STDERR)     at Function._.each._.forEach (/Users/.meteor/packages/meteor-tool/.1.0.36.jzr9qq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)

**Comment by xavcz** [comment]
Hey @kopitiful ! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
