### ISSUE TITLE
Google Analytics Universal Edition

### ISSUE THREAD

**Issue by fabianbaier** [TelescopeJS/Telescope#619]
Hi,

I am having problems to install the Google Analytics Tracking ID in Telescope.

I just copied&pasted the Tracking ID UA-1731XXXX-X in the related field in settings in Telescope but Google says: tracking not installed yet. 

Is there a way to get it working through a workaround like this? https://github.com/reywood/meteor-iron-router-ga

Why does including my Snippet before the /head>in the main.html not solve it?

Here is the code

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1731XXXX-X', 'auto’);
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

What I am missing?

**Comment by Sean-R** [comment]
Should be working now in the latest version by adding your Tracking ID in the admin section.

**Comment by sk4blink** [comment]
Hi I'm having the same issue. I just installed Telescope a few days ago so it should be the latest version. I added just my Google Tracking ID into the admin section and in the Google Analytics interface it still is getting reported as "Tracking Not Installed".  Any suggestions?

**Comment by jimmibond** [comment]
Did you solve this problem, facing the same problem in the version 0.24. Please update on this.

**Comment by SachaG** [comment]
@sk4blink @jimmibond what if you try the latest version? (0.25.1)
