### ISSUE TITLE
Uncaught Error: Server sent add for existing id

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#621]
When trying to add a comment on Meta:

`Uncaught Error: Server sent add for existing id`

**Comment by shtefcs** [comment]
Whats the solution for this ? We are facing same issue as u can see on screenshot below:
![](http://content.screencast.com/users/shtefcs/folders/Jing/media/ee29e5b3-3409-438a-ad85-3facd62f9d94/2015-04-20_1349.png)

Is this related cause we changed the url slug ?

**Comment by SachaG** [comment]
This seems to be related to this FastRender issue: 

https://github.com/meteorhacks/fast-render/issues/80

I'm not sure if there's a simple solution right now, but I'll look into it. Or maybe @arunoda will have a suggestion.

**Comment by xavcz** [comment]
Hey @shtefcs! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
