### ISSUE TITLE
Can not handle unicode URL

### ISSUE THREAD

**Issue by trandatnh** [TelescopeJS/Telescope#625]
This link is broken if it is redirected by telescope: http://hieuminh.org/2014/12/13/taxi-uber-bai-ho%CC%A3c-it-cho-the-gioi-hie%CC%A3n-da%CC%A3i/

Example at Telescope Meta: http://meta.telesc.pe/posts/L6JBXwtYR5eezauEz/comment/Q7NwZdMidt43vCBbZ

**Comment by delgermurun** [comment]
I guess it is fixed (at least example post works fine). Shall we close it?
