### ISSUE TITLE
Uninvited users cannot be invited again

### ISSUE THREAD

**Issue by jasperkennis** [TelescopeJS/Telescope#626]
When you invites someone from `/all-users`, then uninvite this person, and then want to invite this person again, you can't. In the console, you will see a message `someone has already invited this user`.

**Comment by xavcz** [comment]
Hey, @jasperkennis! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
