### ISSUE TITLE
Negative score on comment show's as possitive

### ISSUE THREAD

**Issue by jasperkennis** [TelescopeJS/Telescope#627]
When a comment has been downvoted to a negative score, the negative amount shows as a positive number (so without the `-`).

**Comment by jasperkennis** [comment]
That should not be too hard to solve then. I will have time to look at it at some point in the future but it won't be soon.

**Comment by jgdovin** [comment]
Sorry to re-open this but there is an easy fix for this. Changing {{upvotes}} to {{baseScore}} in the comment_item.html file where the points are listed on line 22 will make it show the actual base score instead of number of upvotes.
