### ISSUE TITLE
Bug: daily view is limited to 10 posts a day

### ISSUE THREAD

**Issue by schoensen** [TelescopeJS/Telescope#641]
daily view cannot display more than 10 posts per day (limit is set to 30 in settings). http://meta.telesc.pe/posts/4QWNrLcktqhTjHYxQ

![image](https://cloud.githubusercontent.com/assets/10222214/5473155/4b17d3ec-8607-11e4-8e76-811cf2aa4fc4.png)

**Comment by SachaG** [comment]
Fixed :)
