### ISSUE TITLE
Post list slowness?

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#646]
Since the latest layout update (with the avatars), there seems to be some lag when scrolling and displaying the post list page:

http://recordit.co/6midswj0sZ

**Comment by bengott** [comment]
I haven't looked at the code, but are you sure it's a browser rendering problem (i.e. not a waiting on subscription problem)? Either way, there's always the option of delaying the loading/showing of avatars until after initial page load...

**Comment by SachaG** [comment]
You're right, I'm not actually sure it's browser-related. I need to check it out with Kadira.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
