### ISSUE TITLE
Telescope not reloading until I clear cookies

### ISSUE THREAD

**Issue by FrequentFlyerU** [TelescopeJS/Telescope#648]
I am having an issue where if I leave Telescope open for too long, it will basically will go blank even if I reload it. Only reappears once I clear the cookies and reload.

I am not sure if it has something to do with the subscriptions expiring? Any help would be appreciated.

![travelmore](https://cloud.githubusercontent.com/assets/4107677/5516844/5da11ee8-887c-11e4-94b4-671bc310b2d4.jpg)

**Comment by xavcz** [comment]
Hey, @FrequentFlyerU! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
