### ISSUE TITLE
Usernames that has space doesn't load

### ISSUE THREAD

**Issue by oguzgelal** [TelescopeJS/Telescope#661]
For example a username "oguz gelal" resolves into "/users/oguz%2Bgelal" and it doesn't load

**Comment by splendido** [comment]
Would you guys like to remove any space within the `username`?
This is actually implemented with #728.

**Comment by SachaG** [comment]
Well, I guess we don't want `John Smith` and `John   Smith` to be two different accounts. So they should both go to `johnsmith`. That being said, the URL slug should be built off the display name, so it should be `john-smith` and not `johnsmith`.

**Comment by splendido** [comment]
Ok, so lets make this into #728!
`profile.usename` will be kept unchanged, while the actual `usename` field will be lowercased with (multiple) spaces replaced with `-`.

Ok?

**Comment by SachaG** [comment]
Sounds good! I think we can just remove spaces altogether, I was only talking about using dashes for the URL slug, not the username itself.

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
this should be fixed now since @SachaG [merged](https://github.com/TelescopeJS/Telescope/commit/31dffc58fb2e3085a703668a70c8aa51cb16334e) `lowercase-usernames` into `devel`
