### ISSUE TITLE
Search for posts by username

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#665]
Would be nice to be able to search for a username or display name and get back a list of their posts or posts they've commented on.

**Comment by jamiewilson** [comment]
Yea, so for example, if I searched `jamie` then the search results would include posts I had submitted, posts that contain my name, and posts with comments from me or that mention me. Does that make sense?

**Comment by SachaG** [comment]
Yeah, makes sense. I've opened a Trello card, so I'm closing this issue: https://trello.com/c/rQxskxJy/210-better-search
