### ISSUE TITLE
New install gives "not found" page on first load

### ISSUE THREAD

**Issue by engagr** [TelescopeJS/Telescope#666]
![screenshot 2014-12-31 15 48 37](https://cloud.githubusercontent.com/assets/5987576/5591234/ba206eae-9104-11e4-8009-e3f24b2a3e21.png)

Is this normal?

**Comment by engagr** [comment]
K. Sign in/sign up doesn't work, so essentially I can't install a new telescope app.

**Comment by SachaG** [comment]
Sign up doesn't work? What's happening exactly, any errors?

**Comment by SachaG** [comment]
Also, are you talking about master or devel?

**Comment by engagr** [comment]
Nevermind, seems to have fixed itself or be my cache. Sorry:)
