### ISSUE TITLE
Broken CSS in Safari browser

### ISSUE THREAD

**Issue by lpatmo** [TelescopeJS/Telescope#667]
Attached is a screenshot of what I'm seeing in Safari 6.0.5 on a Mac OS 10.8.5.
![screen shot 2015-01-01 at 3 10 10 pm](https://cloud.githubusercontent.com/assets/4512699/5593158/60c8fea6-91c8-11e4-92aa-9448cd89fab5.png)

**Comment by SachaG** [comment]
Since the latest version of Safari is 8 and it seems to work all right, I think we can assume whatever bug is causing this has been fixed since :)
