### ISSUE TITLE
Grey out study sessions that have already passed

### ISSUE THREAD

**Issue by lpatmo** [TelescopeJS/Telescope#670]

**Comment by SachaG** [comment]
Study sessions?

**Comment by lpatmo** [comment]
@SachaG Er, "posts." :) See: http://hangouts.codebuddies.org. Still working out some small things!

**Comment by lpatmo** [comment]
Gah, sorry! I left this on the wrong issues board. I thought I'd posted it on on my own repo.

**Comment by SachaG** [comment]
No worries :)
