### ISSUE TITLE
Mobile nav item descriptions shouldn't be bolded

### ISSUE THREAD

**Issue by anthonymayer** [TelescopeJS/Telescope#671]
Only the nav item name should be bolded, because it's kind of hard to read right now. It may also be worth adding a ":" or "-" between the item name and description, but probably not.

![screen shot 2015-01-05 at 9 18 29 am](https://cloud.githubusercontent.com/assets/829762/5610708/f7d0a56a-94bb-11e4-8a54-4f8b27457179.png)

**Comment by SachaG** [comment]
I'm pretty sure that's fixed?

**Comment by anthonymayer** [comment]
Oh yea, I hadn't pulled master. Looks like the descriptions are just gone now. Do you think it makes sense to put them back, but not bolded? Seems like it could be useful

**Comment by SachaG** [comment]
My thinking was that on mobile, you don't want to overload the UI.
Descriptions seemed a bit out of place in a menu like this.
