### ISSUE TITLE
Russian i18n seems to be translated by Google

### ISSUE THREAD

**Issue by pukhalski** [TelescopeJS/Telescope#674]
Do you need any help with that?

**Comment by SachaG** [comment]
Help would definitely be quite welcome!

**Comment by pukhalski** [comment]
@SachaG, almost ready with that. Will take another look tomorrow. Found some related bugs in different packages, so I'll put it into backlog too.

**Comment by xavcz** [comment]
Hey, @pukhalski! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs with this version.

The Legacy version is no longer supported, I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! By the way, there is a russian translation for Nova, maybe based on yours (?) https://github.com/fortunto2/nova-i18n-ru-ru

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
