### ISSUE TITLE
/out bug

### ISSUE THREAD

**Issue by jhawn** [TelescopeJS/Telescope#675]
Unfortunately a somewhat encoded post URL will fail to redirect properly as the *URL in any post* check is URL decoded. 

Example of Post's URL that causes bugs:    https://www.example.com/hello%20world.pdf

Is it really necessary to not  "redirect if we can't find a post for that link" ?

```javascript
  Router.route('/out', {
    name: 'out',
    where: 'server',
    action: function(){
      var query = this.request.query;
      if(query.url){
        var decodedUrl = decodeURIComponent(query.url);
        var post = Posts.findOne({url: decodedUrl});
        if (post) {
          var sessionId = Meteor.default_connection && Meteor.default_connection._lastSessionId ? Meteor.default_connection._lastSessionId : null;
          Meteor.call('increasePostClicks', post._id, sessionId);
          this.response.writeHead(302, {'Location': query.url});
        } else {
          // don't redirect if we can't find a post for that link
          this.response.write('Invalid URL');
        }
        this.response.end();
      }
    }
  });
```

**Comment by SachaG** [comment]
I did notice that yesterday, I need to take a look. The reason for only redirecting links that have a corresponding post is to avoid abuse, i.e. people linking to http://yourtelescopesite.com/out?url=http://spam.com

https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

**Comment by SachaG** [comment]
It's strange, apparently `query.url` was already being decoded. So calling `decodeURIComponent` is decoding it a second time, which is what's causing the problem with certain URLs. 

Maybe the automatic decoding is a feature of Iron Router?
