### ISSUE TITLE
Signing with FB on mobile browser

### ISSUE THREAD

**Issue by farukscan** [TelescopeJS/Telescope#680]
Hi
Signin with FB does not redirect to telescope demo in my mobile chrome browser.
It does work, sign me in my demo telescope account and quickly redirect to demo telescope.
But on my mobile device which is general mobile and ı use chrome, does not redirect and waits in the page that says "Login completed. Click here to close this window." Click here is a link, but clicking does not redirect it.
Thaks.

**Comment by anthonymayer** [comment]
This is a long standing mobile chrome bug that affects meteor' fb integration (https://github.com/meteor/meteor/issues/1004#issuecomment-68652474). It doesn't have anything to do with Telescope.

**Comment by carlosalvidrez** [comment]
Any workarounds?
