### ISSUE TITLE
Share In Desktop Browser

### ISSUE THREAD

**Issue by farukscan** [TelescopeJS/Telescope#681]
Hi, 
I cannot spot the Share button for various social networks, fb, twitter, linchpin, and g+, while I view Telescope demo app in Desktop Browser. I can view them in my mobile browser.

What is the reason to that. I s that an issue or just lack of  feature on Desktop intentionally left.

Thanks

**Comment by SachaG** [comment]
It's intentional, the share button was removed from the desktop view to make room for the user avatars. This seems to be causing a lot of confusion though, so maybe it was a mistake…
