### ISSUE TITLE
RSS Fetching Inproper Title

### ISSUE THREAD

**Issue by jhawn** [TelescopeJS/Telescope#682]
I love the new RSS feed feature, however it often fetches post titles with improper decoding/sanitization. 

An example title that could be fetched:

**Hello World \&#8211; Telescope\&#8217;s RSS Feed Feature**

Its a low impact, but wide spread issue.

**Comment by SachaG** [comment]
This should be fixed by https://github.com/TelescopeJS/Telescope/commit/65f30864c6e457c379b1497a265bb541b4732493
