### ISSUE TITLE
the right way to update telescope

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#683]
I know that is a question more related with `git`, but I don't see anything about it in the documentation.

What is the correct way to update Telescope to the last tagged version?

In the [documentation](http://www.telesc.pe/docs/getting-started/updating/) you are pulling from master... so tagged version is last stable version or master is correct?

**Comment by delgermurun** [comment]
I personally created `stable` branch on my fork and update using `git checkout stable && git merge vX.X.X` command.

**Comment by Kikobeats** [comment]
@delgermurun thanks!

**Comment by anthonymayer** [comment]
There's also http://www.telesc.pe/docs/getting-started/updating/
