### ISSUE TITLE
autoform omitFields and fields are not working when overwriting the template?

### ISSUE THREAD

**Issue by voidale** [TelescopeJS/Telescope#685]
I have done the following:
````
templates["post_submit"] = "newPost_submit";
<template name="newPost_submit">
    <p class="newpost-title">post a new work</p>
    <hr>
    <br>
  <div class="grid grid-module">
    {{> quickForm collection="Posts" id="submitPostForm" template="telescope" label-class="control-label" input-col-class="controls" fields="url,title"}}
  </div>
  
</template>
````
But `fields="url,title"` doesn't work no effect what so ever, Only if I change `template="bootstrap3-inline"` it works

**Comment by SachaG** [comment]
Yeah that makes sense, since the `telescope` autoform template has its own logic. What are you trying to do exactly? I would suggest trying to maybe modify the schema instead?

**Comment by voidale** [comment]
@SachaG I'm trying to have have post submit form with `title, url, submit button` only. I didn't see any examples on how to remove fields of the schema only how to add. Can you suggest how it's possible? Thanks a lot!

**Comment by SachaG** [comment]
Good point. I think the easiest way to do that would be to set `autoform.omit: true` on the fields you want to omit. I need to update the documentation on how to modify/remove fields, but basically it's just a JavaScript array so you can google "removing elements from JS arrays" or something similar. And also don't forget about [Underscore](http://underscorejs.org/) :)

**Comment by voidale** [comment]
No idea really how it should be done? 
````
  api.addFiles([
    'lib/server/collections.js',
    'remove.js'
    ], ['client', 'server']);
postSchemaObject = _.filter(postSchemaObject, function (item) {
    console.log(item)
    item.route !== "body";
});
````
Didn't work

**Comment by SachaG** [comment]
Your code looks pretty much like what I had in mind. Don't know why it didn't work…

But you're right, so far I've only considered the "add new fields" use case. I need to give it a try myself and update the documentation, if you can wait a day or two :)

**Comment by voidale** [comment]
@SachaG yes of course no hurry I actually just did my own super simple form submit template and it seems to work if anyone need it:
````
<template name="customSubmitPost">
  <div class="grid grid-module submit-new-post">
    <p class="newpost-title">post a new work</p>
    <hr>
    <br>
    
{{#autoForm collection="Posts" id="submitPostForm" type="method" meteormethod="submitPost"}}
    <div class="no-fieldset">
  <div class="form-group {{#if afFieldIsInvalid name='title'}}has-error{{/if}}">
    <label class="control-label">{{afFieldLabelText name='title'}}</label>
    {{> afFieldInput name='title' placeholder="WORK NAME"}}
    {{#if afFieldIsInvalid name='title'}}
    <span class="help-block">{{{afFieldMessage name='title'}}}</span>
    {{/if}}
  </div>
  <div class="form-group {{#if afFieldIsInvalid name='url'}}has-error{{/if}}">
    <label class="control-label">{{afFieldLabelText name='url'}}</label>
    {{> afFieldInput name='url' placeholder="WORK URL"}}
    {{#if afFieldIsInvalid name='url'}}
    <span class="help-block">{{{afFieldMessage name='url'}}}</span>
    {{/if}}
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">SUBMIT</button>
  </div>
    </div>
{{/autoForm}}
 </div>
</template>
````

**Comment by SachaG** [comment]
So actually you can't really remove fields from the schema, but you can tell Autoform to omit them from the form pretty easily by overwriting the whole property and adding `omit: true`: 

```js
addToPostSchema.push(
  {
    propertyName: 'url',
    propertySchema: {
      type: String,
      label: "URL",
      optional: true,
      autoform: {
        editable: true,
        type: "bootstrap-url",
        omit: true
      }
    }
  }
);
```

**Comment by voidale** [comment]
@SachaG  Huh! This is super awesome... solves all the problems. I didn't even think on trying it didn't know if will overwrite? Amazing :)

**Comment by SachaG** [comment]
Haha, I didn't think about it either until right now :)

**Comment by voidale** [comment]
Can't seem to to enable placeholders `placeholder="schemaLabel"` 

`{{> quickForm collection="Posts" id="submitPostForm" template="telescope" label-class="control-label" input-col-class="controls" type="method" meteormethod="submitPost" placeholder="schemaLabel"}}` for my understanding it can't be done right now

**Comment by SachaG** [comment]
Hmm, it's possible the custom template I made doesn't support that option. I don't know how useful it would be to simply repeat the label text as a placeholder though?
