### ISSUE TITLE
matb33:collection-hooks > overcoding?

### ISSUE THREAD

**Issue by comerc** [TelescopeJS/Telescope#687]
For example, you may use true way instead Posts.before.update
```coffee
  htmlBody:
    autoValue: ->
      if (Meteor.isServer)
        return sanitize(marked(@field("body").value))
```
AutoForm have more possibilities.

**Comment by SachaG** [comment]
Good point. I haven't looked too much into autoValue yet, but it would make sense.

**Comment by xavcz** [comment]
Hey, @comerc! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on it.

The Legacy version is no longer supported, I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
