### ISSUE TITLE
determinate user in post from feeds

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#690]
I want to use post from feed with a determinate account. So I created and account and added the feeds, but strangely the posts are created with my original account (the user #1).

Would be amazing (and easy) be able to define the user associated with feeds posts.

.cc @delgermurun @SachaG

**Comment by SachaG** [comment]
I agree that would be a nice feature. I think ideally each feed should be able to have its own user.

**Comment by SachaG** [comment]
Done :)
