### ISSUE TITLE
lowerCase/UpperCase in login

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#691]
I detect that if you are registered with `kikobeats` and try to make login with `Kikobeats` the login basically failed. 

So I want to improve the login experience. For example, in mobile is very common auto-capitalize the first letter. Some popular services as Facebook use a effective UX login experience:

```
Password: aBcDeF123
Works:    AbCdEf123  // Flipped Case
Works:    ABcDeF123  // Caps First Char
Doesnt:   ABCDEF123  // Mixed Case
Doesnt:   AbCdEf!@#  // Shifted Numbers
```
more information [here](http://security.stackexchange.com/a/68014). I think that can be easy to implemente with [humanize](https://github.com/HubSpot/humanize) package for try combination or simply when mongo save the user do it in `lowerCase` and define a differently between the name in the database and the name in the website.

In other order of things, trim spaces left and right can be easy and useful of remove with [trim](https://www.npmjs.com/package/trim) package.

What is your opinion?

**Comment by splendido** [comment]
Hi @Kikobeats,
I remember the discussion about case sensitive username input is an old one...
See for example #405.

Btw, Telescope uses [useraccounts](https://github.com/meteor-useraccounts/core) for the user accounts UI.
And with useraccounts you can setup the input field to be *lowercased* as well as *trimmed* (see the options for [form field configuration](https://github.com/meteor-useraccounts/core#form-fields-configuration)).
Lets have a look at the  [current configuration](https://github.com/TelescopeJS/Telescope/blob/master/lib/config/at_config.js)

So we can just change the current settings if there's enough agreement on this.
...or you might think to change them on your deployed fork if you wish.

While, about accepting different mixed case, I guess this is a more sensible discussion...
Should we consider this as an additional plug-in package for useraccounts@2.0? (...I'm going to start it soon)
This way anyone interested to enable it could simply add another package to his own fork of Telescope.

Thoughts?

**Comment by Kikobeats** [comment]
oh, nice!

Maybe enable `lowercase` is more controversial, but why not enable `trim` in username?

Personally I will enable `lowercase` in my fork.

on the other hand the idea of account plugin package for mixed case sound amazing. If is possible to resolve like a plugin package you have my vote :-)

**Comment by splendido** [comment]
Yeah, I also agree on the `trim`.
@SachaG are you with us?

**Comment by splendido** [comment]
@Kikobeats, to enable the lower case on your fork this should be put on a file shared between the client and the server:

```javascript
AccountsTemplates.removeField('username');
AccountsTemplates.addField({
    _id: 'username',
    type: 'text',
    displayName: 'username',
    required: true,
    minLength: 3,
    errStr: 'error.minChar',
    trim: true,
    lowercase: true
});
```

this should be enough to overwrite the *default* Telescoe settings...

Let me know in case you decide to give it a go!

**Comment by SachaG** [comment]
Yes, I agree. PR welcome :)

**Comment by Kikobeats** [comment]
@SachaG only trim or lowercase too? :-)

**Comment by SachaG** [comment]
I think both are good?

**Comment by Kikobeats** [comment]
GOTO #696

**Comment by splendido** [comment]
well done, tnx!

**Comment by Kikobeats** [comment]
hmmm I'm feeling that is now working. I'm trying to SigIn in a fresh clone of this repository after register an user and doesn't work correctly. What's happens?

**Comment by splendido** [comment]
...I think we'd need some more info ;-)

Btw I'll try to test it out too

**Comment by Kikobeats** [comment]
The better make to explain is with an example. I have a telescope in production with the last commit :-)

Let's go to sign-in form => http://zombts.com/sign-in

my account is registered in lowercase in the database. I'm trying to make login with my username alternating lower and upper case, but the text isn't transformed (the same happens with spaces).

now lets go to signup up => http://zombts.com/sign-up

now yes, If I put my username with trim or uppercase automatically is converted into lowercase. works! 

In the email field I make the some, but only works with uppercase combination. If you put a space but the text in lowercase nothing happens.

**Comment by splendido** [comment]
Ok, thanks for the detailed report.
...I guess the thing is I forgot to mention the `username_and_email` field is used on the sign-in page in place of the two `username` and `email`  ones (see [here](https://github.com/meteor-useraccounts/core#special-fields-ids)) and if you don't specify it it is automatically added in the background...

We should add an explicit configuration for it too...
and I'd say to set lowercase and trim to true for the email field too to prevent problems...

**Comment by splendido** [comment]
[This](https://github.com/meteor-useraccounts/core#login-with-username-or-email) is the official example for a complete configuration to allow login with username or email.

Could you please renew the PR to specify coherent configuration options for all the three fields?

**Comment by Kikobeats** [comment]
the PR is merged, is necessary create another one. Can you do it with the same  configuration for sign in and sign up endpoints? :-)

**Comment by SachaG** [comment]
Just wanted to say thanks to both of you for taking the lead on this :)

**Comment by splendido** [comment]
it's a pleasure @SachaG ;)

...reasoning a bit more on this:
- it would be an easy fix and I could commit the update right now, after a bit of testing...
- but I think it **might be a risky change** for already deployed apps to be updated later on

Suppose you already have an instance of Telescope deployed somewhere, you already have users and a bit of traffic...
Then you decide to update to the latest version!

...at this point all already existing user having usernames using UpperCase letters will no more able to login. **But this could be easily fixed with some dedicated migration procedure!**

but what if two conflicting usernames like `userName` and `Username` already exist??
**In this case the migration procedure will fail hitting an index error on mongo!**
and in no way you could solve this but deleting one out of the two accounts :(
...I appreciate this would be a very remote possibility, but likely to show up at the first run as for the Murphy's law ;-)

Does this makes sense guys?

**Comment by Kikobeats** [comment]
@splendido we have legacy code! :P

what do you think try to do the migration process and throw an exception if exists a conflict that must be resolved manually? like `git merge` command.

**Comment by splendido** [comment]
...the exception in this case would be unfixable though!

@SachaG would you prepare the migration procedure if I commit the new configuration an provide  a draft for the update query?

**Comment by SachaG** [comment]
Yeah I can do the migration. If it fails because of duplicate usernames I guess we'll just have to tell people to fix it manually in the DB…

**Comment by splendido** [comment]
Ok, I'll have a look at this in a few hours!

**Comment by splendido** [comment]
I've just pushed a couple of commits to the new branch [lowercase-usernames](https://github.com/TelescopeJS/Telescope/tree/lowercase-usernames).

This is a sample log I got playing a bit with the usernames; there were a 'Pippo' and a 'pippo' other than the initial ones:

```shell
//----------------------------------------------------------------------//
//------------//    Starting updateUserNames Migration    //-----------//
//----------------------------------------------------------------------//
> Found 5 users.

> Updating user KZTWn2DKnRtLQAMqd (Julia -> julia)
> Updating user FsobZZyg9RBe5nHFs (Arnold -> arnold)
> Updating user bfnRE2AmHMK8X7jpN (Pippo -> pippo)
(STDERR) > Unable to convert username Pippo to lowercase!
(STDERR) > Please try to fix it by hands!! :(
> Updating user L3smrbsgZMAWhieXm (pippo -> pippo)
> Updating user Wn6fGa9tisszi4Rrf (Bruce -> bruce)
//----------------------------------------------------------------------//
//------------//     Ending updateUserNames Migration     //-----------//
//----------------------------------------------------------------------//
```

So the migration seems to work! :)
...do you think the warning message is fine, or do we need something more explicative like
`The user will not be able to login from now on, please fix it by hands contacting him to select a new username...`


Ok, so far so good...

The bad news is the `lowercase` and `trim` options are currently disregarded on the sign in page (by purpose I think, even if now I don't remember the reason for this...).
...this also explain why @Kikobeats is experiencing this *weird* inconsistency between the two forms. ;-)

So before merging this I'll need to change `useraccounts:core` to get the two transforms working also on the sign in page.
Nothing too difficult, but I'm a bit out of spare time these days...


Do we risk somethig embarassing having already merged #696?
...new registration will be trimmed/lowercased but then not enforced during sign in.
I hope this merge was not included in the lates release.


Ok, so please hold on a little more on this, while I bump a new version of useraccounts.

**Comment by SachaG** [comment]
I'll revert #696 for now, this way we can take our time with this issue :)

**Comment by SachaG** [comment]
@splendido should I make a PR with the branch you

**Comment by splendido** [comment]
you mean to merge #696 on the `lowercase-usernames` branch?

**Comment by SachaG** [comment]
Oh, I meant make a PR of the lowercase-usernames branch and merge it on devel? Or will you make a PR (or merge it) yourself when it's ready?

**Comment by splendido** [comment]
yeah, I'll make it as soon as I manage to change the logic inside AccountsTemplates and release a new version for it.
I'd say not to merge it on devel until I have a new version published for AT ;-)

**Comment by splendido** [comment]
this should be fixed now since @SachaG [merged](https://github.com/TelescopeJS/Telescope/commit/31dffc58fb2e3085a703668a70c8aa51cb16334e) `lowercase-usernames` into `devel`
