### ISSUE TITLE
/out route issue when using 4-letter TLDs for siteUrl

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#692]
Not sure if this is an IR bug or a Telescope bug, but you can see it in the browser console (note the missing "b" in "club"):

```js
Router.routes['out'].url({},{query: {url: 'http://foo.com'}, host: "http://bar.club"});
> http://bar.clu/out?url=http%3A%2F%2Ffoo.com
```

Works fine if we leave `host` out though:

```js
Router.routes['out'].url({},{query: {url: 'http://foo.com'}});
> http://bar.club/out?url=http%3A%2F%2Ffoo.com
```

/cc @anthonymayer

**Comment by anthonymayer** [comment]
Looks like the problem isn't because of the 4-letter TLD, it's because the / is missing on the host.

**Comment by SachaG** [comment]
Yeah it does seem related to the missing `/`. Now that we change `Meteor.absoluteUrl` on startup though we can probably leave out `host` anyway?

**Comment by anthonymayer** [comment]
Looks like you already took care of it on https://github.com/TelescopeJS/Telescope/commit/c2118954b21fa3e625f7faaebb1ef6010ac998c6 :)
