### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#695]
I'm trying to lift in production with SSL. HTTPS Power!

First, I'm using a local proxy an create a domain certificate, but wss doesn't pass of the handhsake step:

```
WebSocket connection to 'wss://localhost:8888/sockjs/054/pey5sqy_/websocket' failed: Connection closed before receiving a handshake response
```

Secondly, in console have some error messages because gravatar response is in HTTP and break the HTTPS schema:

````
Mixed Content: The page at 'https://localhost:8888/' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/RANDOMCODE'. This content should also be served over HTTPS.
```

so, I have two questions:

* why not support gravatar https natively, or depending of the website protocol (like third parties scripts).
* the problem with wss handshake is for gravatar unsecured, or is not related? how to fix?

**Comment by SachaG** [comment]
The gravatar thing seems like it should be handled by the avatar package. Maybe @bengott will have some feedback?

And I'm not sure about the wss thing, I've never ran into it before. Maybe it's a common problem Meteor apps have? Or it comes from running the site locally?

**Comment by Kikobeats** [comment]
I'm trying to set up first in local, first need to [use avatar images under https](https://github.com/bengott/meteor-avatar/pull/39) independent of the protocol of the app (really I think that I'm a circle; I don't have https because images are not securized and images are not securized because I don't have https).

I will comment about wss experience when first fix this :-)

**Comment by mcauthorn** [comment]
Here is a potentially relevant thread from SO on wss proxying and SSL (hopefully you're using nginx, if not consider making the switch :)

http://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss

For the gravatar portion it seems that the package supports options, including an URL override that can enable SSL: https://github.com/bengott/meteor-avatar

Hope this helps.

**Comment by famousky** [comment]
@Kikobeats is SSL still give you issues?

**Comment by Kikobeats** [comment]
avatars are under https, but I'm not worked more in this... you can do it :-)

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. By the way, SSL works like a charm now 😄 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
