### ISSUE TITLE
Change SignIn/SignUp for Register/SigIn

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#697]
I feel that "SigIn" and "SignUp" are very confusing. 

So I read [this article](http://blog.codinghorror.com/the-god-login/) and basically this is a little table resume about this:

![](http://i.imgur.com/2UNwCSo.png)

I want to change this in my fork and make more easy for the user. Do you like to change it in the telescope project?

**Comment by splendido** [comment]
Lets see what the community think about this ;-)

...for your fork you might have a look at [customizing the button texts](https://github.com/meteor-useraccounts/core#button-text)

**Comment by splendido** [comment]
mmm...,
actually the AT forms already use register/sign in.

is it so only a problem with the nav bar?

**Comment by SachaG** [comment]
I think it's a good change too :+1:

**Comment by Kikobeats** [comment]
@splendido  About this, Can I change only the HTML or is necessary another change to implement it?

**Comment by splendido** [comment]
If you're referring to the nav bar, I guess it's only the text displayed there.
...is it picked up from [this line](https://github.com/TelescopeJS/Telescope/blob/master/client/views/nav/user_menu.html#L15)?
Se perhaps it's only the i18n file to be updated?

...pushing it further on, we could set up the sign up route [here](https://github.com/TelescopeJS/Telescope/blob/master/lib/config/at_config.js#L48) to get the `/register` path:

```javascript
AccountsTemplates.configureRoute('signUp', {
    path: '/register',
});
```

**Comment by Kikobeats** [comment]
@splendido PR in #722 with the changes :-)

**Comment by splendido** [comment]
Lets see the comment about register/registering there.
...Btw, I'm not native English

**Comment by SachaG** [comment]
Done :)
