### ISSUE TITLE
I need login to Crater.io with Github and Meteor accounts

### ISSUE THREAD

**Issue by comerc** [TelescopeJS/Telescope#698]
Because site for this people.

**Comment by queso** [comment]
I agree, but every time I add a package it becomes a pain when syncing upstream later... I will see what I can do about it tonight.

**Comment by SachaG** [comment]
@queso is it really that bad? I wish there was something we could do about it… Meteor should just let you have more than one `packages` file…

**Comment by queso** [comment]
*shrug* Perhaps it is a mental block for me, I hate dealing with conflicts, you end up with a huge list of changes you know nothing about to fix one file...

**Comment by SachaG** [comment]
Although actually I was just talking about @splendido about this issue. A solution could be having packages for all login methods present, but individually enabling/disabling each one through the Telescope admin. If nothing else, an easy solution would be just using `display:none` to show/hide them. 

I assume that wouldn't add *that* much extra weight to the app?

**Comment by queso** [comment]
I think that would be great.

**Comment by splendido** [comment]
I'm quite sure only social buttons for cofigured services are shown.
So I'd say we could ship an `server/lib/config/accounts.js` file (or whatever) which look like [this one](https://github.com/meteor-useraccounts/boilerplates/blob/master/semantic-ui/server/lib/config/accounts.js) (actually considering [this](https://github.com/meteor-useraccounts/core#3rd-party-login-services-configuration) is a better form using the upsert...) 

and as soon as people put in service keys, social login buttons should pop up in the login form.
This would require to ship telescope with all needed `accounts-<service>` packages already in list.

What do you think about this?
