### ISSUE TITLE
Sign-up not working

### ISSUE THREAD

**Issue by obvio171** [TelescopeJS/Telescope#701]
When I try to create a user at http://news.vr101.org, this is what happens:

1. I fill out username, email, and password
2. I click "Register"
3. Facebook/Twitter login buttons go blank/gray (no text) and nothing else happens

![vr_news](https://cloud.githubusercontent.com/assets/4315/5789823/7d0aa2cc-9e61-11e4-9a14-11a447d113e0.png)

4. On the server, I get this error:

```
[Sat Jan 17 2015 14:17:02 GMT+0000 (UTC)] INFO //////// sending email…
[Sat Jan 17 2015 14:17:02 GMT+0000 (UTC)] INFO from: example@vr101.org
to: example@example.com
subject: [VR News] New user account: example@example.com
[Sat Jan 17 2015 14:17:02 GMT+0000 (UTC)] INFO Exception while invoking method
'ATCreateUserServer' URIError: URI malformed
at decodeURIComponent (native)
at Url.parse (url.js:185:19)
at Object.urlParse [as parse] (url.js:101:5)
at makePool (packages/email/email.js:9:1)
at packages/email/email.js:50:1
at Object.AppConfig.configurePackage
(packages/application-configuration/config.js:120:1)
at getPool (packages/email/email.js:43:1)
at Object.Email.send (packages/email/email.js:166:1)
at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:9:1)
at sendEmail (packages/telescope-email/lib/server/email.js:79:1)
```

5. Checking the database reveals that the user was not in fact created.

Any idea how I could fix this? Thanks a lot!

**Comment by splendido** [comment]
It seems you're getting an error while sending out an email.
Have you checked your `MAIL_URL`?
What if you don't set it?

**Comment by obvio171** [comment]
Ah, I had set it, but it was malformed. Had to change a `@` in the username into a `%40`. But now I get this:

```
subject: [VR News] New user account: testaccount
[Sun Jan 18 2015 00:54:37 GMT+0000 (UTC)] INFO Exception while invoking method
'ATCreateUserServer' ReferenceError: MailChimpOptions is not defined
at addToMailChimpList
(packages/telescope-newsletter/lib/server/mailchimp.js:96:1)
at subscribeUserOnCreation
(packages/telescope-newsletter/lib/newsletter.js:176:1)
at app/server/users.js:45:12
at Array.reduce (native)
at Meteor.methods.changeEmail.Meteor.users.update.$set.emails.address
(app/server/users.js:43:31)
at Object.Accounts.insertUserDoc
(packages/accounts-base/accounts_server.js:1024:1)
at createUser (packages/accounts-password/password_server.js:693:1)
at Object.Accounts.createUser
(packages/accounts-password/password_server.js:751:1)
at [object Object].Meteor.methods.ATCreateUserServer
(packages/useraccounts:core/lib/methods.js:66:1)
at [object Object].methodMap.(anonymous function)
(packages/meteorhacks:kadira/lib/hijack/wrap_session.js:182:1)
```

It says `MailChimpOptions is not defined`, but these settings are configured, I've double-checked the Mailchimp API key and list ID and everything is fine. Is there anything else I can do to track this down? Thanks!

**Comment by SachaG** [comment]
This is probably a temporary bug, new release coming soon :)

**Comment by obvio171** [comment]
Cool, thanks! Will try it out and report back. Any particular commit I can merge in to test?

**Comment by splendido** [comment]
Any news about this @obvio171?

**Comment by obvio171** [comment]
It's working now, thanks =)

Don't know if I should create a new issue for this, but I noticed that even when the instance is configured to autosubscribe new users to the newsletter, they still get the banner asking them to subscribe. If they click the 'x' and then later get an email, they might be confused.

**Comment by SachaG** [comment]
Yes, please create a new issue about this :)

**Comment by splendido** [comment]
Ok, thanks @obvio171 for reporting back!
I'm closing this here then...
