### ISSUE TITLE
Minor tweak to git clone url may be needed in install docs

### ISSUE THREAD

**Issue by mcauthorn** [TelescopeJS/Telescope#703]
Hi: In the install portion of the documentation the git clone command looks like:

    git clone git@github.com:TelescopeJS/Telescope.git

...Which results in:

    Cloning into Telescope... 
    Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
    Permission denied (publickey).
    fatal: The remote end hung up unexpectedly

A more universally friendly clone URL is found in the git repo's sidebar and looks like:

    git clone https://github.com/TelescopeJS/Telescope.git

Thanks for the project, it's really useful!

**Comment by SachaG** [comment]
Good point!

**Comment by mcauthorn** [comment]
Sacha: just submitted a pull request for this - fixed the line. I'm not sure it saves you any time but I wanted to give it a shot anyhow (pls. check my pull request - first one in a while).

**Comment by anthonymayer** [comment]
Fixed by https://github.com/TelescopeJS/Telescope-Homepage/pull/11

**Comment by SachaG** [comment]
Thanks!
