### ISSUE TITLE
Admin's Settings page not working

### ISSUE THREAD

**Issue by alanmeira** [TelescopeJS/Telescope#709]
When I try to access the /settings page, I get a recursion error, with the first user (with admin rights). I tried it in master, devel, v0.13.0rc and v.0.12.0 and the same error happened in all of them. Can't get through this only with the basic installation proccess. Any idea?

Nothing show up in the server log.

Live test:
http://trindade.meteor.com
user/pass: alan/12345678

**Comment by SachaG** [comment]
Are you using Firefox? This is probably this error: https://github.com/aldeed/meteor-autoform/issues/333

(btw, try to avoid pasting super-long blocks of texts, if you need to you can link to a gist instead :)

**Comment by alanmeira** [comment]
Exactly this. Long discussion but it seems that the fix is coming up. Thanks Sacha! Great work with telescope!
