### ISSUE TITLE
Pause Embedly videos when is hidden

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#710]
I was talking with @SachaG about this issue. Embedly video integration is nice, but unfortunately, If you are playing a video and hide it without pausing first the video is playing in the background.

The video is an iframe, and depend of the provider of the video is different the way how to pause the video.

For example, with Youtube videos, you need to add `?enablejsapi=1` parameter in the video URL and do [a little of magic with JavaScript](http://stackoverflow.com/a/8668741). The worst of this is that is not a general solution: only works with Youtube.

So, I posted here for try to search a solution. Any idea?

**Comment by Kikobeats** [comment]
I checked Embedly Github and I found [player.js](https://github.com/embedly/player.js) library for do this. Working in integration with Telescope :-)

**Comment by SachaG** [comment]
Nice :)

**Comment by jasonwhat** [comment]
This problem also occurs on mobile and I noticed that the video doesn't scale for mobile in any way (this is true of all embed pop-ups) so there is no "X" close button. If a user can find a bit of space between the embed and edge of browser they can click and video will close, but keep playing, as happens on desktop.

**Comment by ladislavsulc** [comment]
Hi guys, how is this issue going on please? Did anybody find / fixed the bug? The video from Embedly source plays in the background after closing and it is not fully responsive as well. Thank you.

**Comment by SachaG** [comment]
This will be fixed in the next release, it's already fixed on the `devel` branch.

**Comment by ladislavsulc** [comment]
Thanks a lot! You did an amazing job on this app ;)

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. And well, it has been fixed for a while 😄 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
