### ISSUE TITLE
Whitespace not being trimmed from email/username when signing in

### ISSUE THREAD

**Issue by anthonymayer** [TelescopeJS/Telescope#723]
I thought this might have to do with http://github.com/meteor-useraccounts/core, but I tried on one of their demo sites and didn't run into the issue. I'll do some more digging to see where it's coming from.

**Comment by splendido** [comment]
This was somehow discussed in #691 and is actually in phase of implementation on the [lowercase-usernames](https://github.com/TelescopeJS/Telescope/tree/lowercase-usernames) branch

**Comment by splendido** [comment]
this should be fixed now since @SachaG [merged](https://github.com/TelescopeJS/Telescope/commit/31dffc58fb2e3085a703668a70c8aa51cb16334e) `lowercase-usernames` into `devel`
