### ISSUE TITLE
Add a contribution guide to the README

### ISSUE THREAD

**Issue by anthonymayer** [TelescopeJS/Telescope#727]
Or at least a link and then update the contribution guide on http://www.telesc.pe/contribute. @SachaG: What do you prefer?

Things to include:
- Pull requests should be submitted against devel NOT master
- Notes about testing(link to https://github.com/TelescopeJS/Telescope/wiki/Testing or move that to telesc.pe too). Should talk about travis too.
- Style guidelines? (maybe mention .editorconfig)
- Preference for adding new features to packages
- i18n

Anything else?

**Comment by xavcz** [comment]
Hey @anthonymayer! I updated the contributing.md with most of your recommendations 😄  As travis and eslint are broken by now, it will need some updates soon!

Thanks man!
