### ISSUE TITLE
when i build the app on the android device,why it occoured "We're sorry; whatever you were looking for isn't here"

### ISSUE THREAD

**Issue by quickj** [TelescopeJS/Telescope#730]
It is nomal on the browser even on the mobile browser.Before i update the meteor, i have successfully build the app couple times,it was ok. Now the app just launch the structure with the "not found" content. 
somebody have any solution?

**Comment by xavcz** [comment]
Hey, @quickj! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
