### ISSUE TITLE
$gte function and other functions not working in Posts.find when trying to get a subset of posts based off a condition

### ISSUE THREAD

**Issue by molleman** [TelescopeJS/Telescope#731]
Trying to use $gte function when selecting posts from the client side does not seem to work.

for example when i call `Posts.find({commentCount: {$gte: 1}}); ` from within the browser console,

posts are being returned which have a commentCount equal to 0.

But when i call this in the mongo console server side it works.

**Comment by SachaG** [comment]
I just tried that (`Posts.find({commentCount: {$gte:1}}).count()`) in my browser console and it seemed to work fine. Could you link to a live example of this issue?

**Comment by xavcz** [comment]
Hey, @molleman! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
