### ISSUE TITLE
Prevent multiple emails from being sent about the same comment

### ISSUE THREAD

**Issue by lorensr** [TelescopeJS/Telescope#737]
Eg in crater.io I have both of these checked (default state):

 Comments on my posts
 Replies to my comments

When someone replies to a comment I wrote on my post, I get two emails. One would be preferable.

**Comment by SachaG** [comment]
Yes, I need to look into that.

**Comment by SachaG** [comment]
Today's lesson: don't mix up `&&` and `||` ;)

**Comment by lorensr** [comment]
Haha, you had the right comment and everything!
