### ISSUE TITLE
Post Default Errors

### ISSUE THREAD

**Issue by NerdSauce** [TelescopeJS/Telescope#739]
Installed Telescope for the first time today and everything seems to be working except for on my home page nothing loads and it reads:

"Couldn't find a template named "posts_default" or "postsDefault". Are you sure you defined it?"

When I hit view and try the different categories such as mydomain.com/daily they all work but no matter what I set my default view to the homepage simply reads the error about posts_default

**Comment by SachaG** [comment]
Did you customize any part of your app's code?

**Comment by NerdSauce** [comment]
Nope - the only thing I've done any differently than the default instructions was running it on port 80 via the command:

sudo meteor --port 80

**Comment by SachaG** [comment]
What if you run it with just the usual `meteor` command?

**Comment by xavcz** [comment]
Hey, @NerdSauce! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
