### ISSUE TITLE
Newsletter (MailChimp) link not working quite right

### ISSUE THREAD

**Issue by shrop** [TelescopeJS/Telescope#742]
The link `Change your notifications settings` isn't working on crater.io. @queso thinks it is a bug.

The link goes to http://crater.io/account, where you get a `not found` error.

See screenshots below:

1. Email newsletter screenshot
<img src="https://www.evernote.com/shard/s1/sh/97ad188b-71e2-4dd0-9d02-342a864c66d0/d4d9404fd64e78fed068b7e287da2da7/deep/0/telescope-mailchimp-notifications-settings-link.png" alt="telescope%20mailchimp%20notifications%20settings%20link" />

2. http://crater.io/account destination from newsletter link
<img src="https://www.evernote.com/shard/s1/sh/0fd36afb-98fb-4338-afce-96c7068cb68d/64e3d30e547e4818d8730835552eb6dc/deep/0/Banners-and-Alerts-and-Loading....png" alt="Banners%20and%20Alerts%20and%20Loading..." />

**Comment by SachaG** [comment]
Yes, I think the /account route is gone, it should be brought back.

**Comment by anthonymayer** [comment]
Yea, I got rid of it in https://github.com/TelescopeJS/Telescope/pull/581/files, because I didn't realize we link to it externally. The email links could also just be updated to point at the user's profile. Then the route doesn't need to be updated. I'm fine if the route comes back to, just suggesting it as an alternative.

**Comment by SachaG** [comment]
Yeah but that makes the email generation logic more complex. I think it's
always better to have a general /account route anyway, for support reason
(i.e. saying "go to telescope.com/account" rather than "go to
telescope.com/user/xyz, where xyz is your username, which you can find out
by… etc.").

**Comment by anthonymayer** [comment]
yea, sounds good to me
