### ISSUE TITLE
i18n: Can not select the languages.

### ISSUE THREAD

**Issue by tvvocold** [TelescopeJS/Telescope#743]
Can not select the languages In http://localhost:3000/settings.

I had set the right route value in project-tap.i18n and restart app still cannot see any languages,here is my project-tap.i18n: 
```
{
    "helper_name": "_",
    "supported_languages": ["zh-CN"],
    "i18n_files_route": "/tap-i18n",
    "cdn_path": null
}
```
and my tap-i18n folder:
```
├── tap-i18n
│   └── zh-CN.i18n.json
```
and my package.json:
```
Package.on_use(function (api) {
  api.use(["tap:i18n@1.0.7"], ["client", "server"]);

  .
  .
  .

  // You must load your package's package-tap.i18n before you load any
  // template
  api.add_files("project-tap.i18n", ["client", "server"]);

  // Templates loads (if any)

  // List your languages files so Meteor will watch them and rebuild your
  // package as they change.
  // You must load the languages files after you load your templates -
  // otherwise the templates won't have the i18n capabilities (unless
  // you'll register them with tap-i18n yourself, see below).
  api.add_files([
    "tap-i18n/zh-CN.i18n.json",
  ], ["client", "server"]);
});
```
Why and how to fix?

**Comment by SachaG** [comment]
Sorry about that, let me know if it's fixed (if you pull the latest `master` branch).

**Comment by tvvocold** [comment]
BTW, if users do a $meteor deploy then untar the file, the i18n files seems got wrong path value, Maybe it's another reason?
FYI: https://github.com/tutaslabs/openshift-meteor-telescope/issues/1

**Comment by SachaG** [comment]
Untar what file? Sorry I'm really not familiar with openshift…

**Comment by tvvocold** [comment]
Sry,i mean after tar  the bundle file, the i18n files got wrong path value in [github](https://github.com/tutaslabs/openshift-meteor-telescope).
FYI: http://www.tutas-labs.com/deploying-meteor-applications-to-openshift-paas/
