### ISSUE TITLE
Why the  reset  password email come from Meteor Accounts?

### ISSUE THREAD

**Issue by tvvocold** [TelescopeJS/Telescope#745]
Why the Meteor Accounts (no-reply@meteor.com) send the reset passwd email even i set the email/mailURL value to my own(Mailgun).

FYI: here is the setting: 
```
smtp://postmaster@www.domain.org:mypasswd@smtp.mailgun.org:587/
```
and i had restart the App.

**Comment by SachaG** [comment]
Duplicate of #480
