### ISSUE TITLE
Add a ban feature (not just delete or make admin)?

### ISSUE THREAD

**Issue by tvvocold** [TelescopeJS/Telescope#746]
FYI: here is the hackernews source code and maybe it's has some good feature that helpful!
https://github.com/arclanguage/anarki

**Comment by SachaG** [comment]
What would the ban feature do?

**Comment by tvvocold** [comment]
Means ban user or ban some websites.their r "discuss | edit | kill | blast | nuke | delete" in hacker news amdin's page. ( u can run ur own hacker news or test it  by use it https://github.com/arclanguage/anarki )

**Comment by SachaG** [comment]
Sorry, I'm not going to run my own Hacker News or look through the code. But if you want to suggest a feature, feel free to give a detailed description of what you have in mind :)
