### ISSUE TITLE
If today is empty, jump to yesterday please.

### ISSUE THREAD

**Issue by tomByrer** [TelescopeJS/Telescope#749]
example: 
Visit http://sidebar.io/ early in the day, & the list will likely be empty.
I'd like to not have to go to a previous day so see any posts.
TIA!

**Comment by SachaG** [comment]
I agree in principle for Sidebar, but I don't think that will be changed for Telescope. It would be confusing to just skip days in the single day view, and also technically a bit tricky to do. Sorry…
