### ISSUE TITLE
 Daily View - load more button doesn't work

### ISSUE THREAD

**Issue by jdunns4** [TelescopeJS/Telescope#750]
IN FIREFOX - When you have 5 posts per day appear in the 'daily' view - the 'load more' button doesn't work.
IN CHROME - works fine.

**Comment by johnthepink** [comment]
@jdunns4 I just tried to replicate this in Firefox and couldn't seem to do it. What version of Firefox are you using, and is it still an issue for you?

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
