### ISSUE TITLE
When autosubscribing new users to the newsletter, don't display banner asking them to subscribe

### ISSUE THREAD

**Issue by obvio171** [TelescopeJS/Telescope#751]
Even when the instance is configured to autosubscribe new users to the newsletter, they still get the banner asking them to subscribe. If they click the 'x' and then later get an email, they might be confused.

**Comment by SachaG** [comment]
There's actually a built-in `profile.subscribedToNewsletter` property on the user object to avoid that, but when the user is created and subscribed to the newsletter, the actual user object doesn't exist in the db and the property is not assigned correctly.

Not sure how to fix this yet…

**Comment by xavcz** [comment]
Hey, @obvio171! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, and this issue has been fixed on Nova 😄  I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
