### ISSUE TITLE
Signing in via Facebook and then Twitter will create two different accounts even if same email used

### ISSUE THREAD

**Issue by em0ney** [TelescopeJS/Telescope#758]
This is a known core issue in Meteor whereby oauth signin doesn't try to match user records based on email.  The reason why I add this is that it also creates an issue when inviting a user.  If the same email account has already been invited, the new user account that is created cannot be invited.

Possible solutions:
1. Override this part of meteor AccountsBase (I have done this before on another project and I'm happy to make a PR if you want to go this way)
2. Until Meteor resolves this issue in AcocuntsBase, change invites to match userIds rather than invited emails such that each account created in core Meteor can be invited

Happy to implement the fix, let me know which way you want to go @SachaG

Elliott

**Comment by splendido** [comment]
Hi @em0ney,

this is something we appreciate, but it's a very delicate problem (see also #660).

Telescope uses [user accounts](https://github.com/meteor-useraccounts/core) to deal with login/logout stuff and at the moment this part is still not covered (even if I had some previous work on [accounts-meld](https://atmospherejs.com/splendido/accounts-meld) which will be integrated,  sooner or later. See the [Milestones](https://github.com/meteor-useraccounts/core/milestones) for useraccounts).

There are some tricky parts to be securely addressed before going public with this, and the most of the effort should be put in ensuring already existing (multiple) accounts won't be affected by the new code.

Btw, if you had other previous experiences about *melding* accounts I'd be happy to discuss this together and see whether there's something good in your solution to be picked up.
Lets have a look at the code for [accounts-meld](https://github.com/splendido/meteor-accounts-meld) and let me know what do you think!

Cheers,
Luca

**Comment by SachaG** [comment]
To be honest the invite code should probably be overhauled, and maybe made to work as a plugin of User Accounts.

**Comment by splendido** [comment]
...yeah, invites are another thing on the *roadmap* :(

If I can manage to wrap up things with [autopublish.meteor.com](http://autopublish.meteor.com/) by next week, I'll switch back to useraccounts@2.0 to provide a little skeleton on which we can start adding stuff like invites :)

**Comment by em0ney** [comment]
Hi @splendido 

I like the look of accounts-meld.  A more robust implementation of the same thing.  I like the fact that you have configurable options to ask before melding etc.

Why not use accounts-meld on telescope and track whether a user has been invited by the userId?  Guaranteed to have 1 invite per person that way.

Could always put some effort in to some sort of a 'telescope-admin-meld' menu to assist in the initial migration to melding existing user accounts.  Happy to help with this.

Elliott

**Comment by splendido** [comment]
@em0ney as I said I'd like to get it integrated with `useraccounts@2.0`. Before that time I'm not keen to play with temporary integration for Telescope.

One of the reasons, for example, is I'm not going to user the `registered-emails` field anymore, but leveraging the regular `emails` one. This would create intermediate situations which might be difficult to migrate in the future...

I'll ping you once I'll have the structure for `useraccounts@2.0` ready to play with.
In the meanwhile lets try to see how http://test-accounts-meld.meteor.com/ palays.
Code [here](https://github.com/splendido/test-accounts-meld)

I hope you can appreciate my feelings.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, and this issue has been fixed on Nova 😄  I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
