### ISSUE TITLE
2 emails are being sent 1 html, 1 plain text for every notification

### ISSUE THREAD

**Issue by voidale** [TelescopeJS/Telescope#761]
I have checked the console it says sending mail once, But I get 2 emails 1 is plain text the other is html. I'm using mailgun. What is the issue with this?

It looks like this:

email 1
````
MYTEST1 [http://harvesttalk.com/]
voidale2 [http://harvesttalk.com/users/xGr2oFxZps78xnsKB] left a new comment on test [http://harvesttalk.com/out?url=http%3A%2F%2Fcdkeyspro.com%2F] :

awesome post you have


Discuss [http://harvesttalk.com/posts/r5eYC65a2fTutqKrg/comment/hJym8z5YtKsNWREBx]

Change your notifications settings [http://harvesttalk.com/account]
````
email2
````
<div><br>

<!-- 100% wrapper (grey background) -->
<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0" bgcolor="#ebebeb" style="border-spacing: 0;">
  <tbody><tr>
    <td class="wrapper" align="center" valign="top" bgcolor="#ebebeb" style="background-color: #ebebeb; border-collapse: collapse; padding: 20px 0;">

      <!-- 600px container (white background) -->
      <table border="0" width="600" cellpadding="0" cellspacing="0" class="container" bgcolor="#ffffff" style="border-spacing: 0; border-radius: 3px;">
        <tbody><tr>
          <td class="heading-container" style="border-collapse: collapse; background: #444444; padding: 15px; text-align: center; border-radius: 3px 3px 0px 0px; color: white; font-family: helvetica, sans-serif; font-weight: bold; font-size: 20px;">
            <a href="http://harvesttalk.com/" style="color: #dd3416; font-weight: bold; text-decoration: none;" title="Click to open in a new window or tab
http://harvesttalk.com/">
              
                MYTEST1
              
            </a>
          </td>
        </tr>
        <tr>
          <td class="main-container container-padding" bgcolor="#ffffff" style="border-collapse: collapse; line-height: 1.7; background: white; padding: 0 30px; font-size: 15px; font-family: helvetica, sans-serif; color: #555;">
            <br>

            <span class="heading" style="font-weight: bold; font-size: 18px; line-height: 1.5; margin: 0;">
<a href="http://harvesttalk.com/users/xGr2oFxZps78xnsKB" style="color: #dd3416; font-weight: bold; text-decoration: none;" title="Click to open in a new window or tab
http://harvesttalk.com/users/xGr2oFxZps78xnsKB">voidale2</a>
left a new comment on 
<a href="http://harvesttalk.com/out?url=http%3A%2F%2Fcdkeyspro.com%2F" class="action-link" style="color: #dd3416; font-weight: bold; text-decoration: none;" title="Click to open in a new window or tab
http://harvesttalk.com/out?url=http%3A%2F%2Fcdkeyspro.com%2F">test</a>:
</span>
<br><br>

<div class="comment-body" style="border-top: 1px solid #ddd; border-bottom: 1px solid #ddd; padding: 10px 0;">
<p>awesome post you have</p>

</div>
<br>

<a href="http://harvesttalk.com/posts/r5eYC65a2fTutqKrg/comment/hJym8z5YtKsNWREBx" class="action-link" style="color: #dd3416; font-weight: bold; text-decoration: none;" title="Click to open in a new window or tab
http://harvesttalk.com/posts/r5eYC65a2fTutqKrg/comment/hJym8z5YtKsNWREBx">Discuss</a><br><br>

          </td>
        </tr>
        <tr>
          <td class="footer-container" style="border-collapse: collapse; background: #ddd; font-family: helvetica, sans-serif; padding: 30px; color: #777; border-radius: 0px 0px 3px 3px; font-size: 13px;">
            <a href="http://harvesttalk.com/account" style="color: #dd3416; font-weight: bold; text-decoration: none;" title="Click to open in a new window or tab
http://harvesttalk.com/account">Change your notifications settings</a><br><br>
            
          </td>
        </tr>
      </tbody></table>
      <!--/600px container -->

    </td>
  </tr>
</tbody></table>
<!--/100% wrapper-->
<br></div>
````

**Comment by SachaG** [comment]
Oh, that's strange. I've heard of some emails getting sent out twice, but never the HTML and plain text versions getting sent out separately. Is there any chance it's a problem with your Mailgun account?

**Comment by voidale** [comment]
@SachaG how can I verify? I did pretty much a regular setup. But I can see in the logs 'Accept' twice for the same thing. I also use `Meteor Up` if this makes any difference?

**Comment by SachaG** [comment]
Not sure… I did fix a double email bug in the last release, so maybe start by updating your app?

**Comment by voidale** [comment]
'meteor update' updated. no telescope packages updates.

**Comment by SachaG** [comment]
That's not how you update Telescope… Check out the docs:)

**Comment by voidale** [comment]
ok so I updated it the right way, `git pull telescope master` still didn't make any difference. I'm still getting 2 emails to mailgun to be sent.

**Comment by nhorob67** [comment]
Still sending 2 e-mails

**Comment by SachaG** [comment]
@nhorob67 what's your deploy/email setup like?

**Comment by voidale** [comment]
how should we debug this? I set MAIL_URL from the settings of telescope. I don't really see the problem to be on my end.

**Comment by SachaG** [comment]
You could try calling `Meteor.call('testEmail')` in the browser console. Or using another email provider?

**Comment by voidale** [comment]
I have tried Mandrill.com still sending 2 emails it's obviously a bug

**Comment by SachaG** [comment]
I think you're right, and it's a bug with Telescope somehow. I haven't had time to properly look into it yet, really sorry :(

**Comment by SachaG** [comment]
I've tracked down one potential bug that could've interfered with generating the HTML version of the emails. Maybe you could pull down the latest `devel` commit and see if that fixes your issue?

If that doesn't work, could you email me at hello at telesc.pe to give me access to your server so I can take a look directly?

**Comment by voidale** [comment]
awesome! `meteor update` + editing `packages/telescope-email/lib/server/email.js` made it work.

**Comment by SachaG** [comment]
Awesome, that's a relief :) I'll get an official release out soon then.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, and this issue has been fixed on Nova 😄  I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
