### ISSUE TITLE
Users invited by email cannot be "invited" on admin page

### ISSUE THREAD

**Issue by jasonwhat** [TelescopeJS/Telescope#762]
Settings:
- Users must be invited to post
- Users have 3 invites each

1. User 2 (regular non-admin user) invites user3@gmail.com to join site.
2. user3@gmail.com (User3) accepts the invite and registers with Twitter. They include their same user3@gmail.com email in the sign up.
3. User3 tries to post, but does not have the post option still.
4. Admin goes to user admin interface and clicks "invite" button so user3 can post, but admin is unable to click invite button. In fact, admin can only click "Make Admin." Thus User3 is unable to post.

Anybody else having this issue or able to recreate? I've had it with 3 users that were invited by other users.

**Comment by xavcz** [comment]
Hey, @jasonwhat! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
