### ISSUE TITLE
Ability to set up autotasks, like top tweets

### ISSUE THREAD

**Issue by zsherman** [TelescopeJS/Telescope#768]
It would be awesome if you could queue up trending articles to be tweeted by an authorized twitter account.

**Comment by queso** [comment]
I use IFTTT to handle this, just give it the feed for top and let it go.

**Comment by zsherman** [comment]
Great idea @queso, how do you grab the feed for top though?

**Comment by queso** [comment]
Hmm, I guess I just grab the whole feed, so I tweet anything out: http://crater.io/feed.xml.

I've been wanting to get more feeds into telescope, perhaps that would make more sense?

**Comment by zsherman** [comment]
Sweet thanks, that worked!

**Comment by SachaG** [comment]
Telescope already has a bunch of different feeds: https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-rss/lib/server/routes.js

**Comment by sungwoncho** [comment]
IFTTT is great, but it'd still be nice to have this feature internally. Any thoughts?

**Comment by SachaG** [comment]
Sure, if you develop it :)

**Comment by sungwoncho** [comment]
Okay no promises but I will have a go and try to make a PR.

**Comment by SachaG** [comment]
Rather than a PR, I would recommend making a separate plug-in. This way it doesn't increase the core codebase's complexity, and you can maintain it yourself.
