### ISSUE TITLE
Category Order in Submit/Edit vs. Category Order in Menu

### ISSUE THREAD

**Issue by arist0tl3** [TelescopeJS/Telescope#769]
Setting the order of categories in the Admin Settings page results in proper order within the Categories drop down menu. However, when the category checkboxes are listed in the Submit Post or Edit Post page, they are sorted by their order within the collection. 

@SachaG : Short of hand-editing the collection, is there another way to sort the checkboxes?

**Comment by SachaG** [comment]
Sounds like a bug, thanks.

**Comment by jms301** [comment]
Seems to have been fixed?

**Comment by SachaG** [comment]
Yes, I think it has :)
