### ISSUE TITLE
CSS not updating

### ISSUE THREAD

**Issue by zsherman** [TelescopeJS/Telescope#773]
Just set up a fresh install, not sure what changed because I have an installation from a few days ago that works perfectly, but after following the directions in the docs, the css overrides in my new telescope-theme-xxx package aren't being applied. Anyone else experience this?

**Comment by jshimko** [comment]
I'm not having any issues.  Can you share your code?

**Comment by zsherman** [comment]
Sure, it's just a dead simple package.js with some basic css:

package.js
```
Package.describe({
  summary: "Telescope Test Theme",
  version: '0.1.0',
  name: "telescope-theme-test"
});

Package.onUse(function (api) {

  api.use(['fourseven:scss', 'telescope-theme-hubble'], ['client']);

  api.addFiles([
    'lib/client/stylesheets/screen.scss',
    ], ['client']);

});
```

lib/client/screen.scss
```
body {
  background: #000000;
}
```

**Comment by jshimko** [comment]
Try `api.use(['fourseven:scss', 'telescope-theme-base', 'telescope-theme-hubble'], ['client']);`

**Comment by zsherman** [comment]
Nope, still a no go.

**Comment by jshimko** [comment]
Got a public repo?

**Comment by zsherman** [comment]
Yup, one sec, throwing it up there.

**Comment by zsherman** [comment]
Hm, that's odd – didn't pick up any of my changes. I'm going to start fresh really quick and see if I can repro.

**Comment by jshimko** [comment]
If you added a local development package with meteorite (like your theme maybe), it automatically gets added to the gitignore in the packages folder.

**Comment by zsherman** [comment]
Ok here it is https://github.com/zsherman/vinyl-news/tree/master/packages/telescope-theme-vinyl

**Comment by jshimko** [comment]
:)   Well, I'd start by adding it to the app.  

`meteor add telescope-theme-vinyl`

https://github.com/zsherman/vinyl-news/blob/master/.meteor/packages

**Comment by zsherman** [comment]
Oh god, you're totally right. Sorry about that, meteor newbie over here, thanks for the help @jshimko.

**Comment by jshimko** [comment]
Aside from looking at your `.meteor/packages` file, you can always double check that a package is installed (and package version #'s) by running `meteor list` as well.

**Comment by zsherman** [comment]
We should make sure to add that step to the theming docs so no one gets tripped up like me, I'll submit a PR.

**Comment by jshimko** [comment]
Good call.  There's no such thing as too much detail when you're just getting started.
