### ISSUE TITLE
Paste broken in Mobile Safari

### ISSUE THREAD

**Issue by Bemmu** [TelescopeJS/Telescope#774]
Not sure if this is an issue with a customized template, but when I copy a link to my clipboard on iOS, go to http://www.startjapan.org, log in and attempt to post it, "paste" is broken. Tapping on the URL post only flashes the paste button briefly and then disappears. I wonder if there is something special about those input boxes.

**Comment by xavcz** [comment]
Hey, @Bemmu! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
