### ISSUE TITLE
Title url for posts are not correct in email template

### ISSUE THREAD

**Issue by ersentekin** [TelescopeJS/Telescope#775]
When I check out my template from http://localhost:3000/email/campaign it looks perfect, title url of a post looks like this: 

"localhost:3000/out?url=http://..."

but when check out the newsletter email from my inbox, title url of a post looks like that:

"out?url=http://..."

Why does "localhost:3000/" part of url looks like cropped? 

Thanks so much

**Comment by jshimko** [comment]
Did you set your site URL in the settings page?

**Comment by ersentekin** [comment]
@jshimko  I've set to "xxx.com/" 

But url is not changing at the "http://localhost:3000/email/campaign" , when I change my site URL from settings page. Does it occur for mails just inbox?

**Comment by jshimko** [comment]
Try using a valid url (including http:// and a trailing /)

**Comment by ersentekin** [comment]
Thanks for advice, I set it. By the way, are there any way of testing send digest mail to specific user(s) ?

**Comment by jshimko** [comment]
There are a few options.  You could create a test list in Mailchimp that includes only addresses you want for testing and then use that list ID in your local dev environment (in the newsletter settings).  Then just trigger a test campaign from your browser console (or Meteor console) with `Meteor.call('testCampaign')`.  

You could safely do the same in production as well.  All it does is schedule a campaign with Mailchimp for an hour later.  You then have an hour to log into your account and view the result (and stop it before it sends).

**Comment by jshimko** [comment]
Or you can temporarily use the test list ID in production.

**Comment by jshimko** [comment]
And don't forget to close the issue.  :)

**Comment by ersentekin** [comment]
@jshimko thanks so much for your help! It worked after I set the URL like you told.
