### ISSUE TITLE
Unable to load any screen apart from frontpage

### ISSUE THREAD

**Issue by nickhould** [TelescopeJS/Telescope#777]
Since I upgraded to latest version, all the views, apart from the frontpage, take a lot of time to unload and usually never loads and get stuck with a spinning loaders (see on bootstrappers.io and try to sign-up). I can reproduce in local. Anyone having this problem as well?

**Comment by SachaG** [comment]
I'm getting a lot of errors in the console when I access `/register` . Could it be a customization issue?

**Comment by jshimko** [comment]
Definitely looks like a customization issue.  I get this on most routes:

```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
```

**Comment by splendido** [comment]
Should be some custom IR hook wich is not calling `this.render('template')` on some `if` branch.
If you get to the end of the function without having called `this.next()` nor `this.render(...)` you get the above error and nothing is displayed! :-)

Usually you should have a structure like this:

```javascript
Router.onBeforeAction(function(){
  if (someCondition) {
    this.render('template');
    this.renderRegions();
  }
  else {
    this.next();
  }
});
```

**Comment by splendido** [comment]
...mmm, I've digged a bit more.

Interestingly enough, it seems that `$` is undefined and this causes an error within an `onBeforeAction` hook preventing the `atForm` to get rendered!

Any idea about why jQuery gets messed up??

![jqueryproblem](https://cloud.githubusercontent.com/assets/6148980/6274486/45b26f40-b878-11e4-9935-1c3a9e85c9d1.png)

**Comment by jshimko** [comment]
For what it's worth, those console errors may be totally unrelated to what's actually causing the problem.  I've had unrelated broken code stop iron-router stuff from running and throw those same errors.  My problem had nothing to do with IR or `this.next()`, but it was causing them to break.  Tracking down that problem was not fun.  :)

**Comment by jshimko** [comment]
Also, why is jquery being loaded separately there?  That's probably not helping anything considering it's already bundled in with Meteor/Telescope.

**Comment by splendido** [comment]
yes, it's weird that `jQuery` is being loaded from the `media` path...

@jshimko, I've did a bit of trace back on the error and it's exactly inside an `onBeforeAction` where a call to `$(".search-field").val("").blur()` throws the error saying that `$` is not defined...

**Comment by jshimko** [comment]
Yeah, something is clearly crashing code execution and blocking things from running downstream of it.  Is there a public repo?

**Comment by SachaG** [comment]
Closing this for now but please reopen it if symptoms persists.
