### ISSUE TITLE
Email notifications not arriving. Pending status in Queue collection

### ISSUE THREAD

**Issue by john-henry** [TelescopeJS/Telescope#779]
I haven't been getting email notifications for a while now so had a click look at my Queue collection and for the last month I have lots of rows with a status of pending. Emails I haven't gotten in a while include newsletter review and new posts. Any idea how this is happening or what I need to do to correct it

```
{ command: "Meteor.call(\"heraldEscalate\",\"T5BCcMARM2oN56vBC\", \"email\")", execute_after: ISODate("2015-02-19T14:14:30.000Z"), status: "pending", priority: 5, created_at: ISODate("2015-02-19T14:14:30.000Z"), updated_at: ISODate("2015-02-19T14:14:30.000Z"), _id: "LBd6hiudgSBR7vsPu" }
```

**Comment by jshimko** [comment]
Delete all of the documents in your queue and queuelog collections.

Known issue. 
https://github.com/Meteor-Reaction/Herald/issues/53

**Comment by john-henry** [comment]
Thanks for speedy response. I cleared out both collections and made a pending post but in the queue now is a document with a status of failed. So something else is up. I use mup deploy with my mailURL details on that end. Last known deliveries by Mandrill were just before I updated to latest

**Comment by john-henry** [comment]
After updating to latest devel the issue still persists. If I create a pending post as a test. After it has run through queue I get this in my Queue collection

````
{ _id: "SKcFKDnvg9dQabCJj", command: "Meteor.call(\"heraldEscalate\",\"sP73kSQR5wQFDfujq\", \"email\")", created_at: ISODate("2015-02-22T16:11:59.000Z"), execute_after: ISODate("2015-02-22T16:11:59.000Z"), history: " command returned false (Sun Feb 22 2015 16:12:48 GMT+0000 (GMT));", priority: 5, status: "failed", updated_at: ISODate("2015-02-22T16:12:48.000Z") }
````

and this is my QueueLog

````
{ command: "Meteor.call(\"heraldEscalate\",\"sP73kSQR5wQFDfujq\", \"email\")", parent_id: "SKcFKDnvg9dQabCJj", status: "exception", data: null, created_at: ISODate("2015-02-22T16:12:48.000Z"), _id: "52nTezkxttgP8fffz" }
````

No email is sent.

If I do  a `Meteor.call('testEmail')` from browser console email arrives

**Comment by SachaG** [comment]
We're getting rid of the queue altogether soon. That should take care of it?

(`testEmail` doesn't use Herald at all, which is why it's not affected by queue bugs)

**Comment by john-henry** [comment]
Hopefully yes, as I don't receive any email at all from site right now. Ill keep an eye out for an update

**Comment by davedg629** [comment]
I'm having this problem as well. Can someone provide some insight on how to clear the Queue collection?

I found [this post](https://teamgaslight.com/blog/how-to-remove-all-elements-from-a-meteor-collection) which seems to outline the process fairly well, but it stops short for a n00b like myself.

It says I need to define a method on the server that will remove all the items in a collection, but it doesn't say how to add the method to the server or execute it remotely. I'm guessing there is a file where I can add new methods, or do I need to create a temporary package?

Sorry, I probably need to jump into the meteor tutorials and learn a thing or two. Any links to resources that will point me in the right direction would be greatly appreciated.

**Comment by jshimko** [comment]
No need to write any code.  You just need to empty the collection with the mongo console. 

```bash
# mongo shell
db.queue.remove({})
db.queuelog.remove({})
```

If the console isn't your thing, you could also use [Robomongo][1].

[1]: http://robomongo.org/

**Comment by davedg629** [comment]
@jshimko I'm fine with the console. I'm guessing this will clear the collection on my local db, not the production db?

**Comment by davedg629** [comment]
Nvm, figured it out. For the other n00bs, activate the mongo shell like this:

    meteor mongo app-name

**Comment by SachaG** [comment]
Just pushed a commit to the `devel` branch that doesn't use the queuing feature at all anymore.

**Comment by john-henry** [comment]
OK what I can confirm now is that it doesn't send mail to me. So any post I create I don't get notification and and notification an hour before newsletter sends I don't get a link. This is only a recent thing since the last few versions or so.

Other mails now send like new user and comments and new post if another user other than me the admin

**Comment by SachaG** [comment]
@john-henry what if you pull in the latest devel branch? It should include a fix.

**Comment by john-henry** [comment]
Yes this is with latest devel branch which I updated soon after you committed it.
Is all mail sent the same way now or are there subtle differences? For example I use Mandrill. Are all types of mail routed through this now? 
The only thing I can think of is a local mail issue sending mail from domain to same domain which may be typical of a normal LAMP setup but this is hard to track down as it only started happening in the last few releases.

**Comment by jshimko** [comment]
Are your queue/queuelog collections empty?

**Comment by john-henry** [comment]
@jshimko yes both were emptied by me and have not filled since updated to devel

**Comment by jshimko** [comment]
Anything in the server side logs?

**Comment by john-henry** [comment]
Nothing yesterday but will have a look today when I get a chance

**Comment by john-henry** [comment]
Ok here is the error. Anything jump out here?

````
//////// sending email…
from: himself@ee-hub.com
to: HdmB37b01
subject: [EE-HUB - ExpressionEngine News] John Henry Donovan has created a new post: devot-ee.com March 2015 Newsletter
Exception in defer callback: Error: [Can't start Herald.escalate: RecipientError: Can't send mail - all recipients were rejected]
    at [object Object].Meteor.methods.heraldEscalate (packages/kestanous:herald/server/escalate.js:39:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:1513:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1512:1)
    at [object Object]._.extend.call (packages/ddp/livedata_server.js:1455:1)
    at packages/kestanous:herald/server/escalate.js:21:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Object.Herald.SetupEscalations (packages/kestanous:herald/server/escalate.js:14:1)
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
stderr: 
````

**Comment by jshimko** [comment]
Not a valid To: address?  I'm thinking "HdmB37b01" isn't going to send anywhere.  :)

**Comment by john-henry** [comment]
@jshimko Yes thanks. I wasn't very clear. I understand what the error represents but was wondering if anything jumped out as to why it happens only for me, the admin creating a post.

HdmB37b01 is in the emails array for another non-admin user that created his account using FB
He has no email address in that array. Should it be an email or is a marker of some sort for facebook in the services array?

**Comment by jshimko** [comment]
I think it is highly likely that if you fix/remove that invalid email from their account, your problem will go away.

**Comment by jshimko** [comment]
As an admin, you can edit their profile.  Just remove the email and/or shut email notifications off for them.

**Comment by john-henry** [comment]
This gets weirder. So I replaced the HdmB37b01 with the guys email. I then added a pending post and checked logs and it sent him the notification and not me!

I went back and removed the email from his profile and then when page refreshed it asked me to submit my email to finish my registration. Looks like removing his email removed mine too.

So I submitted that form with my email and looks to have updated in DB too.

I submitted another pending post and logs now have the to field as null and not my email address. But I'm guessing null represents this other account not having an email address there anymore

**Comment by john-henry** [comment]
Ok. I've been pouring over this trying to figure what's wrong and I've come to the conclusion it has to do with this commit https://github.com/TelescopeJS/Telescope/commit/ea1521d141cff01554b8a977585557ed1d35a929#diff-716635989057792ba57280b9687db720 which would coincide with my notifications stopping when posting as an admin.

The error I get in my server logs though is like I didn't pass the conditional and it tries to send a notification without the user ID which may be why its picking a random one from user collection
````
 if (post.status === STATUS_PENDING && !!adminIds.length) { 
````

I'm going to comment out the following for now

````
var adminIds = _.without(adminIds, post.userId);
````

but I think there may be something else happening underneath the surface as I also don't receive the 'newsletter scheduled at' email and get this in my server logs

````
// Creating campaign…
// Campaign created
// Campaign scheduled for 2015-03-09 01:00:07
{ [MongoError: invalid query] stack: [Getter] }
````

**Comment by SachaG** [comment]
If you're the only user to notify, and you're also the one submitting the post, then `notifiedUserIds` should end up empty and no notifications should be sent out (because of the `else if (!!notifiedUserIds.length)`). 

I would add console.logs in there to figure out the exact content of `notifiedUserIds` at different points in the function.

**Comment by SachaG** [comment]
Closing this for now, but please reopen it if the issue persists.
