### ISSUE TITLE
Error when starting meteor server on telescopedemo

### ISSUE THREAD

**Issue by andrerfneves** [TelescopeJS/Telescope#782]
https://gist.github.com/andrerfneves/da4ed5acc8f139fdfd80#file-gistfile1-txt

Can't seem to start the meteor app telescopedemo. Followed the info on the telesc.pe docs and your video but no luck. Seems like an npm error, but I'm not sure.

Any ideas?

**Comment by massimilianomarini** [comment]
Have you tried updating nodejs?

**Comment by andrerfneves** [comment]
Yup! That worked well. Thanks @massimilianomarini

**Comment by massimilianomarini** [comment]
:+1:
