### ISSUE TITLE
Reply UI bug

### ISSUE THREAD

**Issue by lorensr** [TelescopeJS/Telescope#787]
I click the first "reply" link:

![image](https://cloud.githubusercontent.com/assets/251288/6384545/b657224c-bd12-11e4-91f2-e3293a654d97.png)

And then I see this:

![image](https://cloud.githubusercontent.com/assets/251288/6384549/c423ba7a-bd12-11e4-9a3b-d042d4a032b8.png)

And keep hitting the reply and it's not doing anything! While I eventually scrolled down, and found the input, someone else might not. Perhaps place the box right below the comment I'm replying to, and then when I submit it, if the ordering dictates that it needs to be moved down in the comment list, animate it moving there.

**Comment by SachaG** [comment]
That's weird, replying should redirect you to the reply page. 

That being said that whole comments flow need to be overhauled so that commenting happens inline. It's pretty bad right now…
