### ISSUE TITLE
Error %2F on iphone & android

### ISSUE THREAD

**Issue by nxpeacock** [TelescopeJS/Telescope#788]
__Sorry, I'm not good at English, I use google translate.__

Many visitors to my telescope with iphone, android is not found error: /%2f

__Platform:__ Safari 4.0 mobile, Safari 6.0 mobile, Android tablet...

Eg : http://thethao.io => http://thethao.io/%2F (404 not found)

Eg : http://thethao.io/posts/8jCcomAYcsW88jx4g => http://thethao.io/%2Fposts%2F8jCcomAYcsW88jx4g (404 not found)

![clicky screenshot](https://lh5.googleusercontent.com/-SLAYrmRtGvo/VO_uga3csKI/AAAAAAAAACY/nCyEqI8PW3Y/s2048/clicky%252520screenshot.png)

__Please help me if you can. Thank you.__

**Comment by nxpeacock** [comment]
on iphone 5, very bad UI, thumbnail stretched,
![thumbnail stretched](https://lh3.googleusercontent.com/-tAQJ7cJlJR8/VO_6TFnbc0I/AAAAAAAAACw/cltJB3SpC4A/s2048/iphone%2525205%252520thethao.io.png)

**Comment by xavcz** [comment]
Hey, @nxpeacock! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
