### ISSUE TITLE
Template mobile_nav is not resolving getTemplate properly. 

### ISSUE THREAD

**Issue by durgesh-priyaranjan** [TelescopeJS/Telescope#790]
In template "mobile_nav", getTemplate is not resolved with the overriden value.
Need to fix in client/views/nav/mobile_nav.js, I guess

  getTemplate: function () {
    return getTemplate(this).template;
  }

should be replaced with

  getTemplate: function () {
    return getTemplate(this.template);
  }

**Comment by SachaG** [comment]
Good point, thanks!
