### ISSUE TITLE
Embedly support doesn't account for protocol relative urls

### ISSUE THREAD

**Issue by queso** [TelescopeJS/Telescope#791]
I just added SSL support to Crater and it seems the embedly images are not being saved as protocol relative urls.

We should save a thumbnailUrl like this:

```
thumbnailUrl: "//i.embed.ly/1/image/crop?url=http%3A%2F%2Fjoshowens.me%2Fcontent%2Fimages%2F2015%2FFeb%2Fsecurity-settings-header.jpg&key=386ad471df374e12ae61b1af9a2acaa1&width=200&height=125",
  title: "Environment Settings and Security with Meteor.js"
```

but instead right now we are getting this:

```
thumbnailUrl: "http://i.embed.ly/1/image/crop?url=http%3A%2F%2Fjoshowens.me%2Fcontent%2Fimages%2F2015%2FFeb%2Fsecurity-settings-header.jpg&key=386ad471df374e12ae61b1af9a2acaa1&width=200&height=125",
  title: "Environment Settings and Security with Meteor.js"
```

**Comment by SachaG** [comment]
If it's just a matter of removing the `http:` it shouldn't be too hard. Embedly also has a `secure` argument (see http://embed.ly/docs/api/extract/arguments) but it's only available for paid plans apparently. We might not need it though?

**Comment by queso** [comment]
Based on my limited testing, just removed the http: should make it a relative url and it seems to work on the images I've tested.

**Comment by SachaG** [comment]
Fixed in https://github.com/TelescopeJS/Telescope/commit/3e97b453dec0a04efbd4898afa10f098d74f9f9e
