### ISSUE TITLE
Autoform 5 breaking changes

### ISSUE THREAD

**Issue by jshimko** [TelescopeJS/Telescope#798]
[Autoform][1] v5 was released today and has [lots of breaking changes][2].  We have some work to do before it's ok to upgrade.  I just started working on that, but I figured I'd throw this issue up so people know what's going on when Telescope automatically updates Autoform and then falls over and dies on them.  :)

Until it's sorted out, everyone should throw a version constraint in their `.meteor/packages` file to prevent the upgrade.

Specifically, [this][3] needs to be changed to this:  `aldeed:autoform@4.2.2`

[1]: https://github.com/aldeed/meteor-autoform
[2]: https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md
[3]: https://github.com/TelescopeJS/Telescope/blob/devel/.meteor/packages#L29

**Comment by SachaG** [comment]
We should coordinate on this. Maybe ping me on Slack to let me know what you're working on exactly?
