### ISSUE TITLE
User profile update

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#801]
Is it possible to add an extra row similar to Github and Twitter on users profile page ?

**Comment by jshimko** [comment]
You can add anything you can dream up!  :)

Just [create a custom template][1] for [any user profile template][2] you'd like to change.

[1]: http://www.telesc.pe/docs/customizing/custom-templates/
[2]: https://github.com/TelescopeJS/Telescope/tree/devel/client/views/users

**Comment by awrelll** [comment]
Thanks for your reply. I would like this feature to be applied to all users. Your suggestion sill applies ?

**Comment by jshimko** [comment]
Yes.

**Comment by awrelll** [comment]
can't i edit the existing template ? i'm pretty new to this and i can't solve it by myself :)
Thanks!

**Comment by jshimko** [comment]
That's not recommended.  If you edit core files, pulling in future Telescope updates will be a nightmare to manage.  Telescope was designed to be customizable for that exact reason (custom templates, post modules, theme packages, etc).

So you can definitely edit those files, but you're just creating work for yourself - unless you never plan on pulling in updates (also not recommended).

Creating custom templates is pretty simple.  Create a new meteor package to add your files to.  Then create an HTML file for whatever template you want to customize and tell Telescope to use it.

So, to change [the `user_account` template][1]...

custom_user_account.html
```html
<template name="custom_user_account">
  Your custom version of user_account.html goes here
</template>
```

custom_user_account.js
```js
templates["user_account"] = "custom_user_account";
```

Add your new package to Telescope with `meteor add YOUR_PACKAGE`.  That's it.

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/client/views/users/account/user_account.html

**Comment by jshimko** [comment]
I built DataLook.io using that exact method (custom templates + a bunch of CSS).  You can see the repo here for lots of examples:  https://github.com/jshimko/telescope-datalook

**Comment by awrelll** [comment]
if this is a field with a string of numbers (to be more specific, a bitcoin address)  what value should it have  ? I see that twitter has value="{{getTwitter}}" . Also when adding my package with meteor what's the process behind that ? I can't seem to follow. 
Thanks a bunch!

**Comment by jshimko** [comment]
If you're just getting started with Meteor, there's really a lot more to it than I could possibly cover in a Github issues conversation.  I highly recommend picking up a copy of [Discover Meteor][1].  It's easily the best getting started resource you can get for Meteor.  The [blog][3] there is also a fantastic resource.

As for customizing Telescope, there's no better resource than the [docs][2].  Everything you're trying to do is covered in detail there.



[1]: https://www.discovermeteor.com/
[2]: http://www.telesc.pe/docs/
[3]: https://www.discovermeteor.com/blog

**Comment by jshimko** [comment]
Also, the project that you build while going through the Discover Meteor book is a lightweight version of Telescope (called [Microscope][1]).  Reading that book is one of the best ways you could prepare yourself for hacking on Telescope.

[1]: https://github.com/DiscoverMeteor/Microscope

**Comment by SachaG** [comment]
@jshimko Thanks for taking care of this. Closing it for now.
