### ISSUE TITLE
Layout css problem during installation

### ISSUE THREAD

**Issue by dickyj** [TelescopeJS/Telescope#802]
Hi,
I followed the installation instructions, but after installing telescope, I get a layout issue, looks like the css is messed up. I added bootstrap 3 manually, that fixed it a bit, but it is still messed up.
Can someone please help? I have attached the screenshot. 
![screenshot 2015-03-10 at 12 58 04 pm](https://cloud.githubusercontent.com/assets/6478334/6569940/3052e272-c725-11e4-975c-bc5b6c77f186.png)
Thanks.

Dicky

**Comment by SachaG** [comment]
You shouldn't need to add anything, so I would suggest removing Bootstrap 3. Are you getting any errors, either client-side or server-side? Did you try refreshing your browser, or trying a different one?

**Comment by dickyj** [comment]
If I did not add Bootstrap 3, its even worst, the layout only shows text, as if there is no css. I did not see any errors on client-side, how do I find out if there are errors on the server side? Thanks.

**Comment by SachaG** [comment]
http://www.telesc.pe/docs/getting-started/getting-help/

**Comment by SachaG** [comment]
So far nobody else has reported this issue, so I'm closing it for now. Maybe you could just try starting fresh with a new Telescope install?

**Comment by dickyj** [comment]
Ok will do.
