### ISSUE TITLE
Telescope settings panel missing

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#806]
Not sure how i messed this up. Where should i look first ?
![screen shot 2015-03-11 at 14 03 32](https://cloud.githubusercontent.com/assets/6716597/6595891/87b2d32e-c7f7-11e4-9092-25951c4208a4.png)

**Comment by jshimko** [comment]
Gonna need more info than that.  What are we looking at here?

**Comment by awrelll** [comment]
It's a fork of Telescope called CodeBuddies. I cloned it https://github.com/ethereumbuilders/eth.hangouts

**Comment by SachaG** [comment]
Are you using Firefox by any chance? Maybe check it out using another browser?

**Comment by awrelll** [comment]
In Firefox it's the same. I tried to update user profiles and i accidentaly overwritten some files via FTP and now i can't figure out why the settings panel is blank.

**Comment by awrelll** [comment]
My app is running on http://ethereum.builders/

**Comment by jshimko** [comment]
FTP is definitely not the recommended way to deploy or update Meteor apps and is very likely to cause problems for you.

It also looks like you've changed a bunch of Telescope core code.  That's also [not recommended][3].  There are some exceptions to that, but generally you want to [create a custom package][4] and add your template and CSS customizations there.  (See the three `cb-theme-*` packages in the `/packages` folder of the CodeBuddies repo for examples of this)

I recommend starting with a fresh fork of CodeBuddies and then follow the guidelines in [the docs][1] for customizing and [deploying][2] Telescope.

The [Discover Meteor][5] book is also a fantastic resource.  The book walks you through Meteor fundamentals while building a lightweight version of Telescope.

[1]: http://www.telesc.pe/docs/
[2]: http://www.telesc.pe/docs/getting-started/deploying/
[3]: http://www.telesc.pe/docs/customizing/customization-basics/
[4]: http://www.telesc.pe/docs/customizing/creating-packages/
[5]: https://www.discovermeteor.com/

**Comment by awrelll** [comment]
Thanks for taking a look anyway. It seems it was an error with quickFormTelescope.js  "Exception in template helper: TypeError: undefined is not a function" . Now it's all good.
