### ISSUE TITLE
Flexbox issue?

### ISSUE THREAD

**Issue by thingista** [TelescopeJS/Telescope#807]
I am not very familiar with SCSS so bear with me...
I have layout issues on Safari. The various Post's modules are not laid out properly. All the other browsers are fine.

If you look here for instance: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss#L72
should it not be say:
```css
@include order(2);
```
instead of just
```css
order(2);
```

Otherwise, how does the preprocessor know how to apply the mixin?

There are multiple instances of these in _posts for the various flex-box mixins (flex-grow, flex-shrink etc).

**Comment by jshimko** [comment]
There is no mixin for flexbox elements in Telescope.  Autoprefixer should sort that out.  

If that's jacked up in Safari, I'd be willing to bet it's because it isn't getting prefixed.  That behavior is exactly what would happen without prefixed flexbox code.

**Comment by thingista** [comment]
Ah. OK. Do you know why we still have these though?
https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-theme-hubble/lib/client/scss/partials/_mixins.scss#L134-L163

Is it just in case the prefixer option is set to off then?

**Comment by thingista** [comment]
@jshimko Just one question: is it normal that the fourseven:scss package does not show up here:
https://github.com/TelescopeJS/Telescope/blob/devel/.meteor/packages
Is it not a dependency of theme-base?

**Comment by jshimko** [comment]
Yes, pretty sure those mixins are leftovers that never got removed when autoprefixer was added.

Yes, you are correct about fourseven:scss.  It's [loaded as a dependency][1] in the theme packages.

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-theme-hubble/package.js#L9

**Comment by thingista** [comment]
Then I guess I am confused with regards to how packages work with Meteor.
To be loaded as a dependency, should it not be "installed" and show up in the list when I run `meteor list` in the console? At the moment, it is not there on a fresh repo of Telescope.

**Comment by thingista** [comment]
I got the prefixer to work eventually. I wish I knew exactly what did the trick... but I am not sure. It looks like you need version 1.0.0 of fourseven:scss and not newer ones. I had installed v2. It seems that downgrading worked.
