### ISSUE TITLE
Use Transifex for translation

### ISSUE THREAD

**Issue by diego-vieira** [TelescopeJS/Telescope#808]
I notice some packages are missing translations and others are not up to date.
Since translating the files one by one can get you lost on track and someone might already have done/working on it, may I suggest that we use Transiferx for helping with the translation?
https://www.transifex.com/

It's free for open source software btw.

**Comment by SachaG** [comment]
Yes, that's something we should definitely do. I'll look into it.

**Comment by SachaG** [comment]
OK, I created a project: https://www.transifex.com/organization/telescope

I'm not really familiar with how this works, but if you are maybe I can give you admin rights and you can get things started?

**Comment by SachaG** [comment]
Specifically, I'm not sure how to import/sync content between here and Transifex.

**Comment by diego-vieira** [comment]
Hello @SachaG awesome, yeah I look at that myself too.
Looks like you get started already by setting a few projects.

Just like you did, I was thinking we should create each project for each package and for the core. My username is diegovieira there.

**Comment by diego-vieira** [comment]
I'll clone Telescope repo and check the structure.
They offer a [client](http://docs.transifex.com/developer/client/), so I'm gonna check what's the best approach for us.

**Comment by razvansky** [comment]
Hello,
I found the transifex projects but saw no progress so I came back here.
I cloned the german lang (de.i18n.json) and started working on romanian translation (ro.i18n.json) on my laptop.
Guess the easiest will be if I create a pull request later.

Actually I will double-check the german translation too (it has 207 lines but the original en.i18n.json has 309)

I will keep you posted and THANK YOU for the great work!

**Comment by SachaG** [comment]
Just added Romanian: https://www.transifex.com/projects/p/core-3/language/ro/

I'm still trying to figure this thing out, but you can sign up and I'll add you as an admin for that language if you want :)

**Comment by diego-vieira** [comment]
@SachaG sorry for the delay on that, I'll get this up in the upcoming days :)

**Comment by razvansky** [comment]
Hi Sascha, Diego
I checked Transifex, it seems there is only a demo stringfile in each language folder. I looked everywhere but there is no way for me to upload files. If you want I can coordinate translations.

Otherwise I finished translating the romanian json (based on the german one in i18n) and I get do a pul request.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
