### ISSUE TITLE
Feature Request: Post comments directly from user's email client

### ISSUE THREAD

**Issue by max-mog** [TelescopeJS/Telescope#813]
Feature Request:

Ability to leave comments directly from users' email client.
User subscribes to emails from any new posts or comments to the post he subscribes to.
Upon receiving an email with the post or a new comments made to the post, he would be able to respond to the email and his response gets posted as a comment.
Auth could be based on email address.

**Comment by SachaG** [comment]
Added to the roadmap on the Better Comments card: https://trello.com/c/GO6fIwQp/63-better-comments (I thought it was in there already but apparently not)
