### ISSUE TITLE
Cannot delete URL

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#815]
When editing post, leaving the URL blank doesn't remove it.

**Comment by jms301** [comment]
This bug seems to have been fixed I guess autoform changed their default behaviour? You can re-create the bug with the autoform removeEmptyStrings option.

**Comment by xavcz** [comment]
Hey, @jms301! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, and yes the bug has been fixed! I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
