### ISSUE TITLE
How do I integrate users with an existing Express&Passport user base?

### ISSUE THREAD

**Issue by shlomokraus** [TelescopeJS/Telescope#816]
Hi, I have a working site with thousands of users that already have profiles. 
I want to integrate Telescope into this site without requiring the users to re-register. 
Is that possible? 

Thanks

**Comment by SachaG** [comment]
It should be possible, but there's no built-in feature to do that right no so it would have to be developed. 

What would the ideal flow be for you? Enter a list of emails, and then each user receives a link where they can enter a username and password?

I don't think you'd be able to keep the same passwords unless your current community software happens to use the same encryption scheme as Meteor.

**Comment by shlomokraus** [comment]
I think the best flow is to rely on the current user base for authentication, and use Telescope for the extra fields. For example, when authenticating, it will query an external service, or simply implement a custom database schema (which points to the one that already exists) to authenticate against.

**Comment by SachaG** [comment]
That's an interesting idea, but I really don't know enough about Meteor's user system to tell you if it would work. Maybe it's something you should ask on http://forums.meteor.com

**Comment by shlomokraus** [comment]
I've been looking for this answer everywhere and supprised it is not more common. 
I believe there are more sites looking to integrate Telescope into their community (which have other functionality).

**Comment by SachaG** [comment]
Well, I think importing a list of emails addresses and emailing invites to users is definitely something that could be built in the app down the road. I'm not sure about something more complex though.

**Comment by splendido** [comment]
@shlomokraus if you're interested in using a custom authentication method to keep using your current userbase, there's a very good tutorial [here](https://meteorhacks.com/extending-meteor-accounts.html)

...and @maronk seems to [have managed](https://github.com/meteor-useraccounts/core/issues/319#issuecomment-82579664) to integrate his own one with `useraccounts` (the accounts ui used by Telescope)

Be warned it might be a bit tricky down the road... and it could be a very interesting project per se!


At the same time I see no easy way to *transfer* all current user credentials to a new meteor app's db: it could be something to investigate though...

**Comment by xavcz** [comment]
Hey, @shlomokraus! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
