### ISSUE TITLE
telescope-module-share

### ISSUE THREAD

**Issue by applocalizations** [TelescopeJS/Telescope#817]
In Meteor/TelescopeJS apps the .post-share is hidden by default: 

        .post-share {
    	display: none;
    }

https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss#L355-L357

How do I override these defaults? Is it through the telescope-module-share or elsewhere?

**Comment by applocalizations** [comment]
If I change the scss file post_share.scss, should the following code work: 

    .post-share{
      display: table;
      position: relative;
    }

**Comment by SachaG** [comment]
`display:block` should work. But it's recommended to do it in a custom package (see docs), without overwriting the code that's already there.

**Comment by applocalizations** [comment]
I checked out the docs. Do you mean in the `telescope-custom` package or in an entirely new package?

**Comment by SachaG** [comment]
You can check out how https://github.com/TelescopeJS/CrunchHunt uses a custom `crunchhunt` package to hold its customization code (HTML, CSS, JS). You can do the same thing to hold your own custom CSS.

**Comment by applocalizations** [comment]
Thanks, Sacha.
