### ISSUE TITLE
Leftover code?

### ISSUE THREAD

**Issue by thingista** [TelescopeJS/Telescope#822]
Am I right to assume these are leftovers (pre autoform I guess?):

https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-tags/lib/categories.js#L51-L58
https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-tags/lib/client/templates/categories.js#L12-L34

This code got me a bit confused, but as far as I can see, it is never executed, it is?

**Comment by SachaG** [comment]
Good point, thanks!
