### ISSUE TITLE
Post edit error

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#823]
Exception while simulating the effect of invoking 'editPost' e.makeErrorType.r {error: 601, reason: "Sorry, you cannot edit this post.", details: undefined, message: "Sorry, you cannot edit this post. [601]", errorType: "Meteor.Error"…}
1404153299d822f394e22e8c0600664c24a55097.js:532 e.makeErrorType.r {error: 601, reason: "Sorry, you cannot edit this post.", details: undefined, message: "Sorry, you cannot edit this post. [601]", errorType: "Meteor.Error"…}

I got this in my http://ethereum.builders app which is a clone of Codebuddies.org
Any clues?

**Comment by awrelll** [comment]
I solved it, now i got a problem with aldeed:autoform.
"Exception in delivering result of invoking 'submitPost': TypeError: Cannot read property '$' of undefined"

**Comment by SachaG** [comment]
Are you running the latest version of Telescope? This looks a lot like the errors I had after updating Autoform to 5.0.

**Comment by awrelll** [comment]
I also updated to 5.0 and i regret it. How did you fix it ?

**Comment by SachaG** [comment]
I just went through the Autoform changelog and fixed the code.

**Comment by awrelll** [comment]
so should i upgrade to 5.0.2 ?

**Comment by awrelll** [comment]
sorry for the trouble, i cloned the repo and did a fresh start :)
