### ISSUE TITLE
Clearing search keyword with backspace ( or Delete on mac ) doesn't clear last character

### ISSUE THREAD

**Issue by ywang28** [TelescopeJS/Telescope#825]
This issue is found in desktop version of this page in Chrome 41:
http://demo2.telescopeapp.org/

If search keyword is typed in slowly, focus will remain on search box. Then try to delete the keyword one character by one character with backspace. You will find the last character will pop up again after you delete it. Then if you delete it again, page will show "Sorry, we couldn't find any posts.". Notice search box is empty in this case.

**Comment by ywang28** [comment]
Same issue happens when user tries to hightlight the search keyword and delete it all at once, the keyword will pop up again. My above pull request should fix this issue as well.

**Comment by ywang28** [comment]
Fix is merged. Closing the issue.

**Comment by tima101** [comment]
Hi All, I still the bug: when I delete keyword using "delete" (one character at the time) from the search input - I see the last deleted character reappear.

Does anyone else see the same small bug?
