### ISSUE TITLE
Settings panel blank

### ISSUE THREAD

**Issue by erow80** [TelescopeJS/Telescope#829]
Fresh install of Meteor 1.0.4.1 and new clone of Telescope in master. Latest Yosemite running Safari. Settings panel is blank except Submit button. Occurs locally and on the Meteor demo sever.

![screen shot 2015-03-18 at 8 09 42 pm](https://cloud.githubusercontent.com/assets/1077169/6723826/ca808f1c-cdaa-11e4-825e-094c8bc4b155.png)

**Comment by jshimko** [comment]
Fix hopefully coming soon.

https://github.com/aldeed/meteor-autoform/issues/790/

**Comment by SachaG** [comment]
If you clone master it should run `1.0.3.2` and not `1.0.4.1` and not have that bug though. So that's strange.
