### ISSUE TITLE
Thumbnails don't appear in email when using Protocol Relative URLs

### ISSUE THREAD

**Issue by john-henry** [TelescopeJS/Telescope#836]
The commit to make thumbnail URL work with https works fine everywhere.
https://github.com/TelescopeJS/Telescope/commit/3e97b453dec0a04efbd4898afa10f098d74f9f9e

I can see thumbnails fine in /email/campaign and even in MailChimp if I intercept it there.

It's when I open the email in Apple Mail or GMail I cannot see thumbnails.

I think the issue is with using Protocol Relative URLs for images in email in general. Some email clients won’t try to use HTTP or HTTPS as the protocol. Instead they’ll use the file:// protocol and assume the resource referred to is on the local machine.

I believe this to be the case here.

**Comment by SachaG** [comment]
Oh, makes sense. PR welcome :)

**Comment by SachaG** [comment]
Should be fixed.
