### ISSUE TITLE
Performance - returning to list of posts

### ISSUE THREAD

**Issue by max-mog** [TelescopeJS/Telescope#840]
After viewing details/comments of a post, user clicks the back button of the browser to go back to the list of posts. At this time if the number of posts that was shown before was not large (10 or 20 only) then the time it takes to load the page again would be relatively fast enough.
However, if they were  viewing   sometelescopeapp.com/new/50   then the time to load the list of posts scales with the number of posts that they have viewed.

ie. if they are at sometelescopeapp.com/new/50  then each time the user clicks the back button user has to wait until telescope loads 50 posts. etc...

Possibly caching the listing page and adding an anchor to which post they were viewing last would be ideal (sometelescopeapp.com/new/50#JPhP7St24DcvsC2b1) so that not only the page would load faster due to the cahicng but also would be brought to the last post they were lookign at in the list.

In this case the JPhP7St24DcvsC2b1 would be the id of the post in which the user viewed its comments/details last (sometelescopeapp.com/posts/JPhP7St24DcvsC2b1). 

Waiting for all the posts to load again each time can become abit troublesome for users.

Thanks.
Max

**Comment by SachaG** [comment]
This should be handled by [subscriptions manager](https://github.com/meteorhacks/subs-manager). But the way subscriptions work right now in Telescope is a bit in flux, so it might not work well right now. 

I agree that having to reload every post is not ideal, I'll have to do some testing on that.

**Comment by max-mog** [comment]
I agree it should be an enhancement.

**Comment by xavcz** [comment]
Hey, @max-mog! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. By the way, we are using SubsManager atm, and we are slowly moving to Apollo 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
