### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by max-mog** [TelescopeJS/Telescope#842]
Security issue:

I am able to view all logged-in user objects from a non-admin user within the console.
The loggedin user obj has most of its fields viewable which makes sense however other logged in users objects are exposed with some basic fields.

http://snag.gy/MJcxV.jpg

**Comment by SachaG** [comment]
I might be wrong but I don't think there's any sensitive properties exposed. Can you double-check and let me know which properties you have access to exactly?

**Comment by max-mog** [comment]
For other users these are the properties that are accessible:
I was thinking about _id, email_hash and profile, and social accounts under profile and services.

_id
email_hash
profile: Object
  username: 
 github: 
 twitter:
  __proto__: 
services: Object
 twitter: Object
 profile_image_url:   
 screenName:
 __proto__: Object
slug: 
username: 
 __proto__: Object

**Comment by SachaG** [comment]
That's expected. Not a security issue :)
