### ISSUE TITLE
Exception while invoking method 'forgotPassword'

### ISSUE THREAD

**Issue by renuanil08** [TelescopeJS/Telescope#843]
I'm getting below exception after latest telescope version update when sending mails.
<pre><code>
I20150323-15:40:35.488(5.5)? Exception while invoking method 'forgotPassword' SenderError: Mail from command failed - 501 <anonymous@[127.0.0.1]>: domain literals not allowed
I20150323-15:40:35.488(5.5)?     at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
I20150323-15:40:35.488(5.5)?     at smtpSend (packages/email/email.js:91:1)
I20150323-15:40:35.488(5.5)?     at Object.Email.send (packages/email/email.js:168:1)
I20150323-15:40:35.489(5.5)?     at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:10:1)
I20150323-15:40:35.489(5.5)?     at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:408:1)
I20150323-15:40:35.489(5.5)?     at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:358:1)
I20150323-15:40:35.489(5.5)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:182:1)
I20150323-15:40:35.489(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150323-15:40:35.489(5.5)?     at packages/ddp/livedata_server.js:648:1
I20150323-15:40:35.489(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150323-15:40:35.489(5.5)?     - - - - -
I20150323-15:40:35.489(5.5)?     at SMTPClient._actionMAIL (/root/.meteor/packages/email/.1.0.5.di98ze++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:879:23)
I20150323-15:40:35.490(5.5)?     at SMTPClient._onData (/root/.meteor/packages/email/.1.0.5.di98ze++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:329:29)
I20150323-15:40:35.490(5.5)?     at CleartextStream.emit (events.js:95:17)
I20150323-15:40:35.490(5.5)?     at CleartextStream.<anonymous> (_stream_readable.js:764:14)
I20150323-15:40:35.490(5.5)?     at CleartextStream.emit (events.js:92:17)
I20150323-15:40:35.490(5.5)?     at emitReadable_ (_stream_readable.js:426:10)
I20150323-15:40:35.490(5.5)?     at _stream_readable.js:419:7
I20150323-15:40:35.490(5.5)?     at process._tickCallback (node.js:419:13)
</code></pre>

It seems issue in the new telescope "Table scope" release. 

I had Moved my code to previous version, then my mail sending is fine.

Please help.

**Comment by SachaG** [comment]
@splendido any idea what's going on?

**Comment by splendido** [comment]
> Mail from command failed - 501 : domain literals not allowed

I'd say it's some weird configuration for the sender...

The traceback goes down to `Meteor.methods.forgotPassword` and to `smtpSend`, then probably there's something wrong in the email templates configuration.

...but see the [latest release notes about Meteor Accounts](https://github.com/meteor/meteor/blob/devel/History.md#meteor-accounts) system.
It seems that to specify the `from` you now need a function rather than a static string.

How is this dealt with in Telescope?

**Comment by splendido** [comment]
See also the full docs about [Accounts.emailTemplates](https://docs.meteor.com/#/full/accounts_emailtemplates)

**Comment by xavcz** [comment]
Hey, @renuanil08! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
