### ISSUE TITLE
Translate UserAccounts forms

### ISSUE THREAD

**Issue by nicolasiensen** [TelescopeJS/Telescope#844]
Hey, I'm trying to get the register and sign in forms translated to pt-BR, but I can't.

I tried to change the language in settings but it didn't solve the problem.

Thoughts?

**Comment by splendido** [comment]
Hello @nicolasiensen,
Even if Telescope is using [tap-i18n](https://atmospherejs.com/tap/i18n) to provide i18n support, UserAccounts is still based on [accounts-t9n](https://atmospherejs.com/softwarerero/accounts-t9n)

The langiages available right now can be found [here](https://github.com/softwarerero/meteor-accounts-t9n/tree/master/t9n). And you can learn how to define new translations [here](https://github.com/softwarerero/meteor-accounts-t9n#define-translations): basically you should start off the [English file](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/en.coffee) and translate the right hand side of each row.

Please also consider to contribute there with a PR

**Comment by splendido** [comment]
Also I have plans to support `tap:i18n` for useraccounts@2.0...

**Comment by nicolasiensen** [comment]
I've noticed that UserAccounts doesn't have a pt-BR translation file, and that's why I'm not getting the forms translated.

My quick fix was to change the Telescope language on settings to pt (portuguese from Portugal) since UserAccounts does have this translation option.

The ultimate solution for this issue is to create a pt-BR translation for UserAccounts lib.

Thanks @splendido for the quick reply.

**Comment by splendido** [comment]
I'll notice down you're a potential contributor for `pt-BR`.
I'll get back to you soon ;-)

**Comment by nicolasiensen** [comment]
I would be glad to help!

**Comment by splendido** [comment]
Tnx!

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And by the way, there is an awesome package with `pt-Br` translation now, surely based on yours! 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
