### ISSUE TITLE
Move ``lib/users.js`` to a package?

### ISSUE THREAD

**Issue by yourcelf** [TelescopeJS/Telescope#848]
We're trying to make our fork of telescope be less divergent from master by moving all of our customizations into packages.

We depend on modifying the behavior of many of the methods in ``lib/users.js``, so that we can e.g. have different rules for what constitutes an admin.  But we've found that it's really hard to get consistent results in overriding the global-scope variables from the main project via an export from a package.  By contrast, we can get consistent results overriding a global-scope variable exported by another package, as long as it doesn't use a ``Meteor.startup(...)`` wrapper and we do.

Is there any reason not to move ``lib/users.js`` into either ``telescope-lib`` or ``telescope-base``?  That would let us do the overrides we need from a custom package.

**Comment by jshimko** [comment]
I just happen to be working on combining telescope-base, telescope-lib, and other general lib-type stuff into one main lib package right now.  I wrote a custom plugin for Telescope that I want to publish in Atmosphere, but it currently depends on both of those packages.  The problem with that is Atmosphere won't let you publish when you have local dependencies.  So yeah, that's all getting wrapped up into a common package and published to Atmosphere.  

But first I'm working on adding all of it to a single organized global namespace with a constructor, prototypes, etc. so we can start working toward cleaning up the namespace craziness.  Sacha and I already started talking about this in the Telescope Slack channel recently and there's a card on Trello.  I'm totally open to having as much dialog about design decisions as possible while I'm working on this.  You are more than welcome to join in.  (just created the #namespacing channel in Slack)

A little light reading to get the juices flowing...
http://addyosmani.com/blog/essential-js-namespacing/

:)

**Comment by SachaG** [comment]
Yeah, I agree that would be better. It'd be great to consolidate all of this into packages. 

There was also talk with @dburles of maybe using collection helpers to replace some of the users-related stuff.

By the way there's also a PR to put user templates in their own package, but it's not quite up to date: https://github.com/TelescopeJS/Telescope/pull/778

**Comment by PranayShah** [comment]
I too find the need for this. I wanted to be able to use the clearSeenMessages function defined [here] (https://github.com/TelescopeJS/Telescope/blob/master/lib/router/filters.js#L17), but well, I could not. Would it be possible to make the entirety of the /lib folder into a package?

**Comment by SachaG** [comment]
Yes, @jshimko is working on just this :)

**Comment by jshimko** [comment]
The big refactor took care of this.
