### ISSUE TITLE
[Feature] Ctrl+Enter to submit post

### ISSUE THREAD

**Issue by dandv** [TelescopeJS/Telescope#850]
Nice shortcut, adopted by various web apps.

**Comment by SachaG** [comment]
It's on the roadmap. PRs welcome!

**Comment by xavcz** [comment]
Hey @jgdovin @dandv, this feature was on Telescope Legacy (blaze) but doesn't exist anymore with the React-based version: I opened a new issue with a step by step guide to do it, if you are interested : #1471 👍
