### ISSUE TITLE
Implemented Reactive Table for the Users dashboard (thanks @jshimko!).

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#851]
Is there any way to make this responsive ? thanks @jshimko @SachaG

**Comment by SachaG** [comment]
Do you know a good responsive table implementation?

**Comment by john-henry** [comment]
I've used this before to good effect. Might be worth scoping it out
http://fooplugins.com/plugins/footable-jquery/

**Comment by awrelll** [comment]
Bootstrap also handles responsive tables pretty well 
http://jasonbradley.me/bootstrap-responsive-tables/

**Comment by SachaG** [comment]
The bootstrap one might work. I'll have to see about adding that CSS.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
