### ISSUE TITLE
Update the package that depends on npm-bcrypt

### ISSUE THREAD

**Issue by dandv** [TelescopeJS/Telescope#861]
Looks like [mdg has already published a Windows build for npm-bcrypt](https://github.com/meteor/meteor/blob/devel/packages/non-core/npm-bcrypt/package.js), but when I run `meteor` on Windows I get

>  While checking for npm-bcrypt@0.7.8_1:
   error: No compatible build found

**Comment by Sizz31** [comment]
I am non-technical and a total beginner with Meteor and Telescope and have had this issue (using windows also), the workaround I used is:

meteor --release 1.1-rc.0 --allow-incompatible-update

No idea if that is best practice or safe to do, but it did work (using v0.15_rc of Telescope), if that is of any help..

**Comment by SachaG** [comment]
Which package is that?

**Comment by PILO7980** [comment]
I had the same error, but after a "meteor uptade" it worked fine.

**Comment by dandv** [comment]
> Which package is that?

[Figuring out a tree of package dependencies isn't trivial].

**Comment by dandv** [comment]
After updating to 1.1, the problem went away. Perhaps worth committing the resulting `.meteor/{release,versions}` ?

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
