### ISSUE TITLE
Too many network requests and data transfer

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#864]
I setup a fresh clean Telescope site on Ubuntu server with master branch (without any code change).
When I go to http://url:3000/, it takes about 10 seconds for the initial visit (downloading tons of javascript and octet-stream), and within 15 seconds I got 526 requests and 5.0 MB transferred.
Is there a bug? How can I disable or reduce so many javascript and octet-stream requests and transfer.

**Comment by SachaG** [comment]
It sounds like you're running Meteor in development mode?

**Comment by xuanus** [comment]
Thank you, SachaG.
Works better if I run it as: 
sudo meteor run --port 80 --production
