### ISSUE TITLE
create a scripts folder for improve development

### ISSUE THREAD

**Issue by Kikobeats** [TelescopeJS/Telescope#865]
I need to do some typical things for be sure that all is working fine.

Things like:

- check that emails it's ok
- check that fetch post from feeds works.
- [ADD YOUR CASE OF USE]

At this moment for do it, I go to the browser, I put a random code in the console and wait the result.

What do you think about add a little directory called `scripts` with a collection of useful methods to use?

**Comment by SachaG** [comment]
Wouldn't tests be better for that?

**Comment by Kikobeats** [comment]
better both: tests for be sure that works fine, but I'm thinking more in scripts for helper the development and make actions in the moment that you want, like fetch posts now for check how is integrated with the view, send me a mail because I customize the template and I want to check... this type of things.

**Comment by SachaG** [comment]
Oh ok. There are a couple methods like this already (like `fetchFeeds`), but we could standardize them a bit maybe. I don't think it's a super high priority, but maybe we can do it whenever we consolidate the API for adding settings.

**Comment by xavcz** [comment]
I looked around in the codebase, we do not have anymore methods like that, apart the test email which is enabled in `nova:debug`: you can test it by activating a button.

When we add new "test" method, we will add them to `nova:debug` with the same kind of nice UI telling you if it succeeded or not :rocket:

Closing this.
