### ISSUE TITLE
Why are there so much files to display the posts in list ?Is this specific to meteor ?

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#871]
Yesterday I have installed Telescope with no errors... All good
And today I wanted to do some change how the the posts are displayed at the home page . So when I go to Telescope/client/views/posts/ I see that just to display 3 line there are maybe 27 files involved just in these folders. Is this specific to meteor ? Thank you

**Comment by SachaG** [comment]
The template are split into many files so that you can override each template fragment individually. It's not a Meteor thing, just a decision made for Telescope.

**Comment by Aklibaitiche** [comment]
Ok Thank you.
