### ISSUE TITLE
New field created from the collection post file.Form saving Ok. But how to display it ?

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#872]
Resolved. Meteor have a pretty simple process to create a field and display it by just call the field name that you have given in the collectionName.js .

**Comment by SachaG** [comment]
Glad you found a solution. By the way, this is not really an “issue”. For general questions like this, http://meta.telesc.pe is better :)

**Comment by Aklibaitiche** [comment]
Ok. Thank you :)
