### ISSUE TITLE
request for admin

### ISSUE THREAD

**Issue by trebsirk** [TelescopeJS/Telescope#874]
I don't see a way a random user can request admin status. It seems that the admin can bestow this status, but it is unclear how a user can contact the admin for a request. 
It could be done via email or notification to current admin. 
Request for adminship could be a checkbox in user profile, or separate form.

**Comment by SachaG** [comment]
It's probably the kind of thing that happens infrequently enough that it can happen outside of Telescope. 

I feel like if you had a site with thousands of users you wouldn't really want anybody to be able to randomly ask for admin status, so I'm not really convinced a form or button inside the app is really needed…?
