### ISSUE TITLE
Problem on the post body display

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#886]
Markdown syntax allows to insert html. Why when i add the balise <center> or the style attribute telescope saves all, but when I look in the html sended to the client there are not there.

**Comment by SachaG** [comment]
Sorry, most HTML tags are not allowed for security reasons. You can use regular Markdown though. 

Allow tags are:

```
        'h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul',
        'ol', 'nl', 'li', 'b', 'i', 'strong', 'em', 'strike',
        'code', 'hr', 'br', 'div', 'table', 'thead', 'caption',
        'tbody', 'tr', 'th', 'td', 'pre', 'img'
```

**Comment by Aklibaitiche** [comment]
Ok thank you Sacha but if I want to center a title ? Where can I change that ?

**Comment by Aklibaitiche** [comment]
I will use css on markdown classes ...
