### ISSUE TITLE
In Comment edit form, Comment label disappears when mouse hovers. Submit button is gray.

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#887]
Repro step:

1. create a new comment
2. edit the comment (http://demo2.telescopeapp.org/comments/*CommentID*/edit)

Issue 1: Submit button is gray
Issue 2: Comment label disappears when mouse hovers the edit form

**Comment by kai101** [comment]
#889 for Issue 1

**Comment by kai101** [comment]
#890 fix both style issue.
Pull request summited.
