### ISSUE TITLE
Body edited and seem saved but displayed without the change :( ?

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#888]
I don't know what I have done. In the meantime I have just used https://github.com/aldeed/meteor-console-me/ . I don't know if this is a bug. If I have a little understood the minimongo concept the minimongo seems to not be updated.

**Comment by SachaG** [comment]
I need more info to help you. But note that there's two body fields, `body` and `htmlBody`. Maybe that's the problem?

**Comment by Aklibaitiche** [comment]
Thank for your help sacha .. You are right when I look the mongodb data with the shell the body field has my last update but htmlBody who is displayed has still the old value.

**Comment by Aklibaitiche** [comment]
A little more info : I have added a field summary in the post.js collection, in postSchemaObject  between title and body .

**Comment by SachaG** [comment]
What is the problem exactly?

**Comment by Aklibaitiche** [comment]
No it's Ok. I have replaced htmlBody by body and now I have no more problem of update and I can use html tag as I want (https://github.com/TelescopeJS/Telescope/issues/886). It's just a prototype I just want to test quickly the idea. Thanks you
