### ISSUE TITLE
Sitemap not updating with the Site URL

### ISSUE THREAD

**Issue by wootwoot1234** [TelescopeJS/Telescope#891]
Hello.

I just installed telescope and switched from a temp domain to my actual domain. I updated the Site URL field in the settings but when I pulled up sitemap.xml and it's still linking to my old temp domain. The feed.xml file is using the correct domain. Any ideas?

I was told to mention @yourcelf.

Thanks!

**Comment by yourcelf** [comment]
It looks like the library we're using for sitemaps [reads its base URL from ``Meteor.absoluteUrl``](https://github.com/gadicc/meteor-sitemaps/blob/c09d4c77c83818f9c169ca422877cb5eed53995f/sitemaps.js#L21), not from telescope settings.  ``Meteor.absoluteUrl`` in turn gets its result from the [``ROOT_URL`` environment variable](http://docs.meteor.com/#/full/meteor_absoluteurl).

Short of getting upstream changes or forking ``gadicohen:sitemaps`` it looks like we can't currently coerce it into using the Telescope settings URL.  For now, you could get the result you want by making sure the ``ROOT_URL`` environment variable where Telescope is running is set to the correct thing.  I've opened an issue with ``gadicohen:sitemaps`` to see how we might be able to resolve.

**Comment by wootwoot1234** [comment]
Thanks!  Updating the ROOT_URL fixed my issue.

**Comment by SachaG** [comment]
Note that Telescope resets Meteor.absoluteUrl to the siteUrl setting, but that probably happens after the sitemap package does its thing. 

Anyway, it's probably a good idea to have a correct ROOT_URL anyway. Closing this for now, thanks @yourcelf!
