### ISSUE TITLE
Cron Job?

### ISSUE THREAD

**Issue by wootwoot1234** [TelescopeJS/Telescope#892]
I'm using an rss feed to post to telescope but it doesn't seem to pull the latest data from the rss feed automatically.  I keep needing to call Meteor.call('fetchFeeds');.

Do I need to set up a corn job that calls a url?

Thanks.

**Comment by azizur** [comment]
Hi @wootwoot1234,

I am using it locally right now.. and everything working for me.

I did not need to setup any cron job at all. It's all handled by `packages/telescope-post-by-feed/lib/server/cron.js`

**Comment by Accentax** [comment]
I deployed to meteor.com and am having the same issue. In mongodb I am getting the following: 
db.cronHistory.findOne({"name":"Post by RSS feed"})                                             
{
        "_id" : "SrQmNh3fmpCEWXYMw",
        "error" : "ReferenceError: fetchFeeds is not defined\n    at Object.SyncedCron.add.job (packages/telescope-pos
t-by-feed/lib/server/cron.js:16:1)\n    at packages/percolatestudio:synced-cron/synced-cron-server.js:157:1\n    at sc
heduleTimeout (packages/percolatestudio:synced-cron/synced-cron-server.js:205:1)\n    at packages/percolatestudio:sync
ed-cron/synced-cron-server.js:248:1\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:
1)\n    at packages/meteor/timers.js:6:1\n    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)",
        "finishedAt" : ISODate("2015-04-06T10:30:00.017Z"),
        "intendedAt" : ISODate("2015-04-06T10:30:00Z"),
        "name" : "Post by RSS feed",
        "startedAt" : ISODate("2015-04-06T10:30:00.008Z")
}

**Comment by azizur** [comment]
@wootwoot1234 apologies I was on a older version and it was working.

I just downloaded latest version and its not working. I am looking into it right now. If I manage to fix I'll send out a pull request.

**Comment by delgermurun** [comment]
Woa critical bug. I introduced in on a05fa134e44ffc397c7b7c3ebeba7bbae70eb024. Sorry about that.

**Comment by SachaG** [comment]
No worries, fix coming in the next release :)
