### ISSUE TITLE
Embedly images and upvote/social buttons not scaling properly on Android mobile.

### ISSUE THREAD

**Issue by onetallorder** [TelescopeJS/Telescope#895]
[Here](http://imgur.com/XnxFUUl) is a screen shot.  The thumbnail is stretched and the button is just barely visible on the right side.  This is on an Android phone, and I had the same results with the base and UC Browser.  However, it works just fine in Chrome for Android.

**Comment by xavcz** [comment]
Hey, @onetallorder! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
