### ISSUE TITLE
Running on a standard Aws Micro instance, 18s to 34s to load for the index page with 10 posts ?

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#897]
Deployed on a standard Aws Micro instance, 18s to 34s to load all the files for the index page with 10 posts . Also there are 7 mb of data for all . It's a lot no ? What can I do to optimize that ?

**Comment by SachaG** [comment]
Sounds like you're running in development mode. I would recommend using Meteor Up unless you have a good reason not to?

**Comment by Aklibaitiche** [comment]
Ha yes ! this is what I was wondering . So Meteor Up will minify all the files ?

**Comment by SachaG** [comment]
Well, Meteor will do that. But Meteor Up will properly configure your
server to run in production mode.

**Comment by Aklibaitiche** [comment]
Ok
