### ISSUE TITLE
Categories sort

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#898]
Hello,
Is there any way to sort categories other that date ?  When i submit a new post the categories ar shown in the added order only.

**Comment by awrelll** [comment]
I mean if i add a new language i can't put it with other languages, it will just be under Lounge
![screen shot 2015-04-08 at 14 12 36](https://cloud.githubusercontent.com/assets/6716597/7044198/6ac4abd0-ddf9-11e4-9f7d-91127b35b109.png)

**Comment by SachaG** [comment]
Categories have an "order" parameter. I just tested it and it seems to work?
