### ISSUE TITLE
Cannot signout

### ISSUE THREAD

**Issue by mitar** [TelescopeJS/Telescope#900]
I thought that I signed in with Meteor account in the past and I tried to do that, but then I saw that I have an username. But now I cannot sign out. When I press sign out, I keep being signed in.

**Comment by SachaG** [comment]
Oh, I think that can happen when you have two accounts with the same email. You probably need to ask the admin to delete one of them.

**Comment by mitar** [comment]
This is happening on Crater.io. I do not think I have the same e-mail address.

**Comment by SachaG** [comment]
Well I just deleted your second account. So you should be able to log in again with your email now.

**Comment by mitar** [comment]
Thanks! It works.
