### ISSUE TITLE
Cannot remove telescope-tags package

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#901]
Using "meteor remove telescope-tags" to remove telescope-tags package, telescope-tags is removed in /.meteor/packages.
However, telescope-tags@0.0.0 is still in /.meteor/versions, even remove it manually. 

Is it due to no version # in /packages/telescope-tags/package.js?

**Comment by SachaG** [comment]
That's strange… In any case if the package is not in `/packages` I don't think it can be loaded.

**Comment by xuanus** [comment]
Is it due to no version number in /packages/telescope-tags/package.js?
The default version number is 0.0.0

**Comment by SachaG** [comment]
Maybe, but I don't think so. It might just be a bug in Meteor? Are you sure the package is really loaded? Do categories still appear in the app?

**Comment by xuanus** [comment]
Yes, it might be a bug in Meteor.

You can run "meteor remove telescope-tags" and "git status"
Get "modified:   .meteor/packages"
But no "modified:   .meteor/versions"

The package is loaded and categories still appears.

**Comment by SachaG** [comment]
Hmm… So the package really is removed from `.meteor/packages` but still
gets loaded? That's definitely a bug.
