### ISSUE TITLE
post is not defined, when calling postAfterEditMethodCallbacks

### ISSUE THREAD

**Issue by delgermurun** [TelescopeJS/Telescope#903]
[collections/posts.js#L499](https://github.com/TelescopeJS/Telescope/blob/master/collections/posts.js#L499)

on server's error log:
```
Exception in defer callback: ReferenceError: post is not defined
I20150410-16:16:21.646(9)?     at app/collections/posts.js:499:37
I20150410-16:16:21.647(9)?     at Array.forEach (native)
I20150410-16:16:21.647(9)?     at app/collections/posts.js:498:38
I20150410-16:16:21.647(9)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150410-16:16:21.647(9)?     at packages/meteor/timers.js:6:1
I20150410-16:16:21.647(9)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)

```

**Comment by delgermurun** [comment]
Maybe we should pass updated post to callback?

**Comment by SachaG** [comment]
Oh, I think we modified it here: https://github.com/TelescopeJS/Telescope/pull/875/files

What if we just pass `postId` instead of `post`?

**Comment by delgermurun** [comment]
Okay. `postId` works too.

**Comment by saimeunt** [comment]
https://github.com/TelescopeJS/Telescope/pull/905

I'm the one responsible for introducing this issue, here is the fix on a new PR.

The thing is, we need to pass the callback both the modifier and the post before it was updated so we can compare the two and optionally perform tasks depending on the result. (like not fetching embedly data once again if the post URL did not change).

When performing the PR I forgot about adding a line to fetch the post before it is updated, sorry about that.

**Comment by SachaG** [comment]
Oh good point. Thanks!
