### ISSUE TITLE
Can't set daily and single day as a default page layout in the admin setting.

### ISSUE THREAD

**Issue by mhlavacka** [TelescopeJS/Telescope#904]
After updating version of Telescope, I no longer see daily option for default layout in settings. How do I set it manually ?

**Comment by SachaG** [comment]
Yep, that's a bug. Just pushed [a fix](https://github.com/TelescopeJS/Telescope/commit/bca4d19562fc2f577c9a49df8190865dd77bbc3b) for it, sorry about that.

**Comment by mhlavacka** [comment]
Thank you
