### ISSUE TITLE
upvote/downvote buttons of comment overlay content of comment in Mobile View

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#907]
In mobile view or small screen device
upvote/downvote buttons of comment misaligned.

**Comment by SachaG** [comment]
Which device was that on? Would you have a screenshot by any chance?

**Comment by xuanus** [comment]
![a](https://cloud.githubusercontent.com/assets/9119888/7104327/e7998fbe-e08c-11e4-8378-2bbc04fcc182.png)
![b](https://cloud.githubusercontent.com/assets/9119888/7104328/e9e20dc8-e08c-11e4-9aa7-0b97f2e9b916.png)

**Comment by xuanus** [comment]
You can repro just by resizing your browser

**Comment by SachaG** [comment]
Oh that's on purpose, it's just a way to save space.
