### ISSUE TITLE
Newsletter Crash if Original Poster Deleted

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#910]
So I've spent 2 hours trying to figure out why I was getting server 500 errors running Meteor.call('testCampaign');

Turns out, I'd deleted Bruce Willis and the other dummy users in the default installation, but I hadn't deleted their posts. When you do that and try to generate a newsletter, you get this issue because of this line:

[XXXXXXX.com] TypeError: Cannot read property 'slug' of undefined[xxxxxxxx.com] at getProfileUrl (app/lib/users.js:43:38)

This should probably be beefed up to handle a missing user.slug instead of crashing because I can definitely foresee deleting user accounts and it shouldn't break the newsletter.

**Comment by nrodastiscornia** [comment]
I might be able to jump in and help with this one. Any ideas or suggestions? how would you like to handle this?

**Comment by nrodastiscornia** [comment]
https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-newsletter/lib/server/campaign.js#L31

```javascript
    var postUser = Meteor.users.findOne(post.userId); // This comes undefined

    // the naked post object as stored in the database is missing a few properties, so let's add them
    var properties = _.extend(post, {
      authorName: Users.getDisplayName(post),
      postLink: Posts.getLink(post),
      profileUrl: Users.getProfileUrl(postUser), //HERE
      postPageLink: Posts.getPageUrl(post),
      date: moment(post.postedAt).format("MMMM D YYYY")
    });
```

Haven't got too much time to take a look but i think here is where the problem starts, when there's no user

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. Thanks for fixing this issue a while ago, I'm closing it. 😼

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
