### ISSUE TITLE
Show notification settings to non-signed-in users

### ISSUE THREAD

**Issue by lorensr** [TelescopeJS/Telescope#911]
When I click "Change your notifications settings" in the Crater.io new-posts email, I get a blank page unless I'm logged in. Either:

A) It should prompt me to login, or
B) Preferred solution: include a secret in the URL so that I do not need to login in order to change my notification settings.

**Comment by xavcz** [comment]
Hey, @lorensr! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
