### ISSUE TITLE
GoSquared Integration

### ISSUE THREAD

**Issue by jamiewilson** [TelescopeJS/Telescope#914]
Hey Sacha, was curious about the reason that GoSquared integration was removed? It seems like just the input on the settings page for the account ID has been removed, but the tracking and events code is still in place. 

https://github.com/TelescopeJS/Telescope/search?utf8=%E2%9C%93&q=gosquared

I've added that input back in on my fork, added my ID and it seems to work fine. Just want to make sure I'm not doing something that problematic. Thanks man!

**Comment by SachaG** [comment]
No it's fine, I just removed it in prevision of overhauling the analytics/tracking system to use Segment.io instead. There will also be a simple API so you can easily add new analytics providers too. 

See: https://github.com/TelescopeJS/meteor-events

**Comment by jamiewilson** [comment]
ooooh. This is really great news! Somehow I missed the #analytics channel on slack. Thanks man.

**Comment by xavcz** [comment]
Hey, @jamiewilson! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
