### ISSUE TITLE
Error caught on publication:  postUsers :  Cannot read property 'userId' of undefined

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#915]
When I run Telescope for a while, even with latest code without any modification, I keep getting the following error. 

=> App running at: http://localhost:3000/
W20150411-20:50:57.536(-7)? (STDERR) error caught on publication:  postUsers :  Cannot read property 'userId' of undefined

**Comment by SachaG** [comment]
Yes, I've run into that a couple times as well. I haven't been able to reproduce it consistently yet though…

**Comment by l4u** [comment]
I'm having the same error as well 
```
at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
stderr:
 error caught on publication:  postUsers :  Cannot read property 'userId' of undefined
```

**Comment by thowar2** [comment]
I am having a similar error in my logs.

```
[104.131.113.91]     at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
stderr:
error caught on publication:  postUsers :  Cannot read property 'userId' of undefined
```

My instance keeps crashing, requiring restart, not sure if this is the cause or not.

@SachaG I'm happy to give you access for debugging if you like.

**Comment by SachaG** [comment]
Well I see the same error when running Telescope locally, it's just that I see it maybe once per hour and it doesn't seem to affect anything. I haven't found a way to trigger it on purpose.

How often are you guys seeing it in the logs?

**Comment by thowar2** [comment]
@SachaG I'm not sure how to check the logs, but the app fatally crashes 1-2 times per day, which I am fixing with a power cycle.

**Comment by SachaG** [comment]
Hmm that's a problem. How are you running it? What's your setup?

**Comment by thowar2** [comment]
Have the app (and DB) on a DigitalOcean droplet.

**Comment by SachaG** [comment]
It's not recommended to run your DB on the same droplet. I would suggest trying out Compose.io and seeing if it fixes the problem.

**Comment by thowar2** [comment]
My issue was with `spiderable` exhausting memory: `Apr 21 11:48:40 SimplyHustle kernel: [ 3879.965973] Out of memory: Kill process 1381 (phantomjs) score 482 or sacrifice child`

Related: #597 

Seems to be solved by upgrading to 1GB droplet.
