### ISSUE TITLE
WebSocket Error 400

### ISSUE THREAD

**Issue by l4u** [TelescopeJS/Telescope#918]
I've installed it by mup on a fresh Digital Ocean instance. On the browser client side, there is an error ` Error during WebSocket handshake: Unexpected response code: 400`

**Comment by SachaG** [comment]
Does the error affect the app in any way?

**Comment by palmdeezy** [comment]
Getting the same error on a fresh Digital Ocean install too.

    WebSocket connection to 'ws://45.55.243.48/sockjs/594/fwuotuhc/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
