### ISSUE TITLE
Upstream remote sync

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#920]
Hello, i just did a upstream merge and i get this error : 

"This project says that it uses Meteor <<<<<<< HEAD, but you don't have that version of Meteor installed and the Meteor update servers don't have it either. Please edit the .meteor/release file in the project and change it to a valid Meteor
release."
My release file looks like this : 

"
<<<<<<< HEAD
METEOR@1.1
=======
METEOR@1.1.0.2
>>>>>>> upstream/master

"

I tryed updating my meteor version but i get the same error. Can i get some help please ? 
Thanks!

**Comment by SachaG** [comment]
Looks like you have a git conflict? That's what the `<<<<<<< HEAD` part means. I would read up on Git and how to fix merge conflicts.
