### ISSUE TITLE
[Feature Request] Open URL in post body in a new browser tab

### ISSUE THREAD

**Issue by xuanus** [TelescopeJS/Telescope#923]
If clicking a URL like "https://github.com/" in post body, it won't be opened in a new browser tab.
We are losing user engagement.

**Comment by SachaG** [comment]
I think the consensus for this issue is that if users want to open a URL in a new tab, they can choose to ctrl/cmd+click. I don't think it's a good idea to force users to *always* open URLs in new tabs.
