### ISSUE TITLE
Inconsistent Titles/SEO

### ISSUE THREAD

**Issue by arist0tl3** [TelescopeJS/Telescope#926]
Please feel free to correct me if I'm wrong, as I'm pretty new to Telescope/Git, etc...

As things stand now, here is how titles are appearing on a site I'm running:

On first load -> TITLE: TAGLINE
All -> ALL | TITLE
Returning to home page after another page -> TITLE -- TAGLINE | TITLE

Seems pretty inconsistent to me -- the changes I made that resulted in consistent titling across all pages:

https://gist.github.com/arist0tl3/431fa3d19c62e14048d9#file-gistfile1-txt

**Comment by SachaG** [comment]
You're right, thanks for pointing this out :)

**Comment by arist0tl3** [comment]
No problem! Awesome work!

**Comment by xavcz** [comment]
Hey, @arist0tl3! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And by the way, it's working well now 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
