### ISSUE TITLE
Loadmore option not working

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#928]
Loadmore option for single day and daily posts are not working in mozilla

**Comment by ajaykumaran** [comment]
It is seen that Crunch Hunt site also has this problem in Firefox. Whicle clicking on 'Load More' an error comes as below

ReferenceError: event is not defined
...Limit.get(),loadMoreHandler:function(e){event.preventDefault();var a=e.postsLimi...
4cb54fb...1c35.js (line 261, col 7343)

**Comment by brianshumate** [comment]
*Load more* also causes an Aw Snap! crash in the tab on Chrome 43.0.2357.81 (64-bit) for OS X.

*Load more* also crashes Safari on iOS 7.1.2 after a few taps, and causes A problem occurred with this webpage so it was reloaded dialog in Safari on iOS 8.3 after 4-5 taps.

**Comment by irazasyed** [comment]
I thought i was doing something. Good i found this ticket! Following...

**Comment by arist0tl3** [comment]
Not sure why this is browser-specific, but commenting out event.preventDefault() in the loadMoreHandler restores functionality in my FF case.

**Comment by brianshumate** [comment]
Same here; **Load More** works in Firefox with `event.preventDefault()` commented out, and Chrome on OS X seems to load many pages without the tab crashing anymore. However, Safari on iOS still crashes after 4-5 taps of **Load More**.

**Comment by kayue** [comment]
This still hasn't been fixed yet.

**Comment by SachaG** [comment]
Seems to work for me on http://meta.telescopeapp.org/ (Firefox Mac OS). Do you still see the problem there?

**Comment by kayue** [comment]
@SachaG http://meta.telescopeapp.org/ is working fine for me. I am using Firefox.

However my local, clean Telescope installation doesn't work.

**Comment by kayue** [comment]
@SachaG I saw you removed that line. Any idea how to update Telescope to the master version via Meteor? I would like to test it out. Thanks.

**Comment by kayue** [comment]
@SachaG Oh you just released a new version. It fixs the problem. Thanks :+1:

**Comment by brianshumate** [comment]
:) Seems to be working fine now. Thanks!

**Comment by SachaG** [comment]
Awesome, thanks to @kayue for identifying the problem :)
