### ISSUE TITLE
Can't deploy v0.15.1

### ISSUE THREAD

**Issue by artiparty** [TelescopeJS/Telescope#929]
I’m trying to `mup deploy` an updated Telescope v.0.15.1 that works fine locally and getting this error - http://pastebin.com/iPAJLNRF

`mup logs` returns:
_Meteor requires Node v0.10.36 or later._

It's weird, cause I’m running Node v0.12.2 :disappointed: 
(full `mup logs` http://pastebin.com/Juxg6084)

Any ideas how to fix it?

**Comment by thinkxl** [comment]
I can't deploy either, here are my logs:

```
	✘ Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
         ERR! cwd /opt/frontendsapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
        gyp ERR! node -v v0.12.2
        gyp ERR! node-gyp -v v1.0.3
        gyp ERR! not ok
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        child_process: customFds option is deprecated, use stdio instead.
        ../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
        ../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialize in this function [-Wmaybe-uninitialized]
           if (tls == thread_id) {
           ^
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        Release/obj.target/fibers.node: Finished
          COPY Release/fibers.node
        make: Leaving directory `/opt/frontendsapp/tmp/bundle/programs/server/node_modules/fibers/build'
        Installed in `/opt/frontendsapp/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
        underscore@1.5.2 node_modules/underscore

        chalk@0.5.1 node_modules/chalk
        ├── ansi-styles@1.1.0
        ├── escape-string-regexp@1.0.3
        ├── supports-color@0.2.0
        ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
        └── strip-ansi@0.3.0 (ansi-regex@0.2.1)
        
        semver@4.1.0 node_modules/semver

        eachline@2.3.3 node_modules/eachline
        └── type-of@2.0.1

        source-map-support@0.2.8 node_modules/source-map-support
        └── source-map@0.1.32 (amdefine@0.1.0)
        
        fibers@1.0.5 node_modules/fibers
        Waiting for MongoDB to initialize. (5 minutes)
        connected
        frontendsapp stop/waiting
        frontendsapp start/running, process 17361
        Waiting for 60 seconds while app is booting up
        Checking is app booted or not?
        frontendsapp stop/waiting
        frontendsapp start/running, process 17790
        ----------------------------------------------------------------------------
```

mup return this:

 [34m[1m
Meteor Up: Production Quality Meteor Deployments[22m[39m
[34m[1m------------------------------------------------
[22m[39m
[104.131.7.145]     at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/frontendsapp/app/programs/server/boot.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
error: Forever detected script exited with code: 1```

```

**Comment by jshimko** [comment]
Wrong Node version guys.  That log output is misleading.  Meteor requires 0.10.36.  Node 0.12.x will definitely not work.  Start over with a fresh setup and let MUP do the dependency installs for you.

**Comment by artiparty** [comment]
Do I have to start over or downgrading the Node version might work?

**Comment by valgalin** [comment]
If you're using DigitalOcean, create a fresh droplet, like an Ubuntu 14.04 server with nothing on it. Deploy using MUP with the default 0.10.36 node version. Make sure you're using the latest MUP version. If you're using an old version, just change the node version entry to 0.10.36 and MUP will auto-install it to your server.
