### ISSUE TITLE
Not able to order titles in the views menu

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#931]
By using single day and daily package, I created weekly, monthly, quarterly and yearly view.  But when I added these to views menu it comes in different order. I mean yearly first, second weekly like that. When i push these titles to the view menu i gave the order field.  but it still shows the same problem. Is there any solution to solve this?.

**Comment by disqvr** [comment]
Would be great if you could make these packages publicly available! I would like to make the same and that would be a nice starting point. Thanks

**Comment by SachaG** [comment]
This should be fixed on the `devel` branch.
