### ISSUE TITLE
Users that are already registered to the mailing list cannot register to the site

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#933]
Using the same email (triggers MailChimp error).

**Comment by demerino** [comment]
Just ran into this. On a related note - it isn't clear how an existing user can add themselves to the mailing list if the banner has been dismissed (or edit their subscription status to the mailing list).

**Comment by SachaG** [comment]
Yes, there isn't really a great way to do it right now I'm afraid.

**Comment by SachaG** [comment]
This seems to be fixed somehow.

**Comment by SachaG** [comment]
Oh no, not fixed after all!

**Comment by SachaG** [comment]
*Now* it's fixed :)
