### ISSUE TITLE
Meteor Error -> MongoDB cannot open or obtain a lock on a file

### ISSUE THREAD

**Issue by rishabhcf** [TelescopeJS/Telescope#935]
Hi,

I am trying to setup Telescope but I keep getting this error. 

```
=> Started proxy.                             
Unexpected mongo exit code 45. Restarting.    
Unexpected mongo exit code 45. Restarting.    
Unexpected mongo exit code 45. Restarting.    
Can't start Mongo server.                     
MongoDB cannot open or obtain a lock on a file
```

I have tried `meteor reset` i have tried `sudo meteor` .. i have tried to delete `.meteor/local/db/mongod.lock` nothing worked.

**Comment by mariorodriguespt** [comment]
I think you have to fix the permissions on your project and also on `~/.npm` directory.
