### ISSUE TITLE
[on namespace2 branch] Pass old post and modifier to "postEdit" and "postEditAsync" callbacks

### ISSUE THREAD

**Issue by delgermurun** [TelescopeJS/Telescope#937]
On `postEdit` callback we need old post to compare fields. For example on `embedly` package we can check whether `url` changed or not.

Also `modifier` and `old post` parameters removed from [`postEditAsync`](https://github.com/TelescopeJS/Telescope/blob/namespace2/packages/telescope-posts/lib/methods.js#L181) callback. We need those for same reason.

**Comment by SachaG** [comment]
You're right. I'll pass `{postId: postId, post: post , modifier: modifier}` as argument instead then.
