### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by pedrocatre** [TelescopeJS/Telescope#944]
If I understand correctly Telescope uses a URL parameter for the pagination. But I think there are a few problems with just using that approach.

1. If the user gets to 100 posts and refreshes, or saves that link, he always gets 100. You could say this is a feature, so that he does not have to scroll again. But part of the idea of pagination is that the user does not ask for 100/200/300/X at the same time. If he gets to see 300 going 25 at a time that would be fine. But if he and many others get 300 from their 1st request than this can be a problem.
2. Also by limiting the limit this way you have to choose a reasonable number (can't be too high) thus a user will never be able to check the history too far back. And if the community is very active information can be lost very fast.

Am I wrong? I apologise in advance if any of the statements is incorrect I am new to this project and to meteor.

**Comment by SachaG** [comment]
No you're right, that's pretty accurate. Currently the maximum limit is 200 post. 

Practically speaking I think this is not a huge issue. Few people are ever going to need to display that many posts, and if they do it probably means we need to improve the search function. 

But I'm open to suggestions. How would your ideal implementation work?

**Comment by pedrocatre** [comment]
Yes I also thought about that, that in practice this might not affect so many people if the search functionality works well. What doesn't feel right is having users grab a few hundred records at the same time when they might not need them at all. It is slower for them and the backend takes a bigger hit.

My ideal implementation would be that they would always have to request X at a time. Not the upper limit that we have. Example always ask for 25 and have no limit, and never be able to ask for 200 in a single request. With this in mind I believe the logic of getting subsequent data would not be at the router level or depend on a router param.

Anyway, this came to my mind and I mostly wanted to hear your thoughts and know if I was making the correct assumptions. Thank you!
