### ISSUE TITLE
category is not work

### ISSUE THREAD

**Issue by Elvenisboy** [TelescopeJS/Telescope#946]
build a category at adminpanle, it worked very nice in my computer .
But,after deploy app in aws ec2 , it was broken.
My domian is 9turn.com
The category url is http://9turn.com/9turn.comcategory/ios , it will return a 404 page.
My nginx conf is 
```
server {
  listen                *:80;

  server_name           9turn.com;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}
```
What should i do ?

**Comment by SachaG** [comment]
Sounds like your site URL is not configured properly in the settings. Is it missing the last "/"?

**Comment by Elvenisboy** [comment]
Oh, yes i miss it .let me have a try.
Thank you~
There is another question:
the url can't have a "http://" header. Shoud i change nginx conf ?
meow~

**Comment by Elvenisboy** [comment]
dear , after i remove my site url , the setting works.
but if i only add "/" ,it couldn't work too.

**Comment by dgmstuart** [comment]
@SachaG I was also a victim of this ;) - it's a very easy mistake to make.

It's not great that the app only errors at this point - ideally it would happen earlier or not at all. I suggest either:

1. add the trailing `/` on save if it's not already there OR
2. add the trailing `/` wherever `siteURL` is used (if it's not already there) OR
3. throw a validation error if it's not present when `siteURL` is saved

I'm trying to work out how you would do this, but I'm not familiar with how meteor works yet.

**Comment by SachaG** [comment]
Yes, I'm working on a fix.
