### ISSUE TITLE
Accept anonymous votes

### ISSUE THREAD

**Issue by Aklibaitiche** [TelescopeJS/Telescope#947]
Most Telescope projects does not work, and one thing that I suspect is the obligation to sign up to vote. This is a big barrier. So make Telescope more success oriented is a good idea for everyone.

**Comment by jgdovin** [comment]
This does not seem like a viable proposition. Most vote style sites require a login as without requiring login voting would/could be skewed very easily.

**Comment by Aklibaitiche** [comment]
One vote for one IP is viable. It's not because they require that you you have to require too :) even if they have succeeded.

**Comment by jgdovin** [comment]
This is still easy to get past with a bot net, hopping proxy or any other automated tasks, easier than multiple emails. This is just my opinion though, I would like to see what others have to say.

**Comment by Aklibaitiche** [comment]
I forgot to mention that it would be an option.If they write a bot just for you site is that you are already very famous .. but the problem you point is not really a problem... And I prefer a website who work and who is attacked than a website with nobody.

**Comment by SachaG** [comment]
Maybe that'd be a good feature for a new package, but I don't really see this being implemented in core. I'm not really aware of any community that lets you vote without being registered.

**Comment by Aklibaitiche** [comment]
Hi Sacha, so if I want to create a package for this, have you directives ? How can I bypass the default restriction for anonymous in a package ?? This is when I think that i should do it with a core option ...

**Comment by jshimko** [comment]
@Aklibaitiche I really don't think you're going to be able to pull this off without making a lot of exceptions.  You can't just do it by IP.  For example, consider if 20 people that worked at the same place wanted to vote on your site.  If they did it from the work network, they could all appear to be coming from the same external IP.  Even your home network would show up as one public IP and all users inside it would have that.  IP address is just not unique enough for identifying individual users.  

The only thing I can think of that would be unique enough and not require login is the use of cookies.  But as you surely know, a user could just clear cookies or not ever store them in the first place.

If you want your votes to actually be accurate, I don't think you're going to find a way to do it without logged in users.

**Comment by SachaG** [comment]
Yeah you can create a package. Just create a brand new `anonymousUpvotes` property (or whatever you want to call it) to track anonymous votes. And you can always combine anonymous and non-anonymous votes to calculate the final score, maybe giving non-anonymous votes a higher weight?

**Comment by Aklibaitiche** [comment]
AnonymousUpvotes seems to be a good name. I think have a complex way to calculate the vote doesn't add value to the user experience and so for the admin... a simple way to calculate so that the user understand the way the figures change is better I think. I will look at that later, it's the night in Paris. jshimko I anwser you asap.

**Comment by Aklibaitiche** [comment]
Hi @jshimko , so yes I know that an IP can represent a large number of users and that a cookies is easily hackable ... And I think also that you are totally right, the IP is not the best idea... But just to explain, I think that systematically ask for a registration is a very bad way (who comes since the beginning of the web ..) for the success of many kind of web apps. Let the user use the app(or a part) as he wants then let it choose to return or not, is a better way to just pass the traction phase easier ...So taking the risk of getting some fake votes worth the shot.
And there are even a solution for fake votes: just save the ip address of each vote and then run a cron task to delete all duplicate votes on the same post that have the same IP?

**Comment by pajooh** [comment]
+1 for anonymous votes
