### ISSUE TITLE
Chinese Name can't load user page

### ISSUE THREAD

**Issue by icindy** [TelescopeJS/Telescope#950]
if i use a chinese name to be my username,i could't open "xxx.com/users/名字".

How to fix it?

**Comment by capensisma** [comment]
yes there is an issue with not just chineese but also arabic and other languages, i will add a quick patch right now

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
