### ISSUE TITLE
Swapping ID js hooks with dedicated ".js-className" class hooks

### ISSUE THREAD

**Issue by andmitsch** [TelescopeJS/Telescope#951]
Though, IDs became a common thing for js hooks, there's an even better solution with simply using a "js-" prefix thus not potentially overwriting or interfering with styles and for more semantic document reasons.

It's quite comfortable and alleviating when going through markup to recognize a class that simply exists exclusively for hook purposes.

**Comment by mikewheaton** [comment]
I support this, and it's a change that could be made slowly to prevent introducing bugs. This is common practice with component-oriented CSS conventions (such as [SuitCSS](https://github.com/suitcss/suit/blob/master/doc/README.md)) where there is a clear separation of style and behavior. It also makes it easier to refactor HTML structure, IDs, and class names without breaking the JavaScript hooks.

**Comment by SachaG** [comment]
Why not. Although IDs should not be used for styling anyway, so if you see one in the code you can be fairly confident that it's used for JS, not CSS.

**Comment by mikewheaton** [comment]
If IDs are already the primary hooks into JS, and not being used for styling, then the benefit of adding classes with the "js-" prefix probably isn't so great. There's already a separation between JS hooks and styling, which keeps the code flexible. Still, adding specific JS hook classes might make for more understandable code that could help those writing themes and packages.

**Comment by andmitsch** [comment]
That's right, yet IDs without further specify are quite fast.

But what I encountered are hollow and functionless IDs throughout the project. Such as in comment_edit there is a #editor, though nothing happens with it.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
