### ISSUE TITLE
Medium.com rich embed broken

### ISSUE THREAD

**Issue by espi** [TelescopeJS/Telescope#958]
The embedly package doesn't display the html in the lightbox correctly for medium.com content.

**Comment by SachaG** [comment]
Hopefully this will be replaced by proper video integration soon anyway.

**Comment by espi** [comment]
The medium.com preview doesn't actually have any video in it so social content embedding is the bigger problem. Embedly seems to be providing the correct html for the emded (http://embed.ly/docs/explore/extract?url=https%3A%2F%2Fmedium.com%2Fconnect-london%2Fbailey-kursar-1e846f1666f) its just not rendering correctly.

Not to get too far off topic but Instagram links from embedly are categorised as 'photo' which then doesn't contain embed html (http://embed.ly/docs/explore/oembed?url=https%3A%2F%2Finstagram.com%2Fp%2F0-l2Ndh6FQ%2F). Would be nice to tackle a rich (& responsive) embed of that content as part of any long term solution.

**Comment by SachaG** [comment]
Well actually, the rich media previews for sites like Medium or Amazon are kind of a side effect of the video feature. So I think what will happen is once we have actual video integration, I'll remove the rich media previews, and if people want them for specific sites they can always add them back in.

**Comment by xavcz** [comment]
Hey, @espi! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
