### ISSUE TITLE
shared login with another app

### ISSUE THREAD

**Issue by dcsan** [TelescopeJS/Telescope#963]
Is there a way to implement a type of "shared signon token" ?

for example if i have `MyApp.com` where a user is logged in with FB/twitter 
using same meteor accounts package. 
I want to have a "discussion" link there to send them to a telescope instance, 
which is at a separate URL eg `forums.MyApp.com`

Is there a way to make it so the user doesn't have to login again to join the discussion on the telescope instance? 

It maybe possible to share the DB between the two apps, although that would mean adding lots of App needed collections to the telescope DB.

**Comment by SachaG** [comment]
I don't know if there's any way to do it without having the user log in again. 

But yeah, if you share dbs at least they shouldn't have to recreate an account. And as long as you don't have Posts/Comments/Settings/etc. collections in your own app, I don't think there'd be any problem?

**Comment by AndrewMagliozzi** [comment]
We had the same problem and wrote this package to handle it: https://github.com/AdmitHub/meteor-shared-auth

**Comment by jshimko** [comment]
@AndrewMagliozzi That's fantastic!  How has your experience been using that package?  Are you using it in a production situation?  How about with more than 2 domains?  

Thanks for sharing!

**Comment by AndrewMagliozzi** [comment]
we are using it in production with SSL on two separate domains.  Never
tried it with more than two, but it should work.

**Comment by SachaG** [comment]
Also relevant: https://kadira.io/blog/sharing-meteor-login-state-between-sub-domains/

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And as we are moving to Apollo in a near future, I guess we won't handle accounts token as before but passport (?) ;  this will be easier at this time 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
