### ISSUE TITLE
Can't select Posts by their catId from minogo or mongo

### ISSUE THREAD

**Issue by capensisma** [TelescopeJS/Telescope#967]
Hi,

May be it's a small bug but i can select a post by category from minogo or mongo both return []

var x = {find: {'categories': {$in: ['WvkeC49iZs576nYYr']}}};Posts.find(x).fetch();//try your category id

and Posts.find().fetch()[0].categories is undefined

Can someone confirm this thanks

:+1:

**Comment by jshimko** [comment]
Issue resolved in Slack chat.
