### ISSUE TITLE
Facebook / Slack sharing preview broken

### ISSUE THREAD

**Issue by timoh** [TelescopeJS/Telescope#970]
When copying a link of a Telescope post (e.g. http://meta.telesc.pe/posts/jFDz39m9oc2W8ey57) to Facebook, or Slack for example, neither services are able to generate a useful preview.

On Facebook, the title always states "Loading..." (as opposed to the title of the post). 
Also, there is no thumbnail / preview image even if the post itself has one.

These can be explicitly declared by using Facebook's Open Graph META-tags in the <head> of the page.

Slack also seems to be leveraging the open graph tags.

**Comment by SachaG** [comment]
It's weird, because we're using @DerMambo's [ms:seo](https://github.com/DerMambo/ms-seo) package to specify the `og:title` meta tag, I thought that would do the trick but apparently not?

**Comment by SachaG** [comment]
Apparently the reason this was happening is because I forgot to add Spiderable back when refactoring all the packages… :-/

**Comment by timoh** [comment]
@SachaG is the fix now in the latest release branch?

**Comment by SachaG** [comment]
Should be yeah.

**Comment by timoh** [comment]
I don't know if it's possible to reopen this, but as discussed, this problem is not yet resolved.

**Comment by adenot** [comment]
+1

**Comment by Kertone** [comment]
+1 :)

**Comment by irazasyed** [comment]
Any updates? Facing same issue.

**Comment by jibenet** [comment]
Any recommended solutions or updates? Still facing the same issue

**Comment by SachaG** [comment]
I'm working on it for [Screenings](http://screenings.io). Instead of Spiderable, I'm using Prerender.io: https://prerender.io/

Seems to be working, you can input an URL from Screenings in there to test it: https://developers.facebook.com/tools/debug/og/object/

**Comment by SachaG** [comment]
Works for me :)

![http://f.cl.ly/items/3n1L3X1I1U343C0S040C/Screen%20Shot%202015-07-25%20at%205.14.44%20PM.png](http://f.cl.ly/items/3n1L3X1I1U343C0S040C/Screen%20Shot%202015-07-25%20at%205.14.44%20PM.png)

This is the Prerender code by the way (include anywhere on the server):

```js
var prerender = Npm.require('prerender-node')
  .set('protocol', 'http')
  .set('host', 'screenings.io')
  .set('prerenderToken', YourTokenHere);

Meteor.startup(function() {
  WebApp.rawConnectHandlers.use(prerender);
});
```

**Comment by SachaG** [comment]
Works for Twitter too! :)

https://twitter.com/SachaGreif/status/624861452956860416

**Comment by constantx** [comment]
:+1:

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And yeah it has been fixed 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
