### ISSUE TITLE
Logged out users aren't redirected to login page on protected routes

### ISSUE THREAD

**Issue by jshimko** [TelescopeJS/Telescope#972]
The `ensureLoggedIn` plugin for Iron Router that get's implemented [here][1] does not appear to be working correctly.  For example, if you go to the post submit page while logged out, the app throws an error and a flash message, but no redirect ever happens.

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-core/lib/router/filters.js#L213

**Comment by splendido** [comment]
I'd say that on the `post_submit` page it gets no chance to be executed.
If you look at [this line](https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-core/lib/router/filters.js#L208) you'll see that the [canPost](https://github.com/TelescopeJS/Telescope/blob/bbf9fb9666cf07299c29e4e96d5fc37474bec1cc/lib/router/filters.js#L89-98) filter is going to be executed first and will block all subsequent `onBeforeAction` callbacks rendering the 'no_rights' template.

**Comment by SachaG** [comment]
Oh that's an easy fix then, we can just remove that filter.

Small piece of feedback though: the error appears in kind of a weird spot:

![http://f.cl.ly/items/021Q3H0Y3z1T3H092x0D/Screen%20Shot%202015-05-17%20at%2011.50.04%20AM.png](http://f.cl.ly/items/021Q3H0Y3z1T3H092x0D/Screen%20Shot%202015-05-17%20at%2011.50.04%20AM.png)

And I guess I also need to look into how to customize the text. If I change "Must be logged in" to something else, will it break i18n?

**Comment by splendido** [comment]
Yeah the position of the *error* is something to be finalized...

Where would you like to see it @SachaG?

**Comment by splendido** [comment]
The text "Must be logged in" can be changed, but there will be no available translations now.
This is another thing we should start to discuss for v2.0: collect all possible texts to be shown and start the *translation* project involving volunteering translators ;-)

What would you wrtite in place of "Must be logged in"?
...I guess something less harsh and more descriptive ;-)

**Comment by SachaG** [comment]
Maybe "Please log in first" or something like that?
