### ISSUE TITLE
icon-upvote seems mangled

### ISSUE THREAD

**Issue by brianshumate** [TelescopeJS/Telescope#973]
I am not quite sure how the icons work in Telescope right now, but in my installation at [Longboard Today](http://longboardtoday.com/) it appears that icon-upvote is mangled for some reason.

I am using:

* Mac OS X 10.9.5
* Mac OS X 10.10.3
* Chrome 42.0.2311.152
* Firefox 38.0.1

Here's an example of the appearance on Chrome:

![](http://i.imgur.com/FvCYzso.png)

and the same example on Firefox:

![](http://i.imgur.com/GLMbirY.png)

**Comment by mikewheaton** [comment]
You're using [Font Awesome's chevron up icon](http://fortawesome.github.io/Font-Awesome/icon/chevron-up/), but I don't think Telescope comes bundled with Font Awesome. I couldn't find any references to it.

**Comment by mikewheaton** [comment]
Actually, after taking a closer look it seems that Font Awesome *is* included after all. The problem is coming from the following selector:

```
[class^="icon-"]:before, [class*=" icon-"]:before {
  font-family: 'icomoon';
  font-style: normal;
  speak: none;
  font-weight: normal;
  -webkit-font-smoothing: antialiased;
}
```

See if you can track that selector down in your theme and change the font-family to 'FontAwesome'.

**Comment by brianshumate** [comment]
Hmm, my theme is just a copy of the default Hubble theme with some slight color changes, but I haven't done anything with fonts yet.

It seems Telescope has at least at some point used [Icomoon](https://icomoon.io/) instead of or in addition to Font Awesome, but I also see references to Font Awesome in `telescope-base.js`.

Kinda confusing, but I'll try your suggested fix for now. Thanks!

**Comment by brianshumate** [comment]
Ahh I suppose my theme is just out of date and now behind Hubble, so I'll try updating it. Thanks again, @mikewheaton!

**Comment by SachaG** [comment]
Yeah it did use Iconmoon before, but not anymore.
