### ISSUE TITLE
Newsletter Sign Up

### ISSUE THREAD

**Issue by disqvr** [TelescopeJS/Telescope#975]
After closing the signup message, it disappears and there is no way to sign up again. It would be great if there was another option in the footer (I managed this by adding a simple mailchimp form to it, but it would be nicer as a core function) and one on the edit profile page.

Furthermore, I am from Germany and according to law here (and I think there are several other countries as well), you are not allowed to automatically sign up new users to a newsletter while registering. Therefore it would be good if users had a simple checkbox while registering (checked by default) to sign up for the newsletter as well. While registering using facebook / twitter, there could be an extra screen “please add your email to complete the registration” with the same checkbox for completion of the registration.

**Comment by splendido** [comment]
That's a good point!
Adding another checkbox to the password signup box is just a matter of a few lines in the useraccounts configuration file...

**Comment by SachaG** [comment]
Just wanted to point out that we would need to add the checkbox in a way that also works for Twitter and Facebook auth, so probably not on the password sign up box but on the account completion page.

**Comment by SachaG** [comment]
Actually this is a bit trickier than it seems, because if we let people subscribe with a checkbox we also need to let them unsubscribe… And that means making another MailChimp API call. So I'll probably leave this for later.

**Comment by disqvr** [comment]
To unsubscribe, you could simply use the unsubscribe link provided by mailchimp - a simple input field for the link would be sufficient. 
Even if the checkbox would be nicer - this would be an easy solution to start with.

**Comment by SachaG** [comment]
The unsubscribe link is already there actually. So an easy solution would
just be removing that other link.

**Comment by xavcz** [comment]
Hey, @disqvr! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
