### ISSUE TITLE
overriding emailWrapper.handlebars not working after upgrade to 0.20

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#978]
heres the relevant contents of my package.js:

    Package.onUse(function (api) {
    	api.use(['telescope:core']);
      	api.addFiles(['custom.css'] , ['client']);
      
      	api.use(['templating', 'telescope:email', 'cmather:handlebars-server'], ['server']);
      	api.addFiles(['newEmailWrapper.handlebars', 'custom.js'], ['server']);
    	
    });

and my custom.js:
`templates["emailWrapper"] = "newEmailWrapper";`

**Comment by SachaG** [comment]
Sorry, I broke customization for email templates, it seems. They work differently from regular templates, so they can't be customized the same way. 

The new way is: to customize an email template, just add your own template with the same name prefixed by `custom_`. So:

- `custom_emailPostItem.handlebars` to customize `emailPostItem.handlebars`.
- `custom_emailWrapper.handlebars` to customize `emailWrapper.handlebars`.

etc.

Ideally we'd harmonize the APIs for both kinds of template replacement, but this will have to do for now. 

Note that I haven't republished the packages yet, so right now it'll only work if you're pulling from this repo with the packages loaded locally (the "developer" setup).

**Comment by sweetppro** [comment]
It works well, thanks for the quick fix.
