### ISSUE TITLE
Adding *.i18n.json in the packages/custom/i18n/ folder doesn't make the language available

### ISSUE THREAD

**Issue by timoh** [TelescopeJS/Telescope#980]
Added fi.i18n.json to the packages/custom/i18n/ folder, but it didn't appear in the Settings --> Languages dropdown menu.

**Comment by SachaG** [comment]
Maybe it's not appearing because your custom package is getting loaded after the settings package? You can always check what `TAPi18n.getLanguages()` returns to see if the language is loaded or not.

**Comment by timoh** [comment]
How does one determine the load order? I have problems running Meteor locally due to some MongoDB lock file issue, so I've no way of testing locally. I run on Heroku and there it works fine, though.

**Comment by SachaG** [comment]
Load order is determined according to package dependencies. If foo depends on bar, it loads after bar.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And by the way, translations run on their own package now 😄 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
