### ISSUE TITLE
Hide default Title on initial load

### ISSUE THREAD

**Issue by sweetppro** [TelescopeJS/Telescope#981]
when Telescope is first loaded, the default "Telescope" title is displayed before being changed to the user defined Title.

this can lead to confusion, and perhaps even be a little detrimental to the sites image.

**Comment by SachaG** [comment]
That's a good point. Ideally we'd have a general loading screen, but I think waiting on subscriptions is a little broken right now. Maybe something to look into if/when we switch to Flow Router (cc @delgermurun)

**Comment by capensisma** [comment]
Small workaround 
Edit this file Telescope-devel\packages\telescope-core\lib\client\main.js

line 17
```javascript
  var title = Settings.get("title", "Telescope");
//to this
  var title = Settings.get("title", "YourSiteName");
```

**Comment by SachaG** [comment]
@capensisma Editing core files is a pretty bad idea…

**Comment by sweetppro** [comment]
how about this?

    var title = "Telescope";
      if (!!Settings.get("title"))
      	title = Settings.get("title")

**Comment by SachaG** [comment]
@sweetppro isn't that the same thing as what we already have?

**Comment by sweetppro** [comment]
to be honest, my js skills aren't amazing it may well be the same as the default code.... but in my limited testing I don't get the default Telescope title showing.

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And this problem has been fixed 😄 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
