### ISSUE TITLE
Can't replace templace not loaded

### ISSUE THREAD

**Issue by capensisma** [TelescopeJS/Telescope#984]
Hi
I got this error trying to replace the embedly template :

`Can't replace template postThumbnail because it hasn't been defined yet.`

Is there a way to set package loading order ?
or a workaround ?

Thanks

**Comment by SachaG** [comment]
If you make your package depends on the Embedly package, that should ensure it loads after it. Although in this case, I think the template should be `post_thumbnail`, not `postThumbnail`.

**Comment by capensisma** [comment]
thanks it was  fixed, just a typo :)

nice work on the template overriding, it's very helpfull
