### ISSUE TITLE
Users Bio, Twitter, Website not displayed for regular users

### ISSUE THREAD

**Issue by donmarcello** [TelescopeJS/Telescope#987]
The fields htmlBio, twitterUsername and website are only shown to admin user, but not to regular logged in users/guests, although public is set to "true" in the telescope:users package users.js

**Comment by capensisma** [comment]
You should have editableBy: ["member", "admin"], in the fieldSchema not just public

**Comment by SachaG** [comment]
In theory `editableBy` only controls who can *edit* the field, not who can see it. So that may be a bug.

**Comment by capensisma** [comment]
@SachaG yes that was for editable fields sorry, but i can't think of this issue i never experienced it.

can someone reproduce it ?
this should be flagged none confirmed

**Comment by donmarcello** [comment]
It is reproducable with a clean install of the latest master version (refactor).

Just register 2-3 demo accounts, and fill in for each user the bio.

A regular user won't see another users bio, etc.

**Comment by SachaG** [comment]
@donmarcello I found the problem, it'll be fixed in the next update.

**Comment by shihanjun19** [comment]
The problem seems to still exist now   T _ T

**Comment by SachaG** [comment]
@shihanjun19 you're right, let me look into it

**Comment by SachaG** [comment]
Here's a description of the issue: https://medium.com/@MaxDubrovin/workaround-for-meteor-limitations-if-you-want-to-sub-for-more-nested-fields-of-already-received-docs-eb3fdbfe4e07
