### ISSUE TITLE
Facebook registration fails with missing email and username

### ISSUE THREAD

**Issue by eelcobrolman** [TelescopeJS/Telescope#989]
Dear sirs,

When registering with Facebook to Telescope 2 things go wrong:
1. The email from facebook is not stored in the MongoDB.users collection
2. No username is stored in the MongoDB.users collection

The first results in having to enter an email adres manually after registering, the second is worse, it prevents the user to login. Telescope keeps saying it misses information in the profile and won't let you do anything.

I fixed it manually by added `"username": "someusername"` to my MongoDB.users record, but this should be done automagically, either by making up some username, or using facebook's username with some random chars to prevent duplicates.

**Comment by ShMcK** [comment]
Same issue. After using Facebook oAuth and entering the user email, the user becomes locked, unable to logout. Reloading the site doesn't help. Screenshot:
![screen shot 2015-06-01 at 12 36 01 am](https://cloud.githubusercontent.com/assets/4660659/7902509/e056b75e-07f6-11e5-923f-8e8fad99dd66.png)

**Comment by capensisma** [comment]
this issue was already solved earlier did you update your telescope version ?

**Comment by eelcobrolman** [comment]
We did use the Heroku installer a few days ago, so I think master/ was used? Can't seem to find commits related to this issue in the last 5 days... Is the Heroku install branch different from the master/?

**Comment by ShMcK** [comment]
Running `meteor update` fixed the issue for me.

**Comment by ShMcK** [comment]
Note: the Heroku quick installs a much earlier version of telescope. Could use an update.

**Comment by SachaG** [comment]
@ShMcK hmm, you might be right. I just updated the sample-project repo, sorry for not catching that earlier!

**Comment by eelcobrolman** [comment]
No problem, ```meteor update``` fixed it indeed, case closed...

**Comment by SachaG** [comment]
Great, sorry about the version thing.
