### ISSUE TITLE
Categories broken

### ISSUE THREAD

**Issue by brianshumate** [TelescopeJS/Telescope#990]
I upgraded [my site](http://longboardtoday.com/) to 0.20 and everything went fine, however all categories now return *Sorry, we couldn't find any posts.*.

Had a look in the DB and the categories collection looks fine and all posts still contain the categories they're posted in.

Any ideas on what could be wrong here?

**Comment by SachaG** [comment]
Hmm, I'm not quite sure what's going on here… Have you customized the site's code in any way?

**Comment by brianshumate** [comment]
Just some basic theme styling changes.

FWIW, this affects existing and new posts.

If you have pointers for how to debug, I'm happy to share or try whatever to figure it out.

**Comment by SachaG** [comment]
Is this happening both locally and in production? How are you deploying? And can you share your code repo?

**Comment by brianshumate** [comment]
Yes, it happens both locally and in production.

I am using Meteor Up to deploy.

Since I was following the tips from the blog post to upgrade, I used the [sample-project](https://github.com/TelescopeJS/sample-project) and modified that; I hope I didn't break something along the way, but I don't recall seeing anything remotely category related in it though.

**Comment by jespervega** [comment]
I have the same issue on http://scope.hackbeat.org. It's deployed on heroku, with minimal styling
I added the posts first, then created categories, then edited the posts and saved with categories added. 
The category pages returned no entries and "Sorry, we couldn't find any posts" Fx. at http://scope.hackbeat.org/category/demos

Not sure if it has any relation, but i noticed that setting the catogories first gave me fx. this link clicking in the sidebar http://scope.hackbeat.orgcategory/demos - until I added "/" to the site URL, like this "http://scope.hackbeat.org/" - it made the url look right, but still didn't solve the problem.

**Comment by capensisma** [comment]
this is not broken, you have just to put the full domain name with the leading http://
in the settings so the categories show up

http://yourDomain.tld/

**Comment by brianshumate** [comment]
@capensisma I've had my site url specified properly with trailing slash for almost a year now, and categories worked as expected before the upgrade.

**Comment by brianshumate** [comment]
FWIW, I've dropped back to version 0.15.1 on my production site and am just mentioning that here in case anyone hits the link in my first comment and sees that the categories are indeed functioning as expected.

I still have a dev instance of the 0.20.4 version available if it is needed to help debug this issue.

**Comment by SachaG** [comment]
@brianshumate @jespervega what happened is that the `sample-project` repo mistakenly had the wrong version (0.20 instead of 0.20.4) until a couple days ago. It'd be great to know if updating to 0.20.4 (`meteor update` locally) fixes the problem or not?

**Comment by brianshumate** [comment]
@SachaG great to know! I'll give it a try soon and report back. :)

**Comment by brianshumate** [comment]
@SachaG upgraded again to 0.20.4 and all is working as expected. Thanks!

**Comment by SachaG** [comment]
Great! Sorry again about this issue, I'll be more careful about keeping everything up to date :)
