### ISSUE TITLE
Callback Hook - Downvote

### ISSUE THREAD

**Issue by lisacheng** [TelescopeJS/Telescope#991]
Hi I'm trying to implement the downvote function, if I change the following in callback.js - is there anywhere else I should use this callback function and for Downvote to work, will just changing this js file turn on the Downvote function? Thank you

```js
  Meteor.users.update({_id: userId}, {$inc: {"telescope.postCount": 1}});
  Telescope.upvoteItem(Posts, post, postAuthor);
  Telescope.downvoteItem(Posts, post, postAuthor);
  return post;
}
Telescope.callbacks.add("postSubmitAsync", afterPostSubmitOperations);
```

**Comment by capensisma** [comment]
Hi Lisa,

This was already solved

https://github.com/jcsaaddupuy/Telescope/commit/ce34a68ce06e8f2a623dc431a05f7ff5788608cd

**Comment by SachaG** [comment]
You should probably not be changing any core files? Also `Telescope.upvoteItem(Posts, post, postAuthor);` here is because every new post starts off being automatically upvoted by their own author. I don't think it would make sense to *also* downvote your own post here?

**Comment by lisacheng** [comment]
That would explain why it didn't work. Can you advise where I would make the changes to enable downvoting?

**Comment by SachaG** [comment]
If I'm not mistaken, all you need to do is add a downvote button somewhere along with a downvote event handler (adapted from `post_upvote.js`):

```js
Template.post_downvote.events({
  'click .downvote-link': function(e){
    var post = this;
    e.preventDefault();
    if(!Meteor.user()){
      Router.go('atSignIn');
      Messages.flash(i18n.t("please_log_in_first"), "info");
    }
    Meteor.call('downvotePost', post, function(){
      Events.track("post downvoted", {'_id': post._id});
    });
  }
});
```
