### ISSUE TITLE
not able to add custom package

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#993]
I am trying to add a new custom package.  But when i give the command 'meteor add packagename' it shows no such package error. Then i tried to add the sample custom package 'custom' which is provided with telescope.  But same problem exists.  Shows message as no such package exists. How can i solve this? .  This problem started when i tried to update the telscope version for my site.

**Comment by valgalin** [comment]
If you're using version 0.20, Telescope names are now added like this (for example, telescope-tags:

`meteor add telescope:tags`

You should also follow the format in the name of your custom package.

**Comment by dittybijil** [comment]
Thank you valgalin. It worked fine.

**Comment by valgalin** [comment]
You're welcome!

**Comment by dittybijil** [comment]
Valgalin could you please  help me in one more thing.  We were using an old version of telescope.  We had 9 to 10 custom packages in our site.  but when i update the telescope version i saw that  the other packages use section in package.js file changed entirely. So i have to change all my custom packages package.js file.  
For example I have a custom monthly view package.  It needs singlemonth package.  How can i include this singlemonth package in package.js file of monthly package?

**Comment by SachaG** [comment]
@dittybijil there's some instructions on updating here: http://www.telescopeapp.org/blog/telescope-v020-refactorscope/

Also check out the new documentation: http://docs.telescopeapp.org

**Comment by dittybijil** [comment]
Thank you sachaG.
