### ISSUE TITLE
what can i use in place of push method in new version

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#994]
how can i replace this push method in new version
postModules.push({
  template: 'customPostShares',
  order: 40
});

when i use this it gives an error that 'you cannot call push method'

**Comment by valgalin** [comment]
If you're already using the latest Telescope version (RefactorScope), then pushing to template modules are already different. You can see the documentation here: http://telescope.readme.io/v0.20/docs/template-hooks

**Comment by valgalin** [comment]
To get and idea, please see the modules.js file in: Telescope/packages/telescope-posts/lib/modules.js

**Comment by capensisma** [comment]
it was renamed to add

```javascript
Telescope.modules.add("hero", {
  template: 'hello',
  order: 1
});
```

and also same for registeredField renamed to addField
