### ISSUE TITLE
App is Deployed with heroku Facebook and twitter authentication not working 

### ISSUE THREAD

**Issue by hashtix** [TelescopeJS/Telescope#995]
Hello,

I am new to this i was interested in telescope as a Tool for content curation... I am unable to get oauth to work for niether facebook or twitter it randomly worked once but not since then. ow do i fix this i do have meteor on my computer but i just deployed instantly through heroku ..... can i ge some help and please any pointers will be really awesome.

i have gotten 2 different errors especial with facebook authorization...

Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

and internal server error.

**Comment by SachaG** [comment]
Can you link to your deployed instance? The Heroku one-click button was deploying an older version by mistake until yesterday.

**Comment by hashtix** [comment]
Okay...https://cbdportal.herokuapp.com could that have been the issue how do I reset the parameters using heroku?


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by SachaG** [comment]
You can redeploy on another instance. If you want to keep your data, you'll have to first pull your codebase from Heroku using Git, update your files locally running `meteor update`, commit the result, and then push it again to Heroku.

**Comment by hashtix** [comment]
@SachaG Thank You Very Much for the info.. i am very new to this. So when you say update my files locally what if i dont have a copy of the app running on my machine? i only running the app through heroku but i do have meteor installed and i am unfamilliar with it... Any further help would be appreciated.

Mike

**Comment by SachaG** [comment]
I guess that's the downside of one-click deploys… You should probably start by familiarizing yourself with Git, since that's what Heroku uses to manage deployment: https://devcenter.heroku.com/articles/git

If you'd rather not go through the Git route, you can check out the install instructions for Telescope here: http://docs.telescopeapp.org/v0.20/docs

And then choose one of the other deployment options: http://docs.telescopeapp.org/v0.20/docs/deploying

**Comment by hashtix** [comment]
Thank a lot for the info I have been taking time to familiarize myself with git.... I see heroku has their own git. Which is what I am using. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
