### ISSUE TITLE
to include dandv:rate-limit package in new telescope version

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#996]
I am using the package dandv:rate-limit in my custom package social-share-count.  how can i include it new version.

**Comment by SachaG** [comment]
I'm not sure I get the question? Just include it as you usually would?

**Comment by dittybijil** [comment]
to get the tweet count in old version in package.js we include ratelimit as
api.use([
       'percolatestudio:synced-cron',
    'dandv:rate-limit'
  ]);
and i called in share.js file as 
 var updatePostLimited = rateLimit(updatePost, 4000);
But it is showing that rateLimit not defined.  So I think i didnt include 'dandv:rate-limit' in package.js. 
Now I include that same as in old version.  Now its not showing that error.  I expect the problem solved.
