### ISSUE TITLE
how can i place values in template positions

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#997]
How can i place values in template position in new version of telescope.  

In old version we used .
templates["postInfo"] = "customMyPostInfo";
But in new version its not working.  Any change in it?

**Comment by SachaG** [comment]
Sorry, I don't understand what you mean. What are you trying to do?

**Comment by dittybijil** [comment]
'customMyPostInfo' is my template file which includes twitter count, fbcount, linked in count etc.  I want to show this template in the template position of "postInfo".  That is under each post. For that in my old version i used the code 
templates["postInfo"] = "customMyPostInfo";
in main.js file.  in current version  i changed the code as 
Telescope.modules.add("postMeta", {
  template: 'customMyPostInfo',
  order: 2
});

Am i Right?

**Comment by SachaG** [comment]
Check out this section of the docs: http://docs.telescopeapp.org/v0.20/docs/custom-templates

By the way, you can format your code using markdown with triple-backticks (```)
