### ISSUE TITLE
Fresh dev install (0.20.4) has out-of-date notification upon first launch

### ISSUE THREAD

**Issue by montecruiseto** [TelescopeJS/Telescope#998]
![screen shot 2015-06-04 at 10 49 59](https://cloud.githubusercontent.com/assets/10129398/7976587/a3940840-0aa7-11e5-8489-2d51be9a8628.png)

Fresh install has out-of-date notification upon first launch

**Comment by dittybijil** [comment]
We also have the same problem
![last](https://cloud.githubusercontent.com/assets/12061565/7980144/ae65a6a0-0ac2-11e5-9b2f-41088ced3dd0.png)

**Comment by montecruiseto** [comment]
hehe
maybe 'problem' might be a big word

2015-06-04 15:35 GMT+07:00 dittybijil <notifications@github.com>:

**Comment by SachaG** [comment]
Working on it.
