### ISSUE TITLE
define helpers for custom template

### ISSUE THREAD

**Issue by dittybijil** [TelescopeJS/Telescope#999]
I am defining helper for my custom template like this

Template.customMyPostInfo.helpers({
        SiteUrl: function() {
            return getSiteUrl();
        }
    }); 

Am I correct.  Here 'customMyPostInfo' is my template. But i am not getting the site url.
 
In old version I define it as

Template[getTemplate('customMyPostInfo')].helpers({
        SiteUrl: function() {
            return getSiteUrl();
        }
    });

Please help

**Comment by SachaG** [comment]
You can do `Settings.get('siteUrl')`. 

By the way, GitHub issues are for actual issues and bugs with the code, not support questions. I suggest you post on http://meta.telescopeapp.org for that instead :)

**Comment by dittybijil** [comment]
Thank you sacha.  I will do as u suggested.
